#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/yield-yard.json and re-run the generator.
"""Activity: Yield Yard

Eleven short Python programs proving, by observing actual interleaved print output, that a generator function pauses and resumes rather than running straight through: calling a generator function returns a generator object without running any of the body, next() drives execution up to the next yield and no further, StopIteration signals exhaustion, a for-loop drives a generator automatically, a generator expression defers its side effects until consumption (not creation), an exhausted generator yields nothing on a second pass, an infinite generator survives only because consumption is bounded, one generator can be piped into another, and yield from delegates to any iterable (a sub-generator, a list, a string) as sugar over an explicit re-yield loop. Every output is deterministic on CPython 3.10+.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "0704907d4472bab1ff95b69ff6859ae79c85a04c7e412e0fcd0752d7c059ef6e"
_KEY_B = "ce5e9eccacfdf8d138be66a2561a8dc8f03f30f4ccbbff87e309a2dd0943d7aa"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "1ffdb3bf1cb35f9130ec41ec2a6f06522b9a61059f2bcc775fe183d0aa42b652adf05e7486e8230fb6604be65426fa6a0665075317636a1147c9a2fc"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "calling a generator function does not run its body at all -- it returns a generator object",
    "code": "def make_numbers():\n    print(\"body starts\")\n    yield 1\n    yield 2\n\ngen = make_numbers()\nprint(type(gen).__name__)\nprint(\"about to call next\")\nprint(next(gen))\n",
    "prompt": "make_numbers contains a yield statement anywhere in its body, which makes it a GENERATOR FUNCTION -- calling it (make_numbers()) does NOT execute any of the body; it immediately returns a generator object, paused before its very first line. type(gen).__name__ names that object's type. Only next(gen) actually starts running the body, up to and including the first yield. What do the four print statements show, as four separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 2,
    "title": "yield pauses between next() calls -- prints interleave to prove real suspension",
    "code": "def counter():\n    print(\"start\")\n    yield 1\n    print(\"between 1 and 2\")\n    yield 2\n    print(\"between 2 and 3\")\n    yield 3\n\ngen = counter()\nprint(\"got:\", next(gen))\nprint(\"got:\", next(gen))\nprint(\"got:\", next(gen))\n",
    "prompt": "Each next(gen) call resumes the generator EXACTLY where the previous yield left off, runs until the NEXT yield, and stops there again -- the print statements between yields only run when execution actually passes through them, interleaved with the three \"got:\" prints from the calling code. What do all the print statements show, in the exact order they actually run, as seven separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 3,
    "title": "StopIteration at exhaustion -- caught explicitly, once the generator has nothing left to yield",
    "code": "def two_values():\n    yield \"a\"\n    yield \"b\"\n\ngen = two_values()\nprint(next(gen))\nprint(next(gen))\ntry:\n    next(gen)\nexcept StopIteration:\n    print(\"exhausted\")\n",
    "prompt": "two_values yields exactly two values. After both have been retrieved via next(), the generator's body reaches its natural end (falls off the end, with no more yield statements to run) -- calling next() again does not hang or return None; it raises StopIteration, a signal that the generator has nothing left to produce. What do the three print statements show, as three separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 4,
    "title": "a for-loop drives a generator automatically -- no manual next() or StopIteration handling needed",
    "code": "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nfor value in countdown(3):\n    print(value)\nprint(\"done\")\n",
    "prompt": "A for-loop over any generator calls next() automatically, once per iteration, and stops the loop cleanly (catching StopIteration itself, with no visible exception or extra code needed) the moment the generator is exhausted. countdown(3) yields 3, then 2, then 1, then its while loop's condition (n > 0) becomes false and the function body ends. What does this print, as four separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 5,
    "title": "a generator expression's side effects happen on CONSUMPTION, not on creation -- print ordering proves it",
    "code": "def loud(x):\n    print(f\"computing {x}\")\n    return x * x\n\nprint(\"building the generator expression\")\ngen_expr = (loud(x) for x in [1, 2, 3])\nprint(\"generator expression built -- about to consume\")\nresult = list(gen_expr)\nprint(result)\n",
    "prompt": "gen_expr = (loud(x) for x in [1, 2, 3]) LOOKS like it might immediately compute loud(1), loud(2), and loud(3) the moment this line runs -- but a generator expression, exactly like a generator function's call, builds a paused generator object without running any of loud() yet. Only list(gen_expr), which actually CONSUMES the generator by pulling every value out of it, triggers the three loud() calls -- and their \"computing\" prints appear only then, after \"about to consume\" has already printed. What do all the print statements show, in the exact order they run, as six separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 6,
    "title": "an exhausted generator yields nothing on reuse -- the one-shot trap",
    "code": "def small_gen():\n    yield \"x\"\n    yield \"y\"\n\ngen = small_gen()\nfirst_pass = list(gen)\nsecond_pass = list(gen)\nprint(first_pass)\nprint(second_pass)\n",
    "prompt": "gen is ONE generator object, created once by calling small_gen(). list(gen) the first time fully consumes it, pulling both 'x' and 'y' out and exhausting it. list(gen) called a SECOND time on that SAME already-exhausted object does not restart small_gen's body from the top -- a generator object has no way to be rewound or reused once exhausted. What do the two print statements show, as two separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 7,
    "title": "yield inside a loop -- a countdown generator, driven with explicit next() calls",
    "code": "def countdown_from(n):\n    while n >= 0:\n        yield n\n        n -= 1\n    yield \"liftoff\"\n\ngen = countdown_from(2)\nfor value in gen:\n    print(value)\n",
    "prompt": "countdown_from's while loop yields n, then n-1, then n-2, ..., down to and including 0 (the loop condition is n >= 0, so 0 IS yielded) -- and once the loop ends (n has become -1, failing the condition), one final yield \"liftoff\" runs, outside the while loop but still inside the function, before the body truly ends. countdown_from(2) is fully consumed by the for-loop. What does this print, as four separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 8,
    "title": "piping one generator into another -- a simple two-stage pipeline",
    "code": "def evens_from(n):\n    while True:\n        if n % 2 == 0:\n            yield n\n        n += 1\n\ndef take(source, count):\n    result = []\n    for value in source:\n        result.append(value)\n        if len(result) >= count:\n            break\n    return result\n\ndoubled = (v * 10 for v in evens_from(0))\nprint(take(doubled, 4))\n",
    "prompt": "evens_from(0) is an INFINITE generator (its while True loop never ends on its own) that yields only even numbers, starting at 0. doubled is a generator expression built directly ON TOP of evens_from(0), multiplying each even number it receives by 10, still fully lazy -- nothing runs until consumed. take(doubled, 4) pulls exactly 4 values out of doubled (and, transitively, out of evens_from(0)) and stops, via the for-loop's break once result has 4 items -- proving one generator can safely feed into another even when the innermost source never runs out on its own. What single line does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 9,
    "title": "an infinite generator, consumed safely with a bounded loop",
    "code": "def naturals():\n    n = 1\n    while True:\n        yield n\n        n += 1\n\ngen = naturals()\ntotal = 0\nfor value in gen:\n    if value > 5:\n        break\n    total += value\nprint(total)\n",
    "prompt": "naturals() is an infinite generator -- its while True loop never ends on its own, and calling list(naturals()) directly (with no bound) would hang forever, never finishing. This snippet instead drives naturals() with an ordinary for-loop containing an explicit break once value exceeds 5, keeping a running total of every value seen BEFORE that break. What single number does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 10,
    "title": "yield from delegates to a sub-generator -- identical to an explicit for-loop that re-yields",
    "code": "def sub_gen():\n    yield \"a\"\n    yield \"b\"\n\ndef delegating():\n    yield from sub_gen()\n    yield \"c\"\n\ndef explicit():\n    for v in sub_gen():\n        yield v\n    yield \"c\"\n\nprint(list(delegating()))\nprint(list(explicit()))\n",
    "prompt": "yield from sub_gen() inside delegating() is syntactic sugar: it pulls every value sub_gen() yields and re-yields each one from delegating() in turn, in order, then continues with delegating()'s own yield \"c\" once sub_gen() is exhausted. explicit() does the exact same thing by hand, with an ordinary for-loop that re-yields each value one at a time. list(delegating()) and list(explicit()) drive each generator to exhaustion, collecting every yielded value into a list. What do the two print statements show, as two separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 11,
    "title": "yield from works on ANY iterable, not just another generator -- a list, then a string",
    "code": "def flatten_sources():\n    yield from [1, 2, 3]\n    yield from \"ab\"\n\nprint(list(flatten_sources()))\n",
    "prompt": "yield from is not limited to delegating to another generator -- it accepts ANY iterable and yields every one of its elements in order. flatten_sources() first delegates to the list [1, 2, 3] (yielding each of its three elements), then, once that list is exhausted, delegates to the string \"ab\" (a string is iterable one character at a time, so this yields 'a' then 'b'). list(flatten_sources()) drives the whole thing to exhaustion. What single line does this print?",
    "platform_note": "any platform, CPython 3.10+"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "xB#ABfQgQCFN;eC`BUrj4s{WO=^l@elVL#lFgs|p_d~UalnafG+XRUSklCI8$(&?Z!50;pR-4KjavpOCVh+Jlk0m$NsTz%I2;`&CSSVYdW0zrkGf?6#PdsN3hBoR(`eJg$MsTf#+!m=BQ+J5wfT|Y_n!4QYN~@#PBmjiD7??eKDI|Bd9G24ZrvY$Ge897;&;5IHeAo!aY*ZFSvP%x)*e%Dh*bGLi;F!sEUq-l=OX;!ydxgg{&xy;exc1S}O+Z2o3%?@&kuiCxSb({lE(Zy)0d5_)*l9<o6kR3mpo-~~0jHrHO#-*u?xiYX<PPX&cF(ZdG>gZC`!iE@nF)^{IJ^uvhhYoHABsc-^cPjWu)z}~)PTdEhYpx2jPkE^4>$0AodcrsTdZ^1#?4WeQFgW&wZq9}RwV!A2@7F+PTQYs&T0<u*|$vJL)u3d=O?|b5NuK*=3WdXtUB-<&a=UJEsL%)!EHGIsLKRq2jD0D^6`Og<!(5GfCo<+lW|3_TZP3+aMTgv;S@vgtS9{sENsxcjYU7BArVL^5b9XW$yOmUc30s@R)?+Cqt#8N69ML85kobk%Sl}4J@s~FCLs(A#8F7mu6;!o<6vyxdHUD(Vk3d+5D|hvs;x;eTDIbr@KcA!mMB{D?}z=qS{_LIuB6|$e)&jq=(3PHG5nz79rVIh6-WX7wkNRP*7tpklTDr1go%D9+5`30L_$W&lTsZ6z}O4`2@GnKF2Cd}VTciQNCNK*TEsd#NcBtt3Cg))fo{AEbXd`bnnOLR2F2YkwfqeuVjx^9r@(>@+rQ4z%`~X-+<#K5N)%saPKXu?c?W=?hM4Q%hO9G|&=o+MyV$jNcCA{<mqwESeJjK3C3g-;%L9gDMPvXmD)-CIPOaQT?b2Nly%?mH`l^u$jZB>jD#4e`x&UoBy8N|v{>NM`e~u%wk)iwChCotqM~Fg%tMnJ4ojhS#BobC8JPW-A$$YT+HvyxpQgQEZ@-yT!DI<@M$FHNd5Kxs|v05W!5|7=K9=A6Xu#Xm^T^N!)AfX-({ZPb~Q4=%YU&s~;9#ia*__Iy!`{&CQ;^S-bA_SbE0<H>QkzPXfS?Azb2mFJ7l*)a;z4#CHBN7ey$66Y*pWGxF6Ww4Kx^nGH0!HiSjP`|)MbKBS&4^(VEz7Gre8%kD8_6xG0ZLN;+(wGpSgSG+VeJ(1Jtq(gMN^&Gm|Vzeh{w;2$+>~SK1=d;Ggq#1E;vuL&DwQOH`r-a#TP1%sWiXH6R*V#C)63?$<JRaU;",
  "Y0Gt1OkJq`d~(K|y+mZlQix~Wb1*1%526+dp24e#YhA9_Q+Qf_d?$MT{)z#@4O=?@(am1G-JZ)HfK`uw0p02g<Y9e64&uaS+2hWD+Uk1x#6noFqJmXw@92Zdg9#OyQq!RSgx$!D3-tOv#OE<NnGp1V*WP65K}n*msZSCz=a<zj0frpxbD`lrXN_f`m>M`)%Z*2I%6GbU=wPz&2Nj!+^AKOBT@pj+2@hMI`?Bwf;o=*lXkviZxamn5V4YDy+1zw`ab7Dg0HwH9Z1*G6)g;XLW&xcGjKoue?By96X-|A-M+yUz6>EQ!Hj$+$t|jrp<hcI(s*^VLm>f)TK5zB4A=E`Q3%k!{ms$o!N)MFj0$-5}M3|L_>=0d|@)7}bYh2O8-Qm*@MmTD$(Go6=DiIR)7cH7D`s_3ij;F*KMz_`L><7+cHiKLJr+yujeKymqQ<yAF2%z@iKLSH%c$$X!$+5YhUIn894Gptu9Lgh>GsZ|=#CJsx2$YT*V5yU2_M2+J_CQV{$ZiugI|&=U4regCysfG5vc+0XK9f}@o>Dfp+$s{Auhekw|MzYNifD18R^GA00u&mEbkgCSQ1b*rpCl_+5+iiJ5<0w+pTnu_6NzR1NyvoCko%(PSiPyae^bL_Ef&ez0AtZ<+kl)6L9qo%`ocX#cuEhHziCH94W4lsN$b6n$WbLj%~yFhM;mf~rQ*1tDt(Q3Hvx_1bAikkMy_(>5zWS!>PI>1uUM*JBr(2=Jm=p0lv*o<UJIVhnA~=5s|ygHhbnLXpZ2I1ixe%LYgUS4H<!l5vF0L+jdJz~rRL5c$gmH(D(JUpW=R>P-7HF-NeO=N2o~nEAbf<Q5Y6>zlMYo<0-sxAQPz?JiaCU)Iv|bk!Ocp5HOV$(q~!)pL*pVuMEVY?F)z2<k4UVYg$(dyWgXn-ESp(oVaX<*(qGH$?7X!Hj~kCZ&QKPY5>{IwS`s3m1b{a}<?lAyR3j2fMiB#uRlOgg`!qDo7LsS+&2_XnhoO0tSNyyke@P2UOYyl1#4|=U4iER6+}zM-MhyfE5m#5Vj~qN;gPSpy*j_ly<t<F#x8e#|-4b(1P|FukI|x}+djtPAVhaQ|r*Fb_fhR7D5~>({MLKE}A{0L72PNKwjf7uLmbS$xD!29e*Z`5RJ>MJ}a9FpO-m7!5E>nAb8x*nR1nuDC",
  "oFQCYrq?9r@x4lCllj&j;#1?)Nb3Fn;3`G8K?Cp6GjT!O-5DE1J~|k8kvJ%A5Bk@i^~Z5@?5Ce<Cz^W11V0$a^$FKg9PFVYuzHFzy>HZ`evc;L=`MJBBF;L~Rm-wC?ar-%)h(ZQ!0l0Cb<Y}5K;FU#ld~`WYomV`RzO5q)00H8S0BIo5~!R@xHG^r*d{E8QiGddrBK|~9)S-WRAj1&4Kk%B(>2E^P|Ilgr9PyOrIigSnt(AA4Yc0XK|_yaTV-)m-0|q&-^GZPyFeo&)FeV(9d1xp1XxDT<$u{rYOMIKY9f$2Fz)CwHY%o7r$`FhanjDg6WrkK_-wd^^4ceTf#c*(rdecw2U6wXm$*-7r9{$cT&*?I;=X)SsKAZd-m)#B{&BvcvbX;UjY<<A@h$-1MhAY7O@|^-lG9inudo;evO%z9m@er98N{rjiHkvKUN-;RJ(xedu?ibuf>9GEWUH>VOfCFgPos4DkNkW>#Q(=9-7k7Vk;XsFQXr8#YpL9R7*hc0h(GW_VOQgFKH$id7>`bwVl-N7WI@BD*z*wuVyCq@{eUwF%8dE>jc25CwghR*p&w>JGtAO*e_T_4eF_t_ClT7;w>~j0F3a{?-XAbKXb&tQe;^cCdw<3plgd@7r67iZw2;J1J}Q+!jkQIaTMEW549EwwlhSy(@N0d^W;}%>-Qpi>r?K#k!Lx6w;j<U)H4#d>E2`9PepEE!kEPrq|4ixIvsgauRIdzsWN9aou)A-R7l{HFD~Px8>yy)?o5dZat~e0t9i$6$*{o_%RvEhvGD<($g2`kXAgTpP+E5$as!+E$D-v!^ceG2byewmkz4bZ`O@+mu@vJl${0H(n#_X+~3p3Z^+2<4(Cm<dU?{iu=BS`fS-m|2O4l$Y}<YJi)V<Ej>=0;VmEInsB-xqGs6o_J?>!k(W7m=q%<hit@SHEWwP?$#t&D~aA0B<d2Bf;!ME9ZeQ!}$aqdJ7a0;ZZt0?T#9p#Z2Wg9N>3POGoa?5ppz#OEv?tZnEm*U|NkF2-MMdjrKotcrAWb<c8JM#uMyE^iQMGNv*ItF5pW1w(q%{&4F;p`)KrCvS1RLnY_Yu+N{b*cnWDhDl_ed5(?ko7(Li$tj7dDQ%R6lFdVEu!NFxv{lo7I{L*^R3+n",
  "5Mq-uFv^*d7(nt*ckBaPRWDT{!7FR9MXi>+D&Lm6f~u+OX{v!Bx2ZY$L86RIUSW5+VT_%ItX|b#-Mgc`U*0Ay?*22KTI@e1VR@NH$uJo}s92|(8Bz}$pDZ4K&6A5K1dK;u8DAN0Fm21>$WgNO7tvSg-A-@zkz@UDRFT*~uY||x$&AsI{lodSAJ2cFW1x<|Sj=KBD(&6anDa@LsM0RpJ7?BKsyBby#juoC7T+&F0uj-uY<r8@L{sHLt{XD<xvKAQSo>%Bps(hST*Yi+cBt_G(@@2ikP3Pcf022%(i8gJ_&o4Bz<B&gS3l30n3^~_?zaJ$0(uu0sCGa^Nw{*6Iw}p0?=~%WNc0z+)WPQ}<1qX#*#~-lq&}n}mhC!Xh*4O3Ru>k)tE4_s#W_Ek6IDjq&Pb@bc`$^f2%Cq*H#hATqJ&@#S4l1sH_Wxhv&WV(IlR6?7WzWJ!G%O@uvm!?oJmbStCWTv@?YI{SWN=U*NzkmIx&U^=SwC&RE<EG3UUXiEk(3@SW6bj*iigpA3l=O<ZVbo;0`2k&*i%caU~u<rR?j<yLZhlfz4jqY{Kr}@Y+7nkI=hw2aZkdfew^bhHC7aqL0zgyz?ZmfMGT=&=w@Av?su6zAsHfyzpH{_WWft)N|&xQji7KM09Pkz5$ydpxhqwE`*Qb93NEMATsH3rrzIim%U%QfC!()%wFO++f<&lM-m9%=?DA8^d9$DpQKX(2jB&OBD(H><A&8=C^;2&1xxz68aGk*F^~J>>k0sZ@WtY1N4#eys0FZqnDZjSE#{(|qG(57zP5{#LQzJ|nC;|C6t!F<Je?|+g{$*(N0^;wR|5$GHZ)y`-bwm&q)+^Q#9)AmG`rZ}g<|4iO=y_36-s6pLC~aV^Y*b5PH+^TimoDJ;N_V{v=SUidl@5P4Ywi@3sRyjuQtI-gBb2OgzcSYEGu&Ci<$vsLs?^Oo#Gtu4)ogD^c>Q(x44&X+za<iJ%)F7+psW4qY7EO5WEgut6nnp#Zix5ylvceOoO8eiF~f7F{f)oCBFXZRou)Q0OfY-W{uQ-S(J}KMztz+s2>Hb{6-;so<cr3ykxnOt5t%{oFEAPzgc9L6?bV^eDt7IjSo5z+9nF)X6373F5Nf@4iE<-TE#vSb+`CqCEnnOTg$E@#k*dmK(%Xs#gbetk%rlAr?eR7Xze0uR_3`(;S~-JV{0wEupV(|(iurT5-Dd1alHNiG&Q@UclU#Y(kZS",
  "hC8&)fG{Yv8Krx7Ny3c^WDrE*Or;&^;8b_BS{(-cMSV<^25Xum$#GD^iL`n)7^Km`mdHPMQ0`KZ^v|~`mrUgP=gdIU3Mo>RH|0)p^<3Fq-|7P(uYfg5hzAzekxj>^#135K%t6v&Z#63Y+n$N}X0-OIcgYzhpy<Z{9GSpwXjo^SOUt4_Xga2m)DRN?Ygy8%*H(9*vxu4)cGIF{dUzs^e<QU<@{J;1Tm?MGmx<%>S$y^!{I`joGXfoA3+yagkUhMw7_jX|s=#}Y4hN`+WtUj2sl)F%umDaF$W<dIXSC={mfKc$8PB-ceWVA^x&I>)-xXGiPxX4^boJ(IqPps%>_DJSOuXgjXv=7=RRnwiSWlp*isRBv7k{kiOr}nL-RpsvXcJ%L<T>eNkTMa__O>(A=Ugcv1o-lo#8MjvmM@1x(louj`@R>{ONSi_%kouu8HhuLv>le{k~KrW3e|rj`mvZj2!db5RGQ8JTKSt_WfNqQ3E_8Yxo-b~C@<DGIwlxYLkxgMTadL8%C7OeT;M+;$el$s=R@^C@yOrZFq+m+(T_x+nyDTt2%1(j>F!q1Eii=~ChSH%M2jtTp2*X{4`1{Bq-^Xh`ny&XnG)#fI1a*^8klszkeihQJ$6junJq$4ICulcrLP|4UJYSB1tAk*>;$!BHHjAKZ_~TC+jXD$NV`uj{b0|D$9)4QqAVqsK>HMm)+mbTgP7^f7G3@lwH(C={F32Mr7Ci**7`sHcSXrGrcdDKy1%X}GH&)Dx++tAu#qAzwGC_U5WaaBj+WUcBhG(Bkkq8{#xB|3I!}riA@f4ZHiGLE9@vS#oFcn4Sa9E|z#-=Mprboiz&?CB)0zrg$O`~5x|AHn*Xo1>RW8u`3{t475R?RA2#@AHVQ>=Fd`20}D?k|d-XLYTnjtFj`H1{n*WjVQcuqVI-*=mE2Ct42D9~MR*3%<N8^zSgMr}#tf$EtEc#m2$3k}IeB|o1~CCBJ{`9w;rn6Z!k(J#eF$=g2zu;M+p;AUM95Dq%8dz%=&x1qc@!0U^NqE#^8eo$7}@IoT+6Xz0CMO9^$9L25yhp<71s(u(E?!2=#)R!){xcJS~a!5|uX>A9l%md!!>S7kPb<P}kx&8`ESRGUo(#x}^HtPh=vM<#mi0tHZle-Pn5VLU^b?fvf)q*_~*ysJra{q8CGQj<t-~hwT|MeICrX4jaB~)VwVQmCdoQ`SEZ3VCQE<#%HVFBGBiNUtTl>VBwp_5&8V<~w_eJ%ogKwxi12aa)PptICTWrZ}=aphQPgJX2a3ZZ%@*YCMv3Nx<+I=00tcr&WNwb#PRo$p9GA4RH|4!XA>@?Jf&0`WkVS{SgzHsS`AnE",
  "e7=)}BMjnmv4Wt4uPCGP8h+4)1?3H*??PB8z4JSb3BzGVl~ly&a_~em9thJ<jTVv-3*VrjggAruFfPFX&k2h%5_Eq}sxjJnh&*@PwmA5KGDjt@d+76dkONYk3`1@i?tve6-FkX=ulOt3b~rI90DQh%?1*a7Ho9y`c|cai{QLK@)xg?tFqc|7wRCKtG3DANUP788SnY4;xNu$xrS9-Lv1m_qKH}CS1LQeqQ@LUx1~vGyWkgLBHISB;cA`zMz@C14Y&!9oQwm8+65ZDz&eQystf?auV|SU{BM$6afRR%-T|cYcYqe>jht<=VYSm%X&w9}B5sFIWJh^LJ`jPnXANtD+%x!vrFB*mR$dpvHtoQBAiP=y{<;V8ik+ntiZ|vz#j1T_Xddfyu^1%^UJO?b|Om^KASx)qxbLzD;y?~F*i#w_lEx0PCTuNMlp!MwQZhVoN%1SHvt3o{KL_{sPYdmfEueqJZKzK0h)b8j^@lR|GuD7N1yW6NhwXs?<T#JY2DqRFH!C)@ID5=CQvjUYq)Q1@_(}FD$;d(EW8xF;DN9KP$%lru=-iM!oT|mi(G7LTpRkkK1%A_*oCTj?n-cY%#r=Rq_+XuUMP0pX!ZI8dk@tlQ-0w2i(04tCh11@Y=F4@J=dS2Ph^rx@%O@=_mK~Ftp<E$K6A@zTTqiRqB2^*a@GgEqo+X4R1#DM|EF7VCzJ+dM#9>ORqx;-gNi&FP+<ne~0V$42_qeOvf)sy}>4?wZWZX_29>;95q<iEcbD_}u@$tEStkg0o?E)41_MiYmkncBdqkjAIHZndjCU7zCNY>2!PG`&ASV+keHgb9wMu&OVU+DnaTXZDvD&z{8$S<?eztC=pI?~Qaaj!w0zZ-F2CUdQjt4P9!=Mbx~qpuBw>rh)e+S35b6s|)ktee-}<LbndoS*p1b_=`0;X6o=4ce-HlDO&<pt&Hp3lDWtqk%sGoImzvXqtSQ20ci#^e^#!GEC)?kDS6K;8^qo~)Xt*-n}upA5x;k_yo0hZK7<WJpwdl=GHZUWAoPy`{JY&m5>INDIs%~<7Js&Xp$y{2H9R#=Zk{8y@5^|$0XvN1#ki^_*?|1og5L{f=J-8``GA}XdCNtDxff90(Iu2m6YY%abr%@ZHGp)o4x{mECDM1*3->qLCmzD)m-q*3mh)R?D08-{?joF3R_?phmX#^r*ptBZ%!d5h`a>h$3VEqzFA@WS@fGbG_@hSSAh&aEnaz&(@k#+|uJo3gKlR)MJoXc7BZP5@Rs2<~%B?Pg#?gK6%*x+pDuDwhWHYi(`CGPT{A|w6Ke^x",
  "2_V6Z^1x(=%!&H1hWQjwMz5jywD<s^tOxpqiAUS{(bIaR;23c%h+?wqN6{hf@e9p!v6Efgn3@ML7A5A$17N&ZX%+71^T<PT@!R%izfo&*eD_lX+)|kK6T|B#Du7pKLO?zX?-2!&7Ag5D+i-hyL8{ON8XPX&+}gdkE*Rkv6c;|b(aazX@1E<u9RP?8S2LI%YHXiibc-&p6cgA7o;r@9c_n<MRYM4T|4V2)6cEO{V25Z@x;9_MDZHLd?8N3yHIfO%as{trBX=>Z^3IO*h&1}z(kX3D1AQ@}aekLl5V_4=$YgeTy%w#}tvAF-ziR2~#F@k0?A5Bk2ogx)xi-~W$9nB*k7n_K^lcnkW+>%CuUvOCHTED8CKM{mUm73e+|7y42XMH;dOAcI=)4y{xumMA(Q*DIkJXgRvsi=HwB!|^m0zi>R~7#SviMO28d?T)xaR4$PhkUWTTFrrB8PXT^b&S4-lhD`+YUZ@D(1_kn-HeG^+1-|+hvm;yw02D!Q@@mkmU~V9VE>X0~%>L%@rMVVt{j9;eOJP2}o?518;+g+hSK!N)`U20*nB#E#9l}P7>x7GxMa>K3h-ZpzK1XtFa~L5~-j|r_@XA?0+$;xopk>p49b&Y}3HGuO!}#3bC0aAr{4zeGfSZ4zSeI+;2(#+5W*fT;W_E<Q~+yxT^``?e4=RuN4_Dl4yVQif(zdZ-%3S(|#xid1}F$aFwKLK4CV%&m?7wz&{UP_l(-l31s)x*|4OncOLY+4w-Z1Kn~Rk(~G;*WM&r51NU^SrYUZI1o(d_{z_97<-%sm(3k=m+KO_Usc?nOh`EuTGgDE1>T(f7+ExiU4)fv_;`I}8FZSdaU>Pt}x7JzJ)TNSwu(@toc<YTmj>WZMsz`g9!WCN-&HQo`9d9DISRuq>JNYD3Hqh&T@{@@Br=3v$=jges+s~Es%k?WUYVXJ%PPZtnQ0wzSH+fe~wD7Jh;xda9BW>eTyS`Hc<7wv7XN<t&zoZH+%BM$4e?mZ)M(BIlt64+$Q@wx9U~}(V<tqT?<<UOW*gHK;hEFnkgYX^i2vTlV#67~x5S>_h_w21^OPWe5?x;J6-3N2*wP1L?rePXtOQrTqcxeF*k3}TzWqhi2_91TdzP1YM)}2)rlWMCG78{RD5*}77MPH*IZM+n$444",
  "E1vS7Ts4DO9Y%eC5rMyB{?giWrA!NnYDlB<BF_v*;*xY)e5{lV*jdPwt&oe7C?3XSo&rSJ^-p95A#5Uy90`_r&U#1&Gpy-%2EvM9hoHiRQ71#G2b*)g$ra8>YZAFTDmmJ)AxQK%rK0v}e-9@F#g7@zxD9VxG!BhJCdc$FIf#$|Ql9U&>QVK5a3(-ApLe&~I%A+vn7-Kq>7!YI1{Sc?w@)lKOb+4*=qJN`9RPuE*~51e`_radTSAmJs}7P-T-+xGg-atmX0-A~l5;bx(^(VjVQ<>hUEjQMMZiQapv`zn&F6J8Rp4n3*4*Pk`|Iu^$;r(-uAWH@0ZYMUusfQ9T5f5f@Ur~H-!eg|g$iPGK4Vzy9JyAk40g*_@hZ3#b@6$ya_TJ|3CjHiVsD-k11o+r_ZT$RWo|fT&N(c|mKd3rC%6YgY$1XJCT%rR<FAMw;#2OjYCRhDc#PlJIHph5bZRA1g{XR~?5UwxUA~Ari~Y;wtiH-W*2WCjXas}0HxnWFH8F6(0-qpqm^pix^wROehBlN?(@>|iojAT_6Ch^)u(-9TW|C%+Ip---B|2a3Q+nqah*-P62$hj`p*zE8s6gw`GO@I5UclV<iEH(76y50Ol$YpdWh+Ly6P>5itD%S_<lq-@19`(9y@S>y0AuFDu-G@58FQXX|Mas#OAxm2Y&U#_Noq2PzTybkMW&H@G&Vlx`Q5a5nxb85CPLe70Y|~s(AU3oSU;#*kE;Jc$XS;6YUbcvtna8S^=@mjdDEOzZWvU%g7!gl6wU6BQb3JByCngz@vS!_*gRP`0Q_o35|PD;n>MtHRVCtTyz-Bp+|n>i@Zx{8bZo+*n>PMni^HW1jsh;U7F>?GTxh<!KAa?aLDYL#gEa&TgG-9#ZO)!}l|pS~GhgS{gl&24k|*#n_HAy`SF)#-rWPwMPPP#ve085zPbTN*?eb^~j|W}3Spf$G=y-lfel=DSwa2s4%v;f9>>fXb7`1EN5dM{kMdG70pyq+Shjs2Uv-iaKPEWH5Qn&oF^Bl`IZRtl5bQU%@({{|&NwaBKAX&EQhky?iG<LAN(uo77l8K%N(p+s_pPxLLAAs7+Z}xUy9E~!e86-!ObNJA`Z}B|$n*F83@N}G9gcfQS>%Nd3-fQz_7U~QcC`ba>c4Fy-Dr6=Xy3c4zhNCdsvE@@(BuYrU9))<G1(ir$SfmGw(@26qxrF~~NDxI}#{_g|VujQIffD%(wD@kjSB-I0qKXXVau=KR5?k|qe03APUnC9bpoT33R~$s))qz$`<0<W&-fMGIqH_Q<(K6Os5|CC#5|D5$*NRoe;PMiDy!31m&>4^LLxXi0PinYMF^{y})mEgpa;r7dUb4zJ81(;4Pp46T?hUDk42t#JqKW3>7zdtn$&h%lp1%lf+Jn*<yn2gIY?^(u-`JYwwu$`t&W8",
  "HK~)YlkdE>ueCT}lx-e{ii6yzGy3C-d(+Cti@?r-%X*DNuWp9Gt(~BQGcY$GU;9s?6CdjT+j;|!{<{udESK$%OI`n!+U;{uFPz*BZ~Y2EC>>4&Llsiy<3x@lyK9)|T6xBNFaR8=tRm6f1Sn(h!?!dl6?J!OG`r?D+Qa({e|+IwuJ4SOv50#e>;1#Q0;3FhBdC%Ry=6k;#z59MK0qxa5uS4COPLg(LjHR6R+a9~MCuHUOHSha!WC^O_0|S%XFTzSTwR6(Af055daw{q*jag6a?rvPI|6;%%%=Lg+r-hQeWh!d7|Cn?v6OrMSp}GN9)Co;^RB+T<w#G+SFNt|zJ!DSgQJ1n&WaLuDu*GAS<Z=C@kxcF2DO~U-Pe-|jEb!WupGr&9HBGz#2P+8rNZHwIt^NoMGL6ED=;w8wCz)F5Xy!zjbI<Nsm+Pupo0hihof0E3Yh+?D9Gy!dc*v*B2bB;oRNU?to7-PIxy+KXt`<R5&rS&Hu2p)_sy=O`_APC*}@9z;Q*a(-+2IV7}v{Z)J|@dx}<R&iggS-Zr?%Hgot3pgtV<Dt}bDlj}J}51^S=vp%x`P<6aD3k&XU7bf&1)(>^*Y0|EV2&>;B5akxe~=&YXap};u;rb}z525$(N<jH8|v{lpnq9lXWz)cS39)NS}h}B=AGkK!No>vL!9a{7GkZs@6B}hM+7C-p->EOIMbVBWVyJ&A0MkQt@M~KiHW2(K$Qm%Bd)(<J@j8JVIzi*xj+NQCOU22!cmNiLgLbxapm&htLV6Hz==;PnP?lkJ|PfenhfE@O4xHF&N)C(G;9pPrH&sIAc`o&CyxO*gI!QfLXyVfsL*?XSCJ|wye^OSF7I;9gwI@FGIDQ^cg+}fE?FiZh7(O-hbFLg%0;R^)w8=1E$;@pEe-r%ye%-;_IXQKV&Fk`&m%ejL*wt*rwDP+{|KD5C`>)px_F)YMIVTYq4enGzy!~^cs7g_`BeFXli+Wn<}6G_Zfy>}W>^M7r?RS$?^=9uIGyloPSLx&r?biDf|b8ipZK3=xrq@p+>Row_u$U&cNmo)8V;Mo+(LOKAts%7HoLDpi-Boa&p;tU7e2X|>G>n~64rD~<InaCu+P;u1V{n!pWoSPlt5wE!uR~`%)QC=n1#{s46y|MyTS+)u-(@2FUeZeVc9x$7-@HynF{;4$DA|y>C50#^^(F%&^4|exH-OoE{^Q^HxhJS_;AHmLB`<5gpxR4U0CNY|3CLE0t6!rmee*R`m+TpHRfzHU3k!Uoi#)firMA0MW)mPqzf3Afqp!LeDYY=_+x{inrH-%22yxpWR&08D-%@Ea0?8i$c=#nhLEm%&h$E)N{MQM0I0EDv0_kY`>K%qR8qJV(o1}#o&Cyl}#OGI|~zl&Xm7h;VNUGWbtp_JW(`v",
  "tvwvnY%XTAbg){9Xh#?F!k&<7+&fTTAd(W47{e7YAl=qFwrcpg-jOD@><537Tnt)#LSe}oh6138CFew(H7rEG8nLvSlMV(&#j_3&QN)fVr9M^$n(wOVwotrq&{a^(`eRUYl>K<3YU-oYZ2bB~bg%~tJhkg2=RZSE0fD3Kpq%=&MU9}o{Qa6{p`ocFR*uv`=tKe58jgcvB-?`N7Hm7jfpBD@B{IBt`#?_=0nFGX8~X9>f*Pftpb_U<<XonU4VIEaMxd2<afdTW`#Etg9sd(g>x(m0Jk^I3h8p#6qWy~Eo97JtjWP<Y7Nv=2B3-STY)uV@>YKnIQ3{GMxf}ikxk7|!Ld-02LH%P`U;ZhT8(UFkRw*&XS~|o}B;@VVg>8Nr3M%@nY+6)#@-SoQ9K`9FV6iW{cUZ#~dgrTjv~bQZ;80!}`&MF$4MNQ{$0DcSdh*oV_=^{0RehBfrlT5&7SIBwm-8p0-RQW}E(m|HrFWQD&KAiGx4Ju_y7>s!85RIBcjtI{SsJajZ%$qJM1=_o>C3U$u~W8on-r@8eMC+)x$nP2%2czPk`_bM_d$kocpKrA`%)G+TmSE|SdFtRfIzXW$h30NKb;nn)W>_1MpUiJesjs%TyKJuN#O<YwLA!H9eT$<v<6h(n9If(zq=7K*zL5YM=*RS@@S;&5x_YZ8axBu$6oSs>xP9KzR4ed;;cZEag(1>Yysb%Qsz`&6kLU(j3He725&O>kS!dHSlK`DQIv8i6U1nWheEZptsx5WY~6ea8og?gRt>bfYdB3{q@Jp_B3}XKE{quHGk$exE31xqiJ>(E%^<w}K;GZiKV8GSYSypX37>9?!?kxqz0n68UZOwtH*IAVpHU`=IG{`W@9R}gb$&aO)bZlmG7AqHW|374Gk_k%X$_(qB!%3_5N&zLR7?|iLU(XzW&919#k0?SKmVAWsIe)MP{O0D6CjGkFeM_05Wyp2^FF5KM=yBnDhlDmE<z`!Pk{z&;TQ0K-nE&HuY~5hxJ0{j^CZ;G6wt`Ek?XV_?h1pMjbx9|+q6hday~cV{u$cb8F1oS01JWqC;c+3qAR8^wBe{*mu-SRXov0K7F{!!QEJE^?HLj&",
  "wXaU8eU_-%x?l9d_>5+A)SEqi2j<AsWt9ia*zGUnmo>#;inKXU)w%W1v*BeoKiD7oCSy<*u-|8cfgJtWup*UJc8<*%Eq-T~VKRJk9%sO95~yRYEKdHUih^6NRO%%~Q5(s0f9f#0km!>i^Q|n0tCS76=L!~RO8AIDs}VJf$Qeh^)U><xQ}88h5`>rlz%Ejlpf^|QB9jHv^iG7@7XY7452;Lay9BV$LEjr4AOFc7d(mCiQLB5H#l(w50Vu*`)dyL?*s;@+J7L<0fsSM?E)llc7B|s6J+PfOm}A&t0vieuzdryAl6X|W{rqK9RG1>0tBGh_9)=#s&g$luAYF`o3dCv|)(Qo@xw(_6+cWKFs2zl>aXQaCF>3C*LR;<8R+`8<QA}QaYCp>3qx{d#qe2?GE~kU^oWHZ8O4?UgvgV?Ff)Ri`hLFUUx^vI38rn2|wuAnn7-M6IQj?M6hNnK0DqLVPgdJs=$A~DRv3q>XaU#3^O3xF^QO9)*1=t(~@<#h&c5cFp#f5V!w|Sd2BoRK4i0n&&4rPHfhJ#BQq&@yk!itnLFM}cC7Bic}ARH_uTMQ_!vjCR8pR3>2$+K-wT$LyTG95T`)p_{SZ&q>U1{rbpcM!Ik^cKrO_#A29GwG3#C3I$-7Ph2^OdheB7_CDtmdUMFd5~D7n*At!O=NzxMtJ$h{u;P<%1~aYOb}K%=Q@ykn|;y$z(P`lGa!=K1<ZrJUu0X@);)rya&&>t@*7zb%f@w}j_|J%%4r1cTU%%zL9}c?3H_|g5yTs&F)dB-Em4AsY;He^KhoUqV|^2W@RVW+oGMJ&d+Wo)85Q4DKAm%zkGFKKQE(wFuao_2<Oj$E#SO`YP>12e*5XD~Ur?0nU)pzhFM=GOa$a_tJX*Rv1Nyp16M7l&IXt~yO_Erls4phx<~S{z!v"
]
""")

# -- Helpers --
import difflib as _difflib
import random as _random
import textwrap as _tw

_LINE_WIDTH = 70


def _norm_answer(s):
    # Fold away the differences that should not matter when matching a typed
    # answer against an option: surrounding whitespace, internal run-length,
    # letter case, and a trailing period.
    return " ".join(s.strip().lower().split()).strip(" .")


def _best_match(raw, options, cutoff=0.82):
    # Resolve a typed answer to one of `options`, forgiving tiny typos. Returns
    # the exact option string (so the caller can decrypt with the canonical
    # value), or None if nothing is close enough.
    norm = {}
    for opt in options:
        norm.setdefault(_norm_answer(opt), opt)
    key = _norm_answer(raw)
    if key in norm:
        return norm[key]
    close = _difflib.get_close_matches(key, list(norm.keys()), n=1, cutoff=cutoff)
    return norm[close[0]] if close else None


def _show_choices(options):
    print("  Choose one (type or paste the exact phrase -- small typos are ok):")
    for opt in options:
        for ln in _tw.wrap(opt, width=_LINE_WIDTH - 6,
                           initial_indent="    - ", subsequent_indent="      "):
            print(ln)

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "yield-yard:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret


def _run_snippet(code, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.py")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([sys.executable, src], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return None, r.stderr
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: Yield Yard; importable without a TTY."""

    slug = "yield-yard"
    title = "Activity: Yield Yard"
    description = 'Eleven short Python programs proving, by observing actual interleaved print output, that a generator function pauses and resumes rather than running straight through: calling a generator function returns a generator object without running any of the body, next() drives execution up to the next yield and no further, StopIteration signals exhaustion, a for-loop drives a generator automatically, a generator expression defers its side effects until consumption (not creation), an exhausted generator yields nothing on a second pass, an infinite generator survives only because consumption is bounded, one generator can be piped into another, and yield from delegates to any iterable (a sub-generator, a list, a string) as sugar over an explicit re-yield loop. Every output is deterministic on CPython 3.10+.'

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def run_all(self, tmpdir):
        """Run every snippet once with sys.executable; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _run_snippet(s["code"], tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual run-time output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return result.get("canonical", raw)
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    print(f"\n  Running snippets with {sys.executable}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="yield-yard-") as tmpdir:
        actuals, failed_id, err = ENGINE.run_all(tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} run-time error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
