#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/annotation-arsenal.json and re-run the generator.
"""Activity: Annotation Arsenal

Ten questions on Python's type-annotation syntax: picking the right generic container annotation for a described function, the Optional[int] / int | None equivalence, reading a Callable[[...], ...] signature, comparing a TypeVar-generic function against typing.overload for preserving an input-type-equals-output-type relationship (the C++ template comparison), predicting what a static checker like ty or mypy reports for a mismatched call, the honest tradeoff of silencing checking with Any, and the classic mutable-default-argument trap. Every explanation ties the Python construct back to its closest C++ template or const analogue.
"""
import json, sys

# -- Crypto / obfuscation --
_KEY_A = "b69f0a8023e5d7646cd0a672a56b31dd9ccf4704efcb1d83ba20f275a0085747"
_KEY_B = "30791681677e4470fe6f83e5246a96c0d5cc1035bdcb7804d368ccd8b78ac2b8"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "a2e7a642468f1f3e5f9a24842033b497b61a003670bc59b82f9ad40417cf0b23be4de20f0a5d24f65b5915d323ffd0479f5297955d8106e77de6ddb964d3fb5dcc23d49a5a"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "code": "def totals(order: ???) -> int:\n    return sum(order.values())\n",
    "prompt": "totals takes an order: a mapping from product-name strings to quantity ints (e.g. {\"pen\": 3, \"mug\": 1}), and returns the sum of the quantities. Which annotation correctly replaces ??? for the order parameter -- list[int], dict[str, list[int]], or dict[str, int]?",
    "hint": "order.values() must yield ints for sum() to work; think about what the KEYS and VALUES of the mapping actually are, separately."
  },
  {
    "code": "def resize(pixels: ???) -> None:\n    for row in pixels:\n        for value in row:\n            print(value)\n",
    "prompt": "resize takes pixels: a 2D grid of brightness values -- a sequence of rows, where each row is itself a sequence of ints. Which annotation correctly replaces ??? -- list[int], list[list[int]], or tuple[int, ...]?",
    "hint": "resize iterates pixels to get each row, then iterates EACH row to get individual ints -- that is two levels of nesting, not one."
  },
  {
    "code": "def find_user(user_id: int) -> Optional[str]:\n    return _lookup(user_id)\n",
    "prompt": "find_user is annotated to return Optional[str] -- meaning it may return a str, or it may return None (if no user is found). Which of these is an EXACTLY equivalent return annotation in Python 3.10+, using the newer union-syntax spelling instead of typing.Optional: str | None, None | str, or both are equivalent to Optional[str] and to each other?",
    "hint": "Optional[X] is defined as shorthand for Union[X, None] -- and a union type does not care about the order its members are written in."
  },
  {
    "code": "def register(handler: Callable[[int, str], bool]) -> None:\n    ...\n",
    "prompt": "Callable[[int, str], bool] is the annotation for a callable (a function, or any object supporting the () call syntax) with a specific signature. Reading this annotation exactly: how many arguments must handler accept, what are their types in order, and what type must handler's return value be?",
    "hint": "The first bracketed part, [int, str], is a LIST of parameter types, in positional order; the second part, bool, stands alone as the return type."
  },
  {
    "code": "from typing import TypeVar, overload\n\nT = TypeVar(\"T\")\n\ndef first_generic(items: list[T]) -> T:\n    return items[0]\n\n@overload\ndef first_overload(items: list[int]) -> int: ...\n@overload\ndef first_overload(items: list[str]) -> str: ...\ndef first_overload(items):\n    return items[0]\n",
    "prompt": "Both functions try to express 'give me a list of some type, I give back one value of that SAME type' -- the same relationship a C++ template<typename T> T first(std::vector<T> items) expresses in one shot. first_generic uses a single TypeVar T, once, in both the parameter and return position. first_overload instead writes out a separate @overload signature for EVERY type it wants to support (here, just int and str), with no shared type variable connecting a call's input type to its output type. Which one actually preserves the guarantee 'the return type equals whatever the list's element type was,' including for types no one thought to write an @overload for -- and which one only appears to, breaking down for any type without its own explicit @overload line?",
    "hint": "Ask what first_overload(some_list_of_float) resolves to -- is there an @overload signature covering list[float] at all?"
  },
  {
    "code": "def double(x: int) -> int:\n    return x * 2\n\nresult = double(\"hi\")\n",
    "prompt": "double is annotated to take an int and return an int, but this call passes \"hi\", a str. Running a static type checker like ty or mypy over this file (as a separate step, before ever running the program) -- does it report an error for this call, or does it pass with no complaints?",
    "hint": "A static checker analyzes the ANNOTATIONS against the ACTUAL argument types written in the call -- it does not need to run the code to see that \"hi\" is a str, not an int."
  },
  {
    "code": "def process(data: Any) -> Any:\n    return data.whatever_method_i_want()\n",
    "prompt": "data is annotated Any, and Any is a special annotation meaning 'a static checker should accept literally any operation on this value without complaint' -- it silences type checking entirely for that value, rather than describing a specific type. Is using Any here a pure improvement over a more specific annotation (like data: SomeSpecificType), a pure downside, or a genuine tradeoff -- gaining flexibility while giving up the specific guarantee that .whatever_method_i_want() actually exists on whatever gets passed in?",
    "hint": "What would a static checker have caught here if data had a specific type annotation instead of Any, and process were called with an object that does not actually define whatever_method_i_want?"
  },
  {
    "code": "def add_item(item: str, bucket: list[str] = []) -> list[str]:\n    bucket.append(item)\n    return bucket\n\nfirst = add_item(\"a\")\nsecond = add_item(\"b\")\nprint(first == second, first is second, first)\n",
    "prompt": "bucket's default value is written directly in the signature: bucket: list[str] = []. This default list object is created exactly ONCE, when the function is DEFINED, not once per call -- every call that omits bucket reuses that SAME list object. print(first == second, first is second, first) reports whether the two names are equal, whether they are the literal same object, and what that shared object's final contents are. Which of these does it print -- 'True True ['a', 'b']' (one shared, two-item list), or 'False False ['a']' (two independent, single-item lists)?",
    "hint": "add_item(\"a\") appends to the SAME list object add_item(\"b\") will later also append to -- neither call ever gets a brand-new empty list."
  },
  {
    "code": "def safe_divide(a: float, b: float) -> Optional[float]:\n    if b == 0:\n        return None\n    return a / b\n\nresult = safe_divide(10.0, 2.0)\nprint(result + 1.0)\n",
    "prompt": "safe_divide is correctly annotated to return Optional[float] -- either a float or None. print(result + 1.0) assumes result is a float, but result's declared type also includes None, and None + 1.0 would raise TypeError at runtime. Given ONLY this code (no narrowing, like an `if result is not None:` check, appears anywhere), does a static checker like ty or mypy report an error on the result + 1.0 line, or does it pass silently, since safe_divide(10.0, 2.0) happens to actually return a float at runtime?",
    "hint": "A static checker reasons purely from the DECLARED return type, Optional[float] -- it has no way to know, just from reading the source, that THIS particular call happens to avoid the None branch at runtime."
  },
  {
    "code": "from typing import TypeVar\n\nT = TypeVar(\"T\")\n\ndef last(items: list[T]) -> T:\n    return items[-1]\n\nx = last([1, 2, 3])\ny = last([\"a\", \"b\"])\n",
    "prompt": "Comparing this to C++: template<typename T> T last(std::vector<T> items) is instantiated separately for EACH concrete type used, at COMPILE time, generating genuinely separate machine code per instantiation. Python's TypeVar-based last does NOT compile separate versions of the function for int vs. str -- there is exactly one function object, one set of bytecode, used for every call regardless of T. Given that, what is TypeVar's actual job here: does it change how last runs at all, or does it exist purely so a STATIC TYPE CHECKER can track that x ends up int and y ends up str, with zero effect on the function's actual runtime behavior?",
    "hint": "Would deleting the T = TypeVar(\"T\") line and the annotations entirely change what last([1, 2, 3]) or last([\"a\", \"b\"]) actually computes at runtime?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "C?q}!psyR~*hcqBiR`CfD#cVmp7>E@OA;X}7i@KcSVSufmzNE&Osqr-Yan#}ZCO|o$dRbF_(7RbbiKs;?JPE5%{`!E*~gZHF_lEFbNMIIe-=IBiZ<f2?${-u6tZ(&KjR%AZc0q_nQODfm1kQ2;lFJ6+IQ(^=k9C|aG*k$@v#m@Sv>O{JChf8Jg@!;lWXhmwpti1tRVZjXcmI`Q$sO)H|NBu#}|QPHE9Y%M2d4P2tK4)+xl+p9wjqc);oDYpA)WX>Z|cP_PUSTE`?j~h)%G6r$%g)WDriqn&PcPL#nAe@o?lGy!797;j`;tqD*2kqzu{h?vYQOk;bt{7_1g%**{LTDXegI1QSjAU7ICCR^p!u^LK3ip390}6@@tXi*mgazcNkzg-$|F<Aq)E_Of+|)iI3t*anu$({tVB3I7hJw0!+oIL>kX{&#}?lxGPE7yl$*EW(_OHJA(J1DOsd;4k{f|4<@m<;t|V4ZAO!qvltA;H<%9jp*sc5`DES?Q{yNm&Lk)l73b~CLg?7rn(Fh7ds2HBY727VRj;qda*t@@7sL)h$04efy0q|X}HR)-B5UQw~#`?2y>KDc^2YpmGvj2OP{)+bR_?^!8X^Ppjb{N7z^r~-If~Ns<vkK6|Q^Nyuc%i4n(szE(i?)K$&mn;obndiH*I3yd{&@peSWE2L`;9u5jpp_FykKxw_mxX}+C7^OsUAeC}8zlx4nNQ-!y0+Z2-SfnSpjWH5N!CA!>}>aq8u^vnai=HX^>w0wpB<13lj06Ix-ceBV0Nr?`TH+mY?e)n|O-hN{-a`vxEh3C9c<i-bF0H6>mzy`XI0N|`=Ws!nc+R{sE`G#fRFW23iY1ya{`R8zViAh`za4KV52b6F$FsLi#iS1uW2&3VRaRz@oRoEUPvm&+DKPc_b)PrEda~Ak3jw_xa+G3ycHK5U<?~G+;DRa%cnp`J1XlJ0S&?PEEvH",
  "(Z@0C6T#1By=$T%yWh5ZlGg)l&ZJzvB=bSFPPlTaVdTYoB|9sO3;yX{5!C!;Nd_Y`46IInGU5yzZ=^uTBbVt1niS1u=d2{JZWa(ld|~_Cwqb3KGS1-Fml#BFWC1Sh!Yj=<UvQ%kYJLEa_v#h3>YeZ1xIvrh<owS^i)XCY$bb{2f1C+3oOPI8?!8}a1M%jKaVOjFq2)9pM&U1fVg|)TYl;@QlG8su@3suziKjq*BBFu1>C!ggCoo{@*Ih`gcI{y1M0<oqj4LI{TZE-Q^9Lb_A9A;Oyv~MDrB4LNFrR5Gf&Y>$1HW$QjeEiLn?a%mnZftX!o<FT9^a(N*26>|V3&CAzy^HJUsgEPgE@?rya2fz55kW19lD2gMPUQXJe*sP;4Jse(GIP`9^@-TMQZ$U*#t2K<d+CjE97@(FiDoHNGTyYYnjnUC||Ox2CPQY3tQW4fw$7iikxAd9MvN_(2(`ZUsI^7w2rx(V-#S&t(ElJEiC&kFD@uWY`ZCA)}pu+Pxw3?R`y4n;sNGV8aBWnA9#q9Om4BjWPk?Bk)a%w+bCO({2Pk#J<MF;i<SoOLc`!dSnHO*uAT>;XJrH=3tIKlV_pYhHjQ@c2o7j<w}(pyO`+yE^!yI7>a9V<ix~MAY3%!J{y)Xo3RnZKY!Q`v+>6CiT-4lPboik-g>+Mobo4}g-_e%1)n>b<sBFYPbytBx2sY2q210GGpbHs$`*MQjVZUQ#+Yo<Zx4d9>8EUPY1NGF$oq<8Ln7xPYnk$7VuHC?>ceyWbnIt?Ph+4wvBSL%bSrs~``M{2vhHrFeK%ke!`9WY6R$M6Kq$2+mh{E7R-_X#ea%mqqTt`9J34j7`Su9#sE;k;M+lm``XyK(1YuM-ywBj4rm%*xNUnu~PtHXNQ7YP9W?3mvF*bf*|K?;Q<x4ez&KzTc`9mc{7C5q!Fz*gKUsiDC-0j(CM+%q5ud2?q{vLA#jjdguAXgk%##5LDOAqg3*7e?qoQ&9",
  "wjztS5KL<KCNz(wiEO(zMjk&aE^|G7!wr+gE6<}S#6exEnGchygM0jtXNAouT%eCpPPDBE(za3w2i#29{=u>VO4=8vE=I1-Y4n_q=HMTP7mHV$62L*qR1mSoK9#z~Ss?r;$#XvpHbmp##TW|AMAN6$1WH^*f%-k0hops^_B)>69$#-39Y^glK^BYG_-b~wCw1syPu&KXnD|d#OC2>F;%^`DdjUp^_>sjQcY<rM<o$VEh)d_T<?b{M8`0%`li0LJcy8oo;{@1?D9*3+d+4JdDICGjsb=$5l_mb+h9mt+RE&+fXR1Lv7mMyR7d6=3H3ODXM3NW}xB}^K*|yI|WMY{<t=1qwZ<tmmXFwcLluxu$R%zNqa$SPuS|WuXP1BJ@S}16I%4Bxomfm<K@FOQgs<<glN?UqR7*rW0J?ppdE@95376OkUUa&pUwikjvq29RvEeGXotE^@t5?!$$;?4-Pr-xdqKu#%#)rikWL0J~BFnkLI#Joo!fa?)(y_h{cvmg4~(>{1g54iH<;ut1BSiBV{X$1b^#(tO9@YpF-XD6+qj59YFFE*z_0u?mBaW86!hvGvR)gX(?){~0LAq{JSE%n_CHJ~)bX(}&1bb_3J$F!(=H-*UqpRnDwCUS2mnKIhVAqN}ug%zk7j?7f|e~VZ7v>V|z10LrBWZez5e+L;dEYt**{@y+&pyA+3#g{8bBifn)YF5KpW}}4U<bgk(IpJXV*T_it_shmEtH?4-e1u*@swT6^X9T8}F0(|ICu=;Jk3;<H@H+q-QwhkQCw5{e(=JN>c+ko0W`Z%fTN^?tDtZ-c8$<$^OSaMTCYAxQ=8Y@qasZZZe|6h>n60$~+3h;g1NwD_<$Qs*y-RbSfnVUq_(sX&-+=|H{Q9jGUap5Fwq>T&wXK<tW~`lEc47|EblOT{*?F8;{KT4rpci;n9ZFV0Ull@0`plH4s)E(k39yaFe_ucArkksQS05{x?09K(@zEh=1ULRl=nft",
  "Wno%R_>EKl?>-Rf5G-IaeLvNqpoj=t3_O}*A%`B~LDgFS&q7hm_H?Q@jdCGwCZ#ZA!dXFq{X<H7k8P3jTEw3arq51P046?22u)9}co_6RD{?)3>4Qv|vRwEyON1PptAjRsm0)fI0&Gdq9CHT0_2=GnSM`Va0qcxN-E5}PMsAlVa9=R_u#lg)i@NHNB@C@e*i&C=@?^tT*aRy*iwb;rj)Sd@+Qy?M___0LQo0pL&WwPd5LwC0z5fevy@aMByyo#2X6XMS>7umTkAif)CgD0{z>h&SUh-#D`-{xRAdM<CY<;Bc^ZS7W6NbE$IYuEH9`*B`EuSO2Ku=Gg=HWidBsOI);KJ#fKf)BhlGcmU0s6}T7cplurr;7zJfn@)MX^cC^8)m9e;09huypk=Q05in{uG^36)*u9pV)BTT7tjsARIfCR9{`59k+AU+lsh0<OqZ$kwv9=JCrBke6(IOsS_nSQ$m3U^ib1&7}ZH+5SkD_ui_C9#f=8%6IXTH6xPiEG3GFGo^zsGaf4@1uNH1b=nIvzuS~i7Xq>%Gb6^RA@%=6K{>z(I9vm$V&D@ND_~Gqky7{M9*X`VWHS33m;zx#a^YP`j;{m@bWet5#24OzTFzt{PjsW!X5BkU+Pe`T|>E3yepo39H1C#LDDuG)(Tf=;TT^b`)N%Q=W@GTpy&#FNu1RU>HalL9DlEM?rv_bDU?-zP;A{+&7`(N57CZl*_VuCJ>ti>daP%|#m_f4|lX~N4BT(}W_keH~vaI0rRUgK6Z@tJ&t3?a%epH!qoNJ_0z+hg}4EV*E;wz<QYUm@Zc>}erIjmmDW4c=^4qY5oDiTfGk7<j{lffBjYKl?ukx*%DSMorjJvcdI)r}~w#;eF>yKbM*ZWTqD!s%N6t*S8Ba;D+?}*lX?x8(V4u%5mKm3^+BROpfEQIagU~B_WHMz;6z)8nbHR<Mg;|BFJ2PHt4y0A|vPZir7=ocoN05RVs_KiwU-f+i|s|-z-bwdkpLN0a)^H#n9N{LEgA!1=tg?<26niyE>ffafxl<!iH%%C+m`Fq#9l+<<JIbr3s1g^^cNlPqV2GLB&j1O0C81MzTdIpn8XWluFtXzKX9o99YDJ@RK^6i!;WaoMTXOo``FEPlK2bIL@gKYcjrU<#%-`e>=$PG1R*cIg3YPe;H2r&;EB%5cbPt{$JjJ%v1j$k;2sKOEjAPpY<yXNZ;b|",
  "X{pb<B5W_<%h@>a!S5(|Tco%n2;M7RHroi_2sdVDYGDk4NUn?FN>qJ=!N=K~jm{z3unIRa;fHsiN^#^t2`6VHMh&?jLi~mPodhf3D0hMn#Wcn>1?k)FP1tqXe={pwrefF*C3+I|C2vc{iCLr|>t_n6i~&1MztRV#kCNQsjuqsHhX+#K`EHooYJGz2f&U~5yu26Yy4<xfDC+;h@pYaf1TMrsF5f;@Pc?Oh4QM`eB2Io{q21Z$DO=jOn4;rFCXwz_G|wJ$a_e!URRh`Ta5vWN6LmzGj}ez1dU1nognqN}Q?z%lEqIl@*4v$am%M?qM>=id!Lm>boj~B9hORAQNMw)IdE={USTmdo7OIp!ES@=ryA8=3*Sls2SJ*W>wqAAuARh+jVQ4HyCEP~66dGTITtln}Xodv+uT9g*XB_Jdae;6Kb^|P)u5e<BrPX3Oc9gR=><o3?FBrvOqBKGeJAy--hkzujA9!XO_-RyWs@bcNbZOw$`9-BKMJiCAs@bJd1D_gzi#SQXV!(8cvide_pnuhlta`F9go#8^YZxh?Am1iTk5REv^4TI{D%yRL&Mb>0(3GH-JGk?(E($knia~>xG)3FZ^hYIjZbZv0b(}fY4%L`mI_%|>XVD5J3=e#`lLT7S064y0Yh*`NZX!%FBe0C*Oha+TU%w@xsyIwUeKrT7wmcw+_AZZtIZlqCT1YL#F0lCT<%v)S{aM?viH3vHx%tmO3*gi*;>E0Zu-v9n4t48Xox>LfdL0uPHt>P}&^UjnV`-Sn%9}LI>-EpzPMI>X{iQCUkw~;@c0gu`Wcl4t-?mpUm`4BiUZ@h_d>~euJz*a$jF)LDJ1PN8oMNC@T#r`S9_WW+2I!$@GyGmv{3K9Dn<+N->pDb_*x(Z?4tikkXGh<`F1|Xm`5qX&sBTaXPyzdjl=6Olo?2WjUZUp~9n<G{Qd81)8u5nf3L5{Ryt4{^7iCZb7T%*U6z4QngiZ#Ti)D8wU<OtgL0*T~lf-v_17ajpe}tsf;{nAmx@Uf7W8nI!M+aPpMxUBV7CW!q@m)_({~DRwo9Px2>x3r%phnGg7tA!(4J3obZcqALL9#HSL?Kkp%eaE8-)K#$+L!y#A-f>M_mf3FAidd2^p{ge)Yew_s_jF;?@qtm#A%#(Y1J&A&1@3JG|zALi1kQSc+ffC{mi|6r1Z`%MdimauvW&)fneU*HmARbiV$Uqb2iyD^4}~hgtaajotE7uo&1Z_07LwJv+S%{BytzaGb^gPBwAOeOUy4YtQ3k!Z<a|A1i}>sCAM+OrQYpPD`ckP%S0~#{IUYv4#rGO?&-Cb089#CLJ&j@Gw-#hHP7!VrllPpWymo$vHLTxX0_Q#{fBX^O=|m|>=-(+thq1VFab>am)I0)d!&Xm?@B*3uR)U`n5YG9kxJT{=f&i$-U2QPPG35n?OvIiN16b=*^I(?Am<6jFj{fwAci(iKJi&cJ1(>s)Cq0S@d6uFi@Q&RV##u<X{V@vQAFL}<dhCv8bd>`?;ov#pAu#bv*gU<-XV49NcrNkUm(Hw3zK6~75Sj^?<vsD_@g?`bBqiWC0}*l36ywtP6XIhg@!Q",
  "br#NplPBR~t{r;g{5am0nDb$54=ce585Lvp02|5-L|uqFu*M2NuZvYkR#S<ZOX^0;9!?gb*K#Nu+;g$@<I?pvD;^fI_g|s7JCPJI%Wcrt&t4ndafCL6P9Vi`Jy^1Kn9`}W?5b`I)W+)8@Zq=;P!IU$nNNrYhbZEB3Bp=LQC339&yxAj9^cNCq)OO(%kk=C%gxF~Fy^{To37?_^sgg3%%)}k?Y(yA5<XTjRoz}N48E4+i_J?)mX*(f=F|R13X*>v+6T%~Z3!#CQe+c8db8WM1U%X8?4)9@g~9*dia8$3mW_2TYbc0-AJQpTw{7MwbQq1VKUC3+o$g@FcM$hv%?+je+o#V7M#MAxi}EvcWTN<cx8q~2Iy&pWt-qKnU{!Qe#wHH2BI2TuMog4S>7bj8qG6#ugQXW*dsD7e+LS}S2JbaWmAsX{16&weO;9!r+MfyKj6XjT8yU%i(LQJSPM_eeQg3piSx5R%mVX9{Ct-=mOWFxL+AUqHB!QjE;%t1X+Z*!_hQXbOwQ)|ttl~{Igp1L;N>{<=YLy$dwU6I7NR;_Q+P*?h0mPc*y=<(Q#h(1ve$oTUSitO@eU*q2`&d$N;Knq(1h!WtkYO{*-nhQ9E`Kl0#`ZXFnOj_6D@lJbTRdkcWXBdw0Io>b7=)L2|3FqUUnLGB2-akP#ygf6Uw_24&`*RtMGywl;J=#&kG09I8Harg2<BSFt#|WapD51QrsKd`KK?gXd!&Xe8^@bf$OYcbDUrRDv#gtZv7_?{_3?DBT~Stcf}3=|OI0R>NZ$xwyGOthMeB#c5S@clnKOFq8ALHOJHiQ8T_Xs~8>9BQxOT6#VJ9HEH1(xS2I@)~(@f9Avlqyeofcvl|AV*f&m~08(N7~U1l_VV-vU{9L4d<5o;vhL2Ck?lgXAmr1|09_&$G$iQ>}{(P#q1@z%CQ}_&qz0t+{J!j3aKX>qmNk(ZNX&FbXpJkuHU>qmOFF^3{f}I3OFIMA}e|!}ADrj$17lWFm}2*o@Xy3%CueDejohzAI$FZTm<?S*}LBMFUP1>3jQlOhuKt+!Z8{pUXd)2OAGmJw=D%2julkPV$Wwdbhx(Lz$@vbT20CF0n`Z1xB`yyS+kJ1v$qsAD0sZA05w-67p#s{D7KIb6H=CUS09aiE#=pr`v2X+2=X4@MSps?SZi7DuBhzvYm;K!%hPR-PafI;3<zIN)Az+=dNMMqCU~<bx^yUOp<;BURHLDLyYW}qE5)mSN5wU#X<9aOyR=",
  "KMJqA<uq$AMDK4oZ4C;oqJxFt;&zs@aG}xcNP}kX@=-|i$*Z?(T)bD|drx2L1ktq9y#vvrO|zIF&@GNTIWI!uDWu}aKYT8cP#=&E6GqX*b{83mq9Rm0nv8Ob?E{-4hVK!?z?yP~+w<Ve09NvuqT{hPORSJdb8Z9N>y(NK-uSd88wt0D3O5mAn)zoqutc0yJZj!Ip|;ei7<XyntAcz?xDxv9nqEfIGZ%x0EoKUIey|Pezp@RS*fe}uo-M4oAd@Mzw}Hm$`iM^WSUf=IpO*Sc(K2d`-YkfRsra%8x13vCw%fnRR_j>3@d2_#_S%nhOc&kn3x7ZB%f(R%wCt0#O0evKQ#$WeQ-+xO*7?aWtE9ZzLm^mFM0QOs`9?U72~2ZHK13ZYfKX&fV0SBG=&b|^ktp3~Ni_OO8#RmWGl%{Fu!YG!6NYEZR_7)+p<DSQhi!;|7=RHjB~h)JdeYq4k!r^T(u|PoP@gnIq!dX|ACy`F+)m~<FJ)G<ok8|Nz)oV<N7g2CiJ(F_%PLpWD=Qt1s8`Zaup_(T^e`~Q<yy^sFTFfw>QB7&BX9JzBt(9D&%uDXIE3@h$&mK;@jR9CJ#F814@p-4uG$m_H$fTncXwT{k`(ld(t90D&G~72|6X9!gKD^)<tM3^|LVebfSU8+^JfkycuppJ$!+{le9GIPKU6*r#J7^I@JKd^-G^vNG7he1xHPq!Jj=Agcs}uu_4uvmC<E@XG>n%BU<@SEAt&dGdigbgpEor?(Wa;jzQIlFX?#nMPrCIH{^fy>bdUP+e3_|RJ~jld%_PdSvQz0g2It3gY~7kDMHl=9fM4SH-;1eDMkL{Dp>Qot7P=!7<02ii35_T1S%X2x_k0#UGBDllrWiIszCnd)l`y>E7kV2heR}Ca+z0PhVWw!r*WjAJd389lIs#P=#oq?~N;icTYcaGMAJ<q1haVULSew$f&?$rO5K6VK;TuuCyRZisM)S~20nt)lNuq{l2l%>F%KSH9NE_Ex{Ml4^ij8^C>iiwWMdTT{r`j;1QpDQNz-b1>--pk{!vr<3H=lr)tKukaW|7n@(43ZEgC$2nJDlI5%68gnE2X<jxSSQIYrC^pb0i=o2|nh$DUiOISa$ZlOtA&IW+x<q%K$FmP664ZF-4fjLpm>l4*n%%?_PHr#I&VKK}OOFG!>Aatv%{0gBe`Sz#m<IGkTD^L&_?2tT^lqozQjEpqqlJ0rij_<S8H{u$*H^#@u_kgbgBj5}A4m0=UFfDp|MIan3#6I#lIj*=J0+7q-@J6LkIDH3qA<BClcp&rB;lIloaXZwif~?3U3A>p`rQerrk5xE^-B#E*eYDz*?NejigAP7@SQA#-+*uPsrL=98{nQM($lC4=qpapC$X<tC_pYzMwd5?Fq$t7R{g1tSBQpil(4|2910W7ebfRn0qP|I7=Z-=&fot>xUGkC{Wz^m*_&kF6Egto8ZUgkSo=hfOCFr+t1+6c|#$Cyd%snE7w>3I4ba77mr9a^1XR;%@(lqxJ*dv<OM&B8dxTDp)$^GXjp_9>E`hIVzRskoxQXosAc)QbZz;9teIFaz52gks5mdUx;2RTt;QOi8{<e=1vp?J^795F7)(oB)+pSs&H-}2|8IcW;m%bEZ&&aye4waoiGsmrXOZMi@DLHQFuY4o$oFUEV8B)i{U0WwCZP%AZhN2>L25Y=^Y2&DMt-q1rXuTJncIC3rP",
  "c(~~0I*|;eTQ7~dxwe~(Q;B}MjRs}YePG&-x8t_=^C6q&b{r(hm9hJ!uYlKLKK)H(bnQ6sKW<%sOA!5<J*s7SMXpVBSdwg;s+%#1K2jjth~-*LsAT!YN5}f4Jy(=E57qaS)0$w`K9r8K&3~8tzHAf_AV+)>MS1$j#+!>VZmZ`uWVd$cg(u^QJ(X>-$DAkhop&Pn9WYL>QZ>Uu8Tz`>qXYpQonx_PME%MzCmD$GUH~DjTF;zjb?~sH!1olyY*B!|s4C0ze9<(^V5pn{6JTd3yH&QyJh597tD*8~(;TAQSuJn3PpO%=I!^rH)1TDjlO|q#r{@b2*f|E`v|M((MWFm=EYtlA2lvEf$_+m-1Qx{Y1gT1(?t2|d!$@a?_N6_4fJQEMuu~it<`j`iMG&B8SKemkbO)j)v=OTKf7UUzxlJH#oQv)H%DUMM7T&#TX>_QT{b7W4AFH3=FWK>6@*qZrn2@b>+D)zrqDjJJ@e0r0D>+t}rlLjYkI~B3pEitQ+@*`chI=EJPkFq`9QqOC23MwAlYm|HFY*v_;>$wzFk}{e3o_ufM!2tfA$iU#6AOfFpk9>(#(sawVMRqk8Jjx*%rSYgug!95SVx*iD#e{n>F?43q+^k>)L&~Y4;-!(jWGUh1nk`7y1>GzbACY3^uNLXI`N=u!-D2|(dzPjq`I-+Vn4!9k2g&^GKE3uxr&wm31TYFXM~gycqbPxXgJVLn2vNHQu#+O0Oa>Z&a~bV>uhsV<H-Q;)gao$F1DOqF>Fd1=VpCrd$DK1O3rdKmR_*n6V{aGYuAc#L-Y1$Gqk_~yztp_n~LVavD!2vtvRs6q}Bm^a>KFJ{`Szk5%Dpr*+mS+9xyfi6*k{ceRJa<m1omA`}2Pcim}i8k08cnJ4hk)XmW;czur@qR3S|HbZMKPdwgHeYT}f)#8tN1i@{*F8E1a`LQhU~mEF&i=jif6u0T1pg$~ji1H)0>v`}H)^=kh#4JXaDgB!XAKs#h7+A?0Bhu_$-S0E|0H_i@aHR1eB_E&YiRLo=kt6u3ITZuf*y%jCF&<x0DH%xZRaFb8}(#q4K;u5$C<*Coz=nmr(Z>w|H%GmkC9>ZdjDQnYm@J`vlBtZ=SBg&#WAe`sk=&Y^%4Sr<dJc)|$6r_MxLIEXJJp%;ul=*%$svD4RAu%wVG7e?z$jxlVIabyrlH>Co$*=FS;LlKhSo)hJB#uF<(%uI&$)l>snmi!)6Ab|0!3>x(f>^37ibv%QGgH+6SR5|4R$Qv)75CvM;(&@sdm}d>m6*~p=uCz2QqnC3Cj|#Vw16Mq)(KsIDu=t!D)hT6HC2S{zz=VU#NHk6T=SZ(vTzEd)bkDlY!$@mL%*$4@190L7de>uca0+k%!a^V1xN",
  ")@G0yJ7zz_!;)k8Qj!VloSQ7Z_Bk)9K?jt>gN`YFgvr4ZBK=B|t2!>k5d|x2vEBJr7<tggzv-hKDm$YjK*eQZUJ*|^osI>a_?&|}kYSkdS4J5enPL60F%Ymra;_u}q11VCyE+!xoCubIz&@nLRHetdl~}8->tl@FG_~~<OV&-!4cj_@<K5MMfi5<Ymv7?wdB+!Nz$YCy2v|SFeaX+i&qE%G8en>nSxmk}N8b_b0l(jc`o3!Q#tLkEWI<JJbM|0<KWg<YxoK3o2(;DDdzl_VAuou&*NWr5e+q(V_e#ZFNp>tT0M{8i;NveIXm)mq-vrKE;|o@m=Q9vqWmxph=%rmqeOH6BL6gA1)v;ceQjl~Qe}O_6uu{sTsl90ZF+{}-|7m#S6K{Fj`5f5O#O!GKXr$Y!@IPDxb1n(lg$=5W&lak@#h5|YVxUV*9(E}EHr9vRsp_R=MX?|uOxpyeGtI#4EhhKR#_p3%8-}XrDDbBZ)P=;7S(!}5+P_+;XBe*(1Z!NFIGVb@p$;~8T^266C|fKe$?Gzn;>ghP;ngy3<U<zC%#;jw$sLJdj@&==tUAj}J2oXsU?15T)w?8@G3;{}WAhxUI5d^SZP_I%f@>Ed*&ScbZ<ez+S$VtVPk(y$ykD{$nMSEL`O%hot^VJL@bghlQ~;X&9eSiaU(g_H!v$*_scld*0rh?k_cf}FfGOPF(L05{M55}e%DA^poDidYumBIu1ls6=TyGDte=Q!IyoAa3gS~Lxvy=9v3)=Hi5F68cCPZce`%;=x6~ygW`CGaLGKZl#NO=emjIvZX@{D7_HcC0nAG`G~=qsxLmdV3PPg(Wf=uTe^al;J-N2&im)H0@OK)I4DrU8vj6Pwe^+TJn(Gvr`Q`t%E8AV#9~gZS_T#e8+-YGQV2H?W~G3r-lkoQn?;$Oz;XH{$+Q!|Z7Q)&zM+O^p$1f}OU;)Hl#=v#2fcF6pTJ$k{wQ1<@&#Mdys9O9dj0lkZL*AJ#N$?>f`@Zy{zM5DN-c?N_UF+U-fLYjXv>J?M2(+Q9;_iGBwo%mlT5W(!2|L)PFHt}6etAUK&3Qg_;$_+j0zId-}8xai}440eTF&}bgH{-R+d$y~k0fAj&itb$?Ptm%TM*Ol--0bZpy`3#XEUG%=s!5pvBl|>%U)=n@#vk(Al%LaH{F4<|LF#_||N9mk{loaZcJm#3vVmG*E*tKq7CS7;M>%<Nta#>ZIvMjc2X6HYpMs^T_)Z1R9dArR_ORIr;F{3asa-M>apn=Zy&7M6QD8P(q8jTC%DKj@UI+v1xUqDF",
  "<a*hk!)a|YyR>h+ts%|Gbi3kw@)kmLJL~PCIDh7p(sJV*|C10?BS5?TE5^KBJFsOGzTUra7jrookv_jWd=Ji>%}iCq@`qliq_VQKQ8oE`%?eF%lzs|e3NiEA06SVNUV}VZdc+Q+H;DlsPh<?nxXV}7{gJfG)p-+XPiD0VSogz1A~|GlD_GQB;Q=7p`~9mVX4PAJOU^71Lt2Dk5kA770|9r~Up&u1@oN6wyjCv+X1Sp)(CmjNUhB+T3s>MZi-V9eqs|r3lhQGq0xT9_#b%g+%)I|Q-*65=SOpDQHcV4qLH~z~#Q5P3GNI!E{m3`#6Va!iCoI=_K=_^C6jaBe(XcQ{TYp@Dw<#vN@&hFyk7FGu)2H}YK%;GP2Ag;~UE&%X>IFenSQIh7X#Yd!3nEeVmX*?HSC^9aqQBBxuCjS3c;i2!DZtk@&BOR9cKe;8&G~t9fB<h9SQu&(35PA&`zv`jJrqH%$J(b?PE#V1@W}oXn|m$i{AlUy$g@6C085+X1q}<T$dqP6(|GKhj~{{ElyO1X)N5b;l9IwN>%f}@et&~JM<_wy)Qd;VCT0Ov!~L%$9GVXQ*gR0bgu=v7{zV=)dy~JlSO&SYrh>1G-TY{pRHY~DM|?Z?eG{Ksn7djsf3|!t<H*8T%e`~EC<9ejtE=ZmxO@$o#6ng*0zv?jx~|sA!}LtF%*({uD|&@M`oILJ*R%$K_|0@C{CJ9D`ABAlB%{jV;5oqBDt0f$I#?qXrlhOHI}Z=o;yRHWiGkhv<tEDGV(WE$l$$5-;$ys-EVgKmcLE?%|IUGYH@l3)jpjKk{6_DFg{nSHnuaNtz}ZX69VCU!Tti5+H4Pd6cnY2M!Y4+PqA=BmF}g3cB79oA{+nj<?8KDd*K+lyG~<IYoftKm8nlTZ6=YCnJLz~h%Z8dW3Z*&5w?H-kv5G2mGt`bYJ!}TGn|+EB{}056^4Y<I{+(JOb$JyrG>;C^hv!0z(uK5og?9?BGuPMqCgf6ol#%(`4EB4mRCJR%GN3iR9HLz+nE@ULdlP71@)XtUw8d@jjnVAyi^q*0!6X}e>jkz+at~A0ja`MSBi%yHY$1@-3bfsROQ^6}KY7yTMT$=iRSQcp@ZT9~9c=cy@zg4KSw7$T6|#VxQ2-h)>YS8}l<qyC&{u~faR$ZU5Q-MO&R|%T6J@tiO%JsGCbc8H;d9E>{q3~W@z`-mq=b|(KSGbNU5U~bByt2R9d<;LO51zCKNNP6MqRE0cHBEsYYWF%neWNUr~{6fwx)r}Avv}qLUFYp+C9q!Np?XXXq;(Z<lFS(c6e~zoes3MB|eWiH?0+%&D^zc^4F-okFtG5fWbBwI*|sV9@Ka)kF|6{@`>lUoS9mDJ}oQ3<4QfWzl%1ioVwj)t36=(>WL2EV-Tku>!>*c|Ft?rfHGV8VkNBG<K(hhPSzid)=+(0QS3&66i01ruZ3oIOtN7d<wR1OSk=fN7!v"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "annotation-arsenal:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Activity: Annotation Arsenal; importable without a TTY."""

    slug = "annotation-arsenal"
    title = "Activity: Annotation Arsenal"
    description = "Ten questions on Python's type-annotation syntax: picking the right generic container annotation for a described function, the Optional[int] / int | None equivalence, reading a Callable[[...], ...] signature, comparing a TypeVar-generic function against typing.overload for preserving an input-type-equals-output-type relationship (the C++ template comparison), predicting what a static checker like ty or mypy reports for a mismatched call, the honest tradeoff of silencing checking with Any, and the classic mutable-default-argument trap. Every explanation ties the Python construct back to its closest C++ template or const analogue."

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation}."""
        secret = _secret_for_item(index)
        correct = raw == secret["answer"]
        return {
            "correct": correct,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(item, index, total):
    _hr()
    print(f"\n  Q{index:02}/{total:02}  {item['prompt']}")
    print()
    for line in item.get("code", "").splitlines():
        print(f"    {line}")
    print(f"\n  Hint: {item['hint']}")
    while True:
        raw = input("\n  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            print()
            for ln in _wrap(("Correct.  " if True else "") + result.get("explanation", "")):
                print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("  Think about each call separately and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
