#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/sorting-court.json and re-run the generator.
"""Sorting Court

A round of verdicts on sorting: which algorithm fits a given workload, what STABILITY actually means and which algorithms have it, why the standard library's std::sort exists at all, and when to reach for it instead of hand-rolling your own. No code here -- every question is a decision or a definition, phrased as a scenario or a direct question.
"""
import json, sys


# -- Crypto / obfuscation --
_KEY_A = "bfc05df14a0b0c1e298eb3db89854f9fcf2ddafb0668a38e082c6180870dd566"
_KEY_B = "91977ca39c8ae9dc5c5547dde978f7b88d4c51c00b17e2673cdefeac4fae01e1"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None
_BLOB = "a757d70cc4b07ff932207b4fbecc5bcccc227d35e0d52f55612c296ff2830efec745f479f1b439aa9c96b539ee42368635b948bf388bd4bdcdb878"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "Definition from scratch, with a concrete example. A sort is STABLE if it preserves the original relative order of elements that compare EQUAL on the sort key. Concrete example: a list of customer orders, each with a date and a customer name, already sorted by CUSTOMER NAME (alphabetically). You now sort that same list by DATE only. If two orders share the exact same date, a STABLE sort guarantees they stay in whatever relative order they were already in (i.e. still alphabetical by customer name, among just that date's orders) -- an UNSTABLE sort makes no such promise; same-date orders could end up in any order relative to each other. Given this definition, if a sort is stable, what happens to two equal-key elements' relative order when they are sorted? Type exactly one of: it is preserved / it is reversed / it becomes unpredictable / one of them is discarded",
    "hint": "The word 'stable' is meant to evoke something that does NOT change under sorting -- specifically, the relative order of elements that the sort key itself cannot tell apart."
  },
  {
    "prompt": "Of bubble sort, insertion sort, selection sort, and merge sort, which ONE is NOT guaranteed stable by its standard textbook implementation (the same canonical implementations traced in sort-pass-tracer)? Type exactly one of: bubble sort / insertion sort / selection sort / merge sort",
    "hint": "Bubble sort, insertion sort, and merge sort all only ever move an element past another element that is STRICTLY greater (or, for merge sort's merge step, break ties by favoring the left half) -- equal elements are never swapped past each other. One of the four algorithms works completely differently: it finds the overall minimum and swaps it directly into place, no matter how far away it is."
  },
  {
    "prompt": "WHY, specifically, is selection sort not stable? Type exactly one of: it swaps the minimum directly into place, which can jump it over equal elements in between / it uses too much extra memory / it compares elements in the wrong order / it does not handle duplicate values at all",
    "hint": "Think about the actual swap selection sort performs each pass: swap(v[i], v[m]), where m is the index of the found minimum -- how far apart can i and m be, and what sits between them?"
  },
  {
    "prompt": "A dataset is ALREADY nearly sorted -- only a handful of elements are out of place, each by just one or two positions (think: a mostly-sorted leaderboard that gets one new score added at a time). Which of the four canonical sorts (bubble, insertion, selection, merge) is the best fit for repeatedly re-sorting data like this, because its running time drops close to O(n) instead of staying at its worst-case bound when the input is already close to sorted? Type exactly one of: bubble sort / insertion sort / selection sort / merge sort",
    "hint": "Think about which algorithm's inner loop does LESS work when there is less out of place to begin with -- one of the four algorithms always scans the full remaining range to find a minimum NO MATTER what the input looks like, and one of the four algorithms' inner while-loop barely runs at all if each new element is already close to where it belongs."
  },
  {
    "prompt": "Of the four canonical sorts, which ONE guarantees O(n log n) time even in the WORST case (not just on average)? Type exactly one of: bubble sort / insertion sort / selection sort / merge sort",
    "hint": "Three of the four algorithms all share the same O(n^2) worst-case shape (a nested loop where the inner loop's work depends on how much is left to fix) -- the fourth algorithm instead always splits the problem exactly in half, every time, regardless of the input's values."
  },
  {
    "prompt": "Scale intuition: for n = 1,000,000 elements, roughly how many operations does an O(n^2) sort (bubble, insertion, or selection) need in the worst case, versus an O(n log n) sort (merge sort)? Type exactly one of: O(n^2) needs about 10^12 operations, O(n log n) needs about 2*10^7 / O(n^2) needs about 10^6 operations, O(n log n) needs about 10^6 operations / they need roughly the same number of operations / O(n log n) actually needs MORE operations at this scale",
    "hint": "n^2 for n = 1,000,000 is 1,000,000 * 1,000,000 -- work that out. n log n for the same n is roughly 1,000,000 * 20 (since log2(1,000,000) is a bit under 20). The gap between those two numbers is the whole point of this question."
  },
  {
    "prompt": "What does std::sort (the C++ standard library's general-purpose sort) actually implement under the hood? Type exactly one of: introsort -- quicksort that falls back to heapsort if recursion goes too deep, and switches to insertion sort for small runs / plain merge sort, nothing more / plain bubble sort, optimized in assembly / a lookup table of precomputed sorted permutations",
    "hint": "The real answer is a HYBRID of three different algorithms working together, each covering the other two's weak spot -- one algorithm for the common case, a fallback for that algorithm's rare worst case, and a third for small leftover pieces."
  },
  {
    "prompt": "Honesty question. In a real C++ program, you need to sort a std::vector<int> in ascending order and have no unusual constraint (no assignment forbidding it, no exotic memory limit, nothing). Which is the right call? Type exactly one of: call std::sort(v.begin(), v.end()) / hand-write your own quicksort so you understand it better / hand-write insertion sort because it is simpler to get right / it depends heavily on the exact size of the vector",
    "hint": "This assignment (sort-suite) requires you to hand-write these algorithms for the sake of LEARNING how they work -- that is a deliberate pedagogical constraint, not a reflection of what you should reach for once you already understand them and are just trying to get a real program working correctly and quickly."
  },
  {
    "prompt": "Space question: does the canonical merge sort traced in sort-pass-tracer sort IN-PLACE (rearranging elements within the original array using only a constant amount of extra memory), or does it require extra SCRATCH memory proportional to the input size? First, a definition: 'in-place' means an algorithm uses only O(1) extra memory beyond the input itself, no matter how large the input grows -- selection sort, insertion sort, and bubble sort are all in-place by this definition, since each only ever needs a handful of extra variables (i, j, m, a temporary for swapping). Given that definition, does merge sort's merge step fit it? Type exactly one of: no -- merging two sorted halves needs a scratch array proportional to their combined size / yes -- merge sort only ever swaps elements within the original array / it depends on the size of the input / merge sort does not use any array at all",
    "hint": "Think about HOW the merge step (traced earlier in this activity) actually produces its output -- does it overwrite the two input halves in place as it goes, or does it build a brand new sequence of outputs somewhere else first?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "oAmW$w3jG>nKW_p!bDBnSY|yBDr-Q061aj6`Z(g+i?>p+Er7t^N@cNdaZbTct>)vXfHDwSQ1*t&>P$^r5YdSEKPxStI>}JnyHK_10=cb5Dvx8UGak!$T}v8pETE$Y?7)(UGe2C$fmh_}8+X_^Q<KzIB;Db>a|{4Qd5%d3femZ*`20&UV@pT>2bdyI1;3sd6%~%x*a}cP-8_d?Zuh~SaTJCc>dtmaiZTAAlwD52>HOcoard-s_aoOuKsa%n5MvqCM(wp6q0$WjhC0flVXNZcqX%W~P1f8GI((SqFuAiXmohbcZ$@;5o-%3X+NN2i1(2xfn}S=O+?A2JNVv-;;Ei<y*OTTrQp64z@j(zCBP0<xj|+v+KSS(-<i_V7tctpr16fDHcWo`U74gtu^{kS_>u)=i>{v7l0+#c{vzWs0Q?j6Xi;0v(x~3(a{c}mI|Jb`&<}fZT^bFF1#^5#3n-gS;M+iiX`M2>ov?C&Y&&&lRi_V94&Y4IySYj`=1jUmYcK)sG)#6K1W>jVJvXB~fx}-zRl9=+KR~VMP%UEgEs1FmQaeB|DAt%9}4bL14Wv_?Ayv~aG^1C&w(~vh>h*C(fL1#zB*NcvsBc9VO5oGjxxguzjWBpkMRn>zA4yrEeQT$SdUmm{Tx;G0)-5B!x8z9*Ef;^VE4yEQHlP1>A1`tspeAQ^D<EN1Jddv_6=Ao$`?+g6LVuaolm6QM(px*MBb{u18vi);v&)M9>K?8UUd7SEoO>}ZVQ~U@h3hkP`@@m_%16<qlqzAMOMJ~d}f_3KL*F(a7!o%PNkWTInGRzi7D6$g*+~FPzE(Szg?pouEM5O~#8jJKLMo%Xk3f(HXfn~m)pp+^dXI_qFXIxGDB4!e5s6Nrnw3qy<wzxmHzd(!z5IexJ0i_AVlYYY{9n05r<!tDeiV%(pmjJpgF3M*7c?W0woxJO3dJ}!{S$V;)*?ol&m_gxab#FOk-Oe4Sq<Q_(11D@2^tdH8gK_BFYHnvS`t%F`j|*@~gJnDUoV4Q%nLOv&Nj*Wzi16Fy*Fz;L>Pt4Dq$82iWzD*$%O#AZZ59d(7g}^!C4&57Z*GFJPUoF3trh)V{26ua-<MPR&pF0;@Gk%Pn$8I@D}z_tU)#$mk41!W3j>{uSWfr0D0t~lF7jn;Gmu&iJLV61hgH_WN=E%7HLzwQ*b(s3",
  "{6uM!x=X6o`bz;%Z7-ERxH0VA{8J-2VEQGh#A6h~Ax3_Je*6vbpzxHXrk=t56{t@ChVY}!orLQ5#|UIM%DRauKe^%hTA&Y#P^s4b^N6VFj4_!bO?fwyY`Dkhw%GPjPadjMe0D|I_PsfYe<;g-*1*@+ff~hJ{A}=^kR}kA{Az1Ynv6?GXX{e+Ov-Whw)Rkwt>-IT2IH><4|Lq@^E5Fz(twe+s0Em9YVyOQ&fA1EZmLcs69XUv74AF5NAs~jPB-jOmV5FN{%70m&wVO&p2I<OEdQLNsO0apyersClBso?-C?W#h+tdC?q-d?0_e-F9F_HlJ+v7z@I^IR1g~A+ARUK;iE>-ZUCcJ>*ayZ)u2@@>tcl3o6HBL85ec5EMu{fPs7fxwD#7jYf{>Pz?@T)a{r~Q}fn8(w63I=`?M#d-eABt>z$_NsQ~5&Cw&H#;0&Mz<7jo#VY;Fwv7Rwv_MZwJxM2L)BP^!bhPAUgOu%Y8y3>T;hJfHlh>!wKZp>ApWihg<TALLN1stDrbGRA)Dew%j}9g@V7QMeR2cx35u{OFmK?0|?TcfkA)4>S=fIgHFZgmIb-4FsFmz!!nW*{aFIeYP996Lbt=v$ifNSC^CugcMCF45y2+&sQiAGZw=i6>ksTRg}j5nrgBFGzyEY?HFZ1)(d<%$s~#Kg!1t*;3i~pQP1c^$0Vo?tM&#ggSuM9o7MXTyl2RzdkDUrVJQr6t9hrhXe3xW|6>WW(Oo{*C6^ID%UPasHMd_F$;?mEMIY-B&>?mlrTEFgVrDG@CQ<p|=FeOLObG5An4N}G&U4vkgCYo~kYTL;0QP4EE+exslS?q<<^81flPT}mGr&xOY)C84U48iTY3r;)6<qfejh>}XgVnJJBf7I&Jv$y14Ay-tP?j-kM?CG@dJqaMf^sV`?WJKemUp(Isg9tY%460yu<(`Z8@L#=2g@M%C;NToIE9M*IwK!ZN2OSHp)_>+@MW}M7q)d-$u*<05RK-`37Fjn`o&l)s~$M>sHo-Koxcm?L=SXL$Dx?&6Y51;piFEhVg",
  "uuSCQEZ?&VttjbW(Ikk>f272CaHs`xRo3Gq!7mn}LkRZbJ9%Z$DMBT*Ki4+<A)llr{uS5Y%sTXIEMpa9w2;Fmj)$h9{XBtfxW?}dwpOLUGd!i1ExfS*UR=}QDk?QOO65;-9I}EjZVnZdSqdazEE4v<LSGbFTUNHsqW21j<rwD~Uhw+!2+qkG19DvqjL5n?;x6J7vS+*i^W<a<c(+>g8G>TSYB_n!J5Fl2pF=G1gX)eSt066HJ5L`k@OcBblh)vIlEBHOC4Hl0KlZ40qh;1N2r*&ilqW@PAPW1+muRa1J4h6Y3xsGpeOYA7uU1WeZ)DA%;f=GKRq3v{dCqy}=T6x?Lg_@s8e1*Yt{fjW22v>x%{Z+VBhG7QC4}5dzUAmoK5d;Ck(B;gHb<4#F5i5nbMueB+Ey0#;9ASPcI;`Sa-J6R*4UEY*9<HdrJ23l-mRzy$ruSshRrofk73f^UohF^Uh_@%F;<|0TB+nm-vh+?L$3|Qj3cp7dlGSVpYd|LsY~hZ<A%%V^r4a26p3rYf%h9iMH*^<e5!7JB`$Y0PYD1w=;W89rRu&p@y)A5DpVi@Ry2&iGP)_7fi^&Acxa@k3f*6V@=d6MvR9w&_xw@Z{|A<%J3**HOG-Utg{sEmwbp+WgxSj2lX#leHyPO`2`+H!^k{>TSyc3#Wi#`;e!`qqP2PZ5p@r41Q;H6J?=H)YJd<dFMoZJ?PnjjG-uv7YdvG}y1KCAK48>kSuM6NT83*rXP!-}n_x|l|{aEs#->1G6*ch|LhhiJ|>si+4!)Lr7I1Q=n96DK7FsG)C$$>J{^&r7XThMuGbHvX17bvGvRfS>z>FyY;4Kr#?PxIJQqyfm0HZPJ45SKcmmS-ahBh;v#9-^MU<Wwl-AEYCzs2Af9+-_{Ru5?(TPn}T=N1W{#gzM`I!>Kq2neyoKq`}PcHChxT=f0QJ5y>Lkz=LEe{2clGiDBk$%G#jts+WCeV9sGBUYCg`^R)hZ%>pTjax7BG<4)ffW#^{2zMWU6`dJiawVxr<!6^CuU?r|#^#_OtOpYVBw$=tSpIz#vwmm1SL@_+<elMRx<_TJMYEsoGaQ$VgvqhX4GpG)6_!am0uEJxZ8d!Z|Hy!8V>Weo~Ack-lDA+Xqik7_k-@SK?bm%?X9nyf(&3NayD#p=$|Ko>wIO_NODnIP3K25o=fu}hi?r;sk%*p$=r0z%^mcJ`0eNIspxNBVdT!=2lv;xh|iVPUH_ra=odRmmx`<$nHrU}qVu}}oOa39SG!c}XYI6KT-?>OhMY-oR6mdt2xGSVO+6Re4U4|Vb*tZCeB5jX0RDj;h0tztMK@~T*OE*X&s2`y0>y?q1h3%*cn{My^d9Csu%M)deJQi5U=V{+{iq(68zHEa",
  "CE?3V_Z?%O%RNK}=3T4C;am;oC@;sl-=GSE@hUuQyXj7zGAtv;mq5rNe6VpghD{z?^!f$^ah##8>Ga6y90D^#r(4LnVtzTJ=(<xD`ID_=7ja{7Y@&Qj3vI>~G;Zm=2VUc9C^vOb;W*#uBaH&30)caVT<z{G+ILJ?){(*7)b@mzJEA5pbuJ+UlKtpW!e)nxCEDjra?zs7A8Y}aA2Zc-5VpMERw<3ohk!W(domu+y5xrWC%u;^(p)z`Sbo7qC=ELmM2;p?^79I$Y0#|1m}i}!{_A{pM2X;K{HHG_2e5R*z&be39K>9Cm<gGtUE^x?MYyNwl#`t^9o(6ItfAmj->Ru<6U}yD*OgpJ1rig<eW2}9?QVWBS)9;|=oO;|&ww~tsbog|Ef#as=?CA^I}+C~Xu0@#7uL$vT?_@Y);B1af7LGK7fw!V0CSW>;mo%Agvulct(y;UyObE=;d*~uei^K;dL4gj0Hqv>3hrWeejEtoqn1@mC>&b1Q>XCppDZ|bSmUX$93f4nn3JdH@yhM8f&KiyO#sUcH%*r1&*aFYPTx-;RobGUHsO5Xdv+*&_!68u#p%X51C_o2t_Zw3hfsE`ST_Sw??Ad@u>&?IC}bI9U@*pkl(-PM?-_tZGcO<KPl0r|B^pZNLF1F-qLzm+g#hDBwZQ+09_WdNfs><~Z@z*eib4P6-It|B-*TMAXm}o;YAHL}JD^8pZFn{4N`MlEo)uNXbfrMy8I4E6x^x`}x8p4a+z}Lq2DSCsW6c~=i<|#{(~Ze%h<VJAkg4aE%1-rc`hv5BP4N*<?`+XokUtuQ%c|^2WeajnfLUGbG0j4wSm7H7U}qI@KYGwIEZSyws7eMBDwIj8RrWa`F#`wDVWOFXLJQj)FCvWr^1hs9Mpf*tD-E^yEF`?=i=2-4#p;5M>p4Eo?95zYhT|D0E7N=drJyrX>wA!5K40A5kKbFO$m%4MLzwHc+~gDcjzHm-te20mLzudZ%CT}^2S?wo6+|YYq5_yt>3iLr^KZh_9T~ftoK+alqfM8a0}S$&TntnTcI}^Y{?RB4muKVD5Xu%BuF}HzP?F7>)7S_4TObz1g57*vB6A3{k4P-r>N}!dq-At1S~y);SOrtf)j<yVJ?_tP3vA(-aAV)M;hm6YiUa{&^ddvxR@|^3)$D4yI3!71VWGq3l8iR{EkQCRWM7J+X?eoAqP26yMm1;",
  "T^~NT9Qam}(E$qj+*>xm%pZ-3>?2x`E2}ee!aTuLp3R(In;=oKL9J4td-ydPn!6SX!9S2rrQ=X-3@x*^jLcp`rjg?_0Fm2ahT{tw7}<dc)BD#apf{qok=q1ZpnW@4El#WFf?~Bkecn@f7e5)&E4-c-G<hubu!eRWC$^%K_V-?&&(NXGdxL*GU6nQ5%@Zglmwluux7}PWFHA<^krSHYr(+JHnksU!U>km2yPKrg%ovqX@V5Znq~+Hd6-QLU+vyZqBg%*GR9mssssktbNK@zgsvdQScD#;M0Mje{M^x~L$Pxtr#6kIi&142L3<cQGNbD#pS(~qtbaDKz!E*)<C;2RVVwIyd@V(Z#WvzgRQNsfR-9bkHd;HmGah9Qdm-4EtH~)dR(eQ*rrH;8QT==ZBij38_0*W8kw#Dh@=ba5+7a{OA521{ki^qXoGEITt_k&Dq{a%_lAkLK6B4qAZOEr}4Ne06|Zz{WiY#JRGd(!B4A!2Wkf6RV!Rp8VUQmN2C(Yl-_NP2QxajxVXNN<}Dkn%9Cg(>`-DUSjNCWBDyK}OBm=Axvg`48Qm0}2Kbmlo)Wa(R7XlzZ%+0lKU{o`DsrN``k=VEk6C(x?#{xd?|aj+5#~@hqW5$U=@nz7gef;hO1;5F%5upRLV6r$?TB0!D<#vY8gwXhcx&D)3)D>~&5AEs1$?Z1q~AN<CW-w8h$w4&+zVLi>lNRJ#@cX-cYlV_i<ps_0SXaG!j`{tI(Y>2}d&5m#CjKmGYdg>GUl0kv-=4M{Ow#=mxM#qAFF6Oj2>%4{U-cR1Ol%p*K|y{YbyVR}ITwLr4od#qjb+t1>I`9A8<-f%+sZ()m4iIMvcvkiY+SJ0?GzG3e}F~#c;o-BOA0p@e?9UGK+h_Qe0E2&%6J+M{XS35-LeYS;y4w^#WSh@E%Gwp{<TLS+#c<3}|N<Q0m_E@Ve7WaJE2{Ol9DXPcb?@y8y3{7D~G#qzph?7jQ1qJ6^-tS}L>?g0O%Gw0$Cl4_)u{3*|^jWV*1t0cOO&rd0QC7{JN(B?6;kuByt@4CCDM-_LoB6X9B1<n(tYU))TX?vbm2aARiQ!k$|5RUdne_gGP2&@I|9_sFd^$)RD_HII6Z5_-@;puNc|Kea1vC<??qD0H",
  "CPx>FuNS|NZPSy=MFKf|l(!}|e>8OLjbB5v0agiE2qw7SA3~nj@;RWSRpp5=hSx9#veu)a5!fC1?tR6fk<?VAk(BN6*>F60w)AJ_5Us3$cHzn;zK#e%rySj$g-f(bUrfI4CgYg86*oJKMw|S1Y_s24vTm=x_fK5njlzCo0x_n<(@0IZc`npN6o44YIt^>EsYx8s&|?R&W)}?CcyoPILde(E>glYctUpZ4#|<0v3`n5R<XKz<T+>E8fzlW7V0U(In<U~oE~ConU)$uyRDmk0H{~lqIiA?BE!09jS~Z?SJRax08vDsrD$ba75W7{(f?i#z);K30`hV<smCywaLmW=1=jk!{GWzwr4&PVH@KKoY{SSeQyxwt8F1q$<FWw%|7qR-_DOI>ab2tD9$YxWW*%@&2!c@M#`RE0UB(yspZcMk&HLL<2tpsnn(gzc10CZtrQd5C#!9;BiIExt0EllT(bC_E4h)Q1SXmn-du@%GTd*{U9$51W{cI-TcxMY^hc3Z7;iFLx5*-3s?Q)aOgp(LJIA%U0zS9)0}hjvc)rHsGEf{1t$vJEdO)AA1jii@N059`p0F}P>SPhNE9?vvy9Lfd+DMiD?A$tvO&272FOGK-2k0SX2n_YOVZl|lF_M-el<6tsNhW{e7sw(9NPG`Y+&<1SXt33NP`E0pi$miP;#A&j#2R_Plo4v>Nou#Ku@e?p9n18K#7<gMX3x!cxJN-X3lck&<AO<Xa}Lp5jt{D_sD1d~Akl>*-<P3-^r=_s--?3Q+lNkh$AQpqTr(E*7;K1fQWxJP!eJI%@*^D&(~W<88ZZHRKOvY9t9z!_(w&9w&boc6qc_Mv$XK4Y$J)50C8=_YT(%Cyh6<N7A5<!%oY>_xBD{MIxsQm8>nhP79FXQbglCKpQkNY>S8a`(*Kmd5V$ur^WIF_MGSV0e6U<%^4LgouL_-y2p+67w3*jzDo~l8VHjc_X&WQRm{W&Mx-y33XBq0sb9Lg`1H!^G^bgQZj9cyG#`x3x3V=U}+Q$B=kiiAy_zWZ9*&2mmewSPP&+r2@EBd-e~Ob6V_PBXb6WPo<TBT2p!^-(HhD&(a-he8fgyt*E~P~cr0am>V<eWk)%e`T(~9!x(dtFP6RtUMw-;*?9-025d5as;=}NSQBW2K)QO9rJ%}LTo_W1F_ThSsJ(VODXAbh(K`y(7we!KCRok^C3B{2=*^SJQ<bfn`=_n1<",
  "Zk=49tZt`R-yW>Z49%?YzFQ)28H6f(&7Hb{vojDU30^FJTATOo;s?eKlI5XE1V`^VZiLD2Lfq?}72n?hEPhaPYIX_*z_G0CWgCH#0X1}r6t#*$K+OtM9r|I>XpB6byf7xHVoMchRSYT{z7t2s&5h{h^8)jP#y+{ak6$DIdg0goNi7Qf&|X;3?pA8+-deE7cqPY0j<q>Ai_`$<+NR586DF3<DCNgNBvgt>sy#kPNJYP`2^sKR4p6tU(SvHujtHr%l%Geo*9LNjNql#?_*2Eg;{8KnN`=1CMy4YXO@4s%K1eu&OJ6z^q-v9F;E=i7gg$s?sozXpPMf`l9z*wTU8KG0<m4xD=5lN;klfPhbbmHJC{aiHait|qIyoMxS6S}6HglBkQpeJ;Ekgwa^nBHjjDtc9xK$jTAA`~@KX;+tzR-1ur~sxZO8@z&4snasR`MP{5hLm8kX`!vIhPh2UWnPtV$w-vK<ln6K-Jr#qZ^aL^;bJ4{O8Od9L!}&+47{ZOO-$>To|7k5s-?RXMasSXzXMotL2Rj!3ABZraQkd2_r()DW@W3mDjb$XlC?YL>U3=Gk$PFd4UqLt0|vA_FIVPUc7s)#?pV&8DzV=Zd&Eqd*R0@`g$h_@;ua?IxQ{~EaH58+7Oo)k@Ii$qhOy-)4sbWXXq#^y&+%cokm&)u21UlTz@UfAuX(RTls*-)^r-k>ozRZhEf&uGrqi3PFUT$vCmGWibSL2c~(l+Ucr`VNe2F@m;-)TJ`8^}53cV$=@o<);iu{#p38r<5NZQoVh)U0_73e<WbulPT9<@%)GfLu|2`=|o7OX3j`CdC;Crn*U#Aog>lFLr1#{rAgZ)>dGL6Mxb1+6>AYTL?W>cF!l(4s9i9fxXeX}Rka->gP_A|BgVfN+F^s_eQcaekfJ+C}={<C=jshFawsrA+f7z>#Osy_`r;&%--YzNMIF|d1QHjAESN?0@2{4(BCIWX+uW1n>Y8w^k&2o?eSGK-XxD=5Cl=$$JNo8uzH9<c;sb=*9Brh7fz0F4UeY*YM0N$itYDm+8n?=GGLbbSLz0W{r7r!8QraQY6#`U;-E!wzcchw|X%EMC%reGotp0bo(ogKd~l4v8k>L8p@Ew>JVSs00c8o7jR5tRT}$cVKH`JKDwy^r}Y>`umLx<g%jyN@dWkQx_)IPpY5=SSiQmRd3W_G~_KUXlAg$sSzfdVs()nbyOhGEvJ}|2ZVpG0-D%5pSqT-=DJX;V-23wbta+R6`dqf>)K!S=q6=28a9B8=^QFheJKf?@REHTRD=iTsmr__8!!O3XI7P*C8p){uN5j16!wi_(0%DMu^rybq*?KFZPGFx8@C1nU32?EbiWL+Rx*38B(Iybs`vIL{{",
  "Y@q|)*r1&l)w?<$GF@z7zAnC=Sp4f`$8-5g3{K4t*W=!FNKB=aQSO=e{!YTFd@Ey}C*%0j=-OQGSD2}--@gl8da6Ue^b$3L0cfsERX=51gi`fDAp9<pj(|qG400C}p+^mlHlF<33#wAu2ef5mhq|R7{CUQ-Rv7I7ct|8ozMOQ}tqKG+KflFWy3=b{1sSR<MSt3?hpHy{F&g?OFJgk)wnr_e6G9~5X2Au8J<mLbw8N~p1m9j*6f)|)h!n$rhYHbDL8^ds%hrRj*%}y?_qt=MK-sR{o7&X&QrLMo_7{SZ%QSUZy6ro$VrYzYB(q#Bu_cnlF2x0o0vF)U^bK<%u$<IY2B7nveZ9PwN}n-MBUckpZ7|3VMYU|!3dr11OrCh0=P>J~gYMG71nu-97H?b$euojn-rM#rGPVX80O#*Rv+RN5+mtXv-@klj@VOWY#p^l?%uVAX;_V*9`{~(3ME&uWh}vxgp2{5A<koiH6}*H!IEAm`0Ax{=E@bZUxSc#h*^^HHc9#pvxH^0;NvvC)1RoStQ$;}^1IZZ#879M)^#coUlM3+&qb1`36*%ZMklfxn6UpF;AWeX^N#&d%e^tC8XbE8q{lM`dxNQNtZ3$A_$VSEQ0ao?ek%yoh76O3iwx;H4poI}Tq7<f7>E-L3E&K`M*xJlu76t+wSNxShpdyD7Bdi6UFwhdnjOtd4HyqUryV)i<qM95F)l*ZM8Libmx;QT`B4(0Zt`_^`bQ^5dJ#>jVRpU88gHFVtet)w1O)5OVtUBi$cm%GD^$F=#y~W)>xHYyRlI-zaS8xahVdvzD6o_ny?gvxibRLy4&`Hv<Z_5~Pfj}BTo6S8M+{!p$s@iQqbwW$XKye%##f*-v31FC`)fRK_0LnyyAIL%M!0QO{Yw#)^s5j4B_Q#*k%+V#Ce))Up_i2jF%#42%xV-_F)3hH8!W46^lD{UNf?<t`w=fink0&m{Wd0Odr7c@#D@94uY6ri6V*jgqbfc3<WbDTKu`m!*4E{%D)flexep5kRPNT3Zf73XGhq>MhqX=vZ=6B2JK-7l+qd9eokW0)OZCpX)OyB7esAuhNAac>aG$5Jm^ezq>I<t6LTg}xTv;ifs8W$Su-BXu>%ab9LWI_mrtqMcHwHuVntdQp<qgL>&CU6ls4fQufG^gs6Hgi{5=vNtlGQ4rvq@4u?t1B*h*8zN#^FOzBw4+aD4N%WC@P76fA_(LfDPr;V)}(@MJvB`I<F6#;`w95{!x0x5c_@|KT^d~!`@FEt`Npxx<+FWc1UC}P^1cnrfmSGB$Iv^d=QGQ093{=^4AG6^AwF9pj@#r25Wt}E0>`#-3S3yo2m*YO$6oWNzObmJf*YD&l>zSuQnOY`f}y!_pBZH5AZ}3AC=~(u<J(mGiBFXyr$(06Z9H3{P^>hSz<C^=fufmWhefH^Y*M@+V&4CNCec**P;8mF+Ob-<mFzs0XDXPnzv9oEDyr(fe4_",
  "I|f_@ztv$^GBSrBmdg5RKfmBMjjHp)NuF5oeG60;p0wZP2(hc<$A3P>sme*uguEJsV$vTp?u6(kouKhEpA;wo<+5u+hzx&-wt!rE{EfQv@FW>}(izDdlOf-{Fj>Li7+D;IoI0NBRlHg83AU4caK2Q&QtuHfl*zFucNAk`sPDsHQ8OPF1B22z<x!ooF&*F$x);%<))@{MiG1dmH2UR*jQNzyElM*F!7I<5K6t6MJUR#ClEJA(d8nS=g0bSu@28>k2#YfBK5c^1QFs{z;!X=yrLJ~>mkk0YzDR_)sW$SVo=`E#DF+brey`HdY0>rn_gIIJ8h2$<(L2W(Zl?h{x$Ox~(o&PKTI!$CWx27%%vzp08b+vVSKAB`QymzWGTP`64f#DJ%A54P)=v8`kz2LRzLT-I`6T-BVYOqsnR&z_Y~|I7_l7dd)wjdpFBk}Qq<(Nt=duE@1{aR)sa=S4QNS~)1{JQXdc0_hlgIH7hDm1;2{PAVry>){k@@C-oCA4^X!XxjWc<MReOKnF_E(yWCcZ;d1#A7~e8&dQ(wEU*n{a!uvPF0rKq5B|!JnyC0B;zbb1O3O?S)v+nV7c|2g%_belxT+md1(s1HqK5Ebi#S&J~C$QU+fdvXiW}u|?Jlhtwp3nDF&u*ZVYTD)N_mY7c|-Av8$e#gcA>O66~FDl8<AoV<~M@1>>H$vBLW9jq78`b)7?xWa*!neDh=loBWXf$}FQWX!;!+Z3kZHT$}Zk%*S>lKzNwO#b@SPPgH!mn_+hReV^mXGC545~O!fjxw;|bsgV@S=@n(BQ=-ygY<y|D;7I<X|XGi<H|@AumMk2;b?zc7T8<#tazY|k-ce!GP4+C&Cmax;QF(}+AbT8=E7<&#w;+`(CU4TU2)pp*>+-8WCP4;MP{94JgIn5zkJL1b3C_SqBrBArc)-S@ybfxG#~DW0oS=c6Z$(`9Qomxo~-0;$i=cQPiJ~J;)@_t1_h`ZlOyIjxTD#HF+A&4pw&*s%|E!j9Mk4LG<hR1t9Orj7^=gL>~d}B91ZOawwpgSCzEsvPaQTg*Xxq8Ca@aHJFnKC$ot}NJ5JxlWq?(knCtUAmsd@QL$YOF<VK;nob&@{taJ-De=m*j)XjT_Q=BQcb8W!IasHy=!O~#<7zyp;LdUPt)2h&<Rd9!)%c0s4R|_BO&UEpm0S_SJL^9Zf4<-B>eAtL8#J~H4IlcF|)9e#yChUo$0!OHN&<*nasNe&G8m&W#|J>tGRIQxmdA-5Y>Z+NIJTN}SD0@oRC6>&g6W=UTcvZz{-lq}c2Bv~gaJau48ayPW2Ont+8$XYnjJ5t@Zv"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "sorting-court:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Sorting Court; importable without a TTY."""

    slug = "sorting-court"
    title = "Sorting Court"
    description = "A round of verdicts on sorting: which algorithm fits a given workload, what STABILITY actually means and which algorithms have it, why the standard library's std::sort exists at all, and when to reach for it instead of hand-rolling your own. No code here -- every question is a decision or a definition, phrased as a scenario or a direct question."

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation}."""
        secret = _secret_for_item(index)
        correct = raw == secret["answer"]
        return {
            "correct": correct,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()
def _ask(item, index, total):
    result = None
    while True:
        raw = input("  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("           Trace through the function step by step and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
