#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/python-culture-shock.json and re-run the generator.
"""Activity: Python Culture Shock

Nine tiny Python programs whose output will surprise a strong C++ programmer meeting Python for the first time: integer division that isn't C++'s, integers that never overflow, names that can be rebound to any type, list mutation visible through two names (the pointer-alias analogy), slices that copy instead of view, and a couple of syntax habits C++ never had. Every output is deterministic on CPython 3.10+.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "79426622204322f1f8124d10ac86543690ae810d7bb284d05bce09801dc3549f"
_KEY_B = "31c3af80805631cf058d5dd6bb582f83cf0a71754720af3de0e1f06b0d915cf7"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "663c9403b4f7f7fd74ed70b3673f58afc57ee9de9503f2dae372eb11e721e353660bd129126106f34d8d2e1e679c5c55f16db7e9bf748baf9026"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "/ vs. // : division is not C++'s division",
    "platform_note": "any platform, CPython 3.10+",
    "code": "print(3 / 2)\nprint(3 // 2)\n",
    "prompt": "In C++, int / int is 3/2 == 1 (truncating integer division) and there is no second division operator. Python has TWO division operators on int operands. What two lines does this program print?"
  },
  {
    "id": 2,
    "title": "int never overflows",
    "platform_note": "any platform, CPython 3.10+",
    "code": "print(2**100)\n",
    "prompt": "In C++, even a 64-bit unsigned long long overflows well before 2**100 (it can only hold up to roughly 1.8e19, and 2**100 is about 1.27e30). Python's int has no fixed bit width. What single line does this program print?"
  },
  {
    "id": 3,
    "title": "dynamic rebinding: a name can hold any type",
    "platform_note": "any platform, CPython 3.10+",
    "code": "x = 5\nprint(x)\nx = \"five\"\nprint(x)\n",
    "prompt": "In C++, once you write int x = 5;, x can only ever hold an int -- x = \"five\"; would not even compile. Python has no such restriction on a name. What two lines does this program print?"
  },
  {
    "id": 4,
    "title": "everything is a reference: two names, one list",
    "platform_note": "any platform, CPython 3.10+",
    "code": "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)\n",
    "prompt": "In C++, std::vector<int> a = {1,2,3}; auto b = a; makes b an independent COPY, so mutating b never affects a. In Python, b = a does not copy. What single line does this program print?"
  },
  {
    "id": 5,
    "title": "is vs. ==: identity vs. equality",
    "platform_note": "any platform, CPython 3.10+",
    "code": "a = [1, 2, 3]\nb = a\nc = [1, 2, 3]\nprint(a is b, a is c, a == c)\n",
    "prompt": "Python has two different comparison operators here: 'is' asks 'are these literally the same object in memory?' (like comparing two C++ pointers for equal addresses); '==' asks 'do these compare as equal in value?' b is the SAME object as a; c is a SEPARATE, freshly-built list that happens to hold equal values. What single line does this program print?"
  },
  {
    "id": 6,
    "title": "slicing returns a copy, not a view",
    "platform_note": "any platform, CPython 3.10+",
    "code": "a = [1, 2, 3, 4, 5]\nb = a[1:3]\nb[0] = 99\nprint(a)\nprint(b)\n",
    "prompt": "This is the opposite surprise from the previous snippet: a[1:3] looks like it might alias into a (the way a raw pointer offset or a std::span would give you a VIEW into the same storage in C++), but Python list slicing does something different. What two lines does this program print?"
  },
  {
    "id": 7,
    "title": "negative indexing counts from the end",
    "platform_note": "any platform, CPython 3.10+",
    "code": "a = [10, 20, 30, 40]\nprint(a[-1], a[-2])\n",
    "prompt": "C++'s operator[] on a std::vector has no concept of negative indices (v[-1] is undefined behavior -- it reads out of bounds). Python's list [] accepts negative indices with defined meaning. What single line does this program print?"
  },
  {
    "id": 8,
    "title": "multiple assignment and the tuple swap idiom",
    "platform_note": "any platform, CPython 3.10+",
    "code": "a, b = 1, 2\na, b = b, a\nprint(a, b)\n",
    "prompt": "Swapping two variables in C++ needs a temporary: int tmp = a; a = b; b = tmp; (or std::swap). Python's 'a, b = b, a' does the swap in one line, with no temporary variable written by hand. What single line does this program print?"
  },
  {
    "id": 9,
    "title": "string * int repeats the string",
    "platform_note": "any platform, CPython 3.10+",
    "code": "print(\"ab\" * 3)\n",
    "prompt": "std::string in C++ has no operator* at all -- \"ab\" * 3 would not compile. Python's str defines * against an int with a specific, well-defined meaning. What single line does this program print?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "PJs3`q9rzpz&3st>KUlEnuLD<*MPKEUET}o9{O^mKFpk6nq7qRS}WN6^}ux7Jd@{Jy2%vYs5b56L*MBS!{q(2sEF6~>>XMJpyqs~;;lVe|NQjj4sh;#%{g{%4ZsMg)REfviIXZQ0uOJYtmz9g4W1<Gu7{s%QA}oCN?4Md=F8gy<6{z-SCqr#$$tpS{fL}@Re0DY6tnQ5KNZDmOD_J7q6w4ToU#)?3*+_vzI(p`cLH5E&(WU9$_NpTBTu6DyTa@Fg2L{@a>lie7gucOVZzx8<OFBG66>_vE3=a4Gqv$)$<+!%Fu9R%d_w%3UoF7!`nfS!1Vk|GyAwXO3CJUm<8SVjK{+01;2~KJ4KIP|c#!nzr(tq}R>7{02a%cp#lTuK|6!EC297cbF~-+UbuyAJq-XIR#&n_6cIn{z<&vi{cU{6qrTfk-P~+|xESBL4z?hX7u8v$+8z)0c3O+s;2{MX}6UzMCrtM>=cz`#-54d47zI&&0tBrA%3Lc09MUr`{lg)Y|CfZkBU|2z9&W`ghB)77H(PD#meom-KseybL$B>t#6lsWrD~<gtPkp+9Z?gki9*ps84X(ur<6|N^HZYi;aVO(Ze;e#n0^}Sc47k|+JubVn{|@9KoHBr?d&c#kg!?-;eFQjSxYf;*LZL_5Wfy$C8Jat2tyZ^`>qf+XoNO_=w3wJsbQ|t6gd#`ocqILZ{3F-A4;(=|Dq4IoUc>zR0QjttU1A3L=w#zC5DtAbrk~wF33xPvAyaAe2;{>bt+0S_-geyAjZ0&zA#gs(YNhw^XVtK(X8c5j5Xel0$(fjWukFyfo3(Q!`RXR2Xz)#_8b|m_z939#)8#xev`%4uAcjF)9to}U&a$`S(I-p6hwXB7K{>)rnJ_*{)o=Cp;y8?uTeQ<&#3l&27ie~4BR-a8Uy$n6Vvnqo=*IZRtMv)9E?X~k6(EQ|LOKCV6S$6c9MnMwcPqt>69",
  "P=!9NAw(ikMQy9w@^)uBQDb%9_L(d!Xt7VfQqH+$vkzcIKQ?-PaL{Pv<LQC1w3KF&sEr2#fJ3mS_<*!lrw7MiFr0>WPHo(GfL)-LrPEGXQoB0%CisN;H&MN`=1poy`_M~#A!G+JK$R*8_k<n->M;1Q8O%3?5?nRjYv?v)vMEPXLcA9ZiZX4wZ>(eJr)Z85C|p%I1rF6}azIF#5ACbw>1UPx*-g$@2F{6G#IvxD5bh5kIv#?`Av$SoveZ?uIQYk7@=o(v-oUkiFc?@r`V6Hc(&sp+|I-F<-%G;?NJxD8IIj4DY9fs!3`~jdTlU_0knhQnM7glMwXOD%=#G~UCyR5#-Rz{%!8L<<UWP=5N@i%N{#<SwKuk=HqI(6a%@!=cQZ%$9Zxvnb02wGTAW+C00lY^?Fc<WAL@=5#Tmy!Gs@@~7jNct^YVEmPACm8?UyT)$3y4cmbHE;bi3Up530LHldXEX_KlE}*qZO<y#O(&ELk$txA<pZJu^-+WD!7xXms4U+ear3nMLta93|QWkN+TYkQa)-R?FvfJ%dy&%TLn$d>*?R#dh-+YeQaR$<GG(?%9;n!D-X+pq_fN5a4H>qrzW>gN%QK@Jxsj-N@iNBcU*d@JZmJ0isX7IXdufz3Maj>5u=hq_l3x4&P>&k-dH2k_?K|u;yy1Nw@a7e^B$Z52ltiw4q7>Q{t7TUammw<?T!tZP}Ykpp}XdM8{5O`ODDUzWwt(8U$R=IaeS}ZcI^ta<s^Q~SB#}Dp)_KrTpO$9f>~Kvi0Uh-fOOJ55HoM$T2yLx;)HyUg^qDxpHtR9fGjbF<GMY7d%h~IQeksI#@G%ClKXi=9Q;<A7esAZLs3IQY|6Px<M9d0zH=N9WH#1cHe$F@0w@a8-+fbjl&MFAeSkHApAL(SqY{d&l?lZSl)$R~VUPi;jF<_;x6WK7msR_HPo&@LaRHkX9!WVQ!rJlq$9>5&qWh{Rs>L6tQjokB){hh@JN!b(RS%9L12Y0_n>v;Hhg>Rpr!~N@p()`6FxtfSe5Qw`_hC@do}SO2q)%0yY4CLs&k8Eh@RC?15PD31Zaq=vO>(Ri-KUQXLV&^m^&h>J_Ru^p%piyNg;Fb{zG=90v*8BzVc09T<z2vnIAN5=cLDdS?kX`Z{~8i?wXfKz55i4v(hlzvpD>4-R%$#}WS}Vf(~b!1DlkU",
  "o|8y_!%v2!k=TPBheLWACZLUQJNWuU0$*wE`F@<wb$m&Djcy5|nZtXf0bElmkb+WMREG!%HFu<i74mC#u?0}7yZ5Gb@?wg19E&Mb6U~vCpE}7*zhTkkiGu93*b<NIAr~D>1qu;aYRcy6Dh#OglWJCBKE*&<G|`^7`D`#$c41TnDl*6WytvBb#rag&CYhDIS$_ah&H=y;xGAIkvBkEAi$oqkY{P^l&x;fLD(3~#JwaU`x;Fc{Dw_jwgv;Otg;ob#vINF9y)w$e;Z=XaNTknJ9P5ZFTp;lS`Nl%ZJwXF`on)Q=%6)nmUdDWzZRYTASSWgMg-}3+i=&bxMg+u&3VJ^r(l?Fvm}e$$B+y})`3|r%cvi=k;SiVRa3|cboY7k`N#^z3IX_PuU!$bk|5M4qozXN97>tziZ^K~EmhDrQ;L+}YVjkvf_T-kR&SrZw+<sV1MgR+k6$Z-m3ke4bV=rv#(wEJ$5q?<rc6=sp1>L~8_z;&{7<!CCgF-tQs)6bPwEAWOuaUti$+>CrT&qiF?*Jj|#^zlkVIZEgM=ayiA=HMK7)-u^LSa0ckN5XQx3B^greOlKo9^(r<YP}WqlwuvkxV8G2Y*AE^Iw9_T6g}ci;>QilV}lLno|uTmAPWsZqNRf-xK1jJd3N@fm?%Q4-?uqO7hHq6@L*Dk|P+mIzU#5O5PYLzgy(073UME&u$p&d@gbQ^xv7aC1o+;JE?`EYSPmL`Xvh?u4V=w>keU3AWVFqRZT(*Q#vcq4-gsZ*>sa2ke58toiGta6b+hzQ~JMqT)yXk0<`R~q8{#IrtO%K&pg*pm7A#lq;g5|O0sDXx=AT#*`VH|<SA5W11P7Y#dYG>)I$h#R4u0mw)ZCwuuGt6n~)#bLE_3u^zUkF&;>tX?NXRLeGwa(6HKTo+z?(yWn}Vd4356RBN?EkQ+-niSnI+phr{7egfcuYUrKE{2Af%F!0{kJy;kmJ;6)J&EtytfNtauO<9&|n2&kjPN9win{BVc@FJn)YAbBelrcs5g`aHZhn2^Cr5A;$k0IH(Sx;lFRorn<kAh+%-+zk",
  "_Xcm+>wri|pzjRMiT=B=t_mGGY??=w-CJw3geiG^*aa%?i?wj4RGvqUQ|bicYyit>uVs7u2tnB@gnxcN9~vc>1oCt(Q7F?h(*dX0)Cbt(YSR$>h~Kq2zxZha4d^IumBHEK_TD}Ej;6xYz)8%Op|T=96ZGE1jW%^q82=+(7w4d9M%9C*8<H!>O?Cpi5gjs6plwm1e9r|q!V$aHS&mEBEHHD<$tVt0eht0cu6VR8O^3<!?zwjw<lr?5b>*ljzq{{8(A;YTD@WK0DFlLGJi1A_P%nZzLVuZni(2+!1KBnTc;>VkVppX}T-GN=^}+j6_pSC67pO*jgjpUZqzj9It2CtA*UHZL7oG)E1Ot@NAN5(s`$=DJ<%ed6Qf8o;4DdSF$T<mF=)8bvBZ814$pOaUbMhO;!n$q=_zy-@8XflSuES^ypxGlJiNz7W#lOvVIh@x`EnBEiy8{lIBM_m}dg3;&hVV>i@qm|r>?OIW+`V_lOap@zWolVFM-Yp<)`P=|pGtyD3nZ|PqV(vKqlJ|D$~F{jv)|a4Hh0c+;zdkHqGYB#2+?-Bbe|gH91eWWAMQoi8}W?V<R@QFrzX5Y#Bo1CPQEue_>Vsz8b#7f$jXICi4jXohxP{y^~i#`gR$%oBje$}l0fb=5Jn>-dPYvEaQ>0)7Z#32Ic2*(Hp1~r^KOYgM)UhnlWPK62G2Md{@{caUB#RvoMzRT<zlml)lcU`8P`2#BUq~v)lxQoTw_L5d=6+}7n`m5^~3PBOa+E4cnA;#I&ZuJI{0p03nxcQ6_b^~MHK!;S;*yLYeBUwW>O6?Bfu!OC~Y}89w;f6u?cr)0M}u|-)j`};<!sSe2Pu_^T)T0^8zX-;`B4nG2n#k^_to06>UWe-;WcnZKJZBwp8(H<e)T6Bn;l7@!BN7_Ga`aa`8A!&a}RGe}->OlW`j#-bUf)UPc)aNr*^pa+a&S-k}zzR%vb3iCs!}Vg=$02au7)`^^c#VM^B<Kq%xlAn4fEEC%-FOvg;SrH_7fwt;nuk^Em8SW>@X%?@k+g549Tlft`SCC>pqAZc%08`pXpqRU_n1q8M~oht3g^qUy!GBDRN#*OanpSDy7JFXj23&1@3MI!^WCp7",
  "SltPF*f?p0Sr&CJf?fpKEX}ZK*Ja|bnOQ?$p~WU;t+}noR@f}hicP^{v)|tJLFH@Jlga_~mb`b2pHrj$RxN`%YHnj2`@(f`FwZX;x5TeAPd-v6U%D)WDFW&dx@%~wec_N3$l{`GlWV^dE?d~tM{dPm)ih)wrVe{l8hyVhT#U7d(xB>cPfi}PW+7B8OJ8~L+EfqUHbh4wV5>Dz-gL303%(+tnrl`-5@o!0GwW}eA_Ow)HOKppn<DGIK-eym6LRpOln5ZW?Oc+Zy)3zBtgHaZmRR@jdl}4Acg?=t<!rG2Yj+$MdJ@BNEfSAmLv#O_r(5V+>2mktrj{!r2xCQFn0)kpR+b?Q?BaOXodo>1!5f#ui${TWxHiga>A|u54xKr8YtJ$|$ZXMU;co<ijoj;{fQ{-WJ#=o{SJf9nyK>7n9`caLIJYh)W*8OOl}^P-n)FN2db)K*tRz~Ow#;3za*!nE%-G~2d9#{-+Fv11Tnu+xxe$555x}UuAiUHHQd?z5^J9ApDx>x$!spWxIGl>jKWiR<{nwN(1DEN_KV)<UlkMU<sh4=LTQ{$w|1<ef<}-qBV&mO-$foAVL-XEv=%nD->q1?57Tr$L->68JA+2^QDkM{XNOqrm!Kb3@3lE4*Q!uT6YYw3(y}cd<02w!OJ+!S3(S3fOW^zqrF8Ip#FYB@79!ed~NHlW=sUceh?oW=1${j4%_Aq-tLd2VoVHN&kT14$$Y4`P1Vdr~dWR@1qHss|6rNlw&=MBhZn9HrmcCZ({qKdUVj(|8&)t@JztW)N$h!sRRB5s=VThjZMK83yU9VXwB*n9Z_K7mwLmRtqq4J#eb-dSNjH)i5Y%PcZp@GR=)R&`mBd>=_0NYnP(J=!QqIQp;@Ov9}acg`PU%GPQp-&J|rc$S)P5%}+}6(GXO_nDwBZr6l)`;|jgzA8JRs9T1Sv^D*r1LI$~gs?GUI?!ZU$PhCdG}hHmBm0=MvLV`%ihhwV_+hY2yw^|d(K0IPN`@=b0TDGt0nXT3{l92j+>>z8p?KcFg00sHqrByh5fNDSye|tO-Yj+aRM_3=2ajs^&7UrTpD?|!KD?++lJgJdC=N6GhVKksupTnpz+raXUD<dxWIq78z&=X{C##LRnAZB){r",
  "T9~J9cfIrF8XuzmIX<)SEURFV{JPm`z2eV=qE6*bU5{7=BA=l5AL7sC&lmOzve(w|`oO_baDv!`i%tOKt^HXF_LyN%>whNw8p>jwCYOyoa%@E&MsK6Itot`TC?}uWuR+$`_@@~UJdVFQTkvRbg^Fi`s*b^kYmvqnt6(v3epVJZkNBG!!lFW^3(%rCMZ&_z;J5PRLr}3nFnyK((M%OJPUN1nIKK<)*4gSJTQgaJJ<;9vgAci`&T}fuUl{awGp+Rn4xHjKz}N6FwCFJBqlKtas7T8Rxl8$jt4v!A%AZRBQ`Sws3C9{9Wv4G9A{lw1c(Y_+b+H&g?ZiO!3q37hIB^IGlPR``Y1xn${ivNL)u5S1qfd(2Zz(Qfq<)oOFSY@pW0%kGYllg2nvXuj<zFBOjskqi8-8ZPBiqoDrg8NatIh<pC<3FqV1z%Xc;0e%2aEhnM-I4sCjrF42BIA<AhB&NN+sg_FBYI9jCB{lyRkd1wu8e-e$eR{)uRinGV;Qy#5-!zjCKwwgw7L_L$&dQ&!Pwj^9yq2uECJu;^vbWXuT|-T|d0j<It3gI{L=wc&rH1-wN}}$TDySdZe5BCNGYd{u^w}sNCX+cqeiSyo*<0`nsd+uI@|;_DK#YKQ_;c{%adEh!RQt`?~c~4ZU}oD%$))*crVZGL>9<ayz(>X%G7WmtmexNbTmGW|t>5AYGkE%T^Bc@`&r|byX(kH*#P49xf74nGNyBk#ZJ)V@X!k1-_b6Wc(|8rDy7)yoa#FOnp7lh2u_1tx8u!LO;_d5`u|PPA9aT_w)T^CvNX&LF@ISINr6bf)7aEmL?bFY|R)S28O7UR@7vpGxFnJMK9z<Dl6DFPP#ReVJ=!w+K>=I%&1V=e0;d1+r02`pZ{uL+qT`SnH@7oU!f-wArT>Pn?4yj{X(QXM1=X`f$$?#Yo54h{Dc2W2@po|W97sC#lK(V#MafXZ{J7ZA|wDxvMu&^NorDWlF~I`bWZt-Q;lA@onv~^)-!R*A<zq=tHp}Mch6Iic>3A8i-Bk<1T2*6DgDe9O73gv%A6>K19JX#vb+{)D2A_mf{{$|L=RFTsH?bJjg$Z*@d=<gxl9<yPgvRKCZOU`uBH`-RxreMIK85mhk;$Lb1kQ9P~L(_Ax0z|5q?RahHQ&>6~`{yq9nyb)biHe",
  "!1+{Bzvvj%kIAindLP`MUOM3m)#du<SbID7%lU8WYJ(H|0sIY=ko*LGP#;j~^Pbs%c^ihr({nww!^TA`rj+Px<ZTctJ5W|VJ(zt*6(@>M;TB<9i<gEnSEWDVNY>K8)<E22Tep60p5SOdzVu^0;aE8yYH-jU`YI$xOz*9qZ}Ib8++GZgbcWuQrdN{6xNG+=kv&lq!1|XcfFqGNa!^IxyR+|F$d~^$Lk*S8q9m8(+|Jw4pPA`ljJykb2|04<VZmb$KoBa)1+#Ld*puC^>fBNeZ_~b?ZW5%(DgmN-ia*0!V=#gwe+E%X-8jatuK=?@G87L*&hV|mS$n$&n(_O|Q2R6t1J$ZraS)<euEAgxiO}MWR41h;@YLPp{3|5+DJAR;=Fa1na}hh;<)kqRr54W|{VvSqhLdl4&VeZ#h;}wPQSJhgnP+8tfzM|0+teMr3L(KS&L?J9Y`ODNzxp6C7AM#Z*fx&0oTbAz$eKoV78&>F-U_0_;wU#=HCe_zBe&w3^An)HNg3$jI$n}d@7A3y1ZJ)<ssXXuQBt?oOMV}zLWX;~4QFSm3KZ$w*JbbWsqTJx&DecZb{s}>3|kdzte>hlBCz9qsQYi#WT@WmK2#dU`u3I_IpFmor)C3dFi(@%XsMq2@GC}*sWjsANWL(5Ns}%R6=Rf1vPL*<VDU1O!@qp~jBjEGTbO$|df&<rlt0}^v{6ln>Js#RFTUEii#c+eP}~~ttuCTZ;!}p<Z@S}?s3HpvoO`i;;)IamWz?!n2K$g6+U>7A7Nbz14(>awz^6sFAcKR1<YmY|fF-aY8dhJT4~k=zJ81A`ImQu)L-@IqbGj%gYRJ#__fOdw&>JgLV85|<%A6gS2*V;}3Dy{3d+5GfzLK&F>mtCi3X1qvISpSXJ(UxPk6Q;04m}51|DG*sU8oWUeD16Mn;N(~D2-o;FjcKvmI&nAO(gUO6MemFp%PgUrF>rrb?WwnL(A*9LZZVfk2bXD<z=L~)J>rdxjS-2;Q",
  "<6TLsnMI6lNRV_rF|4yeD1M4O|2(3@!%2>RA4;&jS~;VgLSNsVepkXdRKatj?xjN3WPen2=JizjCE@fDchDMOH#&$alDbR<PrhZ%D)D`I?NeM&m>D$-y?{Ls_yTH7YtNx&M-ezOhcQUDQzB`H8bWg^trOLm?RNmgKo%exu17n<E7?UMn+=A7*~Y3Jr?Tqf5ia}N%!JI=a4HzC!;<>UncDB9pT;&}kNDS+hxXr58fbjU1^L>prdPVtDgnZMkX`I7G4rf1kV8jKPmaxj?WfY$Fb7=}&b)BsR|A%W+Y)V_Q_MIa*g564(~%ftD!s-$fCnrIHLk5S?a}vXOHvsT0s@&?Fa0*(dYFES^;7L|bae64+t~26;M+7K(81R4#iduNE3`{-_C7iCXU+08&cez09F%>l4*5Nz@KvcHMnOp7#K^t21-_tdK>ce-ArrrA<rX&)-H`n8S1geco%nQR<oe`?c7LlZ*t7wiLLozn;sJBb-?bdBuCm>GDO5{#iVL3_i0qSN9zSBOHIIo~fjmx<nbZw05j^HC5CfV)-W)RMje3=yR+7iKYz~w{H@_B{vmZPd)dC75H5YmYdCrUg)V^Np;q!^JTb~P@9+Z31n(*KzgfVe$Gw0Sko|B!U(JTR*3`vNQ5$sB5dQ1Gpri%*8u5LcwhtV>>uoB)FwbEmfO8UMkRP!ZVHdBqX+Ls!8=?ZX?MM&Vta!hBaoKN6t-ZZLn1j<v{?MKue!F7l@G<2V{-8)xu2?=V8(14;xTi|D5=u#!-7>&cS#zO6p+Yf6<Nh2_oX9;2&U7|lJ?D-}#C_K(ASgQ3yE!%b7zl80LbaVjvYVFD<j@uCb#Yf<vi{uxpUMzciv0>{$-?4n{7<XiKna)%&q6+V}bNJ7Z$pM!(paf4{`lH3O!AIvMmJ$0d-R=uQvS#V^{WD$7frSO0vA-VJLIh(26Rycp@GP$X=!Eo@v;D+1r3TjH2i?d$PHa;=P$Q|3$_{c?+yZUfHKXq)A=5*ISJ;7$IfUfDBYAqMx6`wiH0TXPOWml2Px_%~VQx~5Y&hvH9>?^3Zr^|Gbl*E)2?nyy8w>UKu)-9@#_2AN#h6zi+&-+XbsBXA?nc-",
  "bfy3ZfYCicHsT-F0!Ttp>xVT|vL`4mP-}d?X-F`HChB`>9npXs)*$w##~LCnT~dZhpy?iO+(de0>>~pEOtajqaP<2`cWP@a*GMFgUc;XbnG!xCLDb#3(&1`idb`3pJLlz}wJPA83*At^NxEA0)0qi*@?|Kc>nsfSsONOmf<VI>9tfU4pZk0{E>U&b3$>>Ea=i(f$3b{j4h5KDk0?e5EbjroCk<!@)Ic-j5E62l@LHuimS8r)7qX@d{vtcT*^RlaoTr%Kcv0nZc>M`*RLMP@Pkbkn<o%&7=2C!|M216Tu?#jzilAgDJjDT8Svp!#%NKKB#8S`DP_Xq7nfsHZf+AB%-$4D-K*l>3{X>w<b6Jx|`?GApt1PSdIi)QaB<P0i6f@W+`YWV_3D$4(SalP%Ga_3Hy0W}43n8EV!RF`+94~9+S}5+vJ31&GiI6046Hd>uH8I&`e$1!01soKYs+vWG3iD&7t?Y=#S#L_cl$Jk2Dkjk7J@~?*(|Cx%p72@<D^TV}+F6*HHs9@9vm))^4z?DKXsI&t?5Ia#P8<x|80^?qs9@4pb0klm===L5?V^k|A5K1e3gLgwW>4;^{f=+vxuOws@$b4FCAH(smk*5AM<TE`J`YCrUst_paJBBl5nwsRy6@?#z;?i9{cF4*9pK~<ex@?PL|;L3Z7m*AMT~!rHSw{Uhmis^L6~^8`FBLB8oj5p=iv!pL@rB((u>$vdMPSfZ28&obqsWhZ&1W{c=_`qWm6J(#Z6#&kG<!rs43T~`L>c7zGisk*z$#6{~yn^=3m+Y^>(4j>QtE@>O0`+4i0k|XxNJIe8xP;EIbxdR|XO=UsoBhV22=O4dQzLIT}e&+ZTy9qc#+tII2iv?N~5^a@sMY$<ucY7XZE8)%IN-=quh=(wiy7s23yqc0NG=cxY6@HJe5npue;>uA>5fFYcB1m?ak#GlxCc@9lKnn7{CFSbe*Macdy@wLaN(QMp4R)~hmb&F_<f7g+4uT~a_T?+6Go#lf@_gCA@q8_A1Nku~7UwIg}FUK(kx_dfz*#n!khX=$2JP|Kms;FJS2ZtHD@iX#Fx6QvR$yuN23!Cr$h2QMJW+5^8GYs&kVBk}"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "python-culture-shock:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret


def _run_snippet(code, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.py")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([sys.executable, src], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return None, r.stderr
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: Python Culture Shock; importable without a TTY."""

    slug = "python-culture-shock"
    title = "Activity: Python Culture Shock"
    description = "Nine tiny Python programs whose output will surprise a strong C++ programmer meeting Python for the first time: integer division that isn't C++'s, integers that never overflow, names that can be rebound to any type, list mutation visible through two names (the pointer-alias analogy), slices that copy instead of view, and a couple of syntax habits C++ never had. Every output is deterministic on CPython 3.10+."

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def run_all(self, tmpdir):
        """Run every snippet once with sys.executable; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _run_snippet(s["code"], tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual run-time output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    print(f"\n  Running snippets with {sys.executable}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="python-culture-shock-") as tmpdir:
        actuals, failed_id, err = ENGINE.run_all(tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} run-time error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
