#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/callable-lineup.json and re-run the generator.
"""Callable Lineup

A CALLABLE is anything that can be invoked with (), the way a function can. C++ has three species of callable, side by side here: a FUNCTION POINTER (a variable that holds the address of a function and can be called through it), a FUNCTOR (a struct or class with an operator() member, so an object of that type can be called like a function), and a LAMBDA (an inline, unnamed callable, optionally with a CAPTURE list that pulls in variables from its surrounding scope). Every snippet traces exactly what gets printed, including the gnarly function-pointer declaration syntax, a functor that carries state across calls, and the capture-by-value-versus-by-reference divergence that trips up everyone the first time.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "e2f1ae69d123a9f83dc5f473f9fd9da1c3b5e966a1d60f834c3c941b602a9b10"
_KEY_B = "3f90782bfd644728b8119eb28de526b1e2bb9dfe1358541afc2057c3f174c8b8"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "69677adad2199bc30ef1e78e92d1c8b9e9ac38a4cc00f4a27d6090314aa380d932ea435aca748131c499d700fdfc280fa206e697728e2d1d9fcbb76878"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "A function pointer: declare it, assign a function to it, call through it",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nbool isPositive(int x) { return x > 0; }\n\nint main() {\n    bool (*pred)(int) = isPositive;   // pred: a pointer to a function taking int, returning bool\n    printf(\"%d %d\\n\", pred(5), pred(-3));\n}\n",
    "prompt": "bool (*pred)(int) = isPositive; declares pred as a FUNCTION POINTER -- a variable that holds the ADDRESS of a function with a matching signature (here: takes an int, returns a bool), and can be called through with pred(...) exactly like calling isPositive(...) directly. What single line does the program print?"
  },
  {
    "id": 2,
    "title": "Passing a function pointer as an argument -- the classic comparator-style parameter",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nbool isEven(int x) { return x % 2 == 0; }\n\nint countMatching(const int* arr, int n, bool (*pred)(int)) {\n    int count = 0;\n    for (int i = 0; i < n; ++i) {\n        if (pred(arr[i])) ++count;\n    }\n    return count;\n}\n\nint main() {\n    int arr[] = {1, 2, 3, 4, 5, 6};\n    printf(\"%d\\n\", countMatching(arr, 6, isEven));\n}\n",
    "prompt": "countMatching's third parameter, bool (*pred)(int), is a function pointer PARAMETER -- the caller passes in whichever function it wants used as the test, and countMatching calls pred(arr[i]) without needing to know in advance which specific function that will be. main() passes isEven. What single integer does the program print?"
  },
  {
    "id": 3,
    "title": "A functor: a struct with operator() that carries state across calls",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nstruct Counter {\n    int count = 0;\n    int operator()() {\n        ++count;\n        return count;\n    }\n};\n\nint main() {\n    Counter c;\n    c();\n    c();\n    int last = c();\n    printf(\"%d %d\\n\", last, c.count);\n}\n",
    "prompt": "Counter is a FUNCTOR: a struct with an operator() member, which makes c() a valid, function-call-looking expression that actually invokes Counter::operator(). Unlike a plain function, a functor is an OBJECT -- it can carry its own state (count) that persists and accumulates across separate calls, exactly like any other member variable. What single line does the program print?"
  },
  {
    "id": 4,
    "title": "A lambda assigned to auto and called -- the third callable species",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nint main() {\n    auto square = [](int x) { return x * x; };\n    printf(\"%d\\n\", square(6));\n}\n",
    "prompt": "[](int x) { return x * x; } is a LAMBDA -- an inline, unnamed, anonymous function you can write right where you need it, with no separate declaration required. Assigning it to auto square gives it a name to call through; square(6) then calls the lambda body with x = 6. What single integer does the program print?"
  },
  {
    "id": 5,
    "title": "Capture by value [x] vs capture by reference [&x] -- the classic divergence",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nint main() {\n    int x = 10;\n    auto byValue = [x]() { return x; };\n    auto byRef = [&x]() { return x; };\n    x = 99;\n    printf(\"%d %d\\n\", byValue(), byRef());\n}\n",
    "prompt": "byValue captures x BY VALUE ([x]) -- it takes a private COPY of x's value (10) at the moment the lambda is created, frozen forever after, unaffected by later changes to the original x. byRef captures x BY REFERENCE ([&x]) -- it stores a reference to the original x variable itself, so it always sees x's CURRENT value, including changes made after the lambda was created. x is reassigned to 99 after both lambdas are created, then both are called. What single line does the program print?"
  },
  {
    "id": 6,
    "title": "A mutable lambda -- letting a value-captured copy change across calls",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n\nint main() {\n    int count = 0;\n    auto tick = [count]() mutable {\n        ++count;\n        return count;\n    };\n    int a = tick();\n    int b = tick();\n    int c = tick();\n    printf(\"%d %d %d\\n\", a, b, c);\n}\n",
    "prompt": "tick captures count BY VALUE ([count]), which normally makes the lambda's internal copy read-only (operator() is const by default for a value-capturing lambda) -- the mutable keyword lifts that restriction, allowing the lambda's OWN internal copy to be modified across calls, without touching the original count in main (which stays 0 the whole time). Each of the three calls increments the lambda's internal copy and returns it. What single line does the program print?"
  },
  {
    "id": 7,
    "title": "Capturing a loop variable by value -- each lambda snapshots its own iteration's value",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <vector>\n\nint main() {\n    std::vector<int> results;\n    for (int i = 0; i < 3; ++i) {\n        auto snapshot = [i]() { return i * 10; };\n        results.push_back(snapshot());\n    }\n    for (int r : results) {\n        printf(\"%d \", r);\n    }\n    printf(\"\\n\");\n}\n",
    "prompt": "A brand-new lambda, snapshot, is created fresh on every pass through the loop, and each one captures i BY VALUE ([i]) -- meaning each snapshot gets its OWN private copy of whatever i happened to be on that specific pass, frozen at that moment. What single line does the program print?"
  },
  {
    "id": 8,
    "title": "A lambda passed to std::sort as the comparator -- sorting descending",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <algorithm>\n#include <vector>\n\nint main() {\n    std::vector<int> v = {5, 3, 8, 1, 4};\n    std::sort(v.begin(), v.end(), [](int a, int b) { return a > b; });\n    for (int x : v) printf(\"%d \", x);\n    printf(\"\\n\");\n}\n",
    "prompt": "std::sort's third argument is a COMPARATOR: a callable taking two elements and returning true if the first should come BEFORE the second in the sorted result. Here, the comparator is a lambda, [](int a, int b) { return a > b; }, which says 'a comes before b whenever a is GREATER than b' -- the exact comparator that produces DESCENDING order (the default std::sort with no third argument, using <, would produce ascending order instead). What single line does the program print?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "Ar@vIASMylMjnP;CCm<hJei4;$or7YAo(zE5^^a_HXwm!1R}gh$NL^{j8jO6nO9Bv<^40$w8bV1v2r4K8D8lP(Jd+Kg=9Dygf8C3D7{e^Ob@Y(6HYCJUJRmP<_xhJ+opMMpMfH?II)0~lS_N{9nu6|26ecEyd=|;ha2%`rdD#+VeeV+>U4Ftu^<HxRJ(7g3+32>DRXf1g<ex`ix~^hmfCfeC1$#z$dMYU#)8pEBwrUCUWCj7E->@~0U@B%Ls!9$7}=>j(xCi8S9+|}2al{-Ci{pcWFnYA7kxrA$`UAusIw*RxZV>me&oL?WNhEuh#czylf;eWCJYqQdB<-_*-lepPl|nv%_Bsb*;v2v>@&;0T0b!xj}>C7IDHmA$6l>tn=GUhNh(`6#f!emrUUXa!Ru-3N#~oAUi43WLh`w0nul~5I!Fk1Gu+;dN^T)*A2x7@nRv)*pk6{Jyv|{_0eGH#?Jle?&G=Dj>r;iHUPzZ+&FOpbHHTv=*kPZ%yU7?^gTBHHrSguwgxV*y_w&q>-sd|PUB?ZtM6`&7ob-PP>~6<<3D-1MjK}cT+>%1+ktp&`82r^V_SivysFWH<2FR`+4HYo=Xvb(m<`AJ%Pf=gBTX_bkP}eWF=qFVOEm0QfE@i4OrP}s5Gz2jkZgCs4Hb^$uIiC4F$*xMH2`y=h2p08hNGp1CUWR`2YminT{a<g_zaGc}4Gsf6nDOsFPl2aZ5)L5T-}}!Wjptt?D(3*MY_-71SAMA?o~+7}Ds?EiNitfVN2kluM1GXEc*l<X<TmR(FaVyt!U&%kuW`7_4TXGyKO+>gVhbMqRYwl5d?l@+EROpdj>PFihD!2@2-Lg+=O;viGc2mKj5O1c1ecVd&y$8%hij`djle0)PzVG33w-jdO+<qL9i>+Th4)F%RNGL1id0-nh%P)3KTc~B%Hgj<=r4>7;OT?QmDU?v?oF;U%&r!-N=pVypo$Zvu6oM}uXXxC8Dm>{m0+lx)@rnBhtNHQQ0&$v`m^DdxVl|iRT}4*Xzg3RMTmdxP`gx#xFV<N=OGiodXB|oShJ1#^hB>JS9*hb)Fcu@tuFmq@v`*&skkB~Z|%FgtIrZ^k51b}C;S}9O!{ENtg<>Te%}",
  "g(QvXqd<Lwy*$!5LRqu4i>|czEC~-vI|nL=hMsO}ENCGLAVjjH4E1obkszKKi5cX9aG8SB2~I+lJ}$-LC2TlOZXlbZe6R;#hcXmE1N+M-JrjC575!?ts7dBI3quoV@%=bz>$65ce8L<SDqfm>J7MkpG`7G|czavIZ6wOdNoLB{<ff%94>Sj)S|BR%nKSf_+-lZTb1^fiAqOk)Er8&bf<yp90&!EK$5z@z0K%yc!q7c%4u|uxUwlO`v(`@q=y9|V$FP??x?Nn!kVHJFA%HKJ=FERI-UCkBwdFFeEzHDRjMQ@XrI;IN9ptfdN>Za(Z27QA+pIK}+T^3`{$10=5L71Gu<$vQGx8+Rs$$c0A<FjS59vnwCSdp5<j^lL?W&m#pd#4`Y{C>9pi{nVCRLqQ*+^Z~cj0WjY1?E_SEFuxYSv~>{BUP1fWsBkk}8>P^+;z6p43=d-rj69E`5%0QMOMY-Z9!v(cr3k?H4pLWgn6?BziDWvBqj@SZ0L}q<g&qkesK}6g%|_`3g>&gZ1O|HK=M@-{Ej|R_Y}}=Yl;aV0;io^|~-cz5dhHsVqs!7;7$lYJyE5K0-Uq$8vi-7)$%J`75QkRR&~0@tNSsQ%+!dQOg_M6+tGX3+SgX_95TBv071Y|7z?xp;p5vO*(&m@LZ-2<XqA{uDPbDjiDvqI33}GU#}Ef6OHh0Yl)SZEl^rDV?39@EVnk@1tC8!F^zGQ(f5d2qSUFDl;1VuvkYPbF*yX&))}3uOaSs;$~p+8+kDe2)N=5URp`Y5u){6?6+D0HmpwhPnOdmkQHy5JR@*C^vR-5b|6|ho6vky#ER)-Gc1H%vy(dq|fXa@RQdnO!5QHaU_s$di$!T|z(n1=s|MOt3b{2ee;s8FLdT>kBAy*v01y`va;yV<yb1GXVEgICe_m>F&Y1si1kev>^MfX%?bhp;dW*0uxS!poV5^Q<(WMMJWvP^YWYUSPm9fr$tbw%qioY{dHz<{{dVdChB+iZn7dGYi5<wyNTKqA5Z;Saq+MF",
  "qs+nOJP-F?$SuOy;(s{(m;T66(1g`UWJNKfhAaT{t!Uhwz|Q)IKKo`U0kaK@hXv>-&e=^s@uWcq{z3@C<USzkosHAy_Q75|-r%^w{jT8C*0eH}K0t;G+ckC~-WYn(OKT=AO4I7UR+lB{H?)BT#uMF@B=pY)mF)6c9%McjZC`pU#7Ji~HeX*j;iH^qkEl3@jv9UFSsbOR7b?Bxz!F&~Vkqh;*EPV_RFgK&f#m2Q7)g9AzGgS_AKou4I90M<{DUF9K#&$~YvQ-kWanrAgG4<v&aZ*y$#Ne3?`v^R$p?}#5BrIaibm~b*5OB9TwO|FI1t<!M7;Hn_Ntk4sk6?>u(14IT!z8B^ZG6Ub9F4M?icV$u+XE(ycRh_f(TZLpb+6W@2+oLaiVEABa66{S}jN7u_>Pq$@=L1lKq7nPg?N>aW+A2q2!eyI&V(C=gkEvTrgr(Ti?T$gK*H9dmlA2x+K0TkjOjst_Am0B(cXdYQ)ow5qzU{n?Puo0fop$Li16n<$V1`w<zxCQJu6p=+F~{t3&3-h=nVAq;odAk~goq&+<<ztkKq?Utk)bEAg4&&1l=ar@5d_J(tk>Vs^R262_ivtZWEX=n?Hq*aZx9B!kN4eunXCVIRxi|Ja3Trut0b#Ks$fZHLXQLkllm-tkejL=Z?nl?2Q_VuAT6QmnG7_UXoCU-T-=>~DaY4H%7(N{p-cUGj3?v8oqENMcqOm{R5&aK>*`elfN0@+94II!%f;TP7NssmeZ+d=4!NH<$A}gg3M8+|CaW07|%T1RmWgN-<9Y88P{fdw1)tEI2SXL6hI53c5E7ZV|Jolul&|4<Eaxj!BP)cvPgGf(2n%%}7>Hw17VeoT;32SfFYn?Hm!dBQw)=eSXtmN>XRLnYHdPv-KO^qrPP7$%-KAGz2lBmrjixn?sg?ZJL+WZFAi6pXqVupg-=!nH*P!=2oi4M!*L8=OwC0E<lK4iF!Lb%*FZ3<R1KqNdS<cSij{mjKxsq3_uDHx*T+(L6?mmp2CaKJsoty>690FV+u$=2J7g3BI2S`(*",
  "90dy|8?>qqZjm5=S19~5SEWlF9h1D4x^CL4AcvoNrP)LXmgGpvN65}OV9J-&ko5t&^dv!~%ZeHxCzr}<+X`T;XOf9?wdHd6XbI*ToF{h@^u@loe{@^^f`IPN8XfO1VIFUPlzPU>XeAb=MalZ|SDN=YwTqa<z<;-e0bsTVG%PHGo5S4uS8J<^3k>kC<cr8Cj1kW-$>%b~sIw6|{1cEEncQZ!WSKAA<n03OOIyi1Oc#|fp&${pw1Sr1p(z{&I~*#L%6|>0t}urYe@|=RH{Jj)7oSj&GQW-Qn(b=cB4gr%nR0t;W2j}w4ep%SH-ZC^`uI7|kP)03xOTas@Kf-l_I|lQjp{b2I)IhU*M3$03W;)>2?k{{?WF4R>D-R}?*K8&-WD-2I134z>DMDj@;)t{sc{R8+38A~0r~{v81|%s$QZhj+jtk|J1H-=9!bS4Wwdif<J=)nZQ|IxNq)(|BkI6a4EX{<^~b5jct&r2lgMH4<{J0*1E4#s{}FOLNiPTOL2bSi&dw89G_6IKO9Fzkm}X(eQ4ssCS2Q$a2wex3f9du{>$9~>r!{;F3b>jv0VRpK8HaMm6P?fZ_i=fkf{l`y<n_G+$$|S|*ofD88gWbtkRRhqMs6k<L~@Sf*4Y~T&5*Hq%~&s#Fx0YNHHhUo;&#PBXhhrS+g$hQY~9hIZZ@S=7rpsK=B^<f*M945Q#=_i1s^(^eSD+^GLD$&R9Y3nec}gKnromWKrB%B+h+fjDu~dX-vN6bfbbrs_G_)EN*U_50<{9Kcm)e#Dio;>+eDs_PB75uqFXIfp-<VDmYs5Q)INtH=vxtEe5U?6I>*Gg;%OT*$N@=)bClZldKqf&K|mmlnr>l~YRhGKu}SwlpK#&XNj>?pqPhJ!S)<u?+KeD%19ZM%42^4{MHI9-$(+m",
  "D@r_DdN>B$lDatuU(;Zrws$pm<Rt7WnBLb9OdOt+D3!xTVO@^}{nA6HhGJVj;e>;Lj*EuI<SZlbn;hA80B0FZT{&?MFCr#W7sI1VJ=%9eF0RTCLLc`$1hyN_NRyek-MkXggzi)qb*t2<&06yx)03w$gzO!2lXaVNB$K|Air%0ZtX8{ib{2=T#2^ZRml2qF@!0Jw$CjyG8Y?(I;>h)yy#kF)E)n+qzFAh$<nT6M40g~xhyn-{7R<7GItARhi7Kfs<=b3@tF^#As&*d2n>Oe`ecPI6Xh?E{SSEIuncrS%$~j{?+hE7i6Q*#tCi52lPfG6Dq0M6n`)@CFPYV>@EjZ@c9d$-}cSLdOWR;#Lv>ThA5)uc1FkOex0C-u`oSz1N5eE2qyCAN0!a(i=VD$EHVF}SVWa=w*19wB{Fl=am)NB!wPdy4wUt&GMfnCtzReu`(>ymZLb5c8)7!o=odrFj4CV(5A_hkP!JapPQLfCNyDUFxUG4X)U&yt7W!DgFiOqm`7>`IXl!Fplut)^3|7lf09)F0R!uxN6roSfv&`_yPrH=JMEZ-r4Vp5%!l-_yKR<U<Xjae>N!03wO;<*8ISZ>bS|LwaSCi8~E)<_vfVBLKv@*+mzpHLx)dS4GS(^#|reYMcbkp=VwRKT`G=4M=BUlG3KvuK;j}2C|{nKan7VEqCskIrw~i^(`<6*|m<D2@&?&YVqwrqE@CjZ3vc*``6jA?s~S?1e$9;mqYnQr<L5RDQ#uT_HZ0n<B}h6820Fe9hN+Ht~~E7t93ux%w#)DmqH03%-;OHzG*k@YA{QnumW@SGdW&oe+z4}Eq6G1$f~fN<N7}zYSWcTTU-UtjuAG0^t|Ml54+8T;^f^Z1*503%n}fEky~@FI(3D&NT0y*r0hIOQ^Iw$i<7U+r)A-jL_Xgk+CJqLBt-vpFVbUls3hwkl7W{yN3>Qufp!m=h1h+G-$hnVRE_WoxE%Q>?!t&~#znfNxKsRVbha-dT-3ktBcjWF!j^X_D+~^BZ{QmEiNK{A(_=>e@I8kEVV5gM7+}&IrfC)VD|>pnk0xwAc;iA$95Ws>VTD_MFOs@iFmz;CaGyz=WF3z9HC0yxRwjNTHKgw-Z{FFXeQ9MP^<uRSPu-PUY`_9_Be%lQwT3JLB(#)JTN?ffte%j5",
  "eUvX*a%@NvkU5+z0~K$t)AI7%AfKG6Sn_I$`q>4a#{fiVE6qKruJD2lu&bT8bW;uuisEi+f%0<v;{Q7U=klGf_#)lYWq+S~VP{Hw-kFmm7Ul)+G*DyC?l`i(QjVe*^jb(1Vt2>hZwty2QH$ChW*y;YGsHM!o{lL!58$*UR)@?s!c_Irw=JQEH01+dBiA=Ct})ETZ&$gFSrS!PE#Bh`vC!r|`EL=`H;2{syZ>~L4EGx^MDoSh;*K1&)VHIdj9!f8lo#>BK&6R6C#vr)Vjwn8IM}-tg<u2sU{N6>1%h}0)eW~dnj5zf=WFKxouX@F&u{5vY7WUaEky?o33)}7a^%N_D8OS82Y&0LcGX|Ym`FlY!zo%GudqrS`vE^t?pzXSLVhmpdeam?yE9{37(OlTC~q^U-vimd1v=Y9fZo%-hHbpCo!T^zSR=B-Xfs1P>6W+@kIiOXT)kxI$P*eha}+}0S-i^y{sqSUH~gur5NwTija@DvWj1IeW5QQA!t#k(SA8$~#@h+!g3_YRqkEP5!Phf$>G(+<-vTi2z{^OLN4qvJ3oId7Q2Mr4crFg*yc$E>0~?3s1-7oeoR)3uqBx^#O&`N>Xw!2ea8aLK#l&^b{Y+wlX|spw?VfPMEi~~P+e+Qz{Zu9+1387HyE1vZi0^Ph&RlNO3R_f)run76L;RUc$)M)v@mV5$65KgkwCVxD;RzsO{ssS&1EvPrQR|D=v=*-(Gp^b44Ipe1`@3Yn;2@c2N@88p@#HCnUgo}O?MCWK_~CJz(>7NsyVTiD%{rW&tn{bD*dZiB`Vr<-r!b8yt%v-PPvd5x5qfQRPCNy&C!(L>C4*n>%eG(+zchn9V?-XNF&cbc0wrGD@jbkO8Fsw3f`*#Z&z5Py_yXXle~|-eO$ol+LR1WU5W8=2Wjiqmiebm7pa^o27lI-fbu*UwmwU7Po8s7GApKMGlWM!ENptkMcVfEOL&&wwlLJ9{eUC)srcl1x3L=Pbou`gIE)deQVIy!2E}Q8%8ksM8ydi5&HvigIS`MC%f-<)(f2;-OKcDgeyXMc*%ll>9?cKK|Sm+xab-5}ui7NwJ%YIUJG3<fj6~kg&!6aAb?GvHkwRcQKW2b23FQoyeG8l|A7_BqXIUUOf!@XshAkyn96u(xJ_;S=zhcJ$hJ-k{_=yjxTCA>Z2U|XJT8s3Y53NRgk-{s2oF(+gKClkJ4FHPFdVO$Uicy~bkut9ZLEeL^N@D0VGTE^P~Cl^-bc0RU?M|>T2KfMV}zuu_FuEg9>6U+7C{hyZeJx!@w`F6L5>Xqrt4tg`D`oCp<d_L~S<i}pD;!W^~tV;",
  "Ku$Iu0CY;yv;7o_IX9a-ksJ{rN}4-DZ(bNoBCX<r%@(!5vigCe2pLN<Mn?6-mx+inj!ulVY&Z`SJo|LPodNI4?m2$TDGy+*=NXSz;UCiZx};%Rw9KEoFG5ECn#g~tQj498mStxiMNk~>>4PkkvU8Ff%bH8uCE%uFA6`=84?>bP)x@FcPzMJcworUQ*^BvdJoQ{rL{6MOc*y7|X#)~)UAe*QTz7?EZaQ&xL9<<U)zaz)mi@Lc;m22zvagxWyq7PX<vC@FdtyLiCY0rHE{oggjJV#MC?cK@EM|3uT8x9q24ARuwy+CLgzi*BN$Vo?P(jf|fRx#;UqIy$Pfu`NeoZ1xPIJw1v-c@jSDZq0l@1*>^~qsKoH-GXHRMs)fkp#gW{1IX4Ex1>n#|@vaZKk{BqElrWWCs>4H5F#MiOhh3Dx*6z@6HVkd<&N{vm|$-bZNPfp~jPHnLuiWj+bc<X<Jk0>Dq^6@sxdmio$6raHKL)5u&9ttA&j;8Cf=URZkg+8W>ZJ>-7HLRP94)AB@C;PFskTamSYz?=<E_pXKy#b0jzYGT!CC-eYZUFuZlKUW!d@r3#8;m9U$rIn_iZI4!NF3RvL)LqA0DlLW`Y7~>tL{7u~ZvgOGFB;<1uKpb*@qmS^1r$xR=nn%Gm|4J<u!2x#%PZlD0DkspVirb4+W9x+6N2_5^YFnvHLm_#WWejBaR%0R2Qh#VP91uB(;^XLK<4!SMmS~IgO@bcodn|YxRuI8+XiKzkHro0tI;VTRs`}t{+yl7i*Mk{<KI4AK&K%WbfrrbUOkOwU*pC_-h$1}Ftp)rO6e`3NXnl=q8xR;(T}O0h#&-cR2zrj0OgF*h6;5ap-v^3dqw<@DBo7$B+0>|{hMASCfiRJn&|=n2znY$g$98|#`E&j6W^hIQ;HwUyy0NJ?NB2QpHa=s?W6Wr?ezL_0H?R8(YW4vi!+~|R1d!CpN)nL#{6A}9s|~_3u(dGhOt!sGP`boB(-C*E~JtZ5T15t<8%U1nT*+*>9kcd=mowJhKM9K_<`_}!rzDJJCg2uZ0A~BnO_xwz~ijz#HJso{R1W~YH`eP4_dcpCNeghbGAebE$GdvHuRQqtKn8Q?${aIp;KOH3xRF{f6Z6@XYM>cxMaR;cSZ4KoqIG`$Sdn;3z}=#_f$jql*R|>@^gT(D6S>ENS*{?<^OTqgw0<r9~Ac50}0ETR<O<kD(huzB!L>F*EuVT%1_MBENhT?b?VMive9#r(^Y)qdVN%fdINT*@ntc9%ymvgBuD!zF={rF=LYS<@RVO5?|jh|6*>91w#}>ZUb{E06sjWR9&L@-l@LE=i;D?3",
  ")r!VNiIW&uCaYtD$0_;mdiFo9J#`UjG`aUpgI8=4PFGY?P+VMBW~g5}T8kl}Jja48{Odf$94mwse2u^09Gh6=LdsQmuyr))M>pTiadZf>3Aa0%o8aImz_Vx`(HO@<9_a?h#e1iG2nxRD)rY9)%_c@yV+xAgEFIcJY%3C7KMPO=@0?wYnu}&Upz?6aiX-0(6hlR*kw&t!T>&t76WDlYqM`IZ2ohilE@ggT0>;3$_IzKse$K}J2Jl@2YtmS2lV3=`F1kdRHPs1V!NqK-!2*ISH9I!_2KQErsAB7dbzT$EZ;nWHNIDpv)^qmn1zn+^rOUf$IFm!J>UJ*^q~^Kf8UfFLrvW^lqI^K{4J$=Jf7?egt_jOQBXAyIb8QyPHK&vjH7@Skyp5D2rUYG&JuA_PdThr1?m+@xnf^wXCgdPm+8lNXS8`|26`LeJFDA^mBIH+HFP}2g`e`Y3DfHMrB?RH&f88_%YY9TY`i$p5sE0I>3k?sJ4e!;}%Mo}B&!(c&lsAqKzKG1~9y1k-R?17gBtAE`=vd+aEGY&eGf?Nxovj^`L$$;)vztnZu`V@Ocn9@6nlxOIX*_14twlq9Z#mdMNbE;ZRrmK7H>Ekv$|U8CX;y`C&i6>Tn_Tca4g9|F{AsqX*6HJowRs&o1qb~@m^&eAc`q&fnWJd~ZO*2EK)EOWW-X*#5G0;3jL3|Yj#CGwZfS)cvcY^sm8k;jKHW-2t(WJ~2<zL*;Dl3~laX<OL3u$65FLL&dN8~OwzhwE>-$|!MIbUOT1ovs7#)K|$00c#uD=tv=9uRWe^*AdV%pLvIu!WF4BQG7zf7t=rl{x#LY+V6#rL3&$9V_d_3<mpQyE_@&4Zt!VbO0++EP*jha)l|Wd<mw^;lEh9f?Z>7FvnfN0QdCZaeEPe&Jp<dO<$%$=Bl<<|4wzg+u}Jlc$%p?lqP^<cXW36XMPAN%5SFb-M7i7c*l~(8^f_2)nhBVM&sj_YNPBSEGBFyTtdp5O5XqF&L)jLj1EYAjGC>>rG!8u}m*14<*p{3g-$<ta1Ll_iOCwnn6<?hcD|VFfaXBUg3WL5)g8?wq>`Cvcx&t0Fd&}P1OV&fRWqyhu1A)fu!Ua7Ef&))8z|M3RK+HqaN-4;&k@HYExf6O{@b4_P>xy"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "callable-lineup:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret

def _find_compiler():
    for c in ("g++", "clang++"):
        if subprocess.run(["which", c], capture_output=True).returncode == 0:
            return c
    return None


def _compile_snippet(code, compiler, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.cpp")
    exe = os.path.join(tmpdir, f"s{idx:02}")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([compiler, "-std=c++17", "-o", exe, src],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, r.stderr
    r = subprocess.run([exe], capture_output=True, text=True, timeout=5)
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Callable Lineup; importable without a TTY."""

    slug = "callable-lineup"
    title = "Callable Lineup"
    description = 'A CALLABLE is anything that can be invoked with (), the way a function can. C++ has three species of callable, side by side here: a FUNCTION POINTER (a variable that holds the address of a function and can be called through it), a FUNCTOR (a struct or class with an operator() member, so an object of that type can be called like a function), and a LAMBDA (an inline, unnamed callable, optionally with a CAPTURE list that pulls in variables from its surrounding scope). Every snippet traces exactly what gets printed, including the gnarly function-pointer declaration syntax, a functor that carries state across calls, and the capture-by-value-versus-by-reference divergence that trips up everyone the first time.'

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def compile_all(self, compiler, tmpdir):
        """Compile and run every snippet once; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _compile_snippet(s["code"], compiler, tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual compiled output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    compiler = _find_compiler()
    if not compiler:
        print("error: no C++ compiler found (need g++ or clang++)", file=sys.stderr)
        sys.exit(1)

    print(f"\n  Compiling snippets with {compiler}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="callable-lineup-") as tmpdir:
        actuals, failed_id, err = ENGINE.compile_all(compiler, tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} compile error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
