#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/implicit-conversion-minefield.json and re-run the generator.
"""Activity 2: Implicit Conversion Minefield


"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "8e2393788a6c93eb0161bc90930e084ad94457b2bc0c96f34532f6cbc166acb0"
_KEY_B = "b9763d3f04401796b7fc55b95c87a0b713f6f5fc4cb8b479df3ed3336c8370f3"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "39bdb8b9135596b5fa9c3e87eac9f71f4171616d6548425fa1d91b7699fe6f3ff9ef4ba7aee123c008fdfd0cd2bacf5d03cb2432a5d152ea96e818169232"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "double-to-int truncation",
    "platform_note": "int = 32 bits, double = 64-bit IEEE 754 (any platform)",
    "code": "#include <iostream>\nint main() {\n    int x = 3.9;\n    std::cout << x << \"\\n\";\n}",
    "prompt": "What value does x hold?"
  },
  {
    "id": 2,
    "title": "assigning -1 to unsigned int",
    "platform_note": "unsigned int = 32 bits (any platform)",
    "code": "#include <iostream>\nint main() {\n    unsigned int u = -1;\n    std::cout << u << \"\\n\";\n}",
    "prompt": "What does u hold?"
  },
  {
    "id": 3,
    "title": "signed/unsigned comparison trap",
    "platform_note": "int = 32 bits signed, unsigned int = 32 bits (any platform)",
    "code": "#include <iostream>\nint main() {\n    int i = -1;\n    unsigned int u = 1;\n    std::cout << (i < u ? 1 : 0) << \"\\n\";\n}",
    "prompt": "Is the int -1 less than the unsigned int 1? Enter 1 (yes) or 0 (no)."
  },
  {
    "id": 4,
    "title": "integer division before double assignment",
    "platform_note": "int = 32 bits, double = 64-bit IEEE 754 (any platform)",
    "code": "#include <iostream>\nint main() {\n    double d = 1 / 3;\n    std::cout << d << \"\\n\";\n}",
    "prompt": "What does d print?"
  },
  {
    "id": 5,
    "title": "bool from a non-zero int",
    "platform_note": "bool stores only 0 or 1 (any platform)",
    "code": "#include <iostream>\nint main() {\n    bool b = 42;\n    std::cout << b << \"\\n\";\n}",
    "prompt": "What does b print?"
  },
  {
    "id": 6,
    "title": "bool arithmetic promotion",
    "platform_note": "bool promotes to int in arithmetic (any platform)",
    "code": "#include <iostream>\nint main() {\n    std::cout << (true + true) << \"\\n\";\n}",
    "prompt": "What does true + true equal?"
  },
  {
    "id": 7,
    "title": "char literal in arithmetic",
    "platform_note": "char = 8 bits, ASCII encoding, char promotes to int in arithmetic (any platform)",
    "code": "#include <iostream>\nint main() {\n    std::cout << ('A' + 0) << \"\\n\";\n}",
    "prompt": "What prints?"
  },
  {
    "id": 8,
    "title": "unsigned subtraction wraparound",
    "platform_note": "unsigned int = 32 bits (any platform)",
    "code": "#include <iostream>\nint main() {\n    unsigned int a = 5, b = 10;\n    std::cout << (a - b) << \"\\n\";\n}",
    "prompt": "The program subtracts two unsigned ints, 5 - 10. What does it print?"
  },
  {
    "id": 9,
    "title": "float precision loss on a large integer",
    "platform_note": "float = 32-bit IEEE 754 (24-bit significand, ~7 significant decimal digits) (any platform)",
    "code": "#include <iostream>\nint main() {\n    float f = 16777217.0f;\n    std::cout << (long long)f << \"\\n\";\n}",
    "prompt": "Does float store 16777217 exactly? What does the cast print?"
  },
  {
    "id": 10,
    "title": "floating-point equality surprise",
    "platform_note": "double = 64-bit IEEE 754 binary (any platform)",
    "code": "#include <iostream>\nint main() {\n    std::cout << (0.1 + 0.2 == 0.3 ? 1 : 0) << \"\\n\";\n}",
    "prompt": "Is 0.1 + 0.2 == 0.3? Enter 1 (yes) or 0 (no)."
  },
  {
    "id": 11,
    "title": "integer division then floating-point add",
    "platform_note": "int = 32 bits, double = 64-bit IEEE 754, operator precedence: / before + (any platform)",
    "code": "#include <iostream>\nint main() {\n    int a = 5, b = 2;\n    std::cout << a / b + 0.1 << \"\\n\";\n}",
    "prompt": "What does this print?"
  },
  {
    "id": 12,
    "title": "arithmetic right shift of a negative signed int",
    "platform_note": "int = 32 bits signed, right shift on signed negative int is arithmetic on gcc/clang/x86 (implementation-defined by the standard)",
    "code": "#include <iostream>\nint main() {\n    int x = -8;\n    std::cout << (x >> 1) << \"\\n\";\n}",
    "prompt": "What is -8 >> 1 on this machine?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "ie~z4W~4gB6oxvyrgB~l@W4NTIe5jElW7m&p}jFd*R7K>3YOz)?wLrKh6m2nU0|A9B_Y~U@z;)ad@LDanSy<CY{oXgYtmIQeIz^OmyD#&wzu8L<4a0;l+|?J3*PuY_?%=Y5JY3X)->7WIs-kM2wKXcnlVS5>J@|NJ*nE5<v##*Ss{VMPNA^sEOWmG9xy!Btk9%UdBx`Ng|S72>XD07j)u`L>S#@EQL^1fyBD3c1F9QgotX<;23I|^JWTWrWA!n<MP>6SE(v+g@T}`&;E-Z$(zTO*3V^>E<!j>+A%Fjr90*{RJn3nVlmj?AVRsHzKF2YPz<67hwj6~WnIz#d+XIES3T)$dsoo<VlCLxoL_7Aq`wI+C#hbO!ZM8nn@dW>I&6tcG+1L=?SBF`|6VH$prYSeZ$lgb!5?d;?M`^^Yrjaycc)~K<$ArG4E5d0sbTt$",
  "<`#NtB35f0EWL#D;ztv1xK4viV9Au7<^e+nk<Cn8WmD#n)(m{7A5NMyRQQsL36*qVZEcGd_ndUz=OajkvwB(H@vazrbg@N!JG>Jb$nc2_74+md5KeE}12aEPEPluBAY{3=nAX=j|8+5h*aq)cd*z_gV(MGkvXs(E6cbHTb{KmyCaIrHmukXoI095fe}%FalD46Qh!<=&x&=3PkKTW&>_c!N8FEEK=et30-SWk#$)CQXyLjs$An71ei(=+ywY!;WB>nukQm3J*%TXj9LV(4|SHR{u>*q?pcu7o1`5K^p!|H|yRyLP_1Uu4;emB-}VI&4hY&6`?{Mk>jl~UoZm>Ug`-eWtf+px<((p%Z=68+(mPgllJ&<iNYD<P<jY{^{QB-=zuvb~BxzvbjaJU`X8grBk$1lQ|$q1cynR?j|t^bM@i7i<fHFULHigNq1N_9kzWBhGL(sF5rlqxMiBmQvuW$_WV-Wq&l|b++#&A^",
  "p$T`ixaJQ{^2A>@+-eY`70GS;Y?HsoV}x%XcGknf#L=K3E*UYOwDg&2K8gi=)fv~itiW-jTggtI_m{##&lg|{C<Vgl_hbQO-dj87KHxXi<Go+Z9A;SgzR{lIXetVe_5KDYT3LW*0>Ma5EE^9FJ<W_uB0ecZQ3^No)J76;QSxa)(n%A$uX<1nBkP{x_n7!!5oqN@$v3=!@7R?o=7dPu^-8lkN7D#TiAeGtYik4oNjUxA{4f<hO)B|xZdX<-D_>gMUbZyky;Ru%6_e_Jqr$ZSoCcti>|9!bRPITI*uclk<LS}dsX#CU9`baxT$MPfV#K`~QUWrBzid%!s4_Y09V!&u$G|cNeGG|eF?6`Zy@fpJsCLrnjYva4x7`-UPMAryh@Y`79A*k@7_YDKvWI5sB6RR+@*C+k*PJ4o&($fN9elU?@g}A>B&%2S1iB^9P5q)BMyA_I&nGUs;C!<",
  "`7^Fj62Vb;@~Pcf5X#0~<_IF>U_77B19xO=fJ2q?bt|eBiK|F$RJlm4)6f-jp9zjUagOdWy@$WoCf=xlQs!1=!S(7*mH1r~*0<oy;(N||^{MY8%ga|h=A5l#E+RV<XsM)^=WZrxyeM>UFUh`1e-z2CVW-PUP0zJq!W3eIuh<t8PM87L9iVzjL_J@*A;sZOJF4o%dH!bnvtr25QMkz1SePUG29)YLKiw&vYV|BUG=XQo=aVA@>T=W|TrtP?z+LkvBf*{6K3`mu@k$#sS`~EgS6aaMXX_ixb>7g=cTY1$Oi#k{YIUrK!ZvU5@DU&a2uq%*)GGd&POyvsW29mn=V$C!&vDLPi%pa&8>=Sy52*7!eE-ga(EKJR3w637RCE6n0a3U;I7mJ4=Vk0~tNGYSnV@YnfDQLzHX-DS$z?#pvMEDOLk47uVl<qo_NI~<_sp!Hz4Ti9qg%HAfv_NGIbrAw&-!OE3Yk|NobVqA0mh~W<9*ZRJ;zL!<GW5Pfy~d>+0EEzjcjvcbV7+|hI_5!-rNdB|NE%a",
  "S&;?^1cypt&hv-h%xhv-(|hf%IgFW2Bw&R}(Pu}UbPK#|6wA2sQHf2Hq$gny^T=Cl&RZnwB3?EMjj2F*xK6f0r7?|YDk5*0>@SJ5Dzcl)%q<Vzf4&evk%CP$j=<!gMX7NvL2=Z*@jZV?2qV}3)d5SJz(~I4exdfPm|*y#)l0lf>D=u7N6bLn|BOCtZ_4Aw^q9?Vw}Bdn77KD9Ft=V9UQQ_gOJfY2Z7Yg<0I@G(D2tU=1*aBemX36tLUPH$tV1u1mF~LsT$YZBNxDT$T7eNi585z%c{s$t&Sy~%n~$0|E=ctSbkHyff}B3-7zRXAPjphZ6AZ`VS|9^ytxF3(qPz7a!qMm20Bsuy8T0(?e^Tj&t_YoqJQ>0BD_d4R*@5pG>EUi71=E;}LeAiep1>6DT`$FhCI",
  "_^*?2QLdZ9zbBQDS!cvg%VStuxV@Z*dzh|yQLbnXqcrGrZx1kxl}|7?;KUfl4ms|H&b6rTI`6{v-TO}PWFf1rUJ58gA$E}uBiv(b=@C<|9uLR=;%THg+6zW>IL;`LWivnAtq~(P5t8k_!U0bh0T^-kWOxVl0xsQW;tDc5m?Nuyd`UDaKFC$JE5l|t$FWM(&thl!v%1|G7Pt?E9`Am7LBdejvE+T8>Ufq-6o|OKD&6*ZS%+nw|L27youL6&?-ue8gLyFMuT=J;y1t-wGS{YC0h9Snp%a93LkcC5xS>k4@B",
  "!OeU*Nc~k8;Ge>2IF-nv3!(PqPoNO74G%~(rNgCo9-R$sqO(f!{_TFTM$c3iUI-=uSMDQU^rAkk8mky8;goVPX!AS~ir0XMZu$d`hl*6l%4U@(rh0pJ7xH{dXs_iHUL0Ple$(3ure|dPjYX-tU@_i3u?0OUy~=p2G2Qt}O-`Ix;<!t)d7AcvhfeUv00s%iXKex%S}1EEC0n!a+}GXnt{`OqT_E-v_0sJ#!zDHxgM^w+%$ItZVT6We{(e8?64LdZX&wl6o$Q}e^kVV1&7A(#gf3KF2zTu^<}@wvrzE32=ftkdaNzI^R{fWYCO8o#&tU$Qr3d7L!-y)7D+-_FLW%e=Ln5(^nqlz>4432F=1y7r3BZt6akLX%1o^YeTcdg7MWpb~L!Y|KRIjo5KzSMQAv1GN@)D@G-cXo6C&ME}1RUDR(>nZIVy$2(2J2(%u5iBT(MM=-Nxpu>+A@9",
  "oX-&zNBy-6_~cz{G`5#-+*-^CSbPu-XKBa|GrZLu4Q{9e<GZSF7>dJ!`|(<;waotrrwkR@+aS?NeK=Ur<5|}va=(Kf=o)z$V1(5HTfA;y1nBwj+nyRoVLg!@$)!g#$E`X=;YpSd?#WImB8r4NK01A<7XmbwfamV8Of!Tjs(HYe*3Qo)3bo|mM=Slw;^cR*GTaH?0s?bQ-(ctzPYs=j9>`{Hdo+kof*M-D%D_q#<24M%1T9{f@3mvcT<-`K3tGy6N)05>h{%)p-C%M#8|n8xrCEF*n%nUuyokO|g{$g*erd)Yf%MO+e4kfhU13!MDJ<mJnVD17qh}%yfh$l+^ld?Kl9UB|N7$*+`Sa-2oArQZE-`A?cH{cZERRGVmSB>>+KZ_>crc7XfiC!>cdCWi8Q5n}S|geOO8L9neG31NriksjfaYADe7P?",
  "S~9Y{JI0N{)5&=r*F2oXt-4DQh-9?!taxq+873b%t`I5IWmv#vL9icW&fF_LoVMINlC;iYz^=X|R++%~dM~5e9Ln#jsk;zS{WrD!?c>MWrz^fu9VT?2ufTX_iAXhJNvMgPs$JtBYS|aL3K)olXAS;HowYnICVi<yq@IAqt#r+omYAoLA9D>QnFa>|-R`A_J8zYR7e<2%&XxGRfYcAp1)&DA`BA)g<AG;<_`lg8x1$FD5KQ$$XI9Er7V#uYuNZxR#Eos@sNM0x@MIjiwB3Y53ah<kq8U>|qZI0xI;DZ?+j+#NB%2_E@-LAd1@wA&Vw~2b(K~0w_uX=}3+-73G56jJ$@xHV?iD})ugJFcPINnOIRT@Av0yHpv2mCdh^;wR?vjNL<Igb{1uT(si#!KXZA1",
  "ZZ0h5qL#(+>?vuEd<7?65W*Um<I>?~Ph@n-Gwpru{ekc=&P<B<8*^sSWejzmefUi2h5QdDgYDR<JxKtwj(|M#^<}<c!`2hWJ?W$Vlh-R;N%(q~?+@x~O2-n5jNhko0$6VD`P25eX7)VL3z7aEbB?nY*9cj+)N|hs;pkzbAb5pD2qAXo;n(@e({1@}qHXz{mBz>p(q2*M;a&RCW8z}CQqy%rXQ;3UP0uFQ<`ME9>_u+Wg<|-L$ayy<nfEOcqY6EuQm;W2)VySH&M>Af1gbsVP6+n|hI+hA69e33@P-x>XM6i}T>$dRpmpck0jc~XH5B3fkw0Ypm(~;SOLFV8;^8kM;E$cOn6DMPevWI|K#I1;P-DiipH3G^ClMS%hzeH2tA0PRNImOBW5?MK*o-?<?)-)<$-L#$=G`q2U%2TG-+tPqM{Q7$tEROmB>",
  "X!2%+mIMo2BrDZ%XY*fTw;Sv#+(&qs?OG<*wZG|d7frgE{#ZYH0^Av<78(v00T+_w1O9SDgnJEptSzVB=X6RVRZP2?)qz^J69p>47kL9moLAH8x9*pz2FsMs2C6>+&@ss})y!(@r99TXjZuudQxIUb5u4x^^XMU88g|&Z^Wm{7sDJ1NqYvY;P%XagW9+I|gBY`rbPMJ05ERWbKkZggCU|*d?%?R`#kbG1HiBgIJ3B|(o%iTDTrkR!x~We4(VTx=`<mUWDs4}9dc?f>CKK1(tWO#o0>7AIpBEIQ<605COKIHpS9UWv3zSWm@9#pZ5Y`kXbg@Q4p$}9rC~M`4D$a30>H&SaX7>ll2-Tm<m^rzTv+;fSp`)y}6QKbE+_*IOZ*>;l__hQW{;G^3kC*jh?2c<@1KT=og(8{n+@LCRdX+V-Rsa;`|10xtf#RIMEe>I3@aSmZQi*efqn(W",
  "(_j!z;(hVEqS7J&ur*j2J1YWIw`zXOGmDD>1%t_$02WhU9W`q*2mb_<jfn`(UjN<`_W>P(WW4&xl2<Y!2!%xhaZ(NOeUnK<!^-61baa+(l<l$Ub#mIByUMY|nf`I<*Ck0?$g)Cm;4=IZ(uHFtLifdl5dnQQUi^vrlnOV)^^-Jr`7(751{f)_<!v)Hqgry+x|`u5?Q%MSRAYXp+5^M>S8mVqF2?kSn`$7;^4-j;Z+#YeZjy@rT3}HEAvBQGY_#aRbQ)z`MsmB6O8Kq>U~iBpAe_oTsM42ubJr0kJ5YpnaC0O|9PIKkD^D0gs&xPfHhVL3*a8z+-=yEQnXh5p_0dQFgptsF8Q9)?E;>Ue5-CBxsLywPMrX^C7Yt{rp_{M4f)VJqMic_pk6<=a<@)`Z?5vTj5pQk$>G6(O<BwZV?<u%n=HGZqE%Q_@Em=IBDGCvZQ*jLuJl_Qjpo5hIWHWY05;uxiUfe~DE_@M#xe>cNI_z}K_;rc;lj<eTcSckDWrFiE2n&#Zm4$&0$Ce60hW=c!T9uz2{_~OE4cN*XjWaL%MbwY=IIW3wy@)!Az%lvG7kU&!1jZuUhy"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "implicit-conversion-minefield:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret

def _find_compiler():
    for c in ("g++", "clang++"):
        if subprocess.run(["which", c], capture_output=True).returncode == 0:
            return c
    return None


def _compile_snippet(code, compiler, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.cpp")
    exe = os.path.join(tmpdir, f"s{idx:02}")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([compiler, "-std=c++17", "-o", exe, src],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, r.stderr
    r = subprocess.run([exe], capture_output=True, text=True, timeout=5)
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity 2: Implicit Conversion Minefield; importable without a TTY."""

    slug = "implicit-conversion-minefield"
    title = "Activity 2: Implicit Conversion Minefield"
    description = ''

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def compile_all(self, compiler, tmpdir):
        """Compile and run every snippet once; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _compile_snippet(s["code"], compiler, tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual compiled output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    compiler = _find_compiler()
    if not compiler:
        print("error: no C++ compiler found (need g++ or clang++)", file=sys.stderr)
        sys.exit(1)

    print(f"\n  Compiling snippets with {compiler}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="implicit-conversion-minefield-") as tmpdir:
        actuals, failed_id, err = ENGINE.compile_all(compiler, tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} compile error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
