#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/control-gauntlet.json and re-run the generator.
"""Control Gauntlet

Short-circuit evaluation, De Morgan's law, break, and continue. Fix search.cpp, filter.cpp, and leap.cpp; short_circuit.cpp is an exploration demo.
"""
import os, shutil, subprocess, sys, tempfile, zipfile

# -- Crypto / obfuscation --
import hashlib as _hl, hmac as _hm

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000
_BLOB      = "c07f9744b9eb9c0e1e571f4c3cc53cd5136316712eccf5ed7d302d7e7606864cce813c80fe7b92e459fb2a6a7dfb"

def _decrypt(key_str):
    key  = _hl.pbkdf2_hmac("sha256", key_str.encode(), _SALT, _KDF_ITERS)
    blob = bytes.fromhex(_BLOB)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    ks, i, stream = b"", 0, b""
    while len(stream) < len(ct):
        stream += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return bytes(a ^ b for a, b in zip(ct, stream)).decode()

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

def _compile_run(src, name, repo_dir):
    binary = os.path.join(repo_dir, name)
    r = subprocess.run(
        ["g++", "-std=c++17", "-o", binary, os.path.join(repo_dir, src)],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return None, r.stderr
    try:
        run = subprocess.run([binary], capture_output=True, text=True, timeout=10)
    except subprocess.TimeoutExpired:
        return None, "timeout"
    return run.stdout.strip(), None

def _make_build(repo_dir):
    r = subprocess.run(["make"], capture_output=True, text=True, cwd=repo_dir)
    return r.returncode == 0, r.stderr

def _run_binary(repo_dir, name, timeout=10):
    exe = os.path.join(repo_dir, name)
    if not os.path.isfile(exe):
        return None, f"{name} binary not found -- did the build succeed?"
    try:
        r = subprocess.run([exe], capture_output=True, text=True, timeout=timeout, cwd=repo_dir)
        return r.stdout.strip(), None
    except subprocess.TimeoutExpired:
        return None, "timeout"
    except Exception as e:
        return None, str(e)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ZIP   = os.path.join(SCRIPT_DIR, "repo.zip")

def _extract_repo():
    if not os.path.isfile(REPO_ZIP):
        die("repo.zip not found.")
    work_dir = tempfile.mkdtemp(prefix="control-gauntlet-")
    with zipfile.ZipFile(REPO_ZIP, "r") as zf:
        zf.extractall(work_dir)
    entries = os.listdir(work_dir)
    if len(entries) != 1:
        shutil.rmtree(work_dir, ignore_errors=True)
        die("unexpected zip structure")
    return work_dir, os.path.join(work_dir, entries[0])

def _make_rcfile(repo_dir):
    banner_text = """
      ============================================================
       Control Gauntlet
      ============================================================

       Four programs.  One to explore, three to fix.
       
         Step 1 -- run the demo (nothing to fix):
           g++ -std=c++17 -o short_circuit short_circuit.cpp && ./short_circuit
           Watch which function calls get skipped.
       
         Step 2 -- fix the bug in search.cpp:
           The loop never stops at the first prime it finds.
           Add one statement so it exits as soon as first is set.
           Expected output:  First prime in [100..200]: 101
       
         Step 3 -- fix the bug in filter.cpp:
           The if-body that should skip non-coprime numbers is empty.
           Add the missing control-flow statement.
           Expected output:  Sum coprime to 10 in [1..100]: 2000
       
         Step 4 -- fix the bug in leap.cpp:
           The logical operators in is_leap() violate De Morgan's law.
           Fix the operators so the rule matches the comment above the function.
           Expected output:  Leap years in [1900..2000]: 25  (plus three spot checks)
       
         Step 5 -- compile all three fixed programs:
           g++ -std=c++17 -o search search.cpp
           g++ -std=c++17 -o filter filter.cpp
           g++ -std=c++17 -o leap   leap.cpp
       
         Then type 'exit'.  The launcher checks your work.
      ============================================================

    """
    rcfile = tempfile.NamedTemporaryFile(mode="w", suffix=".rc", delete=False)
    rcfile.write(
        f'PS1=\'\\u@control-gauntlet:\\W\\$ \'\n'
        f'cd "{repo_dir}"\n'
        "cat << 'BANNER'\n" + banner_text + "\nBANNER\n"
    )
    rcfile.close()
    return rcfile

def _drop_to_shell(repo_dir):
    rcfile = _make_rcfile(repo_dir)
    shell = os.environ.get("SHELL", "/bin/bash")
    try:
        subprocess.run([shell, "--rcfile", rcfile.name])
    finally:
        try:
            os.remove(rcfile.name)
        except OSError:
            pass

def run_shell_drop_once():
    work_dir, repo_dir = _extract_repo()
    _drop_to_shell(repo_dir)
    return repo_dir, work_dir

def run_shell_drop_with_retry(is_ready, not_ready_lines):
    work_dir, repo_dir = _extract_repo()
    while True:
        _drop_to_shell(repo_dir)
        if is_ready(repo_dir):
            return repo_dir, work_dir
        print()
        for line in not_ready_lines(repo_dir):
            print(line)
        print()
        try:
            again = input("  Try again? [y/n] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            shutil.rmtree(work_dir, ignore_errors=True)
            return None, None
        if again != "y":
            shutil.rmtree(work_dir, ignore_errors=True)
            return None, None

def run_shell_drop_validated(check):
    work_dir, repo_dir = _extract_repo()
    try:
        while True:
            _drop_to_shell(repo_dir)
            print()
            _banner("Control Gauntlet -- Checking Your Work")
            print()
            passphrase, feedback = check(repo_dir)
            if passphrase is not None:
                _show_passphrase(passphrase)
                return True
            for line in feedback:
                print(line)
            print()
            try:
                again = input("  Try again? [y/n] ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print()
                return False
            if again != "y":
                return False
            print()
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)

class ActivityEngine:
    """Core build/run/validate logic for Control Gauntlet; importable without a TTY."""

    slug = "control-gauntlet"
    title = "Control Gauntlet"
    description = "Short-circuit evaluation, De Morgan's law, break, and continue. Fix search.cpp, filter.cpp, and leap.cpp; short_circuit.cpp is an exploration demo."

    def _validate(self, repo_dir):
        out_s, err_s = _compile_run("search.cpp", "search", repo_dir)
        if out_s is None:
            return False, "compile-error", "search.cpp", err_s
        out_f, err_f = _compile_run("filter.cpp", "filter", repo_dir)
        if out_f is None:
            return False, "compile-error", "filter.cpp", err_f
        out_l, err_l = _compile_run("leap.cpp", "leap", repo_dir)
        if out_l is None:
            return False, "compile-error", "leap.cpp", err_l
        key_str = f"{out_s}|{out_f}|{out_l}"
        return True, key_str, None, None

    def _all_binaries_exist(self, repo_dir):
        return (os.path.isfile(os.path.join(repo_dir, "search")) and
                os.path.isfile(os.path.join(repo_dir, "filter")) and
                os.path.isfile(os.path.join(repo_dir, "leap")))

    def _check(self, repo_dir):
        if not self._all_binaries_exist(repo_dir):
            return None, [
                "  Please compile all three programs before exiting:",
                "    g++ -std=c++17 -o search search.cpp",
                "    g++ -std=c++17 -o filter filter.cpp",
                "    g++ -std=c++17 -o leap   leap.cpp",
            ]
        ok, key_str, which, detail = self._validate(repo_dir)
        if ok:
            passphrase = _decrypt(key_str)
            if passphrase is not None:
                return passphrase, []
            return None, [
                "  Both programs compiled and ran, but the output was not correct.",
                "  Check that each prints the expected values.",
            ]
        if detail == "timeout":
            return None, [f"  {which} did not finish in time."]
        lines = [f"  {which} did not compile.  Error:", ""]
        lines += [f"    {ln}" for ln in detail.strip().splitlines()]
        return None, lines


    def check(self, repo_dir):
        """Build+run the student's repo; return (passphrase_or_None, feedback_lines)."""
        return self._check(repo_dir)


ENGINE = ActivityEngine()


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    ok = run_shell_drop_validated(ENGINE.check)
    if not ok:
        sys.exit(0)


if __name__ == "__main__":
    main()
