#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/dunder-decoder.json and re-run the generator.
"""Activity: Dunder Decoder

Eight small class-based programs that map Python OOP syntax onto what a strong C++ programmer already knows: __init__ as the constructor, an explicit self where C++ has an implicit this, __str__/__repr__ where C++ overloads operator<<, __eq__ where C++ overloads operator==, inheritance with super().__init__ where C++ has a base-class constructor call, and the payoff of Python having NO virtual keyword -- every method is dynamically dispatched, always.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "ef34f98b5a51a3e837c79e9060d61e93d3ceda1ac35406c9c0285ff473b6a2f1"
_KEY_B = "f6327478e4239b380e7d9732f4395bb5a4c2e660fc41a37ecd9d4d5a2b39811f"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "e326f08afb519f51246bfa8f6f20a0367197d191f9b242cd26ed66e08923c3a406148a064795d93bda651dbf3803a92f8009fa053d581cf56f12"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "__init__ as constructor; self is an explicit parameter",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\np = Point(3, 4)\nprint(p.x, p.y)\n",
    "prompt": "C++'s constructor is a special member function named after the class (Point(int x, int y) { this->x = x; this->y = y; }), and 'this' is implicit -- you never write it as a parameter. Python's constructor is a method named __init__, and self (Python's 'this') IS an explicit first parameter you must write yourself, even though you never pass it explicitly when calling Point(3, 4). What single line does this program print?"
  },
  {
    "id": 2,
    "title": "__str__ controls what print() shows",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __str__(self):\n        return f\"Point({self.x}, {self.y})\"\n\np = Point(1, 2)\nprint(p)\n",
    "prompt": "In C++, giving std::cout << myPoint a custom, readable format requires overloading operator<<(std::ostream&, const Point&) as a free function. Python gives every object one method, __str__, that print() calls automatically to get a display string. What single line does this program print?"
  },
  {
    "id": 3,
    "title": "__str__ vs. __repr__: print() and repr() ask different questions",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __str__(self):\n        return \"str-version\"\n    def __repr__(self):\n        return \"repr-version\"\n\np = Point(1, 2)\nprint(p)\nprint(repr(p))\nprint([p])\n",
    "prompt": "Python gives objects TWO separate string-conversion dunders: __str__ (a readable, user-facing display, used by print() and str()) and __repr__ (an unambiguous, developer-facing display, used by repr() -- and notably, used when an object is shown INSIDE a container like a list, even by print()). This class defines both, with deliberately different return values, to show which is used where. What three lines does this program print?"
  },
  {
    "id": 4,
    "title": "__eq__: default identity vs. a defined value comparison",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\na = Point(1, 2)\nb = Point(1, 2)\nprint(a == b)\n\nclass Point2:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\n\nc = Point2(1, 2)\nd = Point2(1, 2)\nprint(c == d)\n",
    "prompt": "C++'s == on a class only compiles at all if you overload operator==; there is no automatic default. Python's == always works on any class -- but WITHOUT an __eq__ override, it silently falls back to identity comparison (same object?), not a field-by-field comparison. Point defines no __eq__; Point2 does, comparing x and y. What two lines does this program print?"
  },
  {
    "id": 5,
    "title": "inheritance and super().__init__",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed\n\nd = Dog(\"Rex\", \"Lab\")\nprint(d.name, d.breed)\n",
    "prompt": "C++ calls a base class's constructor via a member-initializer list: Dog(std::string name, std::string breed) : Animal(name) { this->breed = breed; }. Python calls it via super().__init__(...) as an ordinary statement inside the derived __init__'s body. What single line does this program print?"
  },
  {
    "id": 6,
    "title": "no virtual keyword: every method is dynamically dispatched",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Animal:\n    def speak(self):\n        return \"...\"\n\nclass Dog(Animal):\n    def speak(self):\n        return \"Woof\"\n\nclass Cat(Animal):\n    def speak(self):\n        return \"Meow\"\n\nanimals = [Animal(), Dog(), Cat()]\nfor a in animals:\n    print(a.speak())\n",
    "prompt": "In C++, a base-class method is only dynamically dispatched (i.e. calling a Dog through an Animal* actually runs Dog's override) if you mark it virtual -- forget the keyword, and you silently get static dispatch, always running Animal's version. Python's speak() is written with no equivalent keyword at all. What three lines does this program print?"
  },
  {
    "id": 7,
    "title": "class attribute vs. instance attribute: shared until shadowed",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\n\na = Counter()\nb = Counter()\nc = Counter()\nprint(Counter.count)\nprint(a.count)\na.count = 99\nprint(a.count)\nprint(Counter.count)\n",
    "prompt": "count = 0 written directly inside the class body (not inside __init__, and with no self.) is a CLASS attribute -- shared storage on the class itself, closest C++ analogy is a static member variable, not a per-instance field. Three Counter objects are created, each incrementing the shared count. Then a.count = 99 is assigned on ONE instance. What four lines does this program print?"
  },
  {
    "id": 8,
    "title": "duck typing: unrelated classes, same method call",
    "platform_note": "any platform, CPython 3.10+",
    "code": "class Dog:\n    def speak(self):\n        return \"Woof\"\n\nclass Robot:\n    def speak(self):\n        return \"BEEP\"\n\ndef make_it_speak(thing):\n    return thing.speak()\n\nfor x in [Dog(), Robot()]:\n    print(make_it_speak(x))\n",
    "prompt": "Dog and Robot share NO common base class and no explicit interface at all -- in C++, calling thing.speak() generically like this would need a shared base class with a virtual speak() (or a template). make_it_speak(thing) simply calls thing.speak() with no such requirement. What two lines does this program print?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "aX!4R8GWz?Q#H%WMgR;%Pa(X4MORM1hguhetdW?WBNMbx0R`nUWVubh)7;co{jGfW<@XJ%s=XBtT?zJ`{N&V5aEXj#pWcw3m7o{t+01K8I;^r>ObvLiWX=8rK7NdU<{z;*yHNo!$2hPO1ESph(w7;A{gq>S-?>&kG3D1wi?%yZT;%nCQp|Ao*7EMKH0ZEQ)RBBkx^%787Z-SIiBn0hI|#X|SGVN!Ylasyh(dqBVXZKjusUh}N24&h8Q(~TfxIk2kY6LJ=!2?tho;G>n=wFE{e9+*E}xk=u=D|v^6NMEobDd2l`Ru~cNv|_?~g%Mz)j$7{Fmi`Yf6G`L*Z4D-}shNk1jZIt^fBUSVk2)63VFZ#EjZERtO|Nn^(;Gw5{+e1ms)f1s56hZ%wHU)hmL;XUjd${mGN*M|4+JfYoq0Y2AkkY2&2J#Ln68A(_ih`!OZWr1JdA$uo%Af-O&qw=`#g1Q+)^_Q(9qQ)w<$S?hUK?HWPY`v9zG6#NbZ@23SG5bVk0m>RbMm*>eYA}GZXs)JG`yoJ@*AStDV%Io2PrA3i*eEV3(qat5P!tepO+*@0jhJI1Cm`l~O>TU(GG!@1|rzerkKdUT5$+>`Na=t)=R^MRey9czrk&eR5y6Q%s!p7f@RGA|>qnjv}2;GwAeS>6&ir#T;$AsveCyO6fUUYB_D^~0Phvl&%OK+ALIBI{9Ma;uaw-BkvfgO&`KVxcmBz&`6ryIj>MKJg;1@Yr>(JLP&?acJ$08Wvi1N+zUBEFR>1NkOTRBOEz@aZ0Lho8TxL<LPv#Rlx|_JFlv!M9gv@o1>p(>6y}Bf0k$(>S@1yWe)hoq2bhWwb?#h~(jn{&-@wO<X<ug6#K-n>p^M-bZ8Fvm`|}xEND8N?7WGMSSOg-zJ>EZCikPj&+4ZK$hdpQVTN|*$i*>R^B#<jYS;1ZIRw(9J&$N$F6<iU+EK55G9I*8)FXZXy9N4l2<DjM){A0>6Oo`KO^?$czJ!+q3QMTc8Dfu2}#4AQC|gWiuxJ|rc`U9J#_?ow&Z(J(#=jkZ^0?=Br+1aKZF7H)>MXcjvVHUv^gD}SUyjh",
  "%0l2Qe>;HSL3kBCWyyQY+<+Q+M2#fOab5OBA;s4ES^LQm!-HJsLIF_Pll?7dDu&Y)`dW%a{Z0u--m%B6>qC=%>eqst4tIzq_T#boV6XjV0V(G;i{E$*H2s!Cjqnev;~=VSE6h?OE(3XpmDgOaDwMl~DysP_%;!M50)v+$k10KL3aQtz1ucx9d!Kj-M%a%?%sJA;Kc4orU|=u*{Os{7UAEbu?%0wG#89;W?k;BxLn+I)p3amC83>^RvV5Ddys^;P7HX_{!5ciyq(0kGF~RoXcwpjcn8o7~`xqZ-@j=Ovj*~{Xa&{9NVDjtqEt>8ysEdCL(Eb79TH(XJ;LON`qSL3@ja?cWcM#2OiQrM-0<d>r_M;FVlO?cD585dL4P6#jF?#Vsps7`+#@0;lB9#<}l&3U|yIZkFbzJn0rL`~hVw|DJA8*jaStChP0F?2<kz?aB=xX*Vo%5qj0ff19tU~LcNlEwg_QP+2=#_+^8cQjyKJ>Kp!bDjGfr2F7eipi(EL*;>{rjGP_b{$^c7OxHwrc)-JgntEv-tg3F_oM5*-pIsS?zCJ@#Ix1Dh`UoPvS%er1Tsn2?`2sRh*OLzhbIjHN53-wD+wT-lQahk!|1W*d_FhNA!TSH8PXRZkg|gS0qNE7gO=InmR%)`Ws`ofJB!TJA`TmdzkRAwfOCC@ZJhOn{K!TPf0Rp+<#|XuaLmBY*!pQw^3k#m3N}|Pi}GrA?RS>j43}P5=*cqQpCb7Tc$$QO&KO~b`IvDvb|GV^=qAJJg|C4yK@ZYQ7OM1%zZ9bfpZbPJ44x3{Ll@yNXTV?IrD%1g1Sd~VA9+_s<O!MU-pbDb{_z{WVfBr<Z&=Cx%Y<_u^5Tr+tyUG_Yh`F%$)p+Jr7H>sh#8V8nN8)zp!5OYtKl603eWQLuLV?jW%ZMH&=Dt5%f{<iI!sUSw#;4gNBW_m_BBNrH4<S8%9y9I``<ne+1`gEi{-J{uhCHDGBplL6w4OOx^qZOxO",
  "ul%r`V6PXmaMH|bnB;;UzcARj2fYH70xa6J`#&8=21rCM211&3EfBrC?7hQ`Q{=Kl)5o6G*u?Q46cYx4X7mXb<y*!68U-dquU6*d55d7EEXDB}sfS+@Cmz-Vip1`9WdRWXd`VTE{%y%gVClLD+h;G;i?$IV{FX8|e%`=^$I#h*{%`Wftua<**Y((o-JWqKl5-II$Kutd&nNQ4LvxKHfGM$pyvJoyB&yX|ZA{Q`q&@sv%)LcHUih-vD&uqF-sbykt_IHC9U6AgCImt;L1n8Xag4Y{wi!vOYu!%Ld-M8DqoYq3J|7_=-EJVB88j2>AI}+rZpDhX97imd1mJn$@xj-Dr$t5~3WOL-l#loN!mVcfAsL6}ccljKfvX1m3a9Z>ti=FQYCd(|6kfPR1zQYvJ}B~Zs}$^}m7@22L+)wpf{tBm{@Oi`OcPNfoW<Y^@wkva`B}u0@J;hWC$;qfc&%|os%!DJJSnjQN~E4yd|k=}k>X$)uKbXmv)J|uQ8{urQx=Ps;hiR%I=ffZEY41Jn{S{qA6h*TkhntELbWK5*-6bWd&_eYVri*D#_=L(`y3!_;FmTC*$1T_dmFNW4end&-^#89=lp{w-aTQzFrdqK2Q!BrM*N1+xup0C{Ie}_5LX%-S0<*)_^3L3F-PpPFCqlPuk$?KskmUoUnG!CDO0Hkt4^@(`~sF`MBY5={hKvf)I<c@k~$D=O=_5yBZw}S1jCbnI9Mh*ym}&zRqlxZBF!hKyVuG!EM62S_fk2i@+u=UuZW4s^TRWjE)lLnKuQ1WEF)aPzZInVW~~yhe}OR-=!axieb0xD)6Nja9lgwmjSC~XP9Q>F8qJX{3$ish8vnsQlEmyWw3-pIpiuD9jSl{I_7itUWjM|=9SW0frGyqHbflplq;G!h<|OJwL%orZD`Jlw_R*t}?U44vSvcFsfK-LilojwZiZfbzDFjZRz&E~Ox*%b`BzQk8B0gpn|IEVC?uaR%Q3Jaxh4c`Ox;@157H~Ip8BEqlokg&22x;EkbzKwHEeoE;z(0wVBQ2Z|r=YZHSl+DZZcX%>A`t5lb&9#VgkwB9ULI;99uBov%Rqg7fo6l_g9ox$2YW-+VwPdcBrT!+A-9#G?0x$Q+S9R?8I)YlC*q$GNQ6izSs{4xsisapCg<&g5DYD6+$7O|v2!lc?liWcE+es9`IWmhHoJ6U_8QJ2wDf(5aw`KrkS32TOJjdCA0=guZ-}JMhL{ZnySPxJI<~8@z5",
  "5}(HaM`;bhLd0EnJt1y8J3J29ET+G$CP!q`S+#bJYI9WaV%BYeZu$Wf6~hkNi&ow@TiTy9g+O(TnN410RpL{2<4RG4{UypzFO9-#2OxwN4#BZlMj()SEff<Zy9JwzAQ4ujnG7W^(lN~hdj{3#q|^jOJlKgYzF)CeDx9Nm(0@1E+riw}-MAxS2tx(Z9Iw04$qnF}a*(7?PiqN-j<Q)Is#T#iB7IgP=2!oTL!);<CXWa<(Y+YF@Bfgk_D4qNY+;!HEF|MCi$Dshu?ue{!4x<%R_di)_q76En0UcplMG#v@~+JK4GV6ifvhNKoNCsgAev;@95O^FTKeZr@*%D}e!`vB7|L|t@B2(>!M$0=5*{dIc=qc#4YafQYmqgHF5Zc%EIiKusP}p)>vSRZdN31&mKqW3!TZgOlIW=w<bgWMx^ezGTy(&33$5~F?q~w^L)oT#5XpR3KzqW|+)Ty9L*Z2AB%IE$ftr6B9o&@0@5pD3lwq`Sg2>8fR4lrA&!?yknm<{44x{Az9d$Q)ewud#{jU!vZYfep`+{of0|4<Jk3~!Y#+Xcj#3*>MLtw#HlG_LzBVo~<)L)m#P-NB#z<|hSX@yPbB)KDfKHDT$3s?*R0mbN-GeeqbpkKMdNEZ#hJC~TQ2hK<Wet5oAM$6~xwszm?m;gyg9w98y4qM+s08wata!Ea3di?r?2ao{-`u~4IU1+s$2`=1>DPw@8VC?oGDtKxpUYhl&E4Iddxx-fzy8aR6DM(tLe#0qtD&1tbR$d3({VJ4ohlOg=sDwGTk*_5jyP%R5ztC*}r5ZUk!o6jQKuT;uT4o#wO7_<hHSTls0L{3(v9=EOsOH3uGc+j%$e+~{L_ez=1Qxql++jJcQ}OTuCsSP2>)Ymo%t};z7Y(3_>b-3T8#9c|8wLO*l~#`I><0czQrmP|Nmb%4*+_)E8Q7#9o6PU#f@7iB^0!ka)$W78i{q)?WG|>)m$n0G6N6QRp^s-;%`4G(*QA=@))h4ZXzg=}O)d0EfhX#;zt1!Y|7w7z%Vb(GOw~;tr=TjPpoGUevm&FtQ`=y^l3Ksj8$9q&^sXmD*Hy-;kePHhX#163ejwdBp~8t+{g4a3SbHtQ(P6O-1kas!G^oq|y~EY>H?zNo;<J@|E!1;96$zlTtRNKGeB3cMpvpm_B+wk;jjUpu7xhC!u6QTp%_EwB6k{tMybT93M6UOhzn+kilwb<Np6xr=XlG4S;li*wt(j@Vm6EM(es^d5x~AU",
  "s&7*uJPG-b!OS0rG$Oj`r*gwRV~U%4ABkC9@#e=5Z~v7ADQeU$FP73e=%GpcB0>g=+K~rzl=Rh0sBIq?Ki;9EjL$cAN=6)lc|DciWoRy&Ysd+8WbPGKumH;UuBz`s0!=stfleNs&DHH#zzQ9mY073lr8TBxXCpxDCVk8eKrN<a661KE((P$q*s3=0PdUNC5rVB17HDknU?YYq3vt^3FP-<=CNzSTHB~T{&MyTcGNjVq!h?6vcQ#t|bV&e)y0IogN9w|fQpwFWAF&`?5uW)YP#!Er7UYSFt#N<>cq@Y}7JqAfLp$tqPP6rraiRUNd##Nf|89+aR&kOuCJDKy(E~?u=qPx#d<Vj`O`??CzsT`~M$K6rb#O8lb21hOiWA8K*#_o%hyMP7xER-{>pQSF6<s#1dtD+Q`pC0%IU!&DZ|FH1uD5El-s2;Vk%^{6^|eDA+mg5(zsW&q0;e+WL(&9h`vSzMLG9N5W*6mSYM|OW>Cx=3QC24fAXWHP29JgAk>8pkh#h(V7{ocBNb%*D`^GA3;JoOobNrewCq`oT*ebRjXsL0-&N8b_471hpP7Se@Cn==V-CqN6)K#OZ2h9}Ht3Zrf_%NCxNXh~%CR)*)i*<M>>uA6Gp|Z)yqx<fyY!C2ilA)6Cl;Ys{h}>L4#^Z>Pq2eqJ_k*3^h!p2q8YdewnUhlm(>0tci1u(7Eb9%R&3CqwkP(hhJy{#m%jKX--xv0|!oB9(-(qzwaJLv_eyazTZFOailZ^?&sx>I$$-Dwq@W#J`KK^JUM}MYs$uR`$@G%N!ffOJ=imcL0`H%km(yExra_nNAp70zWD!X3WQt?CInAW^#gMQbukqW~R%3u)T&xhSQvuWAJIY+_)?rgL|`<~P?vDr>C^IePYzD9c",
  "FBo_==RmbHo7TSU+Uf|EOGRq9mL_!~8ISE>aaJ_&FCZwgdVz_28q%|rRSU|nkDke3vk)`!CNK(9riVC6LbFuy4i_tA-G>PrO(~8&SInF+Fo|U0*vkR5h_41Q&T&Qh-Y=>~o^g?N@Bnw++)X@;yQogiDi=HC28oly`f};)=OTFBJ^%b}y^$=8$7lSz<An%6Sf+f4OR*fbirR~RjmH3)1#mVyBWu2PKo9*}+8)@Rtb~hZl~G$9awP`C0a^rp+sd>vA(r-#UVU5Yt@JH|#)HD7>d-EAin&Hch|hh$pGe;3ayF9SFNJKN?U~|Tu33VaRL6O2xMDO>MJ1W#9=co07krXM5E}}A$4ePiY!ZznWFR?4r*I6w?h38ABLnux`UfShnu9{Ze7eUDj`ysZC(A5rrA&-dDq%Y&%er^Pj7IVqf|IoMRthhElp^=uH3$AcBWBaKD>FvEH22sPOYYDN#Y~Pb&_B>3#>0(sQpbjX-7g^px_w%PN76nww*?6aS6ZXkP`S?knn>8s4$$pfnxp(@u*}J&j2V!(CX<@Rem-%-RFCN$My7R-`bnf~Xtrgpi3lJgbZ`3}&@;qv9o%9M?cegt9fd=%SAVrQ!dL38Ric@OQq#FuxvnBH+<3^$rT?CL8&`-=;btKp0G#`P-<F7=zZ98`H4xMvZgAuJsSBpOty7}H|4B0Z+`7dBH*{-gy!_$E;%x%2&`2RK#<5Y1GvA6y(0t|gAeh-KgFatDeP2)K7A--r+k4v&Fszxe>AkhOZRUhUxK_$5N-%6W8u5^1@4O!d)8I^&nQ$liKr&@@*$80#FzWYZPOqw=s+b0I3#5F**e#>B&GzY^g?iD7&168I6Ug^u)XL@(xOWyUq&2c}?q0~>h?p+GlZ@bgg58cPQf^8pHqnsusrAIs9!Dsc81s^-feQbK$aH8tThd(uC`xK4ge^(np#lgM!sZnLin;o7ez;nEB|DJxRkqu(UQ_JgPp%39?9$IAU0{UeuX?>rySS$^b4vN@r7T)f4wWuMkll)cl{$`Qd|_gS$1-S?%Ey)0?k`LbSBQrd!mVNqqQs+z8SDjM0Ss!2pYMiV_U@BgN3i~va05pqFq4)3)!U=|U+m0jhW2xg;c4A5Sppwa!Bo8_nKxy%X5<D7A129YPw`m+2gjta<ZMIf+wER=`NUhQs^eNYIE?U}uHxhjgKFN>9#?Ha?%aUm`0cE5-hL}V2pn?cmH_",
  "Sd(XJ8{X<=J_&!KC3GOofyAm|95kD$OiB@O-V%mY3Yizv8z*Mt!P>j7ma}7`_0q1g2dSM0qf|gIt~RbmF&r;W*Ze2%eh&PR|MonoC1O8t?F1Yx=f^m?6o#^xl=n5rqJgtR(~VmS_llXU9h>?c{k5G!B9x(0f+O+S+{V0+jNeBs@}&4DNBW%jHn=2*Vl~L`O}@Kij3kAhSVfe8nhR1H$Nt5_OKI-OW#5W(=AFpmt(>gQ79iRZdebpd83N}!g_J+Udy!KR70)k}fRr#j><_tloGW}>O+Mb+SYVOoo<Fvphb~(HcONck_ZU_?W`0-}xF6T{Hc`?b$dMdYF_;65%t8Qd4H>*`KaxE58X{m%-sC$QfJh|PtEda*qN`^j><?=kUz|hOMt}w<6wL2?!b)ov?+DF<BA-XZ?E9T=D5^cYd6G%%a;sQsw)oM0^zT1WHL8+HUGz)udt&ij+ts}SaHuU>b>LhVuGR<Mp{n)KAJ!^QRI|wRs)YXDqJFscQ+7b|b7}70HAgU#kmmpyv`(_xtL3R!ddxlo|HX{BF|d^lNvc2kx660m0Z2bt>bv*ptp&y2enNUnQlm6i54gj`*mN1C4RTC2)l5&jwA<j@eOUn9s)9^P5BUVr<UeF6D<m9pU_;03boaz+l8Kb}1`trcqlSYOt`Nj9r0`BLqi=EtjhpHWVYLFBpB4CApzzb|nd3!MXK)$lzY7$FDtdRldVEeJR{INE%vMBf6?X(DlhL_fix>;=b1FNRYs}*C?e8F;068)lpoewel<t^9IfR_idFGI@nk_Dg!GOr)h$GjG(e2tcU^SL9TxY<kavFVTlBJ`1CKAF9(T9kANi8g#N&jAwF{<=*&WFaK+)^5=)AG$c>;3WR$ldP*#MT%3Tkye{ic{0+vkE7eig(mc8~U@G-wc}V=o>eNqNUYI*7<McD_A(Fv^`$r?NKeD`m8rTF{*V{y}ievG?p_?Zyvg~tsD%|2Y4xviVE950}<-t9+I;_vaRoQ3Ns<pacQSJw0K`IE#obE+4#u5vd0$GY#L8Mx4p`sjN=~e2p;7Tt!A*>LcF-IihPBewU=QzAD+fC?w8lQ%F{7bROv$NqbXT`h(_juI<m;5Oz5gpfFe?aZ%I7nDy0k9dJQ7?=c^uFweq1Jn1J^7_xb$66K~50t2!>6j|=ZU+QnFx&SYI>uVqSkG0k_xK;7~02)zY-Gt(h++Qj|{wtH7-Mvummk^>9Lpm;X2<EhnMs4iR",
  "zhmC&w8@6R5qgmXhe_jeXQqguqqNGIX=+`UEwPxnHrAQL)LZYlRW_ErZ3dX_)v8e-X$S&jJxltfvr2KHX0*cdVTNHipiI{z;238z@1W`Riyz?^ri?$vUG^`EO!>)+i1R(wm%1}#wO@V^HAsEThfy2&a)_Xyl}OX;rOQ*guCfM+rdcJPqc^}clg63zw%bn0Uh6)f9w+}q{a)nx&s1JYWsp{T7$Xpi_#gY8gT%DQLz?~<Px8m5Wbkq~r7nRgV5XA;pn1LocnL)${HIKU{`owP<=f4M&xLDG&=NJz;eTLKw0bod5ZTzO_6f93WO5^-N2U4gN_$x&c+qbDmG?jA4pcL_C(h$30A-Gaf;ymKoHkyGAp}|`w4Z9>U?m$hfPokQHt5SuPz7jD&SG_@Lgs=O9M!zYvn83Bc6M!GJhpTyUz@jXfB5Xjx1TKWd1gR@2~7#4(wP`wKAQW)F!%g#G8*;utJ#oOg@?XRQKLxL-2#+->j}<Zr5irzE<$>N%@A%Ai^P>nZa^zzNL<@5X`q~8cc&=1X=eJA)q?J=*GWdfhR_02Kdt2wQ^}WFSaVl&j%W&QxEj=KS9VWWi4)#4!0=m~GSNa5ij7f8kR_4Y4H|Zm6of4;j7yOAKd~JfyVN}@lvZWupl7z_k46xW2KgGd>JL39#eiapSd54n%fOONvi&;S`57}tXXlB9y1a#aXHv+pjN$IZC6mqh*nujP<4p3;Bk1b|149c3=z{BtE8_@=PxbE9nL<dCSwQl1zd(_NZzYMps&|5vjl|lXEwmWM_?&*&y1%MLF`K_d#V5G9&<n4QWV>Fd)m3I6<KY)Q&j{m&)@(#$Y5|AI_-3!vRSV;;3p|n0CaU?>an*tn4}|L)56+DpYw!+~oA&!dTA3A*Yg;Oqb7!|XdJO-~U`i95dE#{zmZZIkhqS`Q`E=k=^R>5Z#QOUwk8C7P_LAbAm0|gNI=50c${{Y%?UzTG@C{k2MYA|;+PK`c5>-abvSVNt>eF@H9zClQ8%5=<ED|~!t2Lh0M)m`qcrc-cbZu*b)ezhn^Yi%U1NytIsSh*<kF{f%eO6wj4-v+%4!^Ca(69xT)%J#6`5x&$DyKXzUS<_O+r{d-FnoblTGt`N%)>=wwdZ9trT-@-kz46HHh4!rNXBz{X)1Wem<O_L7LwCl^n|%CreTK#5r?))"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "dunder-decoder:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret


def _run_snippet(code, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.py")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([sys.executable, src], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return None, r.stderr
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: Dunder Decoder; importable without a TTY."""

    slug = "dunder-decoder"
    title = "Activity: Dunder Decoder"
    description = 'Eight small class-based programs that map Python OOP syntax onto what a strong C++ programmer already knows: __init__ as the constructor, an explicit self where C++ has an implicit this, __str__/__repr__ where C++ overloads operator<<, __eq__ where C++ overloads operator==, inheritance with super().__init__ where C++ has a base-class constructor call, and the payoff of Python having NO virtual keyword -- every method is dynamically dispatched, always.'

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def run_all(self, tmpdir):
        """Run every snippet once with sys.executable; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _run_snippet(s["code"], tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual run-time output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    print(f"\n  Running snippets with {sys.executable}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="dunder-decoder-") as tmpdir:
        actuals, failed_id, err = ENGINE.run_all(tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} run-time error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
