#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/link-order-lab.json and re-run the generator.
"""Link Order Lab

Diagnosis questions on linking mechanics: command-line argument order, the three-phase build model (compile / link / run), what -L and -l actually mean, and what the linker does by default when both a static and a dynamic version of a library are present.
"""
import json, sys


# -- Crypto / obfuscation --
_KEY_A = "b3bd9568d20ea6830f6ea6779f24cdfbd383efe24e7c48be38675acaf435939e"
_KEY_B = "50f9abc1d4dcf486b19e46d1e85b3c01986b87e17b8d84decff9d9d4b7fa8d94"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None
_BLOB = "50d5c36b1d3e511257e4945e77eebfda868783aa1c5ac20ff0d5392918e3aa6a59d4d6ea4418da7c2202af0c9692033ec95dee38a56460fc27881254cf"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "libmathx.a exists in the current directory (built with 'ar rcs'), and app.o was already compiled from app.cpp, which calls a function defined in that library. Three link commands are tried, each producing app as the output file:\n  A.  g++ app.o -L. -lmathx -o app\n  B.  g++ -L. -lmathx app.o -o app\n  C.  g++ app.o -lmathx -L. -o app\nWith GNU ld (the default Linux linker), exactly ONE of these three fails with 'undefined reference' errors. Which one -- A, B, or C? Answer format: a single letter.",
    "hint": "GNU ld scans the command line left to right and only keeps looking inside a static library (.a) for symbols that are STILL undefined at the moment it reaches that -l flag. It does not go back and re-scan a library it already passed."
  },
  {
    "prompt": "A C++ build has three distinct phases: COMPILE (source -> object file, done by the compiler proper), LINK (object files + libraries -> one executable, done by the linker), and RUN (the executable actually executes, with the OS loader involved for dynamic libraries). Which phase produces this error: 'undefined reference to `mx_add(int, int)`'? Answer format: one word -- compile, link, or run.",
    "hint": "The message names a specific missing SYMBOL (a function), not a missing FILE and not a missing source-level declaration. Symbol resolution across multiple object files and libraries is one specific phase's job."
  },
  {
    "prompt": "Same three-phase model as the previous question (compile / link / run). Which phase produces this error: 'g++: error: cannot find -lmathx'? Answer format: one word -- compile, link, or run.",
    "hint": "This error is g++ (acting as the driver that invokes the linker) reporting that it could not even LOCATE a file matching the -lNAME pattern in any directory it searched -- it never gets as far as resolving individual symbols."
  },
  {
    "prompt": "Same three-phase model. Which phase produces this error, seen when running a binary that WAS successfully compiled and linked: 'error while loading shared libraries: libmathx.so: cannot open shared object file: No such file or directory'? Answer format: one word -- compile, link, or run.",
    "hint": "The executable already exists (it printed no compiler or linker errors) and you just tried to execute it. Something happened at the moment the OS tried to start the process."
  },
  {
    "prompt": "In the link command 'g++ app.o -L. -lmathx -o app', what does the -L. flag do? Answer format: a short phrase.",
    "hint": "-L is spelled with a capital L, distinct from lowercase -l. One of them names a DIRECTORY, the other names a LIBRARY.",
    "choices": true
  },
  {
    "prompt": "Still 'g++ app.o -L. -lmathx -o app'. What exact filename(s) does the -lmathx flag tell the linker to search for? Answer format: two filenames separated by ' or ' (library naming convention: lib + name + extension).",
    "hint": "The -l flag's argument is the library's BARE NAME with the 'lib' prefix and the file extension both stripped off. The linker adds them back on to build the real filename(s) it searches for.",
    "choices": true
  },
  {
    "prompt": "The current directory contains BOTH libmathx.a (static) and libmathx.so (dynamic) at once, and the link command is 'g++ app.o -L. -lmathx -o app' with no other flags. Which one does the linker choose by default? Answer format: one word -- static or dynamic.",
    "hint": "GNU ld's default preference exists so that, all else equal, the resulting binary is smaller and shares library code in memory across every process that uses it -- that is the usual reason to prefer a .so."
  },
  {
    "prompt": "libmathx.a and libmathx.so are both present in the current directory, the default linker preference is dynamic (as established in the previous question), but you specifically need a fully static binary this time -- no runtime dependency on libmathx.so at all. What single flag do you add to the g++ link command to force static linking of -lmathx? Answer format: the flag exactly as typed on the command line.",
    "hint": "This flag changes the linker's PREFERENCE for every -l flag that follows it on the command line -- it does not rename any file.",
    "choices": true
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "7n!+god(&^kTnMf@qxnMF%}Ji!B7zYavqzsk%r54E23~9#QhW^0XmsJHQNer<n7J)E7@>VIbAw}>@n=uShNCd4?*cqBphKQEgMh-stuO7Uy(6BNOszNYn{dC(NcvegubWE_n^qOw3y1<$3DKh#}cWP+R2=lzlGb%w%!Ct33yXP&jR9I%V0v(=un?3%gD?<_dL4<hM)ZHzbaZ|czZz^43?^Zu9)gF!-Z1a#XE@++2Ka(ogAB55|1}{VKAW<m=ywTjl`EA8i^raX4YF3e+)Mc$ddaLU}l&wdTZDPFX@q=I5ZaOA=~VN+{2D?DcYm!&<N6bcSL^`;FjrFb0a<r2-`;wdlGvKt}M5@^eX(Fqat^0`M8k5SYi8#79#7KUsv6&fDY-FQplVHby^vOH8=xhRVt?XMicudb@#hw!@qzA1#Y{nBWKqLT|=CweXPib@fSN)f8rE2r4~|9nSzcKN==X4v4y%qqN@eY%xYj=`QGASMzU;Qi>-P%TmSvZs6ErEt#rXI{rPbz%ov)t%mXs=_X_FE5kb%4xn<vJPSn(#9-!sDxl7%ZRf#Ug*8}%@hg8CwGHPAwmF_fEO>(=aWg%IE`C1;5tKFP2RWc?^c?K3Wto#@zbqwOBtHqHXJ%mEa`Qwa=Mltb#SY%v-r9Z`ii+T$VnQA3=HoIuf0R+N3sy@F{c$(vC7-K$q2x~e!!A`3m5v5c^6F0ERj{5kl1hNMKM!B1>;xB1)E8zJwkrI6D*c>>)%$e8TBJ-T~A|@hA`!UzN<-j*Y+V66j_Eg2LXD{%+x!h^JEm{)^4|BBPJk>XxCk~55^GcYt5Sm_{#L^W=tnC$_>XD=u(I)Sb?2!ApS2v_OnDPjl!`Esf;VcE-`QUnu`W6oQ&Ug8R(fuunQsg5Y-FOhUIXC~|V-p(<$4A!WJ-(J+9{pv-VWKvOD|Gr8+y3w+sH8<>PTz_j6}mr9weQM4B0piD9_74QJA&5RPG>bqpd@Di{?qa=av&{)@Yj+T#vFvatgdabqLtKvr90j|k}uG#9HG!hmAWw3fdT!~Xzc",
  "&EgpP!*WpW=qbZQVrX6U&YX@b;0=~^M}o4^gl38wjN+(t_~1<xq^~o)_GwS8h{1(Dy(wM4W(eBsHyz(3+Rs;*l(>L}iRy@l@~V7$%I6viFs-~<Vr6-?P$n34a!v&>v@29UuCBBAn%&8RaJeQ4Egn)TLpPLE*A3f5m0LR~$`Cn01}S-!T|ofR3T<(Dp3@Z#P*{%8ms-@JXi&lsx8mY9HKXB#kU}Y!7p~i^$a*4oI9OJ8M7#BSX<wkbD^B=j(Y5(M@gMI}C{@9MpD6{8dR<s@#4nQff`M}jB>NG)t}SL{+MVU{^i^R2-*oOa?^xxT^?VH4pqsy+DB0kv4{29nG_<Z2W<BSCQc9hTApHIMGDlYHMN)Gatyb*D8b+`2u*VIk5p`4s>pUayoI9W24UTm>WePIE>}%0ED-EZ%Yd2N?no`o&3V3@k$&wIcq^@B_;cvIlYzMi=H!v0AvRmQTEnp>T+hV{QiG}gOFYmJ%&GgsZDmbzc>V;M0sBK<0HU&(<34HFKD3m$v=d7?9O-SL_kRTa9z~ScaJO}tY+Ag)>+%juPe8dBX#|(uUEuQfE^6e4;VvkR?DFxt2<Jgw&>|{@Hs!&xwW2Xz0ZhLVu9b1wHetu<Y$!g#m3^81vo@{>=rLDuwgkBE!4Hz2QWQEmo{s`&X<>v*m>hq^&KPpb*YF+eV^&&WlVzx3??g3WA#ldXqvI}i!Ok6*QTw@QNC>EIXkw6%9f9fi!9pU7MqkoTv?CZ0-82^-vjuX6*ug4>ZPTYr%vBN9^SH9;xYc8k&Cv$-_ope6}<#0V58%NLg7eqw_R4#tp",
  "WhQ<lp^-fY-Q1MyD=)F3GQ}C4mSkC^U^ahSfFC8wENN;cPZ3XK;52a8F%3cRLS==vHfuiHUap&nn$2@f(%Qhn-?O)#o0N9rJ9u<S&#MlkZ6MM5H?(9cPIEG7+e%LN$pGpdt~c~lT6Yh{(i=PE!#e-yjTrXy9>r*wn7+52zI^q{PPqm%^J;R$w=Q+|KUooo335(uN$XA4e)A30osVw5Ugu<CBz?$sH*AR}iEC*ltL2`rsh9?Wt1;)k`2=LpNCYWHxiore%q`J}bRjIZHt+=K@hfGhZf*cFZJ-46v2ZKRxZg^LhDCdI^3ix;`}tbEPOrFYc)l=O>TGO>SH!3!ka{3jBUbd-!v8BnR6m~Y;pxU@dE$KMobJ7GN_l~;j)gl0?4(}iL}!U`@p-U<{L)hN(`>l!Tpd{Pv8sokRK8jm1tbAz9^rqOi(40<(}qJ4o}IQvD*zewI$l4168Ereg5$jpeSl5(1Z*%g-+{Am1vPk_3uxAd!Z7>&#}QlMo)T3~>HySGK;*irsO%lLC55PV^bS@$nb_eqZ-K2vV<buO2F$!-@^Q-a844t0T>a56{O5Xq8vS&Xlfm!j_)fRxY<!27w(b}}+x8#I-?!`^DXH@8$xKN-!Xs<H?dN~_>A#VGA$64oQ?Fg5Foj|~IpYFi0(6i6_{OPC0NIiTC?ES0A@=",
  "$z!!|@HMwAdTbMnE20%g5X(Enx#No|adWH`?~v0a31{`9Q7XFhk!KaGzCBwdSvt3ms@~MrGNJ|iXMJYv+}W01B@^2kmD@2H@J>yo`7s3eg?&?WBBkMH;2x&AwhFs;EqPAsV=|8Vs404?%3GiJKuUs>DHHwN3$-DK@YiOEDot0^npBDbjIw&OwXg(#F3U*>4dP-LvWgZDf*Mh`Iu_}8x8v<o$q8UcV5c?OfiR2JPBrgV$d+dnx-BG^OgkHBTO9dj&S9vvi3+lRz3^lIvqQ_fRg3*PKuv)~)j^q$^N@P*8l~ar4S=H^I?`djv|G#;qslK(nDoD^vFxV%!?$lv5L6}n)qR+1JL{6wH3f1qv-*+AlQKWC&jTzlo8qo{7M|;~%H1?D_GQpB;Dx?k2v)z(Kw5J;cAQZP2GfIiC9VH|DdljkM=5wr7F>BMwu0(g->tIr=V0}!-$>IA(PDrSs=0IGL0=-^T`Spbe8t3T632vc6D7#`@G8tmvZ09xLRi?_=9zW&G2~=2C1JeClO@5DN&~0s`oV3!N-U?;yEDYLjpMajtzof#C6GQg%~mfPXlEh<BmT}jO_@L2bmS(cw6-d)+Q%#K<W9||RnY#<kEdx$St_IzRf7aY((NF(suxLd1`kCG?Zzp4!WBt7kkGi;D_j|QblJZ+`I9v{=R`=oy(R@nhl;S1jhk!qqCRZSiUmTONyI`~h#d3ipmgdy*o$-WDt*mog|+w?qJCWtg_l;~Pff3oYg8@ldvpa=^~BI)5~ho~qc9Q^itFOvHsd#jehOCw>eS&I_eW27k=sKp)Da0>*Z)u!+RtAb#+r3O<v3<-<Mz*Zr&_1>lH#c_yylkfeGm#Ki9Q^6iT9yv=kC$BuG81+^I>-",
  "tIV(ByXM-YCJ}IdrqV(Efk=|$Wq~@Sy7K%wo`SinmcedH4ppnk3H;2=@iXd_hux_UO(N`T6#)<QLa0k>Ett-b4?4L)3nz|=cxH%3cvK+bQCYHF@i14qx<dV!%Y}kB0Jjyj0DQe%cNaraU;&`tj)~*NnW+Gzl4ldQS=bK87Ro+6SG2kt^o1l2Fez@}fv~H)*w8T9e8;IDXz$-|+c=Z@b@Nno-?(#RPCwTK=o^i{xflbfI7>|kc%}wrHu<y7u=A63;JYN?#N28HPC0|K0!fF_!g+d3w%u~O*m_axl%^R8n3JyPP{=QG42f0=+aai+y7Nne&<h?BTSgG-9T_Z(j{tX5*~L%Mx){;W;%?kRMZcZ`RIhV7Ovw7kM$SR~u`v)TnSt=?oBY7on_CV4$!3M%wT6c6vj(m+Q^s4U`|@;(w7^;Lfv;}FGE1z@a*NI)B(VY>CwHh~2e9EE5@a$D(tg23h89eUtFV^8CH=;aHqi;0$SvBAc08SK2CV>}IXsz8jYT_!(A|Ax1Cx`(0OZ2}q8Wb5gMr`fE7&7>bHaT(89VU<Fx5;uw<qEdD5hW9h;Y5J(+nRvLJ{=L{-O4RuJp8C;=5j+6%=n2M@^t)Fk{i@+ts`+F>33Z7=4t=gN~9Hr}x!O4<S+{$r4l-Ai;Zt!MQQM7{;34|4C0yP0;@gg|Z_2EkrhjM?ud8(z`dcvHtZ4%}4K1",
  "R4gJ>>ZL<sE~ddD?D{)_YDm^>>mfV(mvZjCZjbs=-y&b$e0ml`K#C6}#b&^$-F`#w&7DeCN=;<z-EBt-W0Q$l;PK%O!&~Ep8#9|aw93pE2wd2S+T#IF(+Yw^eOmojMq;{k1I^6#{!{(q55C*yqvoiR+=zerp4|?b$w6&A2yu0wUMrpSjKs>&krxxj!~Y1hRL<}g_>Soh33ctm^hY>LMQie;qbt#u(Z7;24}7o$44vxqXqH1Kyr@F+cW;!ECZ8P7WjfWZ_YV}Ii?{8rB^1<(cM&w#<OdrPmxE0pj<=ugy~-nZ@pg1wS<_m1mT9!BjkT@Ixl<p1xQ<;_f=h$4xJlBe=a-E5O{U+A#RKev03YJViIl?i9ycV%-v<aC>w|*~23zj2C2EWqUSz$xK``5u1Ks;3pEKEskQy79hlyHk9idT4vB8x%P~0^j|C<O(i?N7^ZGk=_g|S}hZm>>G2K>`HgAr52Yb2V1r`@fX*Zb_+>h<MrCL}n~{I}Yse3g2BI0hTOK3){5$U3-&7a$pgTdj3e93<Ei;(Z^TElFR9b^+L5BYYnk%=T5(Rhd6tO<A8MgpIlC#*!K4JKS$8&Y!r0y&BZm0sQK+)2%}5V`OxMA$Om#gSp6Di{l^K{?${a&xux3ovX8@nnwiX)ZCp!Os}^HGpw5Vsu)Gn+X7A;jE|vsbf<qw^2kfyZ98*RzG3a_aMqu=-ezAK",
  "f0%!w6?{=&K`x)j9yO`>WDth>ur*%Oz&>o;SV3~nVzT!_uK~uGek0z1p*N~O@<%`MZJwf#$JR0P4`Q@SOep#A=}=I>h>w7``p}_p&%v2l%ZLGN!@@+$2}C)Uq%5brlWsCKrWl?KfqQjx*4}|@zky?;5aqhm-&z)Uzlf^suwQ@!I;Rs{;b}|faeH-1?U)^0@;wsljubPy;Q{7WK&53hsG8kn?tPNR58&XZwA5^wD*^yLTH}&Rsbd#Ke{KHbv5xPuLh41!@$WcI6C5uQUJ|i&Llm#G!iOMNo$02$<}Q#?+NYqgNk#k!6~R=Fu_3dIkDHbT2%EckR%@4@cOJ{hj6*HEN^HJmA;<B$+}{mNdAi`C>f@-atHlfpVaje!@gvD+G=B-xRG`9oyI-WvwVO2C@erVNT9WI!Hq#X+>2C2k%Lc3+#i6Z6tCB(<&!7v`^3hQSKms)ftC07kI0ZD}pa9m|S??^SiM|)8nKL{s27!m{`EjC|%->)He{?E80Wjm^kdskwZ-uPeyLzAOcn(GXj;1g_%;wdt1e$AHcde_+Lu7JDVO%<d^SkGFOCekI{Y{G`@g$&>NXX1N;|i&bM~`WJu!7ZrFOV^13AZ3)wrWp#mq)0lRvN^<;|k(VkJ!#R`Km?;b6c1ag;zHaAJ+tr{Z^wu5MCa)Sh59{DO1Qw(?_<HkKWb",
  "-UCuu7ZsH!g8a4RF&5C3=aspGqHb66YJ@-Sdjl`{DJY?#Ar@@osjtk@77RplFbyc=xc&sQkutYhC;ZpmtR9OsVyN3!5PE&4{Tdxz=qqA3%FXMNG%iUM`>hzXkQzJ)45A6IJ=&IZ2;zDg)WfUWEOfFY+<BZ0i1&~(>^-$}Obf4w{p|e;3NUFcDL+{qSixb1ex|;<UTFV_Xntu&X}BCY4GN!HbGiOD%)P-Clr2clS}9-@iKKup8oV3LE?iea4u*B@EN)OzM`DUKbQb#EG?sy)Ef_Na3NrS(eyHx+)!LV3J+q@O+!IjTJ=<VWKX**K{P#azOUG(@<;bb5UbayHVAxem5ChulYXv!e1K?q)<Nf^I%<IC|x-Ne*CMS6x#0OUH>#8wZ3+?gukBhJQ)ea#mtc2!PGv4p^aGY1yNg?&d8TkzbO1}F47cDAAp+=-{(X~1rHw;4skGCc;L`WY=(+0jG8hz0DMu7E$=y~a)+G4*EM&15z&W*3Xu;8w!Eb(pm-jMm&dPkOiG#B>%dUQ=d=5I6380#Jv_kefS`*8dy!6M4&K%HqcDPBzoY)DFcw)GjuF!!#CI%4#&v7i)<!dPz`96u$$aDv?kMi7uyU%tEo8MbV_1WIghj!+Ll{cDke^dDw)aBeq{>z+CNI<kh??;tr(E~yVAeGJpc^QD6m3k9K(Qp;eJUzWqU_znAK=8agxn#e2X<Gz<G5}_{M1eG+*7*;e&Q=w(gWMLXKc=nYf+CFGE^-ia#fmm}y+3$Z(O)Wruo4xs3s~!cu=;EzgpU{mvhdRKx<!&%A4@JX@<(kbZi5OT9-P1Q7pYt+0+W5!Qr7PdVJzXGToMa-Y3OdQJ6WR&8JK7yFf_C#iLr}dG3{voh`M5stEDf227+C4zKvgU!K<5zl=io-BILF%f19SvL{IB=T+ObsF<e1}6{jK$DmhK(XCLppGu3;ky-&>~Urt>mA@L7JU<81"
]
""")

# -- Helpers --
import difflib as _difflib
import random as _random
import textwrap as _tw

_LINE_WIDTH = 70


def _norm_answer(s):
    # Fold away the differences that should not matter when matching a typed
    # answer against an option: surrounding whitespace, internal run-length,
    # letter case, and a trailing period.
    return " ".join(s.strip().lower().split()).strip(" .")


def _best_match(raw, options, cutoff=0.82):
    # Resolve a typed answer to one of `options`, forgiving tiny typos. Returns
    # the exact option string (so the caller can decrypt with the canonical
    # value), or None if nothing is close enough.
    norm = {}
    for opt in options:
        norm.setdefault(_norm_answer(opt), opt)
    key = _norm_answer(raw)
    if key in norm:
        return norm[key]
    close = _difflib.get_close_matches(key, list(norm.keys()), n=1, cutoff=cutoff)
    return norm[close[0]] if close else None


def _show_choices(options):
    print("  Choose one (type or paste the exact phrase -- small typos are ok):")
    for opt in options:
        for ln in _tw.wrap(opt, width=_LINE_WIDTH - 6,
                           initial_indent="    - ", subsequent_indent="      "):
            print(ln)

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "link-order-lab:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Link Order Lab; importable without a TTY."""

    slug = "link-order-lab"
    title = "Link Order Lab"
    description = 'Diagnosis questions on linking mechanics: command-line argument order, the three-phase build model (compile / link / run), what -L and -l actually mean, and what the linker does by default when both a static and a dynamic version of a library are present.'

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def _options(self, index):
        """Shuffled display options (answer + distractors) for a choices item.

        Order is deterministic per item so the correct answer is not always in
        the same position, but is stable across runs.
        """
        secret = _secret_for_item(index)
        opts = [secret["answer"]] + list((secret.get("wrong") or {}).keys())
        _random.Random(self.slug + ":" + str(index)).shuffle(opts)
        return opts

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation, canonical}.

        For a concept "choices" item the raw input is matched against the
        displayed options with small-typo tolerance, and `canonical` carries the
        exact answer string to decrypt with; for other items an exact match is
        required and `canonical` is the raw input.
        """
        secret = _secret_for_item(index)
        answer = secret["answer"]
        wrong = secret.get("wrong") or {}
        item = self.items()[index - 1]
        if item.get("choices"):
            matched = _best_match(raw, self._options(index))
            if matched is None:
                return {"correct": False, "feedback": None, "explanation": None, "canonical": raw}
            correct = matched == answer
            return {
                "correct": correct,
                "feedback": None if correct else wrong.get(matched),
                "explanation": secret.get("explanation", "") if correct else None,
                "canonical": answer if correct else matched,
            }
        correct = raw == answer
        return {
            "correct": correct,
            "feedback": None if correct else wrong.get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
            "canonical": raw,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()
def _ask(item, index, total):
    print(f"\n  Q{index:02}/{total:02}  {item['prompt']}")
    print(f"           Hint: {item['hint']}")
    if item.get("choices"):
        _show_choices(ENGINE._options(index))
    while True:
        raw = input("  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return result.get("canonical", raw)
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("           Trace through the function step by step and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
