#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/dod-hot-cold.json and re-run the generator.
"""DOD Hot-Cold Split

Run two pre-built particle benchmarks to see why data layout affects speed, then convert a small program from Array of Structs to Struct of Arrays.
"""
import os, shutil, subprocess, sys, tempfile, zipfile

# -- Crypto / obfuscation --
import hashlib as _hl, hmac as _hm

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000
_BLOB      = "4fecafd6965b61f4ffa9c898b9664ded66fd53307a86e5435e296d17e8f71ef462a2317e807b1f11510f5de3de4bbf07473b"

def _decrypt(key_str):
    key  = _hl.pbkdf2_hmac("sha256", key_str.encode(), _SALT, _KDF_ITERS)
    blob = bytes.fromhex(_BLOB)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    ks, i, stream = b"", 0, b""
    while len(stream) < len(ct):
        stream += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return bytes(a ^ b for a, b in zip(ct, stream)).decode()

# -- Helpers --
import difflib as _difflib
import random as _random
import textwrap as _tw

_LINE_WIDTH = 70


def _norm_answer(s):
    # Fold away the differences that should not matter when matching a typed
    # answer against an option: surrounding whitespace, internal run-length,
    # letter case, and a trailing period.
    return " ".join(s.strip().lower().split()).strip(" .")


def _best_match(raw, options, cutoff=0.82):
    # Resolve a typed answer to one of `options`, forgiving tiny typos. Returns
    # the exact option string (so the caller can decrypt with the canonical
    # value), or None if nothing is close enough.
    norm = {}
    for opt in options:
        norm.setdefault(_norm_answer(opt), opt)
    key = _norm_answer(raw)
    if key in norm:
        return norm[key]
    close = _difflib.get_close_matches(key, list(norm.keys()), n=1, cutoff=cutoff)
    return norm[close[0]] if close else None


def _show_choices(options):
    print("  Choose one (type or paste the exact phrase -- small typos are ok):")
    for opt in options:
        for ln in _tw.wrap(opt, width=_LINE_WIDTH - 6,
                           initial_indent="    - ", subsequent_indent="      "):
            print(ln)

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

def _compile_run(src, name, repo_dir):
    binary = os.path.join(repo_dir, name)
    r = subprocess.run(
        ["g++", "-std=c++17", "-o", binary, os.path.join(repo_dir, src)],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return None, r.stderr
    try:
        run = subprocess.run([binary], capture_output=True, text=True, timeout=10)
    except subprocess.TimeoutExpired:
        return None, "timeout"
    return run.stdout.strip(), None

def _make_build(repo_dir):
    r = subprocess.run(["make"], capture_output=True, text=True, cwd=repo_dir)
    return r.returncode == 0, r.stderr

def _run_binary(repo_dir, name, timeout=10):
    exe = os.path.join(repo_dir, name)
    if not os.path.isfile(exe):
        return None, f"{name} binary not found -- did the build succeed?"
    try:
        r = subprocess.run([exe], capture_output=True, text=True, timeout=timeout, cwd=repo_dir)
        return r.stdout.strip(), None
    except subprocess.TimeoutExpired:
        return None, "timeout"
    except Exception as e:
        return None, str(e)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ZIP   = os.path.join(SCRIPT_DIR, "repo.zip")

def _extract_repo():
    if not os.path.isfile(REPO_ZIP):
        die("repo.zip not found.")
    work_dir = tempfile.mkdtemp(prefix="dod-hot-cold-")
    with zipfile.ZipFile(REPO_ZIP, "r") as zf:
        zf.extractall(work_dir)
        # zipfile.extractall() does not restore Unix permission bits, so any
        # script shipped in the zip (e.g. lint.sh) loses its executable bit
        # here. Restore the mode recorded in the archive for each file.
        for info in zf.infolist():
            mode = info.external_attr >> 16
            if mode:
                os.chmod(os.path.join(work_dir, info.filename), mode)
    entries = os.listdir(work_dir)
    if len(entries) != 1:
        shutil.rmtree(work_dir, ignore_errors=True)
        die("unexpected zip structure")
    return work_dir, os.path.join(work_dir, entries[0])

def _make_rcfile(repo_dir):
    banner_text = """
      ============================================================
       DOD Hot-Cold Split
      ============================================================

       Two benchmarks are already built. Run them, then read the README to
       understand why their speeds differ. Finally, convert rewrite_me.cpp
       from AoS to SoA and build it. The launcher checks your output on exit.
       
       Step 1 -- run the Array of Structs benchmark
         make
         ./aos_bench
         Write down the time printed.
       
       Step 2 -- run the Struct of Arrays benchmark
         ./soa_bench
         Write down the time. Is it faster or slower than AoS?
       
       Step 3 -- read the README to understand why
         cat README.md | less
         (press q to exit less)
       
       Step 4 -- open rewrite_me.cpp and convert it to SoA
         The file does not compile yet. Delete the static_assert line,
         then write your SoA code in main(). See the comments for the rules.
       
       Step 5 -- build and run your rewrite
         make rewrite_me
         ./rewrite_me
         Expected output:  sum_x: 499500
       
       When the output matches, type 'exit' to unlock the passphrase.
      ============================================================

    """
    rcfile = tempfile.NamedTemporaryFile(mode="w", suffix=".rc", delete=False)
    rcfile.write(
        f'PS1=\'\\u@dod-hot-cold:\\W\\$ \'\n'
        f'cd "{repo_dir}"\n'
        "cat << 'BANNER'\n" + banner_text + "\nBANNER\n"
    )
    rcfile.close()
    return rcfile

def _drop_to_shell(repo_dir):
    rcfile = _make_rcfile(repo_dir)
    shell = os.environ.get("SHELL", "/bin/bash")
    try:
        subprocess.run([shell, "--rcfile", rcfile.name])
    finally:
        try:
            os.remove(rcfile.name)
        except OSError:
            pass

def run_shell_drop_once():
    work_dir, repo_dir = _extract_repo()
    _drop_to_shell(repo_dir)
    return repo_dir, work_dir

def run_shell_drop_with_retry(is_ready, not_ready_lines):
    work_dir, repo_dir = _extract_repo()
    while True:
        _drop_to_shell(repo_dir)
        if is_ready(repo_dir):
            return repo_dir, work_dir
        print()
        for line in not_ready_lines(repo_dir):
            print(line)
        print()
        try:
            again = input("  Try again? [y/n] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            shutil.rmtree(work_dir, ignore_errors=True)
            return None, None
        if again != "y":
            shutil.rmtree(work_dir, ignore_errors=True)
            return None, None

def run_shell_drop_validated(check):
    work_dir, repo_dir = _extract_repo()
    try:
        while True:
            _drop_to_shell(repo_dir)
            print()
            _banner("DOD Hot-Cold Split -- Checking Your Work")
            print()
            passphrase, feedback = check(repo_dir)
            if passphrase is not None:
                _show_passphrase(passphrase)
                return True
            for line in feedback:
                print(line)
            print()
            try:
                again = input("  Try again? [y/n] ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print()
                return False
            if again != "y":
                return False
            print()
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)

class ActivityEngine:
    """Core build/run/validate logic for DOD Hot-Cold Split; importable without a TTY."""

    slug = "dod-hot-cold"
    title = "DOD Hot-Cold Split"
    description = 'Run two pre-built particle benchmarks to see why data layout affects speed, then convert a small program from Array of Structs to Struct of Arrays.'

    def _build_rewrite(self, repo_dir):
        r = subprocess.run(["make", "rewrite_me"], capture_output=True, text=True, cwd=repo_dir)
        return r.returncode == 0, r.stderr

    def _check(self, repo_dir):
        build_ok, build_err = self._build_rewrite(repo_dir)
        if not build_ok:
            lines = [
                "  rewrite_me.cpp did not compile.",
                "  Common causes:",
                "    - Did you delete the static_assert line?",
                "    - Does your code use the correct variable names?",
            ]
            lines += [f"    {ln}" for ln in build_err.strip().splitlines()[:8]]
            return None, lines
        output, err = _run_binary(repo_dir, "rewrite_me")
        if output is None:
            return None, [f"  Could not run rewrite_me: {err}"]
        passphrase = _decrypt(output)
        if passphrase is not None:
            return passphrase, []
        return None, [
            f"  rewrite_me ran but output did not match.",
            f"  Got:      {output!r}",
            f"  Expected: 'sum_x: 499500'",
            f"  Check that you are summing xs[i] (not ys[i]) and that",
            f'  your printf format is exactly:  printf("sum_x: %d\\n", sum_x);',
        ]


    def check(self, repo_dir):
        """Build+run the student's repo; return (passphrase_or_None, feedback_lines)."""
        return self._check(repo_dir)


ENGINE = ActivityEngine()


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    ok = run_shell_drop_validated(ENGINE.check)
    if not ok:
        sys.exit(0)


if __name__ == "__main__":
    main()
