#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/unwind-tracer.json and re-run the generator.
"""Activity: Unwind Tracer

Seven small, deterministic programs exercising throw/try/catch: throw skipping the rest of a try block, catch-by-type matching order, stack unwinding destroying locals in reverse order, rethrow with throw;, exceptions propagating through multiple frames while RAII objects clean up on the way, and catch-by-value slicing a derived exception. Verified with g++ -std=c++17 at -O0 and -O2.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "600ce2bd8f398328f8099bf60aedd3d2eb9cab4fdc82dbe1b149f57076bac08e"
_KEY_B = "61c10d4f82c14bd8f6ea80fc24fb05bce56ec42f76c40abef803521e47e16264"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "da81aa1069f20d4e3f86de413b9e275b504bddc10db22df7eea5a81de3110d520e01b142609c1b2fb7ac65b383784f64a4206aeaf1f0f715e5dda2020d"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "throw immediately abandons the rest of the try block",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nint main() {\n    try {\n        printf(\"before\\n\");\n        throw std::runtime_error(\"boom\");\n        printf(\"after\\n\");\n    } catch (const std::runtime_error& e) {\n        printf(\"caught: %s\\n\", e.what());\n    }\n    printf(\"done\\n\");\n}\n",
    "prompt": "throw immediately transfers control to a matching catch block -- every line after the throw, still inside the same try block, is skipped entirely, never executed. What does the program print (three lines)?"
  },
  {
    "id": 2,
    "title": "catch clauses are tried in order; the first type match wins",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nint main() {\n    try {\n        throw std::out_of_range(\"index bad\");\n    } catch (const std::runtime_error& e) {\n        printf(\"runtime_error: %s\\n\", e.what());\n    } catch (...) {\n        printf(\"catch-all\\n\");\n    }\n}\n",
    "prompt": "std::out_of_range derives from std::logic_error, NOT from std::runtime_error -- they are separate branches of the standard exception hierarchy under std::exception. catch (...) matches literally any thrown value, as a last resort. Given that std::out_of_range is thrown, which single catch clause runs, and what does the program print (one line)?"
  },
  {
    "id": 3,
    "title": "stack unwinding destroys local objects in reverse (LIFO) construction order",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nstruct Loud {\n    int id;\n    Loud(int i) : id(i) { printf(\"construct %d\\n\", id); }\n    ~Loud() { printf(\"destruct %d\\n\", id); }\n};\n\nint main() {\n    try {\n        Loud a(1);\n        Loud b(2);\n        Loud c(3);\n        throw std::runtime_error(\"fail\");\n    } catch (const std::exception& e) {\n        printf(\"caught: %s\\n\", e.what());\n    }\n}\n",
    "prompt": "When a throw leaves a scope, every already-constructed local object in that scope gets its destructor called automatically during STACK UNWINDING, in the exact reverse of the order they were constructed (last constructed, first destroyed -- the same LIFO order destructors always run in when a scope ends normally). a, b, then c are constructed, in that order, before the throw. What does the program print (seven lines)?"
  },
  {
    "id": 4,
    "title": "throw; rethrows the currently-caught exception unchanged, to an outer catch",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nvoid inner() {\n    try {\n        throw std::runtime_error(\"inner fail\");\n    } catch (const std::runtime_error& e) {\n        printf(\"inner sees: %s\\n\", e.what());\n        throw;\n    }\n}\n\nint main() {\n    try {\n        inner();\n    } catch (const std::runtime_error& e) {\n        printf(\"outer sees: %s\\n\", e.what());\n    }\n}\n",
    "prompt": "A bare 'throw;' (with nothing after the keyword) inside a catch block rethrows the EXACT SAME exception object currently being handled, unchanged, letting it continue propagating outward to the next matching catch -- here, from inner()'s catch up to main()'s catch. What does the program print (two lines)?"
  },
  {
    "id": 5,
    "title": "an exception propagating through two frames triggers RAII cleanup at every level on the way out",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nstruct FileGuard {\n    const char* name;\n    FileGuard(const char* n) : name(n) { printf(\"open %s\\n\", name); }\n    ~FileGuard() { printf(\"close %s\\n\", name); }\n};\n\nvoid level2() {\n    FileGuard g(\"level2.txt\");\n    throw std::runtime_error(\"deep fail\");\n}\n\nvoid level1() {\n    FileGuard g(\"level1.txt\");\n    level2();\n}\n\nint main() {\n    try {\n        level1();\n    } catch (const std::runtime_error& e) {\n        printf(\"caught at main: %s\\n\", e.what());\n    }\n}\n",
    "prompt": "level1() opens \"level1.txt\", then calls level2(), which opens \"level2.txt\" and throws. The exception propagates up through level2()'s frame and then level1()'s frame before finally being caught in main() -- and EVERY FileGuard destructor along the way runs automatically during unwinding, regardless of which frame it belongs to. No printf anywhere prints while the exception is merely passing through a frame -- only construction, destruction, and the final catch print anything. What does the program print (five lines)?"
  },
  {
    "id": 6,
    "title": "catch by value slices a derived exception -- the base class's what() runs, not the override",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nstruct MyError : std::runtime_error {\n    MyError() : std::runtime_error(\"base message\") {}\n    const char* what() const noexcept override { return \"derived message\"; }\n};\n\nint main() {\n    try {\n        throw MyError();\n    } catch (std::runtime_error e) {\n        printf(\"caught by value: %s\\n\", e.what());\n    }\n}\n",
    "prompt": "catch (std::runtime_error e) -- catching BY VALUE, no & -- copies only the std::runtime_error base-class portion of the thrown MyError object into e; this is object slicing, the same copying-only-the-base-part concept from earlier in this course, now applied to an exception. e's static type is std::runtime_error, so e.what() calls std::runtime_error's own what() (which returns the message passed to its constructor), NOT MyError's overridden what(). What does the program print (one line)?"
  },
  {
    "id": 7,
    "title": "a nested try/catch does not intercept exceptions its own catch clause cannot match",
    "platform_note": "any platform, g++ -std=c++17",
    "code": "#include <cstdio>\n#include <stdexcept>\n\nint main() {\n    try {\n        try {\n            throw std::runtime_error(\"first\");\n        } catch (const std::logic_error& e) {\n            printf(\"logic: %s\\n\", e.what());\n        }\n    } catch (const std::runtime_error& e) {\n        printf(\"runtime: %s\\n\", e.what());\n    }\n    printf(\"end\\n\");\n}\n",
    "prompt": "The inner try/catch only knows how to catch std::logic_error, but a std::runtime_error is thrown -- std::logic_error and std::runtime_error are unrelated sibling branches, so the inner catch cannot match and the exception keeps propagating outward to the OUTER try/catch instead, exactly as if the inner catch clause were not there at all. What does the program print (two lines)?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "_Vv?t#GWXGh8e<mD;f+$%6)Sc$B5l;p9;r;+tuKXNuqntU(4&A>{M34w?GYdKRDTQ42W45Pn?HQYuxOl+19Vz@;Zv8{&8*dJItXIVb68olu%Sa3mmLvr$OMx|BEA#aRe33Nk8R__ljrD;q+ktW?mMVqavZ9X9*MVSy~uo;>ysvD#_g_#7+d025UeP{qy*RVKuA8yLY`!S4#Z%JgV7~1<Lv`_8(}Z@?J*9IK0BCije$)xPRi6rbc^5&WS-QPnR$=1{^y*PG=F(XYWfR@YX@TRu?eAXHccj#eqa+iR3(FZV$7?sd#2c@t_T88X|2T1agpBe;heU#e6l!Fd33nS#^TI__svmjgt{yE;*X`I2XuEcL&GH19*E`u+(uy3E|-zY@_<9q3`Lne<q;q({j~sS_5p4%>USx!=>|gpo%b}l)>(9)MO2c>r641p7r8ZnILvPSFx<aX$6?S{D}l~vqis#KcPS&KG=s?zr9Oj>l1~7{SX@$yCa2SVd+IB)~RiZSHWK#48$axEc3K(H5-za*|<GzR<bF3fV$zQT}f)XXmi-&hVWgEJ;w8;W;%0nX&#Z`HeRCatZ6n$TTmM{o^L7Ret+w4i{$3S#|S!0xq(xtFP)>FS|1;vuBLQsI*C)og;$bvpDarR#nfbqk0M+ugm>nlcF+}WM6#cyM8<{hReM|!rvh|QxMq+au}~6mzw;v7O|#ZK3_Z7%|DZk3L{s3&mRk~Fx9)L!?{)+ro`g1pem*bGx;M(3zPq8&bGBc+B^P~FBJ;_t9B0F|Cd!QgF#Ya_UP_x#;&7XVF-o?XukWgSO7RP&vhTD_jqq#",
  "_}Vbwd8`z;+~4K!I48Gk!`IMJZO>jPhDWpZ$labKLNJ&7oo=e#%j985h~t5nHGOU2Dvv+PLTgzA_0%6t_m@U%l`b<{(;@q9n6%hXEkq<Gg~_5AmshM$YVuR~mFQNn6_9-5_lO>Yj;u{oZ)td#-uVJ?$@uR_m+8uhjOi*wHBK2932C^l@LguzLx2=nv>n1fQ@pim88P2UNxT-iXMsVIv&uS%P_YLw)10ZTx=&HVg!CiIZ9BRQP>TZ+h5Fbef$>GgFkUkeJeN!*Z#dCrMxtad$$xjM>0*}ycQn35{$@I?*=F!i^Q%?VBJB4?Kh%9V&SUM)kv@K;DG?@_NPA`KJ;Fq~T*<4%1ps%oIN1;VrZcIaK9rZ;y+Rx;ZhZ#h%u^Z5WR@G(%~>-PA5|Vt<++(p<B#?{Ml#i#{TxV+BvY3$gDECCWY>QeU=68b{aW`C7BJBrN1y_5VAamxhNf(C(&(Adk*PF1f$WpCy_N}hDoFi`qjct86Y<wjX7BxbrM$JT=%apNYI=!jU<Wi`Oku6Z(jiEwq*)$wWz<qK(9w@Rlrr=L*Z0U5f>^LVG7Be5Gg+FnpEjB)@%R8|+V;(e|9@|(oiI7r{=gs}fC0?(VOAlkO7aSkN$STieO9eM(-i@WTVa#oiDANTa;<xBvnXzAB*hFJK!TW5Vp%Z^mSp*wj4EaI<zE+QyrzJDC#PS*P*+S=;+Jdnks4M`(mP}U2FKXr6wl-?!8a?@=S~#HZYSX`8+R9rxID+r17QQ1-a~~1v}Y6J2c^2~|B(nBRQVl9JPra)WG@VNu}ffuf+HVz7YLk(+HkgYW-EuhBmLu+ouGwMI5Yj>!*_;#UzS0gH}5FSfADU=M2g^+hz*3JAQY4EUFZP(SLo(_*SPNQ+D~iI5Cna-C{bU(hzr?UhwWYUhvOkJzNdw<I!)mD;2O@<lDz^UP}nnp#;sZAwzNo>Zv",
  "L|vDQiNwDe`=YNHu&DIL6b2V%*+K11L>`ou*3{y=+x%#;GR=-Y+)2lB^o}OZw9%!?u5m)eE~ie&5Aok5z+3F&6M0a};<I8JP5yA>z_CRfnY6G2sk7I%1GfPJg7$gUEY1<3*o#@zI`eVX48|E_>}JW!*W&r(4kPJwVUJvX_@*j4IAH*K?SS}fSu)$&>iDUZt!-GmnkUOa+-W+Ki6kPJz&|U1YP%(pv{vBhBQEQchcJZ27{P?kMlHDf<T+ss=;I@?@ekIsJXJ2^J3n?_Cug6nC{-Bt2-++VHcy`jaUXC`kPMHd;pZX?6njF?W+CAZ0Zb+FERZOd1+320f0ZN4w|2~KUMi28(MFID_n{<qf6E+IVX6L|!j(ROf)vOxBJ$qTB2z+@i4qiFCpEoEwa!3749hG$VIi`4<OrJ(<4MX%v97uQMG4vpMe${+kMq{=F4q14RPuT8*A+UoP(`rDPxZF$$S(skXQIKBOCr%p%lxrI*O((g;?H&4LolL{g(lMEWlrcKx}Vfq<WIotC+pHzcD>!V1!I`s=ojD0cTRN2K(wlVeu4F}1%{ebZ8TN8Pd6>$pPRr$z|rsjw@6!8`D(aM&qnOOa*saiMHo4-;2`H-mV=A!2i2M)^GM3RwlvWti&3dDM55x!SqlnqkH(UaeV~Hj2P`<P>AdHuvW8TEBH=-Bo^!d1mtuSMj-@$aBL`}1A&|mN3cb}7>*WyH>S71}6{?&}=>Lq#JaW)2%ZuVnbj?d|T<?Ka;=2xA0i)8~A}NCxQVM^ES*ncEsvaWTZfI3<-H?(sqh|h#w*J1ytS)&jw;Aw8kX3J`emVcegTTn1l&hx^x}6cNC>Es(4}gI{OEP_=Q_6^DLBpF5n&F3wzYOV{=}gE$)Xqw0gT`?;P*{pC>gcD<<zFGsndC5767=sVA<x*w%mo@n{RPO5QPi=?auT-S(tIyP<6c1*{^O*|9JYdFijH{+l=H!3fGy150w)yMxC2bh2gvaONOG~>6hQCRJsAI+M`?>LRV+zN1)w`DdV6(W^p$m{wPpP~?Zf7c3}@aBDBFa4&2*;Lsy!8=`5gHnap%GC&DVvqZnZ~Fb5NT6!ElNL%LQ7e4eL#dHN8^eCm<5%hZa#Y=&NuX>YIK29QNH0EBFGiaLBi4urgjQI=!b|h+i`1#X{ED;lv4xJjv>f;;WRlSRfvQx1|Tg",
  "6-&8SC!PlF*U>oB2}77!TBqMN?X!#%o#yC*be0w`N;pE*?VwP*JwmPy-QGZmQP_VuAB0W^B;6hxtDL~l5oS(tQuW+=AVf|_ss9$HMvpg`cnT~E92d5l6nXmSDCH&4fgJT52#1P*?$12YYR;{mXFLUfUd@Sgy<MjtsAK2Ixdk0_xiWQ@_Kz@ndgF;0g|28AITDCYO4FX9(4~92fZ|a;#}(Q{AEgKr1f!9icf*6P@v&zVI-JLeY?*KzXKG<2@1IEJan}+6SYz1|YipRH8-4T=7GNw}gvV;|JvVS`oi-T|lNGBNxuV9@xk6?C^{yKfk*=T-`rHXxHW4!B#e$&MXYW16-=)Ro-kK?1e|v+Wwvc!>Ds|if)>XSk)6gtfEEPbIS-;^KHXjs0U;DO|Au4arL7qwr;^*>(h#b*x=QVSUpFv~M6D8T4*U{SG!mV`_RUw@SlQLkeB_fY;3<chN(lkEdpHVkO#=F2)FWdL8C*=AS96pW(IOYx-z8WVd%EjN$>7?E=N{r9~h75+M^HsspZUW1S;{_)<amXdZwwfCI9Sqd@4qXetcC|y0o)expC&Ppa#s#+PE=gMvr8HEndVJMNhyBX*x0Fy63>tJ;%C_9`Bu$eTXsnK!&}8;1Q9^xPf1K{Io*8j8i?rfKHSNjXp~gK~1=V32*K=f4;D}7$6?V(WD5<-|zeMf<ehAd|B)2dOd?6g`)EV~qjsE$ZOuJ_!om)qze(yv7kzigBO;acQ@2Z94h@7>{JJdWhm{TznD(!Jt2%o{lN~eX=molwEk{*)4FLXBLjT||K-72FA$+A$EP_&<PpqEcxDo(tdM$TG$!5d)q=nA$$@}0vtm7b{};VncN_pDXA^83L{(d}nsn*;yC_4Zq<=ByGa(Lj(*)5P%ifg`e#uuO#fPtNsi7E25cvp(E@6_nXAe>#a{eLD-M>V86X31$qAHQdB8uQRQpK~JguecSoU0vp5`<U-=IX0oGIGzvU*UDmJs!{J01Y`};7!O*2MS1TkjXyv;axOv)nUTnWTup(f718`+9z8`Qy+K|qXCZBBC{4%u|+o>(-<uDmtb_5@v++cAw8XsMlL53O",
  "^hzNQhL<aE)^h0d^|>vW+!P1nVB;IL8XBYnZAv<=6`D?>+?ngzi|iS06XZQQw(FeC3RAKGd^9V;G0%oUp)&b-x$rO{D2yX2rbZK%-{c+mTge}%FG@&EoH8M7ko@mcYhk2M2D5c(SpDtV5xWod>S`_V!-fByi_nb)*qIHc%YrVRR#JZM2vit1BjBCyFRWInCr954@#z?&$bMqq@z^;$<3c%Z%;JyV3AyE*;Z5Qd79pdyC}!g~{dU1wqnajbZ|%xY7jS`H&l+v;QgQeZK79ty9a|U;vh?zD*}IzNn8PjU&vP@9d+uhSk7AW<6Mrlnrpj7@`hP)K<(gfv!||eGa#d}J2&XYE7N>u$Fb;qw&}}g;CK0Fye<MZf*-~yU5^M&x(h4-kb!XHy8Yp$OmGuKApO~o`;M{s~TVkr~F}n@g#7hg~`muoK^i7S1(*p?)t*f9ob61P;f`CdE3IVsWfuw~pw~~M100hKe45qo|GY1WBnfDbwfk$ZT{E&7wzATFZE!UhY$;1`5jI8}bLb9*pgXXrK28ZxD`?^q7-RF2piUXfD;AJP_H_xH`xgV_!s^Mg*9q7`rr97(p<GP@ech4gBZz^4Y@G<bWi%iq|H)Jp9p)ym>rK+bGO(1dUe7=(u)MSPY&-mXKVz~gWW@#5$;fHULIqSd$k^OP7eo-g8P57x0_hL03V)0RULI3b9E3x}W$r``;tc3<{_3q`pQb2<5AG@s3SrSnymcm<AkDd&b{XPZW!s}Hcxagcbye(%Bg!Gy;2*~E6(d&OhpC_^%<>mj{jZ8tdL+B}%0g6zu^dIni#1CsnQ95_oL12Bj2))^zbOQG`04rG#^&axuj95gq)=Kj7pB)c&q+wijT(ikBJ;T4AkxufF*tVKBC9wEbVxi#1o#61K;@rb?x<i<Igt+#ZP(k6E0$7e&q|8=KSk)YIy(8llh6q*`1jICT^Px3+VPP-|^)}L6fW~>Bnq*Q|>G4N95dPWWZ5Jd{@Sk)OzUsuF_eAcI3{Jw<e{<m^VPTh(;qUbZ1RLFu5gPMVFL8eN7Anlpv@!d-^fp5?Kk5f~G)>Foh4cFnE<>;)F#S=>gwW7jWj1FrWkV0pIso%v#-)6No}LkSjBIoeA523q_aeb}wJtP^092#Hz)}",
  "x+xapH*dT@cWi?PVE<t1cN=p&haao}=9GK{<axsW(x`d~U3!JlZ<qwtz{3e3eI_}-<qLDLNOc)K?qt-hPdz%0FxkunTNeS~>!8rNI)WR|9ZHabR&Zgd0vNyV4rZAVY8a%Xg*7onSpDer82Xxinm!S|-8{g=sMuxJVJKwzt~_Yi<tgw@Dsir6G7JZN`TcK`dl{i)es0t-!Go+~&@mM5@W;p{Gh$BX5aBs?S8<o3!rUmv)<28&h54}-tixHb-zsI~`$T1KDPV!ROf#H-%SL){L&6goB};dKbPc3qSj^sTc}CQc1@cRiJ6Ft`39Tw;E*D4&*g7}4S}cBWM`3N(MIu$%bu5KOb>nuwd%6+2W8bcqwAcUue58>lZXM45Ep6Et%6+rgy|Pdq<{LQ33-Uo|vu6<XQ!Iw#f>=74;nKCbOGjc_&$*s`pYY<0#g4_%Gnd9DHz!ZnjQy~h;x193+kG>>rKMm2#2|^A64;o$1>{P`SV9MW<yu)v!#S1Aq(&L0mIUXad`8+q;_Yh$f<chmUJ?t0s07{rt7ydHm`uUK**bYG)n7&!sP?dI4-OIGftsO+cWa{iMF;l1(Wb{6G06;-<<M3YkdOb_@{49l+y&?tD*~Qc1O!PhSByPR-<POu5e&;Ows1Zh4AJScaq@cY)9SuZfGq3o-Nq^Pi;*i{1kJ9E|Nex)!WHzQ?3-=$4FL?Vn|?37>g_=OPAY>yH*A=2&IUxd^;GJ|<ug<_1N-bsT$jMiZW;ef?h+aS5AC&Vkg{K~2K|hCm;Fo%3#E^K#zxsGZGB}<ge1CNnlp9#7BZv~ooso{9iY7zhft)#C+p#74e;p<%ks{NHHAjB()}Uy&_&l+fS<RLQT$izoEOpWH8A$;iOe*PW~Rj<kLtJ(H3y9`e;UJNg(y2MM+kwBV=7V0AAnI&YyW;`f*6432(fsekvh}#*lFqzz3B;IAz!@WIhQQ3c7!_l6hHnu6_x9xy%JK!odwCSxZ&p{O1QnAgi1+R3h8e$KYlpnU?7OiEy~rBREx{E$>4{#*i{Dg&0>!rm$F&HGu(mqb8EfLKC%z5h9fiQ{vWk`S0X{bJzHy&?fv*_A;N1gU62<=2!kW}0D0f0_2)1CGx3tsb3NKC>}&96&}B$J%7$=D#@0ZIpT*}MVdg_;!nk~1HRTp>yc!g}!xSkP8wlSFLMh6^;a+Ve4s*SgoKFxGttSCw!Y5Tj6+H",
  "H?9jU@*tw;<(wdH3R{IzzRR4%wRrHfdJYeVyLL4+FXRlXkB>HGvIcY};(pFK+-C5#uup*ld3X~vS#9E9+<^zw>Y*q`H2&VZkNns=ZA@kGuF!Hg658+eMo^owuw7{KGQ*{6kPa@_3B$MVjty0#@P67q565~p$D2h&7<ancz)RT-V14RA*@j2ZEno~^TG_W!mLk1Ef=sdr%ZAM>gn~#p%Uj*+Ru%*FriBm9Ip*0PyHmXP*vIFp@}2bY2~4L^R}M`H?K7(gK#Uv4Rg>Hq(dVVwuNyrbmvj+u{W&gpZv+N2e-1cgSVnf%{3GE%jvu9<ZPjk&@#{*R;eN>M=4h|jY$WaPD<`^)1$R2k@66FSO;s;6XEsQJ=d-XHHt-bii7=`JV7(cy1+gJV=&!2FndxiEj;<!kZ5L14O1VCZQ-1+p_roI|CCJ8&VUIL`juQRO)Gj?xU0ex|I|<THOx&!B@O+a(?oS&vXXFi<>pLPbmat02I3%w0+_HD|oU5P(ife=jbTMx8AWmgkTkNpF2XoVLBuD@K!{YC--GyrdDOgRpK_<<9%4R3<x{#H%1jqw^&H!(Z7wQv+xnUf<Ocv_&?Wt}2&AJfwrXkbT8Y%#*joOLm=Hc=jxAL)0RR!y^6_NkujUJKC1;h)NPc-S_haxwO)?eIdqhoEH7p0ngoxV-_VcMr0;xMAEM+B>7!;ov%*yNNA)BU}XWrnC9+`zvw@fU=%iQ6PP?<xT-HrsfV4;EZQzvJHBSxz+`G>C_iq<z?>El@M-aAg?iSG|_5nu?6vx<qYIXoR@BD&D|YbuneIB3?J6{?06jzTeQ{E4po{NEGUunHD88yl6#vXb3erGN7|*6cPeA75@>FbNTg8RH9Pxl>!-61<?{!M=%rE$89bb@?FQ0-UQR>9Zyjiy2;=^7LJJ`r<Y&IWSZE=Pr$ii`1OaCuN2b)AgqRnnwqLdb_jH(w8HV`0QzJKOL`B?T(H}l(yc_!Yftv3w|GUdF6t)iTM8pjTTxK^Q9(8<DMQ0Ig<{kfALs7aeVWEcHK*E-0B|1TkPylan4s%S!L88Lu!x$-XH(TrX(@L"
]
""")

# -- Helpers --
import difflib as _difflib
import random as _random
import textwrap as _tw

_LINE_WIDTH = 70


def _norm_answer(s):
    # Fold away the differences that should not matter when matching a typed
    # answer against an option: surrounding whitespace, internal run-length,
    # letter case, and a trailing period.
    return " ".join(s.strip().lower().split()).strip(" .")


def _best_match(raw, options, cutoff=0.82):
    # Resolve a typed answer to one of `options`, forgiving tiny typos. Returns
    # the exact option string (so the caller can decrypt with the canonical
    # value), or None if nothing is close enough.
    norm = {}
    for opt in options:
        norm.setdefault(_norm_answer(opt), opt)
    key = _norm_answer(raw)
    if key in norm:
        return norm[key]
    close = _difflib.get_close_matches(key, list(norm.keys()), n=1, cutoff=cutoff)
    return norm[close[0]] if close else None


def _show_choices(options):
    print("  Choose one (type or paste the exact phrase -- small typos are ok):")
    for opt in options:
        for ln in _tw.wrap(opt, width=_LINE_WIDTH - 6,
                           initial_indent="    - ", subsequent_indent="      "):
            print(ln)

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "unwind-tracer:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret

def _find_compiler():
    for c in ("g++", "clang++"):
        if subprocess.run(["which", c], capture_output=True).returncode == 0:
            return c
    return None


def _compile_snippet(code, compiler, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.cpp")
    exe = os.path.join(tmpdir, f"s{idx:02}")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([compiler, "-std=c++17", "-o", exe, src],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, r.stderr
    r = subprocess.run([exe], capture_output=True, text=True, timeout=5)
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: Unwind Tracer; importable without a TTY."""

    slug = "unwind-tracer"
    title = "Activity: Unwind Tracer"
    description = 'Seven small, deterministic programs exercising throw/try/catch: throw skipping the rest of a try block, catch-by-type matching order, stack unwinding destroying locals in reverse order, rethrow with throw;, exceptions propagating through multiple frames while RAII objects clean up on the way, and catch-by-value slicing a derived exception. Verified with g++ -std=c++17 at -O0 and -O2.'

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def compile_all(self, compiler, tmpdir):
        """Compile and run every snippet once; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _compile_snippet(s["code"], compiler, tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual compiled output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return result.get("canonical", raw)
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    compiler = _find_compiler()
    if not compiler:
        print("error: no C++ compiler found (need g++ or clang++)", file=sys.stderr)
        sys.exit(1)

    print(f"\n  Compiling snippets with {compiler}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="unwind-tracer-") as tmpdir:
        actuals, failed_id, err = ENGINE.compile_all(compiler, tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} compile error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
