#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/dunder-dungeon.json and re-run the generator.
"""Activity: Dunder Dungeon

Eight short Python programs that pull back the curtain on how attribute and method lookup actually work under the hood: an instance's own __dict__ starting empty and growing on assignment, a class's __dict__ holding its methods, instance attributes shadowing class attributes (and what reappears when the instance attribute is deleted), the __mro__ (method resolution order) of a diamond-shaped class hierarchy, dynamic attribute access with getattr/setattr/hasattr, the fact that a method is just a function object accessed a special way, vars() as a shortcut for __dict__, and __slots__ refusing to let an instance grow a new attribute at all. Every output is deterministic on CPython 3.10+.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "edfcc8e47391886414417c96bc958270c61841835376c817bdafb19589da6e2c"
_KEY_B = "ad3909e7d822d8a789c01da89e9698da9e7ec0bfefb0ea6204641754f2ab9369"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "d50d0a1e4bbe23352bd2172031d6edce9ca3bf163532a53d2b37da4b075f523977f6ab2b00631a04fb220feab62c32639daf7621fd73e6aceeb4616d3150f0"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "an instance's __dict__ starts empty and grows one key at a time",
    "code": "class Empty:\n    pass\n\ne = Empty()\nprint(e.__dict__)\ne.x = 1\nprint(e.__dict__)\ne.y = 2\nprint(e.__dict__)\n",
    "prompt": "Every ordinary Python object stores its own attributes in a plain dictionary, accessible as __dict__ -- this is the actual storage location behind the attribute-dot-syntax you have been using since decorator-x-ray and method-trinity. Empty defines no __init__ at all, so a freshly built Empty() instance starts with nothing in its own __dict__. Each assignment e.x = 1 and e.y = 2 adds one new key to that same dictionary, in the order the assignments happen. What three lines does this program print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 2,
    "title": "a class's own __dict__ holds its methods (and other class-body definitions)",
    "code": "class Greeter:\n    def hello(self):\n        return \"hi\"\n\n    def bye(self):\n        return \"bye\"\n\nnames = []\nfor n in Greeter.__dict__:\n    if not n.startswith(\"__\"):\n        names.append(n)\nnames.sort()\nprint(names)\n",
    "prompt": "A CLASS also has its own __dict__ -- separate from any instance's __dict__ -- and it holds everything defined directly in the class body: here, the two function objects hello and bye. Greeter.__dict__ also contains several automatically-added dunder entries (like __module__ and __qualname__) that clutter a raw print, so this snippet filters them out with `not n.startswith(\"__\")` and sorts what remains, keeping the output deterministic. What does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 3,
    "title": "attribute lookup order -- instance shadows class, and deleting the instance attribute reveals the class attribute again",
    "code": "class Robot:\n    voice = \"BEEP\"\n\nr = Robot()\nprint(r.voice)\nr.voice = \"WHIRR\"\nprint(r.voice)\ndel r.voice\nprint(r.voice)\n",
    "prompt": "voice = \"BEEP\" inside the class body creates a CLASS attribute, shared by every Robot instance that has no instance attribute of its own named voice. r.voice = \"WHIRR\" creates a brand-new INSTANCE attribute on r specifically -- from then on, r's own __dict__ has a 'voice' key, which SHADOWS (hides) the class attribute whenever r.voice is looked up. del r.voice removes only that instance attribute, not the class attribute -- so the lookup falls back to the class again. What three lines does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 4,
    "title": "__mro__ -- the exact order Python searches a class hierarchy, for a diamond inheritance shape",
    "code": "class A:\n    pass\n\nclass B(A):\n    pass\n\nclass C(A):\n    pass\n\nclass D(B, C):\n    pass\n\nprint([cls.__name__ for cls in D.__mro__])\n",
    "prompt": "D inherits from both B and C, and both B and C inherit from A -- a diamond shape, with A at the top and D at the bottom. Every class has an __mro__ (Method Resolution Order): a tuple of every class Python will search, in order, when looking up an attribute or method that is not found on the class itself. Python computes this order using an algorithm called C3 linearization, but the practical rule for a simple diamond like this one is: a class always appears before its own bases, left-to-right as they were listed in the class definition, and A (the common ancestor) is pushed all the way to the end, appearing only ONCE, after both B and C. What does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 5,
    "title": "dynamic attribute access -- getattr, setattr, hasattr work on any name, computed at runtime",
    "code": "class Config:\n    debug = False\n\nc = Config()\nfield = \"debug\"\nprint(getattr(c, field))\nsetattr(c, field, True)\nprint(getattr(c, field))\nprint(hasattr(c, \"missing_field\"))\n",
    "prompt": "c.debug reads a HARDCODED attribute name, written directly in the source code -- but getattr(c, field) reads whichever attribute name is stored in the variable field, at RUNTIME, exactly as if you had typed c.debug by hand. setattr(c, field, True) is the dynamic equivalent of c.debug = True. hasattr(c, name) returns True or False depending on whether that attribute lookup would succeed, without raising an error if it would not. What three lines does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 6,
    "title": "a method IS a function -- accessed through the class it is a plain function, through an instance it is a bound method",
    "code": "class Box:\n    def open(self):\n        return \"opened\"\n\nb = Box()\nprint(type(Box.open).__name__)\nprint(type(b.open).__name__)\n",
    "prompt": "Box.open (accessed through the CLASS) reads the raw entry stored in Box.__dict__ -- an ordinary function object, exactly the kind def creates anywhere else. b.open (accessed through an INSTANCE) does not return that same raw function object -- Python wraps it into a bound method, an object that already remembers which instance (b) to pass as self when called. type(...).__name__ reveals which of these two different kinds of object each expression actually is. What two lines does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 7,
    "title": "vars(obj) is just a readable shortcut for obj.__dict__",
    "code": "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\np = Point(3, 4)\nprint(vars(p) == p.__dict__)\nprint(vars(p))\n",
    "prompt": "vars(obj), called with a single argument, is documented to return exactly the same object as obj.__dict__ -- not a copy, not a different structure, the literal same dictionary. It exists purely as a slightly shorter, more readable way to write the same thing, especially useful for quick debugging (print(vars(obj)) is a common one-liner to inspect an object's state). What two lines does this print?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 8,
    "title": "__slots__ -- a class that refuses to let an instance grow a new, undeclared attribute",
    "code": "class Slotted:\n    __slots__ = (\"x\", \"y\")\n\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\ns = Slotted(1, 2)\nprint(s.x, s.y)\ntry:\n    s.z = 3\nexcept AttributeError as e:\n    print(\"caught:\", e)\n",
    "prompt": "__slots__ = (\"x\", \"y\") is a class-level declaration that changes how Slotted instances store their attributes: instead of a flexible, growable per-instance __dict__ (like every earlier class in this activity has used), Python reserves fixed storage slots for exactly the names listed -- x and y -- and gives the instance NO __dict__ at all. self.x = x and self.y = y inside __init__ still work, because x and y are declared slots. But s.z = 3, attempting to create an attribute named z that was never declared, has nowhere to go -- there is no __dict__ left to add a new key to. What does this print, across both lines?",
    "platform_note": "any platform, CPython 3.10+"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "PDkBh>s6tJkLvifw&VG(iKm``nu{ALdkNh~UU_0E(*S7DZ7DU>1Krj~;S3CZrDgUZBXtv`ymi5IHKHiRU8%OJRyk=(!psuz%*RZ6r&Dz^cv!@F(S-5K70DSTL`$6CE2iA^bhM^{HR$OeN*pOEGkv<on8mevBxXceafdz5a9?)U`F$$5{%neQVNMfvA4-{N`eNq*7{Svef%hr9#S)|1ON0lzy!fH_je}%rv92HbXK~HbkvfFZ2K^se8C{{JnU9GXQw31jD6zCq60u{J;PSw*1S*je6%LT;AKu*HHm&ZvY34$|h{nkg-jF@a23Bnf?j$)*oRYSq9Oa%03FuZOs!Qep&=g&?eqd7b43MWljnhpT39+v7Yvg#TViXi9wm>YnbWvEhy6hK;X@xuU;LKV?^oAacsF_x-zKP;O5a8XyFXFRX@-tGEa(QO(pF77@)q}TWa)|lB!x{=nSVOBcCX}Ss<DygR*y*|r)-H<&NXS+U1+07o1>S;+F}tp{2$5Fc9<S{HCd5lY6PW8o3%ozVbdp_=7(OrWnpJCp2H6!NH*dYx%tM4T^>pcCn0GrPKu=y-y4Wiv;upd%it%DNdpu#qNG*b?Z#`K?f$K_rD=43e7Nrk0iD3r0RN5pF7-a`O`>a`;_YouKaHo1j3+q?%!!gTUl@7IeN^Xzas`0GK(^u{lRSFD6EqtEtMPE(1rNYnD8VGzXD~*GTWlIi}X9<J4=3ZPz{x8bS##TjYfNrN!$Q^g=leogTNavId;$xU-PE&!^{=e-K$&jhw%&3$r7iDxs3dACB2c??$sB&H8Ky|_apF;vCGqHI#3^KGOH7TO*6L0Vndd2vf-+ZBF*dK9&Gdp7Wz$rRXU`9)*>%`93b{n|e)STT1Iy^A${Qr7y?R^;hVp9F|hgK*+{F~g_G_%ycc+L8h)$i30nxhO-5c?}f780aJ-!--LjK9MsWBjDb!7r5@M<375G)Cje?m;irk6~tKi($4QKGk#n4+~o{k6^F<HHbZ;7W^z(UJ8b;?VCBUR8607;jK^Vq!O6mnF&MNqYOY0gyML&#C>k&oo(74x`llqggL}p^Cvs@kczbIX67Xiio|$Ry8*ol4%QxK*PzLNY&Yd9V8;Q-z>bh*wV;01WO-(&",
  "cy&O-fAwL`^1qMi=;p3`eIM-8l{W}{do>CPwWvd5^@@u+6;BZ8jHar$JM>mG8w-YR@6Av5b`~{78`BWauT5OycaNJScSnAzM3bWv2@FSc=L)lx@+#>c^@hM!vp9W^kCvawQ$Pc0e$c3<K8X|#$@sJ4-pDC5zP`9xqM<sf;R|9%g8#29^5mR-5puu>8aZn2k}M8ha0(}s*0=K56hK6Kw0d$%Ep6+tOs(iRw`%G-i|(x_INo{GS7kjfo)18md9WEvIG{{rAhCY;r487{zF%p%XQ%39LZt^5q^mqMo$|By>v9O!8!>O9$1(zoM2<K`a=|*M6ueu94?m+6#|cD?pe>*S0joc=sMp2BKHyZx%(CuUm`<&<Xdl39{;)l+kh{%uP{f^`hSU((>%A}E_EzT;H}EO~=#(vG%(?C0j*O8Gk@vI2No2Ji>N`3tZ!=Nevc_ogW9@Zd-K_FNW=K>Q^~9<#Sk7y{Gw_j(hP>)T3M*t8Ba)R3ogQ|-pFEjC1=tDatbJ836=y9@c%JyJqVT*o2iNbS7s7^wh|mu^*96^E^GL#PBw>&Nd|@)t#OO_%hz$$p`5RV2mX)c4_brX=J)^CO6X}kg6)W_Jb0B4EE8R&sSAitG(|PP#m|HhypX{`aVJ-79fEYc6WE$RMnqI%|a$I@B5^MP8`BZjs$inj$RfS>|$LH-`h+fA!E)pHGbcBL3$OdVxV@CPzbG>h3723y_zf(Q$Nu?a2!gs^pwVbNw;{-X44->e|cMDHj^*U8SH;+?iaJoFDH^|K<rxbHbEB;_s(Wd4B3&+Q@iC09MRE*up3bC)SI_+@Fbc!v#Aveo&q-2<avHhSqWEfh=tne8ORq&In2~jD#G+dDA{#@r7(T=pq8mtsBzlSkRI8C?=1QT0w22q)d8f{MG@|!_U^lo2V5uMk1sNOTgz=k8N@cC$eXi8)i!V1LU%s?PVZsB@oHtaJFq3TdW=w|IODyzDzF!3Ex?=#O1y;C1hz4F%ays6d5w~AYXZDr9eEZ)l}JxNgcclO5uXH42!1B3",
  "AvePQLzrej7G-C1N%r<S3UOdsXAdz|!oA{m1P)Z`1rnA#>6L8$NUD2V{FhPwt7@g}Y!PhD<Qddxuq1~N;NLuhTlOK=E3*tA%`$s##ii$hT^(eqmOjWUOVP>L=xM2W#ZAcX!~n96=;)aw7Ii<f$G#wfi0rVs0>(%suaNzroRmttAXBKX0oI;s?GKdB;0)|`1l(dHuxEQU0$cP`zeBj{YP9#TOl>L4&KxpY%Z!tMe`^swfRIHeH{ah!B*PnT63d!IMSzGaMPa8~Ch1(I$GcXJyX`~3mBZE`xUX99dlNmy>~51Gwar&fwR6gzjme(Gic~K-L0Soi#$K)iC7&ll^uIERdb5}A8ckr&i!p=c+X+8K9W>AebL<u`{XboUNzccYj?7%IA(r+Vag*1oR}bh(SJglR3N;(Z1smn=GC{FS=}7}zbL)I>5Oc|h=Oc#p?Zj8Zz?GQYL0D$S+4A9mv+AN0<UHaO7bwOJ^3Icw6F7GK7<I1dPm3aMC(0olVGg0;!6ODUN4@3SlI1J$cMk<Q(9BM~;L$ts(KdlEu#Xd3($w26Q3^LJW`f$x#x7BDwpG80ZPIbx{7ppD2F3#veKIYP=Y4`hp+-QJ3`ooEOFgEbcHWdflCH9J1fi8Q%jLAAI%CC*P;{6yXK<8SjHXqzqoJ{Tx}m$^=L_m&PF}o|-;U^ev`aTC86ENCV@+Hae>+|KXAI(pNLNp`-FklfCt~D@cFc2A-n+Ry*4#(vr9D|@t>KFKB8~)slLLaG;iP=92rcX>urfF<zbpYhZ290L;<rIdC}>TnHL1j`dGaT57M);*WTgm79AgAdr|D}#CR2pvY<<m1#2IvQ`0@M!t@gT}s7K{AOoJi&e28wlkmlOlNRwHP;1?HL2d@cK3?t&fHJ9rz6cnsqUaZR}7=E57P#)30V>|rWh3HNp&5_vpV&)z*6bC>>oBlIEE{!jJ!hX;~pI>j&WV{0+)*a@eQ!P9}1H)pZ^Kjeg*JQ_#R&BU5)EPhTdXqSipEU((fTZNz|Bo0Nf}!rQPgB{eg1=W737Ws(MbxrX(S#b;<HJR)#EzTlfqe+!fUJB6zn&ZG%S&^eF8qw4`QlRz!U0G$xUj%&8OUP6H^HGH!~9@a{-PqKiGR#8&3oRCszms`#H1_`iVMPb$C+nb?Bgvhs@NUg2bfg0*B?s0;}RH7|9<&4nIoF_$)E<vJF%a!#gIofnZT)TK>",
  "HU-c*1nFxx6PnsB`FZmc1-OZ(%&<G!g)X<$v1$Y{tvhdTzx>l4b`PC9S4~uN$th;<9KUcKd#CL~(cBHfY(-ve-M>&|*24ypxf$eCRT*fEs$r6Z<LoAaLWpPRTKuQpawgrqyH5UAZqr+Sox8_qSpMb?Iq>qeuU+5c1tmLPb5Bjz(UKV-a1;&vIzNNuw;IT~e&5!KIvtY4=ds94#x2vTJT9cYq)&g}QoJuA`%{&^S};m`&!M7NoK8)O@sya1g%P4+iPXHst_mCvXO&i95TSvz??@BVx6M`ao@#SD)O{A&qp%vcG$r~O>l2+d@MIQkpgGLF--mp~*outzHe7=O@i^b76gKS?_nm_dVm!<LtdOh4-VPfSU2?Ldjc^D|jave5J<Y8}@!{it=v;A=2(!l3)EtRHOpYdwBwDoY^7T_evyUHuUx+EJ=m)QDDpjp`ZiaG<ushP&FZIu_SP)|0GY~EWwZ4Q-VjGhD1r9HlF5?7K0iONON%<Ffw)r9SJ#}2)sy44r3%6=2EA_SLTV+%&iFo-Ju$r$2;WjY-Z&$h^8I#V9+Pnd9is2%#<a1;H&VUXRfRYNCAX`aJ`A<6cQDpGTYDIx{!H(<Ji9-a_^6KjJmbQ2_$Kk?HqXV9Q|4b0Em=wy~@<e|cJ)XO@z7~4#4LaD$dC2fO-^nCAt7Ytac-S<oSkYUCm5FKXacs|DOhUC`r`e&Rpo-R^hXO?<x}pb`8YKZ*G-q88HT~w!<%V&t?iPgFfegmzL0qIFql=-k9Jh?<{xyq-#U-&AsBoVV{Yy5#mF6m3S5&9cm10m&%>>Yg&+#By46xAriWjG~V1If3^@bmB?O&R~UpyvuqCX?hvPbnSER43<B$>jWT1vTEHZgJtSNODm1?o{rqj$i!C`8Tm0y5*Q5wP+WS%+p|0_E@o^Oq+F94#_6<r(GNNq7`?*z9e_AMQjzF>RHR6VKj;cWK&svJjK1e+vX<zbq4DikySp?xvpz9*yL9qSkw(Kt=1tEs~hq{BP45-y2AOig<}IFy=c4YKeCaDdd6WHlPOUy3d>1!+x}SkS$WH!KjQ!m%7E^C4Bdiu-<P~j|lYK@^{6d4p|OW$|DIB-wrSH)cZRrM8j87?2jpOl8xR`oaH9IPJAZ{K&e5R;=~s`?Zjh|>c!Bk8=&1y?cwAgQF|pZ<W?tf%SM}x{gg%>Yl)HAN*O*yU5RttOgZgyD-4z<Wzv9MP{RY2sl5I8Km`nmOfWKoXGp(XXdgfe>Jhnx1t)3o#%~6b+)g<r#TlNyf#P1eclt1vl+811Y#pHBm$5npUo<15vb9iC1+IM9hoaW+3$qm$-YS!`rQvOXTcrt*bVv}z85AwB=`WdvtzS-w5Mp5K>1+{a$(v0CE%vc!FjsT~=LpzKvX845sLuLn1>L?1f-G{GHxv!q>jX(Tnvziv!L@w^62eZWFmm<aM%dY}",
  "y|NhBKK?>@P>Ll8-m;2+sbpujUBiI;Y-__n5fd=RG7wg7!<m=3s~EI3vDWQdCv`DEZ7kxlA?ULxjw+)wL7?Q8Maz*@EMa?W9I+{-;XN-|c|c#qi3cI%5DxN4|G`s>l9D8rk;bTReAk!mD!uvMmTSn;DHw;o7jHc$)>=qtPmJ0)#Pd=x*ycn{QC<;_sd}zK3b6Zwnr$2~1VJayDktRP_vFl~&9FOuAE!x{49!m`L=8l_$JWn@Fr~F5@FNw*zNa3%E6}Fa;>cMwkNq+pN||6@qsAIpB37<^3K1+OEmrq6=n8m(ncYy9<O*`Fk*OZYS%R(BC>_i3)`;!UOg7Eb&#AjIqBotWtroTA;REyFIgbZ<#62C%OaIq6#W&<0TMo`I#u%K3{TX8Hvud$<uYu{-vIWD}1nG_nA%sa;14{)jh^x7eUz+OI#p@WylZH!4-9XZ~lXY!BHq1(t!PkTYVd8N^`#K*x7w|4xzjt15tzsSNV3HromIi7+1)Fvu6(GI?p0Jtu_nM7*w2)2V=|qcJrB2<yc8=9-c3<!Zr`04xokpO~ONNeF{x+&CfXQ4cm8hQw_4H}n4H*Bc%!zr=W00GEZ|t|HCRf(?`xkx*EpHtN)gTJk&!&U@&5`&T=Br2MU}#KS!9u~D6B*7Yn=&ygW2Ant-_X^57CU*g#0BZ+%iq!B@4>YIb6B(lS|SNVxZiBS=lW3~T(UbtTrOuWIh|1Mk;}UdBe@Ud;DxCMZOYlyq&|dfZAYAoECW24a|(CpX{m!3s;68kVd+I2=QQk~>bN$4r@OOMooY0tPG`FOpwn>UVHI!ntJN+VdJdOI)EJvu#|&-OjNMQ8^r$cS_d52PY~~s|jbp5GIy#0gyFZ-_XpgyJWfM1i!;}~PV1f=fP^;-2b9_xPLxWTs=1K|pS8fZi2>A2X-`u14x>R4P2hCFleZ@1ts<%5R7W9+%TTCmHYxYqCKDC~ZrIh8>BAS0`4mHBv`d}IKQy`8#XS~cTx;QPI5PEUeRfs{ltD4<hrAJwpWwu{<hijrYm!n9&DOTGbO>vpQt(CE0B<w(6BVHUM5qaR?zzV)6iIogDtZ%W&Q|3Txu%VvJETsI9B#Euwkd%L2I50F>iB6dZK(hQR0<Q|k<U*VDJuF+@$M_d2*p-?_(ycA(^(~G}JLfkR)de>|O!@uZ1~K%W;y`ANz4CrHujyG`=m{3~{%z4v(8yM3brvG%)@+(&W--lnZ#4s*Z?^Ff#}CdM",
  "2_3%O`~)WfSC@D=q%d)r-p3(`KGVg{3WgwY@voy==O3`DpbE27?PI01!jIC(N=q8A>8;q|T-=Q6o892HktxoB$?ldhMm>vq{LcU(8m@(}%?k(|P1~KqXJzk0^R#<a7D`RtYe8QnGLn*ADC3K{7$I+}_TH^m3rWXLMAEecUkB$~vt3+t2#+hb6e5Qwk~aFIoxj)r+nM6qgflQb&5#y2<6!vE4VdUrrDIRTR_)~YYvqt6;tMq+C_HAo0?eZ8+C?@wFY^NCKGZFdn{u<8iJKdrb7l34gha&nKUf39GePZ@{YvRsms)Uz1IAA8=~bv2;Zm?KeV|_oev9#F^TKUzU}WIPohJweMo}Z7_XyItpQdSlpdD~_{erjPaO!FU<)sUI)78i0yJJ&4i1u28Ch0>HpUNT!^_eM+Ilpm^a&T?NzTOHJ#M;B_A#D4^OBwrPhDs$2ERvD<uGyRSW=o|!?tqEK%5tg3%luA@l`~<Jxbyqen7Xm;+ZJ{D6CxKo2QC2r<5+~_EZ{mS)qpJ7aOgr;MDJU80DY}{#yTF5ZYw)L9`#^Er;2Sibbcn#3$}@26^=Lj5-6gx8VL*U5Wji2qK@d63Sq3}4gVqFi3*w_u};3Jx^TYSun|MD8D`{i)l`Dnr!vxv^a2u5lg{}1iI1^!WUf@w={wb<elaxxL2e}fv>AFDY_WtH4e}ZsqHpMndoc%(p2gNF=Vvo7{2Q?6meMlMoPBO3a1_4>r)oCx5KiqwY4#e2NtQSfp8$v3MnF<xB@KymRx@6@W>bt|PTaqN#iHs#PzAadc84hH@CsOW0XtrCCQZH@R9*@0JqJ2x6a8&Y$xju53fE)(*zV<KTo4!vjD#NvkJy3WEh$WR-tWMHe568v2p+kh3SnFY$%Q8$IM}^6UB!IK5GJAJ{Epz7E#BS#R*eJ0F6db>$n0V&z4c$1<89htpMO38YGW;f-@tgDi-+&y9tn!ZA#3-v0#)sf!FRa~>->NfT`5TVoxsBLKP?>i*%42Daj?WtXW}P#Wb{ul5QM5uqvLDHvBXM7q2hs=MXwCH$vu9&NhP@|0yu0sA0M<t9o_Y9S&Q9?TJgkwuBj%%+Z##%Pu7to(;`i`N(_m8{48Ka_4(r0FO+mU&o7DiZZoosaGc}b5Mf|N2P~!6KR+SYx|4T}(vX?2TsoCVfMS-V;`s<zb7=T0w|rdahsXrZhjmjO!KkfDW;$({%$i%36EFTep6ki{t76ivb~ya5dvtJeV#_D$k;<+v8yP!y;N&6V8SHt)7=bw2!LeE_&BdNQ)|I@aCjPvd;{",
  "+^Gw#-_GcYJ${LHwBLKE!;J8XsMc8%b>2&j=36P<)WN%l0UNDkhWhNQ_t8VL4EZpFAT3UHIl(N_5F1j&(e-<gX>O-UjC;u=vSuyv2;Y{Go9&Y(M@QBsy7y{e_3w0Tfu<8V?I`x_Zk1wa`Rkn?I*Wbk<WWCf){Qsi+#KF{w4q=X!g~)6hQns}CA#-h9v6U196g4T5yn5SX$icw%pSLJ2h21x8CPamC{e)WCTEx8CKoF~#>&@1Bm{y?1PcmrFxIpaWGxi2%!mSxD&hUbS^02e>58B@+J+N5jxir40{p#gBC_{&;RQYcP%ujcb)A|@2@^GHs08ys*`CYF!IRh`s)C#rk3C4tyR;%Mkez4gfv$LK{Ugk&;<TX-RM;YQ@@*AME2gKmqZm{Mp2kmXh|H_fx)$$RM6W);HobD!!UZ0tn;OE4|N99QMVOS1phnVw*E2!8udGKy43aGlfe&ol{qx+?cU$EtJI#|bzi=gaSz_&3I4Y$si~ttHw!_~k(FhF_JePw2#LDje_`5G$vBEx94;bI;LALiBY#!dlIHy?FVP=E!`F*xGd%zM)?aYsizp9*VxWBXl5pGo1RfR?Dg<T?-S4Cq4bt3q{@<Wr!gUgaBH<kl3cz32W9>i0O{LkC3j+S5^k_#Mb^`_ZaU;WKA%3oLhTR7rpAPz7|Q@rAkwT&^zOqHY?f;jlwBhVYz%xlL^{HupF-c?YAr@d%0oQ0N%Y}G}N7B?{|v((xDr%%YK8aZSG(__->@ruVC_J3A0sg*Zs>i8nk154o>RUF8_yBywXJkV^<D0Nw5U2~_GRg~{7Jk<cJmEYTI={l?V6SX9nve8p)ni$7P{i|syR{3LS1puYzW5vC1Oh%*wife$)P-SA~5^NcAxS&ZBBbX^ksr^Qx>-Q-p9o*3n!UtQfAw2hhbWwDn#Yso%YsKC0RPMmow#c9wI}q7`Sl5trG@w)NbJg0zneQ8!SQv#5TGxC;4p!3isco9{%F|L6z5ELP&v<ryGkZokeoFDi{LF&ulIt3_0$iv_phg04n%9+KOJNgck0)so!y98yeSOS_YP7%TdgMm_CwhA|8-BoUAxE85RVo|KmYdySo-DGLlh88Rva4|L{o3%SmjPz%^7!d$u(|zU$B7I4yXRyEP%UprW^qiJ;CWE??x{=",
  "tH8K#??8cE4szyc-8bLf$%lZA{T;+o@3sCS4o{-v^5a^(q?ogxTpMmJF&~78{+3K)g!Qm)jXPY=KR9yB`Dwhs14wQI?MjZNZ)+W_<R7c}i?Jp`00R|Z?Xkc&&!=<8nq}Bk6(Lz;Hv#r10%EIJpV!+K`^Un~p>V>H$4L^s^@LdLR)oI{e!nxm=9=~P?P1<*>b%z!8#xkIFx9f<WnQl{abk7WVyhB5r8vrMtb|?0!%!8Ku-s$e1f*HPYoo~x<0>&=Rl0K{NL1DD=cPN#ASC&uET*h1siEngJ~iSd#>fYj-{dLB`><b6_4c36&K2{Wd`gWXf&sU5;h509)aUUg`Up_TXX@<_+5)dp4EU#CRMs*Cly&BqG{|I@j#5A<*-mbJ!Lnj<KzEP2?mDA<kuAO^<z)AZGPubiY`y!F;X?|QO-$hxUJ+afvUHp6d?858jBcqO*EsKnW#x~j09N&LrLttupX^*Rd}yaPVCuNl@lH4A@BHni=E3qI|58cCqJrtO0GP}Jv$)LMUE7{vx5pEaFVgr%F6RDL)A5bQ(LbgAfgR&x(&Fw(eSHkGWqK5vm<m+*v2Qe-2y`f^0DDrT&{|V|%LF+m<ju)`n70Vi2u`cyY)#<m04scG2-$_Kw9gw;tmZwlRP5k*<Hc`JYB?8@(`bFsWJVZ8i|JI1C#pSd5ttCreviIn4trKqz`95@$r)dSkaZMg`KyL>OhZpoT96u>?2o^av_awoE!O7VmU-=js`cFZ-m2)e0pbxfEqr=Nvu9Rm)#^I=)@oc>y}oH+8VNLHFG1@m=tr4(ONp??a-y^aD??LsYFVH<E&QW%)=Ls|S>lB%r5P&$&_%Y>4sZdNvCdZfppL-wt_luP1+Dam0HTOF1J5*0N<B2W>>C`)IpB6hMUkr5DMzUe=dQ7A{Y2E^x{e$PvJ7UjL@@Kp;d~F;*9;3p6A$PTBpaF*(dr|G@TSUXV`sgrz=pn4r+#?fsynU_=me*A(pW!(i|l5_R_;1Byvd&0=I!Ev-eG=jBKP9c8$hG@;`O^eHv+@3sJvBmvq9}U`2Qk<%8_@cO9az-*4fwI_$Wqpljdlm-36Wxe%6CNF3cA~-ynDj5_R+vCQXtchfk|8ayALdeWpDwFSzY%{hxv)4&aWjQCpeag}|dtzRFVT)p#y=S+YQhF1Q8@k^$l?3$#O_NY#(n)`td1=aDKGj5RNU>GjN8B!QGGD<anCeK3?_euY}yh(IAEcm1Ju#tDB=V#6If@Xj{u&iUlHjFGCsi4|KXpQCC6r1npc$s@?VM{L@Iexafz`e{2DU&C+1^r~G0<oVoTIrGVCJJYt{dY(|rUK19H!0;CjqS#iWA2wnGg#q_xjU49}JEo|-MNQ>Q?wpS7qe80p*`$Jgg?3#Y(k;vT4K;g4+nKUgtdwVh>f)CI#|kd9@t$0HR@;hBxp($2^{26>@w$8WwYWM4r^|-M+$y<kg_!"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "dunder-dungeon:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret


def _run_snippet(code, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.py")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([sys.executable, src], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return None, r.stderr
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: Dunder Dungeon; importable without a TTY."""

    slug = "dunder-dungeon"
    title = "Activity: Dunder Dungeon"
    description = "Eight short Python programs that pull back the curtain on how attribute and method lookup actually work under the hood: an instance's own __dict__ starting empty and growing on assignment, a class's __dict__ holding its methods, instance attributes shadowing class attributes (and what reappears when the instance attribute is deleted), the __mro__ (method resolution order) of a diamond-shaped class hierarchy, dynamic attribute access with getattr/setattr/hasattr, the fact that a method is just a function object accessed a special way, vars() as a shortcut for __dict__, and __slots__ refusing to let an instance grow a new attribute at all. Every output is deterministic on CPython 3.10+."

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def run_all(self, tmpdir):
        """Run every snippet once with sys.executable; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _run_snippet(s["code"], tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual run-time output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    print(f"\n  Running snippets with {sys.executable}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="dunder-dungeon-") as tmpdir:
        actuals, failed_id, err = ENGINE.run_all(tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} run-time error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
