#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/index-vs-node.json and re-run the generator.
"""Index vs. Node

Concrete operation sequences on a dynamic array (like std::vector) versus a singly linked list. Each question asks for an exact numeric answer -- how many elements shift, how many pointer hops are needed, or what a dynamic array's size/capacity become after a sequence of pushes.
"""
import json, sys

# -- Crypto / obfuscation --
_KEY_A = "c2fe606ebfcd2acb5905587be52d6e0914b453e4550ca725051fe37e3cb3da00"
_KEY_B = "a016327c33fb0c4474c3db027acdece8b3e19c4d0210ddf1f2979b52749795b5"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "2f3ba432a5467d23f669577acdb900941a3e0b3137afed67e5cb80bfc1384b03c3a0ea885443bacc0cac4e5fa9546a40ea2ec8211eab56fab9526f71"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "A dynamic array currently holds [10, 20, 30, 40, 50] (indices 0-4). You call insert(2, 99), which must insert 99 at index 2 and shift everything from index 2 onward one slot to the right to make room. How many EXISTING elements must be shifted? Answer with an exact number.",
    "code": "// before: [10, 20, 30, 40, 50]\n// insert(2, 99)\n// after:  [10, 20, 99, 30, 40, 50]",
    "hint": "List out which existing elements end up at a different index after the insert: index 2 (30), index 3 (40), index 4 (50) all move one slot right. Count them."
  },
  {
    "prompt": "A singly linked list holds 10 -> 20 -> 30 -> 40 -> 50 (head at 10). To reach the node holding 40 (index 3, 0-based) starting from head, you must follow the next pointer repeatedly. How many pointer HOPS (calls to ->next) are required to reach it? Answer with an exact number.",
    "code": "// head -> [10] -> [20] -> [30] -> [40] -> [50] -> nullptr\n// target: the node holding 40, at index 3",
    "hint": "head itself is at index 0 with zero hops. Reaching index 1 takes one hop (head->next). How many hops does index 3 take?"
  },
  {
    "prompt": "A dynamic array holds [10, 20, 30, 40, 50] (indices 0-4). How many pointer/index hops does array[3] require to compute the address of index 3 -- i.e. how many sequential steps (each depending on the previous one completing) does random access by index take, regardless of array size? Answer with an exact number.",
    "code": "// arr = [10, 20, 30, 40, 50]\n// arr[3] -- what does this cost, as a hop count?",
    "hint": "A dynamic array's operator[] computes base_address + index * element_size directly, in one step -- it does not need to visit index 0, then 1, then 2 first."
  },
  {
    "prompt": "push_front is called once on an empty singly linked list (no existing nodes). How many EXISTING nodes have their next pointer touched or modified by this call (not counting the brand-new node being created)? Answer with an exact number.",
    "code": "// head = nullptr\n// push_front(head, 10)\n// new node's next is set to the OLD head (nullptr) -- that's the new node's\n// own pointer, not an existing node being modified.",
    "hint": "push_front allocates ONE new node and points its next at the old head. Does it need to touch any node that already existed before the call?"
  },
  {
    "prompt": "insert_at(index=2, value) is called on a singly linked list currently holding 5 nodes (indices 0-4), inserting a new node between the current index-1 and index-2 nodes. Using the standard implementation (walk from head to find the node just BEFORE the insertion point, then relink), how many pointer hops (->next calls) are needed to reach that node? Answer with an exact number.",
    "code": "// head -> [i0] -> [i1] -> [i2] -> [i3] -> [i4] -> nullptr\n// insert_at(2, value) needs a pointer to the node at index 1 (i1),\n// so it can set: new_node->next = i1->next;  i1->next = new_node;",
    "hint": "The node just before the insertion point (index 2) is at index 1. How many hops from head (index 0) does it take to reach index 1?"
  },
  {
    "prompt": "An empty dynamic array (size 0, capacity 0) has push_back called on it 5 times in a row: after each push_back that would exceed the current capacity, the array reallocates to DOUBLE its capacity (with capacity starting at 1 on the very first push into an empty array). After all 5 push_back calls, what is the array's SIZE? Answer with an exact number.",
    "code": "// capacity doubles when full: 0 -> 1 -> 2 -> 4 -> 8 -> ...\n// push_back is called 5 times total, one element added per call",
    "hint": "size just counts how many elements have actually been pushed, regardless of how capacity happens to be growing underneath."
  },
  {
    "prompt": "Same setup: an empty dynamic array (size 0, capacity 0), push_back called 5 times, capacity starts at 1 on the first push and DOUBLES every time it fills up (1, 2, 4, 8, ...). After all 5 push_back calls, what is the array's CAPACITY? Answer with an exact number.",
    "code": "// push 1: capacity 0 -> 1 (must grow from 0), size becomes 1 (capacity 1, full)\n// push 2: capacity 1 -> 2 (must grow, was full), size becomes 2 (capacity 2, full)\n// push 3: capacity 2 -> 4 (must grow, was full), size becomes 3 (capacity 4, room for 1 more)\n// push 4: capacity stays 4 (had room), size becomes 4 (capacity 4, now full)\n// push 5: capacity 4 -> 8 (must grow, was full), size becomes 5 (capacity 8, room for 3 more)",
    "hint": "Walk through the trace in the code block step by step: capacity only changes on a push that happens while the array is already full (size == capacity going into that push)."
  },
  {
    "prompt": "A dynamic array holds [10, 20, 30, 40, 50] (indices 0-4, size 5). You call erase(1), removing the element at index 1 (the value 20) and shifting everything after it one slot to the left to close the gap. How many elements must be shifted? Answer with an exact number.",
    "code": "// before: [10, 20, 30, 40, 50]\n// erase(1)\n// after:  [10, 30, 40, 50]",
    "hint": "Which elements end up at a different index after the erase? 30 moves from index 2 to index 1, 40 moves from index 3 to index 2, 50 moves from index 4 to index 3."
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "8kBe#UT@T`J55GdV?`w0(WZQ3DMjA*b|*MB9j9eGREfGKP^xuNxoI_`3iQp!deBkUhV#Z@Iz586N;iIX{TdkuvkLJdV(q_-3!*$MuN?X3w#!{jPF?Me^JV2rn8KatvgZ6=_H&P>MG_OsJzACe%uIB76xPXh-YOdE`+QW7w<}5mLB64Apy?PFh!2I6?w8|cu|S}{hKd#yWQ&0J@Rjor{3%EMFBDbKp2HSW4W1uZBWnS~*lXRfwV|WZMw^4Gwap-SBy*9cM8rX9vFGGTx;*m}mH_C->1F41fL^MO6@J6}n#z%dB^zq}t<Ne#wfp8qWL1!3U3Z?c>W^G^PQccbT1Qj@BVC+)4{xd5$Fs7g<5_e+lANk8gI<znnOv>pF(ACr8=$aTgQM*2@u)J$E~kLzg*t!e;b^Bmk+FNw<#_;>cLjz8=|wO>zorZ`UYucWx4k%zq!a=gdUiTVUY_ehy#fmjW#(ivZwH%upVb{7Qwf)Hak_n0P!=H<S>`Hvr%wd%#ynHXMaY&gWi;pIF>0CNsGaGc0<dT-hfA!;$O#jp1t-|vLwhz92Ixa1PEwNhy8k-Je%J$}MdpnR|9s8$g(p*A<?{`%_2!OlXJIF!)(o?$qmnU;6ZsGzF?`OqC+#vn){kqy9e#zhLLvoB(1^RteVL(WFrxeuo}}aAF)$aOJqg23v8v?5G(Szd`2_=hsxGAp@Li^8Qj|VI1wHRR9h}6=#gh~uspW!~TCDZVE87*YO<kwWDIOW(HXk%@8IVz3I-=`r78I$h?)&&2gua$qqzjN%kDjR8UeBh{1gWf}wM}=}",
  "@s##@C+b1YGj;S@BhRPPluFXpuP=7}%tyNeH?kSJo|&9cR;0pc{WN&LU-*TX>o&onx~)a;zh!^l-w>2d)_0129bu`Vff%&mS~5fKmq$S^5V;7?=&{A@V?%}<ct^Tkyh(C1o0Y?_r@vFsfve(vCMp;Qyf62bH$fg+38zoXTxLV<MV*<}9mqQg&ySsqFil`9<W^yj`fI_ST3?M-Kmt@pvPwM98-DAruTC?50m@r=Fo7SxohF4Csk#Pz`$6Q{@rR1KV`rvLz1fm&>exfh@H>txWz3w6#HZgymp=nA=-P%mOdHx7g%{%buYGB#zvy!SngFP<kJ46boZmEC8HU6SXR5R&fK6cvakF;Jk$RO9P~8o3>gp`ObG^4_S5>7pO%Tp)4ii{-Ukaq!ztv|h{q}%|8<dSICO&|?;;AOfMf>{$$HmYY@PVV?Vm26Jz+W#z+K`;MKFWG7g)2|A&v7Wzw4`Oj=gx0(oz^zkPAL{5Y_}|3@MwO3;aSU)ELMK2&xH6;OR9ZJ=QxfSH?qHoKUI8*kBRs8-#SxzypmCw7Jid>l}&r0BP=zJGDH+PAEQ>t-QOGXaT9e5^K&cx9t<fBw;Eu2tg550DvlS8aR",
  "b5jhRD}@yEOswF^snPf+Ro&WKA;}R1YU@uX1N4egV;NH#Gi++*mtyc7#Qor3J1Ya=mz&sRe~;eiC0qqY$xAniSD`z81pzKxi#*-dVj!t77-MAgE<V+6-mk37xH;$a9>fup&ET?cz6$_(PTkhVp`ofsPykr_bd{7)|8^m%p`mJ_Tf_|&>G!0LyU>lvoZkoVyNMa>o~c!{$MA0&nD!R%-~_YBkorjBThqlfo6pij<e?duJo9WEsHi<oecs{OA3%)itVacK?sebO84mLYH)+4gu?0mLC+$y*i9z1*-XpZ-UP^OtW#Oy|^-}8oIiD%({NM304GpiA3W?{drj0$1=mil{+sLt>Dhp9qmZlnSbIn6Z#OkY*_^W=r%5zA`ZA*xo#$`R3IFWYP#mDxU@d4k`P#5An^TS^*)*MB)_}@H9AoH#`zjtt?y_mEi#j4uqb{&sDNY`(Y*zI1hCw^^Kpa;w%Mf40CK=&rV*2l5hX`xH;Ry&JuZs(C7#!^HRKkJlD^3->up%Yo1+^zMj5p{K^_W4IZ57R#rq|f9fs+Ta!K*|!_wB%#bU}D#!CAJ9?U=m3V8hjkdHoI}zNUhr~3CO*bUyl@_+MHT%IOU_Pcqa>(%t%L2PyWDurZU%b0XhfZ_wWAV%&r`!3rv4vvzv-ENX(#!m&Dj>=poe&a+)q^<#scW+*8p?inP0heK!5K20o<&4Ci&+Ui;@1_4PPI{Q(9J8JlXBF}v1PdTa16IpmTU;!1Q){b47b3s8VX0OL?&OUMy9pr%dIJTmX0^3ptv?ma8sYd?19+iy@XKp-)fyy^nDzEni(VXDSeT)PXjX{;l$|MeK+;QoL3Vuq|lz=v*&qEzIJg`K7Gn`DKaTWG~gq#Q9vRFp6v^M{WV&<@A9XfBIzY>$LhrZ={Z_ZLJ}BY_HYawGrE>qrTmWfm}EdqO}P0-=N7kPiA>ytQwyX|Va1l4PzJ0c2-b",
  "ZrnjSsfekX6{HIpvRTO_m~zYj5s_go*$v@`cQJ1Pd6kDr$qdl`g6a{R${1a;++0ahRMy|Mn{9fNej=Giq{eG&eG;c#=H%3p#=$3XK*OG}Saus&9E;xR)#5J>cp^y5qi9m4LNu5dp!p#3@p|R%t+KSbwWamqLzadyJ5_yG{Jw0nivW|{u|_{ej;K%n^q|$q%;jl~7*wGDv}|+MGs*}vC5#C0<D9zU)cd>?3tSinw@Zff-BbgM555D4@iOf8s}aadpLR&9Wk{6$P=#U+45m+)b>%<QVbEo+OtmATr}X5!KkfaM4rcnMHPryBU8TJTx&3j5lN_h3CVq-Y1nlF)obu|v^=oPKnzm;4lp<BZyR$+9t@mX2;fuL7GPGleT{U@xF&@&m?C>^9FC_9?2SGK8fC`I$i^ct4O{2C#{77P1=kWJ(IrEw9wem^r<%Ww_Fw#L6X}qHU#A3vv_hX_o3h%%$c5E&g8l(Sc%3q=*iVkE!{F=>+Bqf}aJvdZUlmd96$fS+g3jLHCMrc><)g3IJg^|ww-t5b?N~-ire6}r{C8_H9FOa>9);5(%ndbYpqDosXk=0s9)#s)+WqiCK5=8quzSl#;z@Lh;KznVLdpX^w#fW_eWhF}2Hv4d#q4~qbk;8M)_3hcqH7&m}`zEh9hkJ_",
  "2`)ihZK5KSk9^pXr`X|{2G#Hz+q#RRMRy@QZ@(d(+|M#H32Q=w7oXN@1=lg6L$hSZmZ@bxe3kvV5i2M-%kXW|0`Z9R<tS$EVtt8ZHx-O4>q-TZRBm6g-#gleGXOCII!ZRX%I%tM2`=#;;w5^jitJW^5(){1(z_z0S(#}~2b1&DPvvbc;n{9mO9E^Udkn!6<+fJui5O0t^7~(_8_0b#1?@UY+Y|7*Y*`caRUMsGfQm8GxT0xtUBza)J+jCcvyuzLncuxq%1wP~v^7o{e1@~XpsP|lB*$#2DQ)t0u`tJ~E^LB-8@|HGbdUK>cq%cCRu%oP3SHgJxhYQ`L}VIQauU;1ZlhNwF~VPR_Wb-c9VwntDp(UYOYY&44<2XrqMd;!HDUs+VWO$aZ7$ooWH=KPD?mwZ7-A?bPKn46PVwHQ=OxS|$}Hltac$Y~?>8vbgbdmG6lv*m#q4oG@|^bovBe`C4=dkfSV{>8gugW`-$bDkT$00OYt2gDOgM<`Is!%q()&YrJ{!-Z37&Nd2-loAUaf!#rCBy~LT0|>Xidt;bN3NJDec@gi|aE*Ke0qO4DiMW$_uXJFTG#ejjjlEUt5-?Z7+;i-a4q3um}lqxxZ`8i`z!zbO}_hFL?^|U^_$9K{#aAP3(X(<PY^w&_$NafiF_kzKuT1-PkeE?Bv;5",
  "Ot27-CxjH%cIJei!;nG!<C1juW1p9_-wpi^XxrnFm9Ixlxpka86?PRQFBpekb9uyK{`7lnjj51r9U@$ZDy`*KkfsE>swiY88+}kAvoBY(aZB$mkedMVMT%PnDk?x=C;QSQt)nG22v?i;ALZyF#E;AhKOh^ww`+VaDdt`c_ZW`-MCS|h{&7$!#Eq*D5~<!-{OlCvTF=}pKPM}4yEvZTm|F$hia^2hSlu*8JsKIqeHY>EvR0Xd>ATo&_&5cMsiC%XU1*GQcsRLX&5<J6+b62$h02e2Xkr}y`v&?Y6>|X_5DNi)zLQvQ3r*I}nK99M5YK$C^lS#2Kzbn8j7U0R@o&rUo+lCyX|JaL{QguEUA_cmXqTy^TiMcuK4hWv+Z5bM)BO4;*I-g0pq-MHQ@OF@KS&;Yth%o}np)u0<>cs`q5wIRm3(!z50HN(@AN(gBE^oEJ-%JY>&>$i_^1uV`ShqFzuRxL0hO7@>c1ZY=o7D18wuAnmLfe%$!Nt!+yDW*204}*R@MeJe&h%@&xx@EUndo1wq=_HeU#H&-GjL&f{(F>Sx@-T7MO2o>+J@Qx%x+Yn$1W_2andbG7}ANIdOzCtS*w}+kro{xnF!1_Vx-!%c3g@66r6d;<~NPAZIrz&X1V00Qw}<)6hH!_?GZFnkxEEHkTuvx;faFLQWg2U`>O3W=}Mm5hR*{B)&64NSfe*zAPn{6hmssJo(M8zLhrAr){(jr%}aq8VEIWydX0|w#5&k",
  "<kxs2#dc?KR~v{8E&iYMPuqY*lU3x9eUe>jY`{j7sCyZI?KFD{o4VW_R>(Cw9mwM`icH|9m|)5v#X5o6m!NaPLGi<i56s<C^#{Ulw(_#^zy(aTj=8^cumLwE+&$}exmlds1)fHysTt04#o18H!6uZXs0wo2VZL`={3j&wW62@*r{}}Uo+Q4ErRmvRZ#>2j9n&g-1t+m$b++|rpnXH|_s6=p(Q=`3cDSJ)ZWkb9%}>_U7-_$>h5f}za=2X#vG^V`lorh}e&eW{nK3ScGl+weW_44^6+tki71+KquQ2{+g+mp5Z02kfX`=p(tcQ*8{ti~ta7Uqgi!Zr=U)>6$b*b&ry~JedA?dk2Z#RZ_LOSl}^4smWo*2aw$B=&^Y4}u^kO~NQJWS?!l{OauEGKXctN`yWpAEEEbz52%y`2?;UMd$$c$?gc08Ha+6_qYjlgQ}l=zL-;bwBvCFe5mykl1j8oD~-p^VIa+Xqz(0vvb|#aMq?6_K&eq0Y@u%v{PB4JF;TKeLsm78K@5{%(&j-#V472w}Eb-5A(3@!R`wNntA&r<vlC0qVDi~)7l?gpmG5M$4E-0umDJ!8%1&QNDbMVX_>65_>M+LHyDrSkS3&~KL%xnhLA3;AO)y2_gaHsCYsfn7e&}M(-fY`iGf+i7{I%Ah77&iBij~)Z=y5s8|r<j3pBfDpRO1A2;EwFM(UXtT_9K>;an(<+-dVlZ{#^xeQmZ;45FL>$zEqkVE%TozJSpH2mPra-7@F3&K^)bnDbr@c1@uzbeFlngrz^D;p~PxyMTn&!|aPXb)SeFBAsfNG8<^Ssq&x^Q7%eHog8!vz%Dv`mnt~=_o-TNFQ^+DoFWJe$p=C6A`e$nhy6~MZfc%C=!E$Y9o)&=4t^`b!nRECe&`={e8C#~w@#P",
  "(PBrSZ>|IVFq~!gX?dBlLKm^EH?U0Dywv(?=;ArCn<XF0fJ6F<2Kpz#nLuLp4IIdPg(X3#W^V@LRY`pv;qJi1n+EHlK=w&Nx#(xdhHr@JcRe!9t~wTLClE^wf!-{}1eD9pjBknEthqQ{Uh50LDY4Gl$#qUx?WCG>=-yi$sHh4SI`*XSOwm33{*)4tB^2}58im0Rq_%-#cwf)qr`LVql=DZf4%WJk;iB|g76A!ur)QS1T@uMg(zXk=Wn$*oWm()!s0vS>P2U~y;d@cf5;k9eUBUwucL?<E6Rhjkp2h#Zmd!=qWTVAzUWr2a3@^aSW43<_QY*`<$a$Z^+^u#29`0>P`^24GG(#Z6n~p<*D&=OWS<8hv#Os56NLuw13xboWrSZeL7+P(-Lq5cB%8J>Q=n9PTaRgYPrlOK@6PFoy1?!a<?-~Ull$G}QVA9?L=2dFf#qR%sE!+ImT_bfkkQK$PSbx$zRJ-J@X4of2IbydFxz7O)3NY<!GqW@$4iGz=3Qawplk8~m?mr#K1BR@L!by|W#={1wzVD2O!#W_cPSgaEk+NDHrP*Zf%1CI`#b|I<DwRW)LXC!bQuvpubWTCSvENQG+t}G;S+0EyIb%Xn5jQ~GPlZ9h`d@cf{iiMF1<9nwxFS#FctcJ9_ETCVB`g+kf~JLAQp+{Y27T1INg4<mg(gIJOUa!"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "index-vs-node:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Index vs. Node; importable without a TTY."""

    slug = "index-vs-node"
    title = "Index vs. Node"
    description = "Concrete operation sequences on a dynamic array (like std::vector) versus a singly linked list. Each question asks for an exact numeric answer -- how many elements shift, how many pointer hops are needed, or what a dynamic array's size/capacity become after a sequence of pushes."

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation}."""
        secret = _secret_for_item(index)
        correct = raw == secret["answer"]
        return {
            "correct": correct,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(item, index, total):
    _hr()
    print(f"\n  Q{index:02}/{total:02}  {item['prompt']}")
    print()
    for line in item.get("code", "").splitlines():
        print(f"    {line}")
    print(f"\n  Hint: {item['hint']}")
    while True:
        raw = input("\n  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            print()
            for ln in _wrap(("Correct.  " if True else "") + result.get("explanation", "")):
                print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("  Think about each call separately and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
