#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/ring-buffer-rehearsal.json and re-run the generator.
"""Ring Buffer Rehearsal

Trace a capacity-8 circular buffer (ring buffer) by hand through a sequence of push_back/pop_front operations, computing head_/size_/write-index using modulo arithmetic, the way ArrayDeque<T> in the deque-two-ways assignment works underneath.
"""
import json, sys

# -- Crypto / obfuscation --
_KEY_A = "78c64234cc71ab59d74d3491c15ae6b8657661dca441a3accfb49018d2b88623"
_KEY_B = "880c0f113018d51a35dbcf3838c2225188249c497a157b4c9e354e2085323591"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "336b337ab1ca879a92120dba6c179f2962f8141c745e349038c75c74bd4a02696c1be70271384dc13250883674e79f"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "A circular buffer (ring buffer) starts empty with capacity_ = 8, head_ = 0, size_ = 0. Five push_back calls run in order: push_back(A), push_back(B), push_back(C), push_back(D), push_back(E). Each push_back writes its value at physical index (head_ + size_) % capacity_, then increments size_. After all five calls, what physical index would the NEXT push_back (a 6th call) write to? Answer with a single integer.",
    "code": "capacity_ = 8, head_ = 0, size_ = 0\npush_back(A)  // writes index (0+0)%8 = 0, size_ becomes 1\npush_back(B)  // writes index (0+1)%8 = 1, size_ becomes 2\npush_back(C)  // writes index (0+2)%8 = 2, size_ becomes 3\npush_back(D)  // writes index (0+3)%8 = 3, size_ becomes 4\npush_back(E)  // writes index (0+4)%8 = 4, size_ becomes 5\n\n// physical:  0    1    2    3    4    5    6    7\n//           [A]  [B]  [C]  [D]  [E]  [ ]  [ ]  [ ]\n// head_ = 0, size_ = 5",
    "hint": "The next write index is (head_ + size_) % capacity_. head_ is still 0 (no pop_front has happened yet), and size_ is 5 after the five pushes shown."
  },
  {
    "prompt": "Continuing from the same buffer (now holding A, B, C, D, E at physical indices 0-4, head_ = 0, size_ = 5): three pop_front() calls run in a row. Each pop_front advances head_ to (head_ + 1) % capacity_ and decrements size_ -- it does NOT shift any other elements. After three pop_front calls (removing A, B, and C, in that order), what is head_?",
    "code": "// before: head_ = 0, size_ = 5   (A, B, C, D, E occupy indices 0-4)\npop_front()  // removes A; head_ = (0+1)%8 = 1, size_ = 4\npop_front()  // removes B; head_ = (1+1)%8 = 2, size_ = 3\npop_front()  // removes C; head_ = (2+1)%8 = 3, size_ = 2\n\n// physical:  0    1    2    3    4    5    6    7\n//           [ ]  [ ]  [ ]  [D]  [E]  [ ]  [ ]  [ ]\n// head_ = ?, size_ = 2  (only D and E remain)",
    "hint": "Each pop_front only moves head_ forward by one slot, wrapping modulo capacity_ if needed -- it never touches the physical positions of the elements that remain. Apply (head_ + 1) % 8 three times, starting from head_ = 0."
  },
  {
    "prompt": "Continuing (buffer holds D, E at physical indices 3-4; head_ = 3, size_ = 2): four more push_back calls run in order: push_back(F), push_back(G), push_back(H), push_back(I). At what physical index does the LAST of these four calls, push_back(I), write its value? (This is the call where the write index crosses past physical index 7 and wraps back to 0.)",
    "code": "// before: head_ = 3, size_ = 2   (D at index 3, E at index 4)\npush_back(F)  // writes (3+2)%8 = 5, size_ becomes 3\npush_back(G)  // writes (3+3)%8 = 6, size_ becomes 4\npush_back(H)  // writes (3+4)%8 = 7, size_ becomes 5\npush_back(I)  // writes (3+5)%8 = ?, size_ becomes 6\n\n// physical:  0    1    2    3    4    5    6    7\n//           [ ]  [ ]  [ ]  [D]  [E]  [F]  [G]  [H]\n// where does I go?",
    "hint": "Use the same formula as question 1: (head_ + size_) % capacity_, with head_ = 3 and size_ = 5 (the size right before I is written). Compute 3 + 5 first, then take that result modulo 8."
  },
  {
    "prompt": "Continuing (buffer now holds D, E, F, G, H, I at physical indices 3, 4, 5, 6, 7, 0 respectively -- wrapped; head_ = 3, size_ = 6): two pop_front() calls run, removing D and then E. What is head_ after these two calls?",
    "code": "// before: head_ = 3, size_ = 6\npop_front()  // removes D; head_ = (3+1)%8 = 4, size_ = 5\npop_front()  // removes E; head_ = (4+1)%8 = 5, size_ = 4\n\n// physical:  0    1    2    3    4    5    6    7\n//           [I]  [ ]  [ ]  [ ]  [ ]  [F]  [G]  [H]\n// head_ = ?, size_ = 4  (F, G, H, I remain, in that logical order)",
    "hint": "Apply (head_ + 1) % 8 twice, starting from head_ = 3."
  },
  {
    "prompt": "Continuing (buffer holds F, G, H, I at physical indices 5, 6, 7, 0; head_ = 5, size_ = 4): how many elements are in the buffer right now? Answer with a single integer.",
    "code": "// physical:  0    1    2    3    4    5    6    7\n//           [I]  [ ]  [ ]  [ ]  [ ]  [F]  [G]  [H]\n// head_ = 5, size_ = ?",
    "hint": "Count the logical elements listed in the prompt: F, G, H, I."
  },
  {
    "prompt": "Continuing (buffer holds F, G, H, I at physical indices 5, 6, 7, 0; head_ = 5, size_ = 4, capacity_ = 8): four more push_back calls run in order: push_back(J), push_back(K), push_back(L), push_back(M). This brings size_ up to exactly 8, filling the buffer to capacity (no grow needed yet -- size_ == capacity_ is full, not over-full). At what physical index does the LAST of these four calls, push_back(M), write its value?",
    "code": "// before: head_ = 5, size_ = 4\npush_back(J)  // writes (5+4)%8 = 1, size_ becomes 5\npush_back(K)  // writes (5+5)%8 = 2, size_ becomes 6\npush_back(L)  // writes (5+6)%8 = 3, size_ becomes 7\npush_back(M)  // writes (5+7)%8 = ?, size_ becomes 8\n\n// physical:  0    1    2    3    4    5    6    7\n//           [I]  [J]  [K]  [L]  [ ]  [F]  [G]  [H]\n// where does M go?",
    "hint": "Use (head_ + size_) % capacity_ with head_ = 5 and size_ = 7 (the size right before M is written, after J, K, and L have already gone in). Compute 5 + 7 first, then take that modulo 8."
  },
  {
    "prompt": "Continuing (buffer is now completely full: size_ = capacity_ = 8, holding F, G, H, I, J, K, L, M with head_ = 5): one more push_back call runs, push_back(N). Since size_ already equals capacity_, this call must grow the buffer first (allocate a new, larger array) before writing N. If growth doubles the capacity, what does capacity_ become after this push_back call?",
    "code": "// before: head_ = 5, size_ = 8, capacity_ = 8   (buffer is full)\npush_back(N)\n  // size_ == capacity_, so grow first:\n  //   new_capacity = capacity_ * 2\n  // then re-linearize existing elements into the new array,\n  // then write N, then increment size_\n\n// capacity_ = ?",
    "hint": "The assignment's growth strategy doubles capacity_ whenever a push finds size_ == capacity_ (the same strategy std::vector uses, from the big-o-lineup and growth-witness activities). Starting capacity_ is 8."
  },
  {
    "prompt": "Continuing (the grow from the previous question just ran: capacity_ is now 16, and the 8 existing elements F, G, H, I, J, K, L, M were re-linearized -- copied into the new array starting at physical index 0, in their correct logical front-to-back order, with head_ reset to 0): N is now written into the new array. At what physical index does N end up?",
    "code": "// after re-linearizing:\n// physical:  0    1    2    3    4    5    6    7    8    9   ...  15\n//           [F]  [G]  [H]  [I]  [J]  [K]  [L]  [M]  [ ]  [ ]  ...  [ ]\n// head_ = 0, size_ = 8, capacity_ = 16\n// now write N:\n\n// where does N go?",
    "hint": "Same formula as always: (head_ + size_) % capacity_, but now with the NEW capacity_ (16) and head_ reset to 0 by the re-linearization step."
  },
  {
    "prompt": "Final check: after every operation in this rehearsal (the initial five push_back calls, three pop_front calls, four more push_back calls, two more pop_front calls, four more push_back calls filling the buffer, and finally push_back(N) which triggered the grow), what is the buffer's full logical contents, front to back? Answer as a comma-separated list of the surviving letters, in front-to-back order, with no spaces (e.g. X,Y,Z).",
    "code": "// Surviving elements after all pops in this rehearsal (A, B, C, D, E\n// were all removed by earlier pop_front calls) -- list F through N,\n// in the order they would come out if you called pop_front()\n// repeatedly starting right now.",
    "hint": "Re-linearization preserves logical order, not physical order -- the answer is simply the order elements were logically pushed and never popped: F, G, H, I, J, K, L, M were already in the deque before this rehearsal's grow, and N was pushed most recently (so it is last, at the back)."
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "UN|Dh6UdRS*xy){y6Am4R=9+qTK=xEx8b`QTm_WAewhPHQOVW{JfiMX_jw-ybyRKSz#pr_H^FT%A?r5U>Z~jLKiFIfOb4*RcpJxxBMJ7OU0H`9nK<@Ow^Un~IpJdV{VeMd&y-b#fAjMo1q2hrMDXA6&7YfuCD1()aspA=dd%pp&ijOUL5K*8O&~<YEv}2%G%)7-dyVd&o)MgS|8V_<N$&M`oo*k9OPt`VBg@=v3m-+EPx9{wcDI@%m!Q}{n39m3zNOHM54$*N<U)A+YcCYkZLXC&v_l1=bhx(5cn<2&CYWaOzfHU&rik^>F>=@?Ls!#jDu#b~1BYiKv;@QrDJlUfTu+gNj8|$DJhAm?0HXQ3`Gf*_o!ZpJ3(NpdmX*J@Y>9MJi`o|@$6W}xrllM7Ok>I3_c}4>L0pR@F?(K`O%-i}n}TK*Iz*~#gCuN-BZ6^x|FD28S?Lpi53RIe0_3#35ZKLLt}-*;{#^(2sZ;3OgCV7dwrCBF)%5Hd5SIEAMbz<U@$qx92N1gFrCdNI0is6qjq=OadQod4zJoARJ~q4)w&9;6@YV4af;)zP2ywQ$pHmu}?H1DKP||$#_b7~yOG!ay)WFR#NGz!|ow!`0oDr0`baHjH^lIO&=SpPs7Ff##imEQvD?&!$*c?FdnKF9PLpkcX8Pd;6vO_>^N0VXGj7T9ZWEc9qvJ^AoAuDiUw97i$760ZqKrrgCS62X*=U@zF1{!CS+9p&u=+(ufY4-@@rbR}YOI}^It}VQF`yDn^s)Z?}`X};J@ha*?{4T1j{UF@bA=96&1tDZY@N@",
  "Jw@K=6a@JD8LINqU?={fhv8#s|KhKdLF^q!W~hM`!8}Y<B}tN?L*ybJN7DpH1ydS}J^hx@`c2|}^)8H@$~uk=mR{FKtbj=qSc5Z*_d1E3Wh)QT$<9wvoeIbLCs4+(;+3({Rf#Ci-{$kO?FumTq*h)5pdC|ub1}Kh<Bnm(qD2u->@uIL&P3vwk*l~}HlV+?x`%hM+jsqggNr;$B-x&Om(Kxec8deVA4qg0d2&T3!lt|Q&%p=3-fVtPH2I{=|4)IPhz#QL7u}oUEV2qZ^Z~2qb;*b>MmIT%E%qZ57C6}o2<2{VI-u;X&~dL#qgnipeWp;INTF*YI}Ya;(jD8|f`8}q){bIuRs@_wX%>IP3x0s}Z8{1@3ih(G>UuvX!hUAtn`q2}XTuSvOD+tpBq8N1z>T%^+6Z@t%UM<zQsXYx&!t1{Z)v_~cy)MNG90LazxG%Cy!Pc=LAkt@^B~Yl23%n|4#7yNPF1qx3>4`gGVymoI4xcSAioQ83SjMc_tP$&N;f&daa8BNdCJFa&PO32a=)MVIcJ2n@g(A@$-?6&4Z}&ol+Kjx`t8Y7p!WFRieiRas}+e@0=F$VZE5aoANmCh8F)4}_8eVpMFrA!$Eect`nHxEar86P!U9Y=MEtuzkrzIC>76S{hm8q3JwZLSV@0phR!l6W`LFz6lk*IbeF=a)OC-9xOpP6tQ6;oDi;shFnK}2d8;^GiH6=m",
  "m!@jw69D93lAgMK|5XKMQQhOx;H7eT0s@?G9WK7DSVV{rk<}69Fn;r`<C;#122i)XlB*<TRBxJ)LeKVLyp<MM!IxTV>f2XpKMI;8yT5)3j+8)1QY@2gB*T6ID1YbR5wN_sAsmt@_0Oc+;<>JS@pJe{J}GB5!`L&f4Vq#^E;I22n2rGQXIU0ub_>=f-$a(&k<U3td*w9Hc)gKeumI=i%k=o4NKDx)@71L2ymoX}oGEx)@WLe_2E}P)P}dFamYW#yf$VqJlVS_rRM$ZWqpI{3iUF;RjKhB+H_9c%>VV7x5W|6II`+8=wCkuLX5Msn-_5##I7uu|J_*8yN+12*ox;rA!=(9^xG|bAht{NR#7eWrq-&+y+km$dYWB($O7#&g;m2b}_SQ{3UR0zv(xldLZZ%SExNyDpqcB@Y-Wrv-D&+JM5&GA_{d*Im7_Pv(>$4oAdyx-7Kgnaeo;=Zu7TTdEGwF)P_u?bHQv{dmLjEJF7!y1<{iOA}66>BV9Z*~X@b@y3<}4sT{W)OPRZw3)^q6^KJL(#miezUJX#J+sb&^6TC_s_X?Q1MLH9<O4b;GX)eYvJLW%QWwf7hQ2CBi9%x|QxCgv!$ICJ2z_g`pL?_Lp+iwRorLbUs<9U2fGaE7<tR0soaAPHnpxk&>2lf^rEi16qNi<q&zE$&N0h1K!3nA1=)r@L)am2f9`kzyFVvYM3?|ml`&4ASC}){dt@H=F6p_@VM!L^(Fa7hDzA-t{vE(&f(fsY;!*y#|jj7=xQ5^EudT9Eq5SSXL_&zzfqm^<|8o+wq$35A=kRX2_f45LGG<`wHK+a<M^^;8nqD~AoM%KWUDuo|JVUdsY5Z{S>OZUe?ZqPQ6dp5xZLpV>HrfHxQ`vX7#R*j",
  "(^&E6`7c}+z6~?{0qKLq5YN49A&Q+Xr77^W(S4RO=QMeFhOOU`r)Ij7Nb(y+MXp(-FLh*S$3R$W{7ee7Om5Xm33w3_i3~M!Wd^*9wn3cH*dFlg$|2MFepz)hjOF63Zuwn{+!4!qzgi1W6(87uoA>k2CrJ{1ZBUPR=uSGI<pg)v73v4T-tv{~oZ%#-QgogtY~AH5@tKmOH<PzG-O^W}K^0)u(CL_9wUtaa(2ntQn)RCEkD>0}ABRAfN5Ayb6RXkQUnMo}K2L}d6BYo<$O_3bSQi4dDK#bli;8E{0g<SgJ3A;gUD-`;>>y9tlY<cI8U4RL6ntZ{8&g;SFZW<hBLU7d(lTISRy=?@Tg;AnWV#2J+>y_R-~iq%wD@TxCY4Ica6gJNrobaFRKlIN(=1Aax!+`(<CCzFQTKmzoW*8O$#OeJnul}f3{w_=%~uu%lKsP}L0K?H^>B*%$QE=0&AR{O3IkOk^a5$H$v87IV(}52sYc7+r;B{=1RdMO<Sk?k9XM~EC^p!uuXX!g1V2NA*ALPRBVGYlBfPpS3B_-amC@xM8-dzMv>Yn;Xsh38F}+@1n^Er)zV)%2F4nA`?|!?eo!j#6Mk^!S0u0N0WLYCs&|nHAA;n(oL5Wz#C=~}AUI!__0bT7696LM=R*pC*T{MqeeFUV?",
  "m|!3J$It%B8a&{v_#t>`Jp>XBa;v=L!eBb9lv-%9%Nx5sp8ujqV#QO~G^8VKA6*U2QO-nD+~do+h^xmMX<G#{_ASwl$XEDzx@Ko#zSXb3q{ZOD#~l}t;#=A_T8C6kDPH{V+Z(^}_F+{wScL;2oAkjK;{|GK1L7)gw=YKfj1hAwDp0q5AI|r-6YUZfqR!{@$07Kr>;j%teKD|bQ7O$FQ9-`+1ARwO+j4Z3E04MWkHF76t;ml)tt9W`3-e+S-&s7(N)4X|o96<kN3*p+9K{A!ipXX(J7UjtG$~~*Y{)@?^p%e&Tcw<@FO%=J=gpmRYZ}L+(+H1{jz#hs5^+F=pl*OS&a?@rgwli04_(8BfOP7~vkYn4%XJNo*8I^I1cwneI-IdPA|^P5$$r_<f7Io{q}xS_EKVGmrl%W<-tKcw5(#0pXt-db8SiM?C?b?h>8Hh8aif4W&UZghuxUS;6ZlLWOa#J%WaK_V88}1wFv>T?vc<SP2p`e|)F%A)9J(Nv7*Cb2S6>YIq%F$TOqQ$oq4rB0W(tN5MK0}J<FN|I`)as6Poe~7qSgNxkdQl*>N$mUYH%Lo3*{Hsdfzg`maJS43Wli&5)v^a(k=v?wY)WlYV%%}bvw$y?nFcpi!TUBK9Cf5(E}P=HPEmDBD*e&C4Ay9CwPMm1^qkc)bKbMfm5$DWJXm^QfULBSzozp?&3+4k_5&$*k}y4pi?_^hC);4OjJ5=3F^TsQX`wRPlH*-ARN?T#>~TpJmd=fT{g}NC7eH%YGm@p9!&_9mjH^BF}}<(d@NBz^s{J>MTu@7QkSU",
  "0cr@Lz&Ff6C5!tmf@m&!x9c{Z@{1e8a1lbh$~9l;giNgLkxlUJ7=?lQ)=UY&rXcuZSB`3zg7P8*ZccI`#H84}>1YtW15<-?VqiCHG}bp*c!gHRd=AA6y3SI+<*c~iWyDH)jmW%V!>!vdc@2AG7=~GW1#SIjiD0&p9~WSWa4wU>7iiNwcJhbXXdjxffv0)2_>O~_=7%m0jC|xi+(yQNk~I(WQtvfW1)KR?PMyH7CtrQMCd9~yHazG#g5yMT7BEsiI%$-?U!=LvPTMZAUyFUwv15p!@H1iHI79nd%!1WV6tn#^e@+?W2dT!HPO=F-c#P-}uoTog_Auj@BR89oB8hF6QrHP*?+zkQfYA0o_Rp18#*$?EOly9Y&efBK;<=!Fpn(1g`O-I#@X{=rqI@luWo&`wwC79|s0Wr7bk1wbD?3mB|8fpi|Lf>+_2^XwH4ksDR#EhAm&-}Zu)&Kl`xp~Yx^G2(;<NAzXKp)M<O_d-wS_cO&aUGtG7@1@0Dd|vYEI(;Lt%SgVEbC4Qh+zOtXx0}wLN<z6-xVz|2?V(?EwHwdMs)$im1iz*<c*yn1*{a$z(AKckKga#-&idv6%yJtSuS3T549;Ryq*Sc084@@`B-RDp(-;R0f8O;n*M}1igY7-OGmy;*=RyqJcpo8`QvtGEs8JaPVMGeC)<3n@uJwysmk*5n|6z%V_yC**_{2sxYikZT4K2FA|K@(V>AxAJ4wEvQ^z?j<E_CCe;Q=nv%l%QtRVO0|IMggix8^+kf{3HvdpkkOQlJ@W#OCktf1$gdI?zvl#Ie0cjI14)vd5",
  "Wf{psN^b<-&U$N`NUA%3U<~Pm*_j%4ac@Z}INKi_Q=1;#dg3M0KIyg30wMjbisaMAuPQTiS|}rp-`cpv1zS8`JIepkm5?9XD_em79tVk5GacwnmUL$|WH^^EuM8Q|YgB+J(%_{LF_mgNgnin{OxXi*s42VguaQzR)eEl&%a~r7i_koWRSVn3bXrhof6>z0@3Tg@HGniq1ZVxws*G-wTnpvp-JaHqTmf#P`6FOM6a-Dbv42`vj|Vs<TIi=B*Y?_#fA!y*w-3jgKEvFa&+2R;*myvwC0S4kbai#h;T-d3gy=SpCDGh!UC7DpO|k&^nLZI4pZjf}1JJ)UuT&n_NRH47;rtM($lJ^EpzDoJ5!`+mrHC1y<YDvY89@=^vtS_?lK{z-9M=(~Kf%-Ab84E~w=S911v?Czf_|d<dbdxH>$v-*%J)lkQeQBXW?S0JmNK72lpax0X8>$ZS#fdx_#pX7nK0CQZgQ?QC^Q<sBn2VEu-IL`pkvGI(JD0?UuIq95cn-H-l^gd8n2nT|1Jzfc1xQgMesU-iS4bPHoB56dL-u;fG;2!!&`oc5as5+s6SsB?zESm>K(fM;JuPIg4Baxh}a06As3-wW`@Y&AcJ?t59`!^Ex`-g!yP5eWBoko&DrYyIZ@MLzezBUf6)Um1OXT&OXj_iypcy2xffUd5w0OJ&Qn4bqmo!{;jJC|XivDcS)bM$*zNkLe2hr|51BS*2|>n=k>*1X-UZXNv}9%4eUuW%X%&7Kz&TsvBwGflt)ddD%y)e#U#YaVuWwhVM7O2+Id-eFCeD4Vy~e7&G3&dSDZqgK)-3S*6it{Ngm0;=O!wgZaj^0*ILO${;?|;It9)0F2RD!xQLF>SrcnaOEv<g&+3*p>q*|k2M)j4qZM}nMZFGSSguBYNj#5{i2Wx9#kp1+<VH()1;2vhZxfk5L+$jr&n8Wrec8YDiWKE^-qY$8?GW}5VtLk{0wBo8X`Ve$4Q9;TAl5Y;G)~c>$!f?jAjn_>zT-3O5O(Ok8A^",
  "n`xS)e@<(ydSr~<AJiduq`~<tJ7bq)gTe+Cdk(=8zNxZg)dW^NQsch*da(P_iYALX`ngv|b5;qKDa(FwRHwf*4PD1i{=E#l@pE3{)Umf0wCb8_N4I9yhk@G2{|yiZ$;a$G*+rdOGaiMk$t(iSp|?0gZ}&b=Zr4|!)8~mt1`nA|+^O{7^)`+GoutO=7a0kA%Pgw^>Q2g`++Fkc6Z3T>6Jd}D!D$K=I)%K8gg)0%QtC_bNy3Uh1j>MAXm^B%y91=qv17<@`CtTv2m@%K3HPKLAUVSu+pmK~0I1jGoM-?rl44xPtj<<39J62B-<xjwpFdJUo+g1*u7@={7_21_s&?{YIX_L21ur*~DIWO{GNe$KHjF1+$wI=1qQQtqOb9nCaM?UeoK}u^4V%@yhs-7iwQ@+m_$sWbM0BChD|#7Ln<BthkLInn*nsFlK@V%gWeu(u&bjJN(qjd9z`5Yygm0$l7TBsl*<x5C4m>P!6~)cOb>M@32A`06wa3XW-NG5G2;irly{T)P{C%doLt<g?IiV;*kF11Ao<EC$ISE7fCgF!3B4=w!KNAK%5ys9|QEzRvten_`$p2+hM|*9|;&UAr#|v_P1!Ve!bskxCeDkYl)<3KEkk+&yK^z#<v+0*~O^#dX9MdeYqwGp^IUbrzYn}Bln+jU{woj98OWD6aA{ADIP<ec~g&rx&O}$A$S=F4*jfch?f@-7Gn=ahf8im3NSA!BC2uVKIf-L$f1BsN?zSpH!ird|Dz&50WKu|*S$GC(BBMZ$!RmyD6bc!?{Kl=&|nroYB+gnug)g88h-#{Tk@scENxA%N`IaD9B<+~OV&(uUt!P)ea`iM8n*2_@dJqk1CtPPzzviN%J2KOeQY*R&|mdS6Pd_W3t$G<^=E_*5e3w}&d45)?}3t<XA0wZY)ND_89L)O=MD4QBJc`1$fT8&*9Es=JAyqg{z!zgUk!ICZ!Nz;l5@e9zv3T({>(C>8",
  "O0H37a9{^dthv4Q$H<PVw}ZxEUBKT@=S#5YP~#x@EI8Cgmj<2O$CJHf=R?SCzK%7SY}L8S+y-f{vy4C!k~-<W!+9_o3g5+WZ_$4bBkq6x<i~5OW*ijEsnK7JB6!PcD;eQJzk<n9VFM>yX)w4x5yD5L!ek_|V3~taCgKPn0F$_G1uSIyx)hc0lnkvY<u74WKzHCcm_<zXyF4LykS^9x4X&et0R$99$EQXY0XtJt36WHI76^5F`RpIVM(lO^M__`3guAUPuHX<JaVeCUz21mValfsYLl8|-mE@H8wh`aKLO|YbMn#XJrJ@MnD0F74j5Q}9*9){^>SG*(5v0(6{2DB)TT{r@f@jscjKl982WdzSBGP$1JuIVobZZwl83qzhGbH6@=tI80+eo2n@xHiyFUf*&!b=m|GJPkf1ZLn1s|?R#z>Pm`N$zdes)IPd;1N+{ejEIPLF1+8V#n3))L1W)vvFIDs6lQjxp=?fSlRI1rtAWX0vPn?O5oM&!X||cUz&AoPxnz_X+SD$j?l%t{MhmI@22$yt&ipm09b80-Su-qp_&W{x=)g<?8d}DVBYS48^c^U;f))s>b`15@P<|5iLGx5Wereb;nQe-9n|+Bx`APZ+UU8$t4{`*^1jAH@V}5PrYM}FVt{e+#~~-*Nkx5~i4pUH#XqE+VKZ>UD`3)vW2mAPAJEzvA2_It9)?8xV!rOwoA?q)D20*t6E)#1PWC>j71=W6UE4cRqkQ-9hieJ3XyK@o4&AYP#;j`u;1fS*l*rEl)~}h0;3AvewK-oca%c3*d<y#F6VD{bXcb|>4He%^_innW+Sg>|icBgCU!%kW&}__-$)jWKaqn>w&oxThJRH3eGT$wqlovetYF+318Q;e*mJb>L@6IC-BU#})jI?U$Y9UoZ2Ig<`#`)L|TyjG7gF2_R<_o%q8De&IcL|OeTh-uzm%fdRpeXx0CAl;8%MI8UhUOpS>SiD<bOX;{am!cu_j&ExVMn!u@6G&}yiNeRb&0M{`1eG-l9-5&&zK_Btbbqmvl*v0iu=WfFH(X}w~hKA=&60iPs~tnlElEi>vrw?as(Q1g-SXqnY*7l*Fz*Va_>iImFAKzfQ$`A8~"
]
""")

# -- Helpers --
import difflib as _difflib
import random as _random
import textwrap as _tw

_LINE_WIDTH = 70


def _norm_answer(s):
    # Fold away the differences that should not matter when matching a typed
    # answer against an option: surrounding whitespace, internal run-length,
    # letter case, and a trailing period.
    return " ".join(s.strip().lower().split()).strip(" .")


def _best_match(raw, options, cutoff=0.82):
    # Resolve a typed answer to one of `options`, forgiving tiny typos. Returns
    # the exact option string (so the caller can decrypt with the canonical
    # value), or None if nothing is close enough.
    norm = {}
    for opt in options:
        norm.setdefault(_norm_answer(opt), opt)
    key = _norm_answer(raw)
    if key in norm:
        return norm[key]
    close = _difflib.get_close_matches(key, list(norm.keys()), n=1, cutoff=cutoff)
    return norm[close[0]] if close else None


def _show_choices(options):
    print("  Choose one (type or paste the exact phrase -- small typos are ok):")
    for opt in options:
        for ln in _tw.wrap(opt, width=_LINE_WIDTH - 6,
                           initial_indent="    - ", subsequent_indent="      "):
            print(ln)

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "ring-buffer-rehearsal:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Ring Buffer Rehearsal; importable without a TTY."""

    slug = "ring-buffer-rehearsal"
    title = "Ring Buffer Rehearsal"
    description = 'Trace a capacity-8 circular buffer (ring buffer) by hand through a sequence of push_back/pop_front operations, computing head_/size_/write-index using modulo arithmetic, the way ArrayDeque<T> in the deque-two-ways assignment works underneath.'

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def _options(self, index):
        """Shuffled display options (answer + distractors) for a choices item.

        Order is deterministic per item so the correct answer is not always in
        the same position, but is stable across runs.
        """
        secret = _secret_for_item(index)
        opts = [secret["answer"]] + list((secret.get("wrong") or {}).keys())
        _random.Random(self.slug + ":" + str(index)).shuffle(opts)
        return opts

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation, canonical}.

        For a concept "choices" item the raw input is matched against the
        displayed options with small-typo tolerance, and `canonical` carries the
        exact answer string to decrypt with; for other items an exact match is
        required and `canonical` is the raw input.
        """
        secret = _secret_for_item(index)
        answer = secret["answer"]
        wrong = secret.get("wrong") or {}
        item = self.items()[index - 1]
        if item.get("choices"):
            matched = _best_match(raw, self._options(index))
            if matched is None:
                return {"correct": False, "feedback": None, "explanation": None, "canonical": raw}
            correct = matched == answer
            return {
                "correct": correct,
                "feedback": None if correct else wrong.get(matched),
                "explanation": secret.get("explanation", "") if correct else None,
                "canonical": answer if correct else matched,
            }
        correct = raw == answer
        return {
            "correct": correct,
            "feedback": None if correct else wrong.get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
            "canonical": raw,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(item, index, total):
    _hr()
    print(f"\n  Q{index:02}/{total:02}  {item['prompt']}")
    print()
    for line in item.get("code", "").splitlines():
        print(f"    {line}")
    print(f"\n  Hint: {item['hint']}")
    while True:
        raw = input("\n  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            print()
            for ln in _wrap(("Correct.  " if True else "") + result.get("explanation", "")):
                print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("  Think about each call separately and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
