#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/paradigm-lineup.json and re-run the generator.
"""Activity: Paradigm Lineup

Read short code snippets in several languages/styles and identify which programming paradigm each one exemplifies.
"""
import json, sys

# -- Crypto / obfuscation --
_KEY_A = "1d0052507418923bb2bfbb244532e4b71d33bd7558e5566f1fef56b65cd31cca"
_KEY_B = "8a2475e573ac06b49f926d49b5c1993f52db292e84fe96e5af136ab829ec48c9"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "80bda12a8878332b0c58315fa3179bbcb02a55580b20a917f98eb2977524de81df2b2eefe19d173735d5a0472b815889ef393cba0019ba"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "int total = 0;\nfor (int i = 0; i < n; i++) {\n    total += arr[i];\n}",
    "hint": "Look at what changes over time. Is there a variable being mutated in a specific sequence of steps?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "# Python\ndoubled = list(map(lambda x: x * 2, numbers))\nevens = list(filter(lambda x: x % 2 == 0, doubled))",
    "hint": "Does 'numbers' ever get modified? Are new values built by composing small, pure transformations?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "-- SQL\nSELECT name, age FROM students WHERE age >= 18 ORDER BY name;",
    "hint": "Does this say HOW to scan the table, or just WHAT rows and columns you want back?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "class BankAccount {\npublic:\n    void deposit(double amt) { balance_ += amt; }\n    double balance() const { return balance_; }\nprivate:\n    double balance_ = 0.0;\n};",
    "hint": "Is data bundled together with the operations that are allowed to touch it, with direct access restricted?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "% Prolog-style facts and rule\nparent(alice, bob).\nparent(bob, carol).\ngrandparent(X, Z) :- parent(X, Y), parent(Y, Z).",
    "hint": "Is this a sequence of commands to execute, or a set of facts and logical relationships the engine searches over?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "class Shape {\npublic:\n    virtual double area() const = 0;\n};\nclass Circle : public Shape {\npublic:\n    double area() const override { return 3.14159 * r_ * r_; }\nprivate:\n    double r_;\n};",
    "hint": "A base type declares a method with no single fixed behavior, and a derived type supplies its own version -- what OOP pillar is that?"
  },
  {
    "prompt": "Which paradigm does this snippet exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "for (int i = 0; i < n - 1; i++) {\n    for (int j = 0; j < n - i - 1; j++) {\n        if (arr[j] > arr[j + 1]) {\n            int tmp = arr[j];\n            arr[j] = arr[j + 1];\n            arr[j + 1] = tmp;\n        }\n    }\n}",
    "hint": "How many places does this code directly overwrite memory in place, and does the order of the nested loops matter?"
  },
  {
    "prompt": "C++ as a language supports writing code in several of these styles. Which best describes C++? Type exactly one of: imperative only / imperative and object-oriented / imperative, object-oriented, and functional / all four",
    "code": "// no single snippet -- consider the language as a whole\n// C++ supports: raw loops and mutation, classes with virtual methods,\n// and lambdas / std::function / algorithms like std::transform.",
    "hint": "C++ has for-loops (imperative), classes with virtual dispatch (object-oriented), and lambdas plus <algorithm> (functional-flavored). Does it have a native query-style declarative subsystem built into the core language?"
  },
  {
    "prompt": "Consider the bubble-sort snippet from an earlier question. It could be rewritten using std::sort(arr.begin(), arr.end()) instead. Which paradigm does THAT single-line replacement best exemplify? Type exactly one of: imperative / object-oriented / functional / declarative",
    "code": "std::sort(arr.begin(), arr.end());",
    "hint": "Does this line specify swaps, comparisons, and loop bounds -- or does it just say what end result is wanted (a sorted range) and let the library pick the algorithm?"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "Qq}D9pR;k>GAa~P&-Z3PCaq2_hQ&_<*Npp#s3fP^0f22HYV^=>=oK)rjFc8t-zLD)`jv>BrBeWI7kb&V>swP8?GlO%8iFsQkl#fo@$OtBN$f!H(U|jRb8*Y277UqqU*AzTzuCfQ!Zw5jw+z86uc|1>l?h$Kj}?z=a^sE8`Vym53Z?;$cWi4o;8Xcu!wK-&#u&ia5D!=%!Uh(Ks@gGyT(+GUH(uZFLZ#~%nOo8c%d?~aWzwt3wtzh3$}>>ud@U=<!K6q#m-vvOxKjLS6Q>b4Ut`C5H!Qcs7U#1*yL^~_Q`@Q$!I1q)d*xkKhL@9Uvoej3a9N<c*lQ7w3rB&w>?<QrGqyna2*Car7yH@MAVSz))Bc-Z?{&oqC4ebHdM|oI1=}E6b3k0^`Qe7Upkk^n?6NKcI)|9zoHtwnB&jdd`J$?s9EGb1cFN!5eLh5NC3BPZ<xVl8AMscWIIPrk7gfV%G`eZrS<=`ilg(^zj>=L4DFySRsA8*_Rh4LjY=sh`ru@l-$=O<sxw)#F`EgiU%%Jf-(@lSm$Kh)7Z^A$#h+of-s<cPDpjYsN=7NbwC-sY(`2-0(a7lrEC(braFbF~gGJEy6QXy+*x5L$SLj",
  "8_UjxFj|)I^K%e$j_cRn(L({#;gmwA5~j5~`)`TU;x}$cffZs~>11V}2cEe&<8bfX4)ltSgO#I$I(u%BF)iSl)?2yZwea0Hos?AT6wIV){Bb?%hg@xq)%z)=NTQbUzunN@AcN{HCT?qzM`7N0@%<*ob;9k~ns`s4%y2&u96)}L?d|l&y?%-}zasp~NFNcV6MLK4TM3&xr+I&hjum_8TEhlW0%(nk8F6%)t=r%=R!I-h*s&z%fBRotL{xi!M!Ux+n!x{>GjYHh`K!ToAU=%H={n>-KObXasTbmKq(`8I6i3#)aq6v%(z7cqD?>-yP-{$%o@?@?k#wBmjMNQ#Eu~Sx!6+|A{qfCHhDDmId-o}3RRQ=1{iY<A2NGtDV~g_fmlOLAE~_gADVhL?g2!!D`qABAs{tjAj%ZIfDb(Uuv68Ly8FURXB8}FT1`u&yvbs1(0Ki_HDX8cZ83p?BYSW2ebEPopl!Rc3oXqQYujPO)#Gb+C*`nDR7;{#E%na2zrUUjhEpzJ%$1kLeK9O~3s5l5R^IOKlu5d<Fd=kA=&rr~XPQGerOrrs4`yLliul@(Ltnp)j%71ozJc(x2BD%FEy6ID{6gb;z5u9xOPek^3Hd0#HW1~$Uvm^",
  "(B?+0+Ozs#ZSl9udcJ*WA0|h8#^+>|URJg5uZq0UNbSlSeKH*doWD*t)_hmk+#)ClgRvZ(*{*J~AFpHr^>iDm9AVwPX5Gi@lVrUhy}#9)93tW9lEo%q37?wx`H_sI@rB3*T;$=ih9Qp)YhVUNe-7EPz)T0+tg$~`F3>AgYzTR-*GbJ1&w-3UwSYDq#fS$M{w*+N5ZKb5TRKXVUi^c0z)Ba}h4%>$bWl!_#YvRO<d%+|CyXd7h5)?7GdkMpfzDjRHM?1}xw8=R=9=GP3jO~;QUcy-)CDa4rn&GSe<xb!EhBCW!OU7>g56KL<RpLh=>QXQMU0hK<TFR>CcZ|v9(i|Bw}_LJv?t-3l6_Z-bgQHq8`gsg3iB?;Aib}sAytd2KRzR8V7(ah2t-8nq9r#lne!&tn?i9_={l}q*Ucdu?J1OuP#A%xldoKvAlY@kI8jH#0sK$gum1#)9fyCF@&R+gV&$e6$xY%|jNpxlMrNmFRs93F6Cj}-@07K+&TRhSP2|K>9314h9RMqtpU;&H4~;WhG=a@>=6u!XK{nQP?K2GnxAr~FPe6-bwIH>q(2dq0wfTWDC^iV@w9%A526;Z5{Y8WPF<|0XWk$gRRJ0=`@&S}si;b9F",
  "q?dW0-Rg0(X^uXH8gorwe@FU!{_Rq6=NSN6y=kFfQA{Zx-L-vZDUXOx%Shi)vH4q8Ayh(HIhv1!W8l1?A9l^_YQn?^E;p{7O|Of8_lqb+NhVFgI~|&7=4n(u%Ja58=69(c#;Ub{{076Vd!>#!tg=B{P3DHrnb$vWONPHQWl4AaCIj#bcF`)SeF}q^r<C{&y@4X()Uo6bT+*q7?nv6By1`ef96Yb9w00Gy0CTHhL&*%EYSNe4E1ik<mjNJQoMLHP&dq>9lP_r_Ts43AZEYOsje9{^kXkyIA@`Su>L1YyCs&O72-F47J=00dq;8Q6w%-KzVw@*=a<v7oV7{#ho0^8jGNKY1vROayt?j6!e)^-++bw~gp4Ig`Pe8II^k>~awp`kCNNN?KTYI5mzhbGQC_Jgw0P#92?^<cBM3&oMwNNw-X^Kg=BICYoPkXDmoD}zpR8P@%$G{UPPL8d%=I>5|e^Pjq)ZY}!BNv-OtnT7w4BTLY4>@?UB$9QOX-{lJ$zYh(VbCk5{p1D780N5;&Lq`-8lUsnL!L(OnUEzsV1_ak&4=;tro&?wyKb``H`x@I`tW75+}Fs4uG=uCmi-g3BzMCLGSTQsV{^QIoG(&ueCk?3@v$wi0SoRN{%<%|B9+2w4JX*F>w3Q^)j-ny{Nu5MN%j~*7-O&bAjWSRp<Oys$L+7-l>iz6%-(Xvda^hctF-2@",
  "&t`MH^x!GY+UB9(yB!9>DAQy1C8ni0#HYy{Ehlytz66Q@(16U&ab(!kC<kotA5)-vm8L~2!Q~<ot)WrZx$VzPfx;M^<PXIdGS^umbST<b&@0jMy8nXtj+E!+$k|jeItOpX&k$}q7DB^GI!g`e(0`}X>L&qVu1ms7*u7aQ0@xDnGtQy{=s*Sq*(E}TbQH(DoNLlHb}-MwPQGmK-q2Y{gmj$g@zOV3HjsQLv)ot_SIM#+VEhC6uxmO-2LbFNuHyp+QL83cx@HV8vNq!x%+-J11txlcGb+r2-p1b<mebriYB*RRniz|Q5&!pX499aad@}EYXT=yYao|(liAU{<Wm10Cbadow7F+v~b+mC6;mt-k-gGWYgoY-7&QMFEeD8^TfI2@CHz*9nBp5p|n<!^Nz$^OAAIfQjZPq58Zd<H5C|7tfv4%2N?n4%26sB#d)HlSVF8)W3H<>!!aM3@dHL1*`pKVuIY^9Vfp+P&T$4P_gLl9;)t{K6a3FGE#?RN!kk?_GtX`0<R+TM2`6KEuPeP*m+d9h;A_Z3hNF>zrAW$#r80+7IE4wW^+Wv-x{!gB4=0OV2_o51jNNwKzM-kS",
  "#-qSP<H8D0K#`x4xJMobr~5lvt@bf;_DQ{CkdHKS=>v$DA^aHnxnsfV{o}MC@KZo}Sk;~j)H%1?v&ABgQ9A%Ql8UGi_me%xV|bPVclVqhSG%s<<a{cihxAUzvrb$v9+hg&d}K4Zh6?960*kcT<8YR_y3GI`+ohVf4Nu&tA32H!e3!_vt3-7YyFT=DX&+d?Q@YYMA1+0_QY^lnbY)m~(Vd?&(1#BM$)5u1zI^R5a|~5bTwER0CL6+3>ne)WxAE_P{u?YDwQr#O_w_S^+YAoCec(u``ToUod0<|$XFEy=+%fS)qD5Qmtt&O}*Ej1ZCx>V4E8MWxoqyjM5qKK#@nyB|gdlI)Z>Cqn)S~bqyZ8cSWxM+UUqvHVVD|S&mcbluWiV5WfZ2TD<p7FsNiy<CoA(aJ`UqI+2Z5Vsm&j@;nXH?>XkJU9%a=Q{T~CLT6Wrs`sK5PXwcbMa7iYxEq%qwQs|g+x28*A@9T18ftF?9*J}AO&;M8Oqj}4B&!a|<qm?jw{78_AV{&OE1S;<EDXfW>k5j;yg(0*TR*p@dTPV<58pP`}rpmy2X($_jQv_UOGzZWsj&gg1e9p{1qG%6sR(!;obgl$XtO|jsf=*X(}$SO`C4>le>or;LiBbQhqrm{`LdpAqbn@wHA){g",
  "<iI9l4@NJr5~|f?;Ar@SjwqT}yA2Uv2e$RE@u5dd@*bc>gxVNdrODSdHq#Ty1IeS?(}TF$;^=(ih#i0XdnGeph=x#Gg;uG59ohE5XtMmNJ3}Vv;PeLG9iE5m;T~>kyQd?kVnJ&?JxBX!bD-Q*>#BNu|F%0}ugs<k=m-e7jHqe11|#p`yFx|~S-L+2CC)hG_D<_mxCIS8FX0?WhRV7}dOdFwsq|+buJjIijLun(3lT9KNn+KPec_6xQ}j2H85uT$F2-pDZaVy$>W_gjq@Gbws#Zct@e~nv%q1*3G6F`OWN{g>()2J#vD$^6Cjg8@Go@&_@bTBLc0UodLo+CexD~}q_EAs4WqoHEa6!mCuigF+M74>NAKS~Yy394!A6v)cm_y@li<Gmyx?J{`Sj+d}<{RbY-!!wou&*B8`<=_GE`C<!RK`62iI|H<mfcWbLO+6O)dVB^Im!x6a@$Hzl^lp_sw?=MKg946W6En*@`;nAkg%v*NKU2#K%8DDD1%w<<m-}ctV9h@q}~+~C@87mnheWhbTlr})P^-<Zx1?z)H`bYYaVpOJ~tS~#mPyx3mOX|1@zUUeF%;<iCO06fZ1#|@3vj@HSJhP(#`iPAes>MKF+8X!}7MUBP25G^-2D5-fhXz&;n{u{{",
  "uGgFR*QZH~Sp^2~&D5f))1h}4h+t=3v!-%DLt%mL-XhO^smsF)yvoV0><55nv(uIQUsA1t>RI>qu;#i?2C{9cViv-!evf5>ZHi%nTxx@uTBgCp673~cA0aajjbMu<j&8%nrCSY<HPQgdrx{%Kdc|X^jA<F~R-JH3WFoK;*Fj{R<Gb=ePf^)TRD2WV2CyQ$0CF1jmDPLHDR?IUGMaL8@C!#i?CQ1&h^54%52J}Rf`(^^zCl?T&6a9O)5m7^m-RurZT&NzD>1&pWv4^cm;O(8O#)TLw|dYIy%@VYrl{?IKv9D&P24*YulNbB_ZGcAd4xnV)4IHExnn<aD0R>rX1m0jqgC-*g6zcvPVas-NNpR=<_SQ`+}itrX>|&67ZOXQXr)~3e)~95_e=^I6SOY?1pH)&=f^T}-?cLN$`TGj7BwX5re=8~OZLXwj9~qWBlXaoQaK}F{LLoiCy-C8(F3(ZRkLZem?{mv)!C!!9WSY@XfMEPg^7*hKTvg<^pfy{3W3{5J^Q@&i$DJ;<XbstnH=MOB;cV}&>>%JHBo7S&q$d$qyC<%noZ{-o}6v;EJ|9vaQzm^1!n)98MR9-WKw_|vQdT89V+mgB`g4U$Ni}*4a|EzCKnBhxwUK4%-1!z=*^$X>MHyFYR)qJMD6i&YwVp9T`uy!hVlF|{g~sGDxJcnV`#n;c0Jn+)b+2~sue;XW5l`HMqt8bB;e`Fl0Ff5F<&qRWzM;2sNKi=fN<oNlhQdVN!3YnbIJ`^AT<@rKaN?AA*p$R",
  "6)Fg;x_%(ga?xlY_?rs-J{9dFt9CT8&F0GPZ+Bril}|gmq9@8pB~=iP$()MYcC*QI7&g|5!3hv$-2aI5LAVB|J;jX;5}YTEHVHQ>KghYV&o4SSm8N&!Kx4g>d*M~qKk*${_I%8G0|%ZT4`=p|=51<Dc^@T^X`D;z#mKy2?qtxc{r@B7-+GEVaMvjt#6q6Bgt|CTkiDt->iPSyTj%MxeuPwCksUA2-La}Eihc)eLy`>pfJ>a=?gxR#oi4KvB7@DkQ!y%U!DitN&JJc>P6E?LZRv}rQKRldiTL**EvHl?qrN%O9D5rz->JE2T`}PLPGdhrM|$|$41#|^+ypD8iyAFHB2##W=$IqUH)^^RdS|EVsaZn#Xxz|Uh|6brg>37WvK|Hh^W#_zf6%Kv|7MQgYit}iHa`ha|J$5&K=xt<OH64hIS-S=lncZ~oNC!Pv)xAX^SeLF`u$c~MaRqM(CUv@mC}{d8~G;0`+Pg|P6)<jDE@$(4MdKhr##2SNx(CaWi!CoH;L6Sqc;35zgM>m2-C%%T|H=f#9-#S;Y^t{L`2FQmPNzUYInQ|78%|g_<7Lo9t1~6x*UjH)~NiP_VScb?f<6WB<HnDyD&#mmqK}DQyiuH%GjilpLuEr8KY{|+~(UYv@%Zs>PNLx0V_YPA5=!%nr(ZSZuh{t*d3piBbdlERR1y>KLDmDfO^6gAiPRV_C*kd$gvQ}5AUK{*C7&-X4(m<nfma}nnYPmLLKD;vKv}z)J%Rj_d;m@AOqZ^blZsgWVdIUuqwGVyYOImK`vP"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "paradigm-lineup:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Activity: Paradigm Lineup; importable without a TTY."""

    slug = "paradigm-lineup"
    title = "Activity: Paradigm Lineup"
    description = 'Read short code snippets in several languages/styles and identify which programming paradigm each one exemplifies.'

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation}."""
        secret = _secret_for_item(index)
        correct = raw == secret["answer"]
        return {
            "correct": correct,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(item, index, total):
    _hr()
    print(f"\n  Q{index:02}/{total:02}  {item['prompt']}")
    print()
    for line in item.get("code", "").splitlines():
        print(f"    {line}")
    print(f"\n  Hint: {item['hint']}")
    while True:
        raw = input("\n  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            print()
            for ln in _wrap(("Correct.  " if True else "") + result.get("explanation", "")):
                print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("  Think about each call separately and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
