#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/typevar-tracer.json and re-run the generator.
"""Activity: TypeVar Tracer

Seven short Python programs that make runtime-observable exactly what type annotations do and do not do: printing a function's __annotations__ dict, an annotated int parameter actually holding a str at runtime with no coercion or complaint, a TypeVar-generic function returning its input's own type for both int and str calls, isinstance checked against a 3.10+ union written with |, get_type_hints resolving a forward-referenced annotation, and the mutable-default-argument trap observed directly through two calls sharing one growing list. Every output is deterministic on CPython 3.10+.
"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "4cb72bfaeaec7e847cb7054c982cc6d3c33257c978165e3a517521afb34d5ae5"
_KEY_B = "23389f4366a0db39d278b7ba785bd11713cb509db9442ed0ea3e8db62204dbff"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "57b87093652f1c238219613f989aeb3f8de6523a837920d8fe54087d554170fb60eadd7b79b097617876f95d2d363e1e94187134af6c6cf82d09"

# -- Public snippets and encrypted answer/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "__annotations__ -- annotations are stored as plain, inspectable data",
    "code": "def scale(value: int, factor: float = 1.0) -> float:\n    return value * factor\n\nprint(scale.__annotations__)\n",
    "prompt": "Every annotation written in a function's signature -- each parameter's, and the return type after -> -- is stored on the function object itself, as an ordinary dict, accessible as __annotations__. Nothing about this dict is used to restrict what scale can actually be called with; it exists purely as inspectable metadata. What does this print (the dict's exact key order matches the signature's left-to-right order, return type last)?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 2,
    "title": "an annotated int parameter holding a str at runtime -- no coercion, no error",
    "code": "def label(count: int) -> str:\n    return f\"count is {count!r}, actual type is {type(count).__name__}\"\n\nprint(label(5))\nprint(label(\"five\"))\n",
    "prompt": "count is annotated int, but label(\"five\") passes a str directly. Python's interpreter performs no coercion and no check based on the annotation -- count simply becomes whatever was actually passed, unchanged. type(count).__name__ reports count's real, live runtime type in each call. What do the two print statements show, as two separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 3,
    "title": "TypeVar preserves input type as output type -- for int and for str, with one shared function",
    "code": "from typing import TypeVar\n\nT = TypeVar(\"T\")\n\ndef identity(value: T) -> T:\n    return value\n\nx = identity(42)\ny = identity(\"hello\")\nprint(type(x).__name__, type(y).__name__)\n",
    "prompt": "identity uses a single TypeVar T for both its parameter and return type, the Python analogue of a C++ template<typename T> T identity(T value). Both calls run the exact same shared function body (return value, unchanged); nothing about T causes any specialization or branching at runtime. What does this print, as two space-separated names?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 4,
    "title": "isinstance against a 3.10+ union written with | -- matches any listed type",
    "code": "def describe(value: int | str) -> str:\n    if isinstance(value, int | str):\n        return \"matched\"\n    return \"no match\"\n\nprint(describe(5))\nprint(describe(\"hi\"))\nprint(describe(5.0))\n",
    "prompt": "int | str, Python 3.10+'s union syntax, can be used directly as isinstance's second argument, exactly like the older tuple form isinstance(value, (int, str)) -- it matches if value is an instance of EITHER listed type. describe(5.0) passes a float, which is neither int nor str. What do the three print statements show, as three separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 5,
    "title": "get_type_hints resolves annotations, including ones written as strings",
    "code": "from typing import get_type_hints\n\ndef area(width: \"int\", height: \"int\") -> \"int\":\n    return width * height\n\nprint(area.__annotations__)\nprint(get_type_hints(area))\n",
    "prompt": "width, height, and the return type are all written as STRING literals here (\"int\", in quotes) -- a valid, if unusual, way to write an annotation, common when a type needs to be referenced before it is fully defined. __annotations__ stores exactly what was written: the raw strings. get_type_hints(area), by contrast, actively RESOLVES each string into the real type object it names, returning a dict of actual types, not strings. What do the two print statements show, as two separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 6,
    "title": "the mutable-default-argument trap, observed directly -- two calls share one growing list",
    "code": "def add_tag(tag: str, tags: list[str] = []) -> list[str]:\n    tags.append(tag)\n    return tags\n\nfirst_call = add_tag(\"alpha\")\nsecond_call = add_tag(\"beta\")\nprint(first_call)\nprint(second_call)\nprint(first_call is second_call)\n",
    "prompt": "tags's default value, the list [], is built exactly once, at function-DEFINITION time -- every call that omits tags reuses that one same list object. Neither add_tag(\"alpha\") nor add_tag(\"beta\") passes tags explicitly, so both mutate the same shared default list. is checks whether two names refer to the literal same object in memory, not just equal-looking contents. What do the three print statements show, as three separate lines?",
    "platform_note": "any platform, CPython 3.10+"
  },
  {
    "id": 7,
    "title": "a second TypeVar-generic function, this time returning a container of the input's element type",
    "code": "from typing import TypeVar\n\nT = TypeVar(\"T\")\n\ndef duplicate(value: T) -> list[T]:\n    return [value, value]\n\nints = duplicate(3)\nstrs = duplicate(\"z\")\nprint(ints, type(ints[0]).__name__)\nprint(strs, type(strs[0]).__name__)\n",
    "prompt": "duplicate again uses one TypeVar T, this time to say 'whatever type comes in becomes the ELEMENT type of the list that goes out' -- list[T], not T itself, as the return annotation. Like every earlier TypeVar example, this changes nothing about what actually runs: [value, value] builds a two-element list from the same object twice, regardless of T. What do the two print statements show, as two separate lines (list repr, then a space, then the element type name)?",
    "platform_note": "any platform, CPython 3.10+"
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "ZhYal;C<l|e~+qFadZ||$SjV9KjmpfZnjbL!UnKnp6M1B>ZCfbP5M8*P&E}yTs&X@&ya^*hw0f3N|2Yvf9L=Vy~uNGD5i!efZ2kCrt~b4ca_wIK$hb+E>%sgC1x7h0uB!z5;-xk;R+f1Cz-a`prHQ_Iw^%;Y~?^!WK7OWO{>-{iOyjyf-5Xy_J(3kW4FF&xnT-3hgICO$F)B@>(3a0U&J#QKRrghT;Rf~)=`Fcw{<mnWr_nfI8^SXX!=cAZAa2=rz^GfPIHehE+qTtj~lWaCu{Y!{!o*jP^D{&hx-F%e?)5vwp*IKi|#uGTlm@bE^_Pn9X@)OZDc@HqN*#76q0eW;A?A8$}Mmn`FM0%bfKELD;V@yzyWAlSCTQ{pU}`|t21wF<{csXb1B;*=)mm&3pLv)gD#JpVOH^gAg4Km)8Jx~v)7T!0nsmX;^Z%d^;P<tXl(lMQ=j<g#%fNx->MrdHJJdC4*)7+#}{G!MBC!xIVR@M5hyq|UK)fKYrv+i&$t#`Tko_Nw=Hy2LyJ#5P@87tuTmTWB0VSe$Mt|{p&teyHXrzn83*h6ooV*HFVLCuypwg45x|%9=*wGPEZ1%Mp00hOk_DFmze72+dJag=w0OgLT#?|wo%?TS6ZsH6kqqCvgN70mG0e;fLsXt?!bP=X)|H+oL2~3tc@T>Ln(292b!sJHgY5)8Rs9o*m71OA^ieog{ZS@5q<qj8@6OC4b7$<Cd#h|gjW{(k%$b5d8#wre&T2##N;Ufk=pah?dWI`E2Fyt-%fWm%C>FCatx!_&IhU|--rAEYp-me-wzZV<_}?b?9T52Qw^ox>4QD-<{RY+67oZZo9_JxbwD~|wK6eYT9dmiJFeF^BRC^p^402B+M5HbXUGd{fQAM&;QcA3w+BiSWm>Y(eN>y!g@dlC~=4r}rUO#)mu(ybmi>cxwyb~iD9bo=X>}%&c6<{+p)~KVDPMvqIOqEQ4C;<WMERQ?e#4na{{_{msBg#r0Qy*N1aLaUrH$A0x+>dqNNc?=@9592-1Of0%s7s(X3Xqm_WzPM+({>q*;VriEZ!^s@=EnK9-3NG)wE6moQg$AkZUB*mBF65ccqvDCZ#hs+EOiub9F1hj@b6Zc`vNbdeQPF<Q0`8{A|?vo=EpW+T@s4=;THxOrq5KtaL_q3eULWOxd33fxBfShNLMd;ZE}FX--Wj(Tl&}Zusm4OPNCv|s!nuulH%cQCkG}AHIBvd6&f?*;aC",
  "7zB;fyD603ds%V*$vmNBPj<1WH{6)|(&cbvxhlKfYMm8|Q2zZyxtaIT*ON-nEQZ-<0sVm>o=97#*X&x@=^4OauJ<BvRDS9rg>f@f3`C>QAXa|^2n51sAzwJcrppN@!A)l9y`xEo#cZX2#<h^lE02>I_QV|%W0?fR%AXgsBH&Egq?wbPkD=n1)^fYtm`TFgK(xb%5z6LATvlFZ#0+C=2uJ*L(uTWW$sWd{p7*o>LS;O&B9#qEKM8Lzjgx8Y=hQ#W&MN0Cr%JkIcES$MmEJ4{hCLQv@Y*chRyfx<)wQ9ZSb)G#0b#L65X_sx3hO4__uY4}Tdkn^c)t#vd5d1PP?qIPK)U{MOzPZ=Oxu&<Zhy9+H;Ke|m*|s0Hgg0WO}w2SSqkrb7q;<VJ{Ap0$~>yy$OFVM48^MeRJE1ey{9?h&2;q&%~blDeVZWj6u1RG2=3b)IUL<RwrDX<R!S6|Uo44V3P4?-YThC{U>fLp1CZWhCsA+6rF+BnZQw17kSXXI-LstoQchve91C{ox%^$#{qg1a)h<*1N)zNri&Mkfo*iR*VDHm18>#U7)JA<Cmb9<p{t{?0w4^!ru7mkV8l6A*=z0@tU|IMZainv5Os3P30^gzrY&&I)d20}8hlpdRPJe_(Kwn)boX1OB-K!>C@>j9f)j-&>1Q({pSXtz+#q<1?t@C`ucU!mj1*4y1Be%~1DiCvV#0RTc05w+mxL6fxL{rf6>l9m9I*3arrpo+?N~G8)r<@>6UM6xAyOMFP^JMV*ZQ29tg8hOs{ZM+y;avi!l~EoN76T-51rbuMG)i!!Otc*^V)JSQUAnQxIS32tj*Sw6L6&cOV@`7)#C5lG%|ZKyd`GS-q2DqkX(|jbj{Pbf+^l>O{Wp!FipyUj7xFMCqk09^KSKUQz*Yz0c&Ft?<uJC@G0ZsD`{-%XYZ5(&HcSiOreYudGQwx8Wlr`EVKFG8C(Z=Rq3^dqZv!Xda!=dnIYMNqv%z3Uw|Nm_aNb-DY2e@-4&`DsG<x8NBHAbhW8pL?LI@0N4gIo@uPL4x",
  "LN5^K%(&9z@J3b9Sy1&UDtN6bqf>>oOxW10s<TH<Iib%ot42Kc<?E!$$YKM%!@|~Uvf%ij73%4>KqGC`v(p(BaKu)@u7O<lM=!5+?r!G#TX+n~V-R#W%8V!-Sr>sxaEEAD|77mJ9=03kM^Dd9rJzRYOs8D<G5dFtllQV%aHlp+dI%E5b6GWZk|AFeVb)DYn?}PU`%^6Isw4|#1qH0%lfNyU4wGk)X(B;u;#QauD1v1)y_vA-{zdStmWxYRutzqk&Ykh&0wnLtSSjgM?jgwnjX7;u`IyWaSUmiMj;y=vR8pq`B-W3vu8a9<A!r8q&bBgaM(Dh!qAJFxNy0{g*c1Utue$oG*^MJ`PWf6Q0e%jzGt4ID{m{&$uCAmV_v9!-0Js^m*dAFa($Q=h5tVCTbkaB9#%kI4N=^2RT-$J!hP`GfWoa8PfhTOm6S`CNu@G3^9XdoB$gTvhC}<C~W-?RE5!A0nw(g7B;enY11x_^er>LBw)2j7OQh%)2hJt}p0m-pxKL^1JR%@r#i0C4x3K=i=AD<Gwe4duQ2|Qlcnov5jTMAlwEV-xutjekGRe_Vk>H@YN((DYo6uWQ9u-xU^bMnm=!jQj#8-n5M0{0awQ-!+n6=2eMf{`P-!n)=6&G&4ei0F0CLqicYV+QeJ<cHo;4{|(2gL4ePFJ0*@0RCfjzMkbJ6U#35K7=7^eFxd=%fM?0Hjnaz33=TUE*GvRU?@w!UBpcRSBcLZ*73hQ+IAHQf+hDFw2ZJSrq&ThOc7!f$hTevP;pQnWt2Y48xQHKOSM9wIWid$k4=->74kvburuk*is&EdVFk->3NxV-e@bUbLxXK;ycXt1sOhU?FB30_8(^SLY?g456?7|knf}=CMV;Gk>b~^_9uu0xlEFcqAIfTK^BpidAT9(u3wjBP3Xl~j@5k7k{InEc3hC5uAQ)_14WY{^zfG}#1@ZfH&Bv{72k@b=+R>S0J?c<ZO?wG9c1Mk)tSH>2PnF@X$Q8pLw!9#<Gw`#LOR}w$mR7c#cCdgAlev#Gc$4{)_r?kg3hi3|51VIE!~#L$*Vp31P7Q&7nA;v5brQ^%Mf&irbhWW>o%Du%+aBZ*PkX4>j;{yNT2i*1-twFAPQ#So2EadE86f",
  "4^Pm3Qh~svq>x>nvvbVYQPbQ&cXH8u%hyYN%d$V?UaXUo4)oxXLae7gNp!IkuNoD3CQvQ<K|w7C!=NqY`Qlo{TP?tN=;_HrQsXIQpJpDk{l*l`Bk>CVHGPpfqW`*^t!&hM%tb2kWI1AkjYZANQhIB(A)lgs(6s+}A}Ys^xyH^V)=-k(pz}@vB5HBQH+LaHpJu30ilv4W{P(AxGBrU)he!?_W}Y575=@pXX)i@UK$v3!g@NeH({enpDZizs`rR6B*_LKGye^7VMdgc5hMAC~0yy8(4^c!q1H|$OVrJ}h@skY<qzK}Tb<@b34I)kpzKXICXmOnM2lTdD6HS=Ms%um~YR8cADJS=GW07prDK9+}IQ~is<}=mscm+O)@5fOga^x&=Cc5mgy@~Duk^prLHBo_U*zVevU1X5L7dm()hH8DP#N6MAZFPDicxCJp;^21zS%sO+(jBuOlEUHo#`oL^TYKCR`sJEO=2q`I&Q8gq{<J5|Hh$4L8L<yiK5Ks;N?hxZ#NXKRx`#p$@+ZI2#uI^G#+yKQ5HS__`rRPb&_Xmx2Nj(O524n>N-^JDg)JWeyr7&@o~N^t0LM6^O|(2ouu`y*jmM+W4%mPZsK$^D8g0uD6&12%@6$XxFZFJb+!4+C?8U8lKWIN0Hb7D*O(F)mnpky}*Z@4dEl7A<Dhmy(*Hi9`PTcDBywYB)z%ae~(r_9~g|+sfeNnl~sP6ddI%u^p`$rNq3zQ{<tN-q2(PMrs`)7k{XkL&#LSXgu`nYmz7+TQ@uUn-K^F*MDx*6ij;r7Tl*X`VDOqAZ^sx4tWpf0bcK3#6iYL23n$iUGoW|=cu1R*HE7~0(sycCJ@Y}uM5gn;If`)`fUqm+B<XQ=WhJMhzxfh?)BT3c`_m}m8nE4f6y^o9}RL?`-CHKpoba|&C!L*(Bj?3CEe>FRAIrAe#>n?m=0pfgiffhS?aYQJ37VBKCV`V8#h3vybl8DI!jA&QzM>ST=%-e*cJ&^_!9iF}tZplsZd@41*J9}w8v_u(vcKVc_>`*6z}53sRw&4r??X-QcaXGGMUl9yzgRk1VJa?${9C2>4LItPRPI$gFxE@InXd3wLkX)hc#Q=vN+WHBHi4QCdc9%mry_oOF7@g&ZzdYk<Ke6ptU5CGcDGZZ8cP9D1&ZMIX_3?)%K{2;OAXg9jRsG<",
  "@u7Ps3PZa~cQH8i2Ni^lEPVs0z{|LlzcKQh3{wV*BuETx0GH3#xNBdSJ~ejaS$W6R@{>ZoDGW!AUA{gr*l}K&qcf@e0}=XsK&c!fEUk4j!;8uU>tb2JEYsizmNqw7;ym>L8!Gq~FJW~8vln;?mmdJh;3`?$p7|djooi)2D~4xuRiuQkGesogaus$v)x@Z<TXbl$!^tYy&#izcF7+ofi!d%K3|k(Rqk&U;l#X*q{|KJy2ZN2%A0qVV;@#E8*@t?Yr6YA|uRF2sfs|pZ<<EIkO_Vbn#Uo84f_2rA<JMTi;^>)-v}1@RjxztkL|yEJlx0mo&qZt@H3k*aeyJitkFHQ>9JXxldsa@fCUT&Yn#hKl#1|}omjU<*QbsyoJ)DQF!`35#);&2?C(@EOx+P%v4Zs`k)yV#U+^yJ|eN;gv(;$VQJ);GX=vE`DW3m;qBJQL3*;9;K2Ra*8vo%tR(=X8!$8Z$f-_4ufT0ist$11LTmSNQgiZJB$T{Sm#EK@y4cbG8a5O$~xC)JmR*-Eg$ORApYL!<<&<iyP$#ajhC{A#@XB%**P<B-Z^3m4{!RL9Z1_oTgY-r`SD02%$F_XNdwQBVPPCJ8t-L$0dPbn1mYrGUC{H&=bLId)PAbDD{LX~DiSW1bu2vVXk;CBZxo`#Soj)BT?a3scED6xtNp0|}TFL8S7)S<wzkGat}(t0Q8&3!)C$Y?6r8yj@@j$AgZCrOgjWS{{rgOj!ol0MWILyOkwctM1j(s#G$sAiCM4j}25+qW%-Z%?I<iqlhhI?lEmXh%%68U{}$1q`I%x6>&@lr<GL$A1p_RNv*h2#BbMU=g}IN)@;>sPx%m|LUv_!MNM<VllikQ9;F@w+`_R9Rzw5K>zN}eE-p}|ROitw95U-lV&~Gp-Ng30vR?U;Dit>Gx0s2pumBQaciC;x*Eo@tDbBnNvaBy90wlAKq@vclcZut-eF?8LYd`GQr*&X{S+ofT6mp8+ss6kDoY%bHw^D4|*kR1Z#@%>?5Ck$OBc2djspRlTl%8U;G=FO*)!^|*;vZ^u5+EXh%WN`uF2hhx0O!|3=LM{-7;`*6C1Z9#ki}uTN#5LX`|8v)BW~)LwVlFoleu@W4<QSTR(ZSQ83kbWyCR>wrvpACY$ai^U4yVhU|6i54!j^|MmOs;gu05hV!F)@b&1m;&TkJ9>#@CICQ(_T<gg6VA>akv?8o_>ov1!oEI4Rbl6|V-b_YGj<d<jUc`I%x?+x9zcCe&n#l_ng-e{mJYIrsxlkQ}2)SGEcc4=~(rR#~zn>DGgVhTNC1g<Bi;C<-",
  "3(F*Wa>G0Njl1hU@viI>dMxsV{M4~hYs@69#mAit;S<(V?YI$}z5ku0qY$Nsc+Sg293`$19+hT{Uy-BOc6E%)iRrPWkEk>e&evesuf}^7-hNRjUpw!^iTxIr;C>$63R;qF3n<GO<{&;l@hCb(_;HHUplEJS?NB%`4^)gu5r#-QZ;dVK<hStqwK;)k#G|d3`>EbvexVVQkZ4Rj@9hf=sOh+&Vz=~DW2IgR)H58ev7kem@y-^w8gctE<{QXu;x{wP<FB?xyA3V;z_RQoj@pO3tGR@s)e=>fXu{|6(fzi2;Xtxe-(j!Ix2(@Hv%I*kcZ9{F7<bhMGfEYf&YyOGv^GtX1~&!YpcHTwroYO^IoKNQG1C0cmEAUMWohg-C&{THdQVZ04(U?Ip1WCFF0g5V{`oti%wM2-qjfvS?A((`sum#HOs2}94DVna*_dI{<V3EXrwj7@o!kAn_Pgz9{=IniHD+Pi{2kdmeP56*GK9ji0FNpLQhuO~JqQ|Cpl{5*7~Kmk0pgT~uOkW2DnLL-M&z)io`rFl(++$W_#rKpRY(n~!BXVTGU7$2u(D2)C(I=)<ga#Zk8HX|C~Szx?B=;Xq$oeYWHTkbl2Y#LC2QLKx1=<ULo?$3jBzLHB{ju66<+o5Z`rXnPx<--sxW{<LrJPgl}({E@?q3}4g7+RrU>jbw;Nf&dQcdwXUl4`E@OmmsTONyI%~j{E}&fJ>zR>^xH3WHz~#ROQd39)1KmO?5Ce0e@^bP42Qpt>dkd{iAVBd>Uxl3BPjP9zR0>xuzE!SQY^saHrUrH#Vha_f6vA1CgXG34H;7n_W%nQdNfrfqwH!n+8Vqq#rbLv;j+Mx-oytOs!FY;c_FxiLMjD#%w-KgUxXOlI6%A>qyXQYZ#hJfsR90%%9E_{k0P4LzthmT>XB~ieSz&E*nUR7GdG%*GKy-z1%*1um=-&dxj#k~dX$=bPOrPY%%*z~Xo;O#&iIayg1^MtX$kvYGnoOQ(Ev`^oF)g!Gn$iW)7{WOgs^0<XRWlNMw9of?Z8zeq5)kP25wcpUo*2KxPmmKw#28D&fnT=o@2_nfxL&|Z#}pBgn*ww|xD1t#ZQ0Fw8JP{T6ohkeOAE}6?nC#dZog9j#Z>|u^@!$?HeG9nG^{5{m7;LLUFjcab=yk<+_KD_7V}^M6&*=h^*M?PfB",
  "ZSwD;pf~^i$vz!$)J>Z0ZAS7qu$(jb0sF4K7o=r(O@+6p)NxD+kY#A1GQ6tC7#h&a9I8S%Ud;~a(ZOGemxe|lO=R_OPgD3;s`QpaMW0*y5M04-^PFDl@i_wdQ$`bNwr@C)tbC4o^Q)*>Fu~?{q=cO5fS2V}VZM{Qm&D42o?$s(@e<oYJPd{%@5nCanOwzvDRMHqd4Xf9ycYb%?ng0fVOjIgS-a)CDtRfrgQ)bfEom!0Vm<fD*=~?)QWBv;b8cC15X*=ftlEr`d!+Po^9}BV9SV*P%b3=eHwt9RXl*ZU#(7(Haaz#r5yEE^aBi?$_LzC%dPy>OL6`K58dBEvXS0#!cYOjMKNN~C9j$fa7TaB!;v1|{-O%`7CET7>3uDu<$Upt7`mv_)p(&s);L0%IJYx^iS?v&MGm7u{MYKX#3}jNiKU+Y(y_l*YDmd96?zji148ar!yfT2M_0i<%zt=``r{ipkxW)XQp3gPpI~72AZ34Ak%-pr~te?@%c&w_fvcvD=XIB*t+wE03GHs2IKl2oG-ll~Gogeqmuis^kT>|B}bSBe<{~0c1Z$kcv_Jd%OarNEJA8pT<7}Z5UH$_f$*4H;DRp;(Yl*7lVG>f(vcu$MtK3Q>QCOL9Xr$b=pF}DD_OU$sll2i(Q?=;^*e-;|?>CQPJdvxGHdwn9e-UMz`?S%nz@a~T(SA4}u7%Q}E+ipauTi4s<dkszE&YtI@8(C`PVCk_1I`6{Xk?14WsV~OhY8pB>d|(B6Td7=K^;7(W`b9|RDDDZt`U%JJNpGlaBFw%ax{$6hz>@g(QS~HBGHN-k|L^XG?L?Ux|GYK$c!h(B!4u_c64)q~XJGZS7t<x|KFGh{;L#yqQTkoqAc8z>jKwGhF`Ax(qQek8_;_bZucc+Zzv_VJT)`OqTYQl%%BlDK#BXCroDN^O%L%t?(%(}I76$EyQh|diM=!rH*d3@Ybn(yo&!e~Y2NOw0Y3vYw<b|ySA11q6M6`{3oaCE)wNlj+zk$RDW%b2`={`4YyyL8+fA1wAZnwj6NLGf-2nv&;?Yi$R7^w)CZve(XaV_T0VxM4p!Qy9lI^CVTjvIsiX^q2oXBj_%ukRZ;(tDtHT+_qb|8}Q?barhRS_QzklW_nX|DF0fa47iW+=dY5)#STHUZuG{3>vwJL*H-!uY225i9mcWm!m^76+wdloShALP@$DkSQekAqxKgdDjNIM(A^RV`kxn4+4T;PR#jJ-f(odzfel>SF3ace-Qsk`AiC)YxOpbf*>={W#{"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _secret_for_item(index):
    secret = _open_secret(ITEM_SECRETS[index - 1], "typevar-tracer:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet data -- contact your instructor.")
        sys.exit(1)
    return secret


def _run_snippet(code, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.py")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([sys.executable, src], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return None, r.stderr
    return r.stdout.strip(), None


class ActivityEngine:
    """Core check/passphrase logic for Activity: TypeVar Tracer; importable without a TTY."""

    slug = "typevar-tracer"
    title = "Activity: TypeVar Tracer"
    description = "Seven short Python programs that make runtime-observable exactly what type annotations do and do not do: printing a function's __annotations__ dict, an annotated int parameter actually holding a str at runtime with no coercion or complaint, a TypeVar-generic function returning its input's own type for both int and str calls, isinstance checked against a 3.10+ union written with |, get_type_hints resolving a forward-referenced annotation, and the mutable-default-argument trap observed directly through two calls sharing one growing list. Every output is deterministic on CPython 3.10+."

    def __init__(self):
        self._actuals = None

    def items(self):
        """Return the public snippet dicts, in display order."""
        return SNIPPETS

    def run_all(self, tmpdir):
        """Run every snippet once with sys.executable; cache actual stdout per snippet id."""
        actuals = []
        for s in SNIPPETS:
            out, err = _run_snippet(s["code"], tmpdir, s["id"])
            if out is None:
                return None, s["id"], err
            actuals.append(out)
        self._actuals = actuals
        return actuals, None, None

    def check(self, index, raw):
        """Check a 1-based snippet's predicted output against its actual run-time output."""
        secret = _secret_for_item(index)
        actual = self._actuals[index - 1]
        correct = raw == actual
        return {
            "correct": correct,
            "actual": actual,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all predictions are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()


def _ask(s, index, total):
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    result = None
    while True:
        n_lines = ENGINE._actuals[index - 1].count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print(f"  Actual output: {result['actual']!r}   Type it exactly to continue.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    print(f"\n  Running snippets with {sys.executable}...", end=" ", flush=True)
    with __import__("tempfile").TemporaryDirectory(prefix="typevar-tracer-") as tmpdir:
        actuals, failed_id, err = ENGINE.run_all(tmpdir)
        if actuals is None:
            print(f"FAILED\nerror: snippet {failed_id} run-time error:\n{err}",
                  file=sys.stderr)
            sys.exit(1)
    print("done")

    answers = []
    items = ENGINE.items()
    for i, s in enumerate(items, 1):
        answers.append(_ask(s, i, len(items)))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
