#!/usr/bin/env python3
# Generated by scripts/generate_activities.py
# To update: edit quiz-data/os-mental-models.json and re-run the generator.
"""Activity: OS Mental Models

posix-file-tour, file-io-contracts, write-your-first-syscalls, and hex-dump all put you face to face with open/read/write/close -- but none of them stop to explain what an operating system actually IS, why your program cannot touch the disk directly, or what a syscall is a request TO. This activity is the missing conceptual opener for the row: eleven no-code questions building the mental model every other activity in Basic OS Theory quietly assumes.
"""
import json, sys


# -- Crypto / obfuscation --
_KEY_A = "83ffe3731a8b50cba009e6bf28948db4cde877e41eb2415e70256d6655e924dc"
_KEY_B = "26e176e95995b09f35091d2ab89ad47872f7651b90d3970bdee0a67410c7d805"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None
_BLOB = "e9d0f9d71518ae9cab0d680ac2c4e770c62ef141895bbab12ad085e297cc57add64e8ff9cc18fcfbcbddb698bee56ab4c9fe38d00971958621"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "prompt": "Before any syscall details: what IS an operating system, in the most general terms? Pick the best definition.",
    "hint": "Think about everything an OS does across every program running on your machine at once, not just files. It manages who gets the CPU, who gets memory, who gets the disk, and it stops one program from stepping on another."
  },
  {
    "prompt": "\"Kernel\" and \"operating system\" get used almost interchangeably in casual conversation, but they are not the same thing. Given the phrase \"Linux is technically a ___; Ubuntu is a ___,\" fill in the two blanks correctly.",
    "hint": "One of these two words names the privileged core program that directly talks to hardware. The other names a complete, installable product: that core program PLUS a shell, utilities, package managers, and libraries built around it."
  },
  {
    "prompt": "Your C++ program cannot write directly to the disk's hardware controller, even though the disk is sitting right there in the same machine. What actually stops it?",
    "hint": "This is not a permissions setting someone could turn off with a config file -- it is enforced by the CPU chip itself, at the hardware level, every single instruction."
  },
  {
    "prompt": "Which privilege mode does YOUR ordinary C++ program run in, and which mode does the kernel run in?",
    "hint": "Your compiled program's code -- the loop you wrote, the printf call -- executes in the LESS privileged of the two modes. The kernel is the only code trusted enough to run in the MORE privileged mode."
  },
  {
    "prompt": "In write-your-first-syscalls, you called open(), read(), write(), and close() directly. Each of those calls is, at the hardware level, a ___.",
    "hint": "It is the specific, controlled mechanism a user-mode program uses to ask the kernel to do privileged work on its behalf -- switching the CPU into kernel mode just long enough for the kernel to do that one job, then switching back."
  },
  {
    "prompt": "SHARING is one of the three core problems an operating system solves. State the problem: many programs need to run on one machine that has only one CPU (or a small, fixed number of CPU cores) and one disk. Who decides which program gets to use the CPU or disk at any given moment, and why does that decision need to be made by something outside the programs themselves?",
    "hint": "If every program just grabbed the CPU or disk whenever it wanted, with no referee, what would happen when two programs wanted the same resource at the same moment?"
  },
  {
    "prompt": "ISOLATION is the second core problem. When one of your own C++ programs segfaults (crashes from an invalid memory access), why does the rest of the machine -- your text editor, your music player, your terminal itself -- keep running unaffected?",
    "hint": "Think about what the OS gives each running program in terms of its own private view of memory, versus one giant shared pool every program could freely poke at."
  },
  {
    "prompt": "ABSTRACTION is the third core problem. You call open(\"data.txt\", ...) in your program; underneath, the kernel is doing something with disk blocks (fixed-size chunks of storage on the physical disk) and inode/filesystem structures you never see. Why does this abstraction matter -- what does it buy you that raw disk-block access would not?",
    "hint": "Think about running the exact same compiled program on a machine with a completely different disk, or a completely different filesystem. What would have to change about your program if it worked in raw disk blocks instead of \"open this file\"?"
  },
  {
    "prompt": "posix-file-tour introduced the fd table (a per-process list mapping small integer file descriptors to open files) that the kernel keeps for you. If you run the exact same compiled program twice at the same time (two separate runs), are they one process or two -- and what does that mean for their fd tables and memory?",
    "hint": "\"Process\" was defined earlier in this activity as a running program plus its own private memory and its own fd table. Running the same program twice means starting it twice."
  },
  {
    "prompt": "Two more OS jobs, one sentence each. SCHEDULING: the kernel decides which of many runnable processes gets the CPU next, and for how long, switching between them so fast it looks like everything runs at once. DRIVERS: pieces of kernel code, specific to one hardware device, that know how to actually operate that device. Given these definitions, which of the following is genuinely the operating system's job?",
    "hint": "Both scheduling (who gets the CPU, and when) and drivers (device-specific control code) are core kernel responsibilities -- neither is something an ordinary user-mode program does for itself."
  },
  {
    "prompt": "file-io-contracts covers errno (a variable the kernel sets to an error code when a syscall fails, e.g. ENOENT for \"no such file\"). Given everything this activity has covered about user mode, kernel mode, and syscalls: where does errno actually fit in that picture? What decides WHY a syscall failed, and where does your process actually SEE that reason?",
    "hint": "The failure happens on the privileged side of the syscall boundary, but your program -- back in user mode after the syscall returns -- needs some way to find out what went wrong. errno is that channel."
  }
]
""")
ITEM_SECRETS = json.loads(r"""
[
  "am6L9Tu?Qs@3MGqZ0NmjJ?bAwpWFlzh+Jv^`arjGnd!48JoI!d3(4%cZv3^u!3I`LNakQV;#(<IyQj5!nZ1CE^_S#0`d7KJ$z*vI#leBYyLl8cRt`B3n<WL8Z7|O?UpP1r4hXZCII-(xyq>mm&tTS{lq%^%50<nK{wzJ>JX;=AeJ&|N<~sB_jf9czIDQKI=qUdo>wysf^Ts&E>CMhuB9C8Jeg0j7xBxeI({?np`jW$<_z>i3fn2wrt&NY$4i{|N_K+O|EB<M-Wvc8pp<u|84YH4vSrG-MrskZ*`E-*e$E_~UGek`+qGYfu_*<#?Tnn*&Pe^wEu6==P<&*^8Z4sKN^Y7u7c8WgAPCjtzUh=O~wId@hB+t<PJG&h|b;y*@qBR)-#=PopQkpa6XQDf0+dK<VnzNiaG=^gWynP+?A^;$yO9SM~Z=yb;_5C_JFPjR>*&r-=qk`2aSV5900IE;6&p&5ZMP|CA#t06ndnIf)HwY>5Kr*(G=^s={1jTO&QN(K<P8cgTw+wWHuIEkyo!lQ65xYgQRO@I2iBG}U>-}%XTI~v;2C{+3NNLr8ZM2J-Ee*YN!BpL2dtGCWJs>>CB?5b7fViA6>yh&82j2a;vOIGy(J2+y|7;&{plM(27_kXz1^35WK7b%V7t7p4`DEi1)S^hLw$BVbA)jY9<<q)y8z1d^Qv!&9Op?Gbb={yB{;t!0?#Py;zezwScN~(K(f}p;DH`h3`uANTRmCmF@rbJ5d!3|uTV-c@5yi($WgO+53`M=75kq_}VXfEcI(~_CcJw@tzO9PNM#X$Uj!Rzo6K;Kg-y)3i2j)`!vQR;rSH$SPfBBCH(C9vVW94*JPhGvP^k^DijV!bpgw#}DC)_w+v^-m*{aa;}!JgBQP!00=tBN=(yV{M7Aoo!J`f)HO-zoPG^1BEZFF#8ohhmpjn1p294?*_bw|n*gO8y5XMd@EiS*0au&WDr*z!qri;5!6_C5flqUulLAqLVVL^mj}8U7`mpmcUO-7QhF@BVNt5BTyU*L^f#5_1J9|&Fk2C>o;GyM=YXXUG6QPHsgRmBodNF>>M(20Le}Q%sp>P+QjlRa`4ltp6%8M>!!4Wat5R)^=haE>|M|1P+irs+owekd{82VsXlE<t{GP&qGP7LfI6Y2;EXZrq!YMZ*%Ba}C>}jGI)!g2IW202!#}Nu!k<wIK|eGRB(3tmBYmIz_jy%uY(o9XLp1>_d=YAW|M!{GeembsI;F^d^V=!oPL<ip3sCZPqv8-^2R}0nn#gdbs^m{^uR{#%RN=2X64lNEM!ULq3#tcFK-t6LSSx0J(EesXAna`t$sqRA^P=kA|EaZbEyIQDQ;t&*K{EefljFHp8Rka^IyI@Q($U3YLs5SZzaHYAFM&Fp$s+vsr5x(%R36FkE(kMuo&lq&nV9dWrT",
  "@WAI6h<fk$pK^l)sLn;_NK8OcH}K>{Kam@8soFM9FpuM~Xqk`j0SSD27KKju2BDCTGjRd^r!y6cfd}=h`M0~&=&L2<BunJz-jkKkxSG)YsR>zro+qaJ<7nVuN?-`E0jUmro$uvM$-~_0Z`IeuV5*_^$6|j@N>wO1Q1P-uT%MUvm1p!9ii<J9{p3ZmAn6>RVLL~khCkbS5BIOz9ddPwIre^z%`Vojsk@&Cks!Fg%Fv~^Fxx0(m1F$u`XxhiY0rv@UF^<WREaGRJY`Q>8@bW{^u$dFy|cQ!v2Zj^72Q>Y22lKMP(S?$PRc9dEe+^+3*mkKf3`9H&C}^%>d_zF7D#doiIe=@I_u=^4-ddzD+aMbRmS*gnwee{gM)3Vg*I6g+Wcrj$W6G6rr5iiWSCJog0Z)*O>V(w?iG~a><K_D3|gra^59efF-2>iVbn4tcpBSlsd8jI>;sPmB8N%Sbh(f&X`isd@K*~^(@(DlP=|&Kn{QfKn(012VF`R1tudmFd1;orkwKgo)`LIsGCPn^7aqFVs(sR9oofNPx!nojNVCsKR1`REEi%U4kLJ)is*cCQqZj1biUoU0`(3f`>_F0&{#<JD!L=dm_n7fswCM~9!giXc;CxRn#L!HEHUE>~ApzL?!EY#pHsTpm#|85hEaT?TSGp~lowE71VNc(Rqw)6?rE6UJc)A}d5ThG^@3g36uPSE1`^BE_bCOboS}hZ8aD8?b#gMZpXY=WfIn{k|U+Y<0%~We!xEa#56E<JP%RozI0^a?(`!0mtQM>7>lCR{#Nz^9X+NDKRR~UV<(~;lR&&1oyIG;Gj(|2F?v_pOuyB}2_Pqmzz;MBBivGAKs7c=3qv?nwKiM#1x+uSjFDN1+Q!<^2PqT(;^l=xL?Z1+DKPh3x&oiZb-`n;mttjN4qFqiE7LZPgq0<{`r&6PV8J!)EouAE2%ds0*)kv!<acxF@6=L7$qh7lJmT+fq~TBBE8KpAQ^S*3LFF9dGX!Vq~#32hN8tc^NaCQJ99h>M^?Ts{AL|4|;Mgx~+F_b(8nE|oH)D&2!gII7@`YSdK$eMAlX!5E_9(0uctl`)pPk3ZoSp39x*zTbDK{x((wE?n-x0cTVgVt^IYs}Wff_PU>1Z)v~!)*cZ$2~rj{fSTOAOwGDtcrcfF^DK;?S)|OC!0*qMQP>(E(=*o?E$F!yw)4}j",
  "E8k8dMa0IV0YLkK?$o_2=G~?35P?E9W00s|%@>}n$Tb?uqH#s_J><nVl%8)kxM}RCVEY5N`eTER;(m&Jjfs(`O70Ks^|l=&+zg|58J=C0`d0H2xxgj<C9|E~#NID;!Jm`IdNtF!{mzi&K@Qj~ut`zeHv=;;ryQR|O2gL#&<G!)VNmk@FzM*kye@3?9E{x>N7gfMHu#Cgt@`oN4m*cRo?`>-YrW)NOeM94sByHv4fLISId43K?4Y}+tb51|fVnGA-^6k3R%^DsE8*(CWe@p73<74g!OS8cY++xms4IT&JE;8cVjv<Y`Nn)vMcW;Ivh99I(6h|^Ke~TCqlyr0fV<E;pt6-}u=Lz`;qi5ympSId{PQrTOBcmvqOb0FYFO1NR?DNTkm#*GlZ^=-G+MHVl3KAys`^>leuj1XV5E1P!1AIut1U;+04!ZmI-g=vUq>q}(;kbgXu$Tr<}o>_qRHEb&0Lp3Hr#jZS%}d@K%h2-7CnmzZFH>l=~l!W#aq*|m$ek^4zZCT3AkKgDNXjwgrj57bbOvvlR~aFL4{*yh|(1r$`}VsVLxKS>G$bUeH7U{w1`nAEdTcaMNt1DKTD~sn70jHmN$289HR>8=qTYr1w?3D)UpT>MulZTHrp5Dw!K=)-I9SF&IDZC{7(vb!3ewJRgEI%FJ>#|tZAuuIUAeNR|rsj)d{}Oy&6YU7o^9XsoK42c`0Lf+0z_k^d8`s(VuZTSMyZ|Z;ayVb60x205>n2wjpgG3}q>&LzD2U4Em`ZvmUGF)rWS;E{l5>Oejw52=$}^wvj6=MF7$hR7Nfpup??O2nfX{^qSRtro>k4>_=`}|Jls1s{~<7_`pzZ=!NQA_XQYvtQn0Ik!_qow_p>bC-CZ6rrihKY-_FuaQBITF)yY^oYX0XK9HmY+;1WyJ+l(zR6xnsQ<@JmrbJU_Sk}WKqV&dSs4C`2+6-1lpDrdg7_Uwi$w<5qk8`Zr$umR*Xx$JT+u#MuX$7V{9~UN)cw&2aItlS5t1$$FA;MvM3k+F9ke3?$XQd&vxM<?B;~;>1M>jiRTo@rVu3kp$cs7W1b@ro1iCzi-=>!=zmMr3X$wfuow!Bc9j?5m&MsUCdHF_fpKGs39X4=k*#!QR49CT~i<*bhjOLIo?HkchR4rt~*?4lMktKlW00g0zdZic*^T{iZ__9+V2VuTHhsr*(ey8sG2*;&6#czm5lS6v36Qad!_PVosXg6~d9w@XVUvDquvogi9Cb>>WT#&afHyU;wK_kdK#7}H`2t3Em<DZ0$D6fV=)mOKr(HYMi*k42LiER^P!xP>Hg@{{)qUuk2$16%2*-UXV9RCakhjyQowA}fJUzkpAb1F4hs&|YooI@7s*?E",
  "UV{YFbR-f1CI^e_p3kpjBdX6P4-xI3CjhYwlqR44Y7I~%F$Z?+OfnJ77h0{-j!f}#{t9$a_!x6eA&*u!_%ahIn5jB$W7!GjY>ekU6T9`6mANfd(sx(toZGP*4AIiVirmCD-6EpUt!M-BlwM99vp@r6vp3@c)n4sk%ut*&qoWXr#oGJ?`fIWM;>y9<kdp*q=5Sy5;bP;JuYYrJmNq!+ff6nawLH~z1FIe+$;4jd1O%;<b}p&<kG}n7E4MA;>MO~L2bkoRnN39EjcN#$G)=x45}AN3;nc_EDzyUH<ZWV>d>t`WyD=nW1}1@t4vga>GeUTdb%f99bDR413@&V&WWa~9>hcLlSlcO}WCZcnvYPiychacLkdjlTKt{)8<+Y%d2})P<*|WCnRz?KvON$PJgz172VOT*X{0NQ5D1yCFVx8u<n}Q|+=)f&k(ONrY`ESo%#asuT`sYvHJ3lMWY`EYHs98&i4ml`8)rnfU>hGbDD$0@zVa6&;-3V(hkUM_PxYimsu^QFK2n-$!Ks#mo58(aJE1s(u;l8jn_rn%6MfRLHXLmm@T`Go{<=5Qm1T}@rwp2Q0devZNd&XAqU4ygIwZQ;L<whTTZASx$b)`g|wl*=IcHyl3?V*~f+o~t2CS-TqPRk+3U48AvMub{6d(wZiS~z1(##aQYQ=!!YXAzBq-$f4?ilE(LZmVk0JIEO)XZ0cf6sFi$?&sUv7NT&tFLcv#l}+4&8MG}}RM*2s8^lfkg9!SE3<0ZBJc>YpMAl-OlP);JLE(77$PZ%<H<I1Hi`14?I|<~c(cfja3RlF5?ZffgdmC^W)WD)NJFEJ88uB=I9*NX!BdfCinKId|v}0C^gl-!Z*R>Sql=~^{dJ0eje4{+3G@uw<I#p#yc12Ja+$@gpkUyqu&9C&nYvc1J!9F)Bb5#6y>#IFFz-~;(U5vM-XAh|B0P*6<#=G@|OyHZg49&*MwQhF2$xKCEVys{O<>D54qhedVk^jmKU*k~^oulJuW`?1UU_w25WBygUAO",
  "w>JORsLP^dvOc=s_OR_*bOpMe9B{vU0j^C>IwZ)`lrnHi>6|kI*vtiMI<JE>lilvUXi-!cT`Qq;lN>G-_?A6?m=RI#1ZKa=Ckw726hZ-)zZim9P@mRtLEP)rmv!_j>8SlP!hMuWMw2gXHgW&CMaUmw48we{U!}baWCG_VsveKKdXTz{)WDZ%xBRZRT;kI*_YeR8nz2Dl28<k<HtH7$per+&xk@ZuTLZ|?7;UV==Vsg<UMRCk-Vy$_Oq}B(=+y`rs3=Td)h~`bP8a<RiFoAJ$de!WpRx(AOnU#naT6vgtT)>;VyV9ZD%wBc5wQkfK6KTopJ}xCerz$sYU~i2w2fEC<(ORZpt9P3o&7lTZgzdE%jd2WjK%qTS3VWTQL53zdp5jlK(Oc*Lj5;?d_Jd=%Udnd_f!|=SdcMSxh3_(SMLpjGjHz{OtTBM_iC~zvSO9J`ps6Y_h;(A#N&x<R#7j3O~q7IJqSiwYixpkACoh*e~Oehj=2|A!vvwCX^?!?=T9A+Q~!;RSn~#21P%Dd2@SC=(LfnZDULu-j;j@fFFfRw#ekM4U_k~(iX_1<0H)o2AR9K9bPL(Vl9*V&bF4Duv!iC>Tdzq!p#*h_8={Zfy?LUSxQ&OM5U9fO?u5UmkCA(|h$m1JJ}?rH2V)~E*&wn%X&$(pVau^0X;HLraIR<@jfRkrwNFpbu`8z*BUHIMnEwgqLiXV{iZujZ8b*3$-+%MNh4y|8gK%I(`Bt~!+S>~ofv|!eO3T<gcf7!o0n+W`l1?>h#b>9=J%3?9KwQJvdlJ2PI`+EAA@)64tp*hwk<!%hNN&TM)|B(aE0K^OMHOZfQ~m`vt#6OR;p)?Q%R~yKhy6s3Lp0;u5LAkZD%}jqN#QG*pLy>d88@fH2uSw+k|PK?<{bJK1E}ckZu58hDE{suIX4&|2vEiQeN2+}5`bG!$WL5)3_b&wg%8DoQyFaa>5fq&+v&|e2ut{fTAL6+Bqf7(=#CII3H<*tJk9HJ+EXW~v8ecf#QUfA9TdcA064@I(fVGh2@)*<`cWB%j<5`UyOzjbJdKCPCR;=xRFt`;SYudV?#3lOEi{N@N^G{~^3YtaZGa0DLmFW;i@9yi#^9;R{;!OaB)vvQ8tO`j`MisK{GydoC>Ra0q)|rL0WJCwK51XFMnYh%L1uH#!)-#tv$-j@MYz*4r{ojvUnY8uf22Jp!M>gk30ik0zCf$BNghv~VAp4pCku(Aq|oIXn$VP-)I%^QdLd!J*zdOV->n?b?ex1hum7$jwCGS=^bFv+>@^o9Y`21d=sdHQ-hA;Dxf2K|+n&~RHt^sEzi5j%NFJ5JBZLk2Z?V2It1N!G8OcqPZ({06y#~!+vTXau=v4pgP=fpdcnmT0(EE)rb&5MZ<o**FT!RJt&Bv=asj29dO<W<6_WgT~#8oh~=$zsy8F{3<vw;YKM*`Hlc8%6-8uP<GRgURQgOGRvDr`jrg_Bru(|{84fEwE~KUNWs*q<SH=YNmZWV~Gldt#$1oOKmK&%G|wqT2h*<GlFEWQO|(N5sRa0AB_1>bE?vR|h%*+p%|=cz7WkdBxf",
  "BTld=Gq_xI0eVpn7?==?&dT=sF=>MP77hHINkhpe*=D3KD)I8I^ohu3Z<EwO=afH1-EEL&sl??<Yf8k%?C8><mBU??!)o##s0`-{$MLQvts=eCK<nfeImfQQ*<{{&!<EP=3qycY7-dLbs>rpY^J~Bg?XI}&MGcvK^C}9UtMguKcfnlk3aA*HMiik@SBg*yC@-gl51vB1vI25EW7)rCpH!fj7C0(Y(CRtQPx=wP4Ej()wk@7k=pXGvYl*f<Y^)CsJaiy332!3gx1(M3Hz{hU$FDBLu0X7nN4GIh)-OHS(l2Qn<aUwh_mEHP?hp^QN9U?hq#6m8r?TLI6V9{%$>}DNC&Ig?Yy{k*$T09$mWb-Jgfg6hO1%MZWg|6iUd&D})-Ftart2b@J7aZ@6Z>j}fZfX`sbQRqt@3FJ{y!$3_x9>FNZqVlqZd15SFB@R#-R8HP)%T+ghcx=0@z&1emWUf3vb;wb7W~Ig$FeNWVBE~k&dlQyGjNp+sHr^*Qygg_&G7CMW`p{cViM)j_|uC(WN8K&hbOV`(%H`c&()-!>BuJ`cGtqHdX5RA0-HS@o7HV>tK9vqvkG$WEaZTi@CRTz6`xW&rp{1fXRJC^zTBI64EFuzp6Y-0}1IcULOAD@I6wLQEK<AYZrsj+jpEmAYEF(Q7vc-kaU<+en>4Oeq1~ce%SYWTlp8rfNx3n3P;f&&_UL5J*?38(qR7xp&T>ql0+It8~9+#@<Ay*hUiI~8p=0?%--^GBaRy)x;>;dO_*4J`R4=ML2*YKRCvlJ5Zk|83-<6i&|G7k7a0-u@7jvzqOehy8JOzkrckiQnjJFmtuVkI-~gWqE&rnHN=LpopG{1IyIE=_5s5~7{C{?6HebDek_{|sGfxb7l9vlw7jplD5ig#e94<$#^jS$go{GUj9xdGkK>WBszQhCB09)j>9oxxnjFoWGWFqsSA4s9Q8JOmrvKirJna)$^=KF_y(Ap}qV{uLv5iQDgep4g(|MN+7kimD1rS0mdu*uIX-U<3@x0$R0wiN<Fy0<7WjS-qx_l0*x3!@SZi00WFaiAq>ef1g)=hEGXL6GI-82V>kB41B9A*Ma4sb}^d0Wv~XIq2Wp41{&;Uz?P=HbiS2G*0~TTqNn;?|lj|iGMge(+K2H0No8pOW|Rt5-nrFBiuN>*bWje|7sgi&44>X3|lMKZ;1-DGM<D`-_`LU19Glh_T%_ki@<uxpItN1cW6h$Q)9IWMDG4(?iP=?aFUZpk~{w>T%<XGz4qA#Pq>-pmkt0ug%IM1yh&@bo4UfxaqmO&&543&Q0!~?#Cb?ie$l8d<T8`REzMrso;r2meNef`WZfcNTIlqRa1Sc?Os3GSV$Nwl6T#U9Fi?}cxtegpZzRSR+@lN|io}p6gJJO!",
  "|Bv1p5NLHCe4kQqq-ur<DI@Gi?IxRwx-MR+pr=ge3PjCe-@^Bg7P$R51>bf;(b4y=MZ^=UN&Ca3P4GM17=w}!oUqZ0zKO3f;XDs`N(C;R7ei=@sGc^Xxp}Sgwn@45C&&<>+nJvLpL%H1p@Q;VpxkmZvA}A2ebAzD2)f?3daneVeloK?<NznPSI;r3c=odxyjdDcO!d-+TRQ-6=Cy#=6j><OyyqRYTUR9<_KgyGQAaSnNlmwW^ozSkB3uA$He`O?ZhC`Ve#zYf3z}RN$cGktz}X!}@*DAY+|N3>&#?7mv(j%oi54Rwz0z{bdU7h!sOol%SmlQDg$d~6Y(N)L{youyIhn=J%0OOZv(JKC@!MZV*=c$(y{Og$Yx9*#mY&<4JRfs`?17jeqYkx{BdVNBg(CL1U4G6oX%ak(7C4Vc6^>;Ay<v&GN3cEk?VBAdn9sWWLC*a<Q&KwN=$zu!Z#i|hf3p*lnt%rnuE>+w-raYD!wWBTVlKFxB6axW=L(caeAAphoK)P5RLDiPwm}cYtG?(fmx1}mxl(~?o&?Q;2+l81LUOH++3}(eAZ=yF8JWR+$n5Dw-=pW&v8XK{Ez<X?He`@?Sn4S?wFWdaw@*I7se%UR2G?pf4+z3ad?-{EfqK<a0QeZUg0Sn)Hw^1{RkR1ZraGD=Xnc#~TYmpAz$nG=66Qw?ZNS8SfGw7x_r#d}@XRrOYO-Ht^eMz=i-tv7<Z2x_s>;!sAdRhsdYW$Rc(12=uz<+PVoVXMIIz&e!KrxoTM%CTmE*bCs>0Wl%g^{kz75n`&G#0se6SnUdAui9hS&=5&wp=f^?^E}(|XTkxxTuir(f9<3)O2(W0)VJ_@agH&U=AMomsyXAvAIyrSfddH#?RGU(a5ZD}XU^4H`g-v)jR?#ZD0uKUAYA^-#>5qd~#6+{G8yjOue?b$=G!8;w8R-LpFQ@S|`dC!f&ngW|1`Red2w-WO?#0m5dNqDh664I-V*bY;)TnMM?P!{wwrj|@)IX{{mO^wA1y;`Cm=5&I|;w+-k8>rFf4x(HtGn5jk_dd}sJB@|@3BuS7-q-{N7`XWxk(q~I%lr!`}2oZ0+&yLBE<PXobtGymnj7AL60q37I0dAiG>+7~HetICpLmQsFp7dB;O>|Rev%vcGNUQ9p_Uu{(v8?YLgpj(5I9Aw~&wU@MhQ20_+aR7r3awbyr)N1ij!z__rJHsAy<WeJl~EX8TNaq^CI",
  "C;%m%$=BlLO;sS#py&{yjUTjTp!%nGHq`}h5-{Wub}>hGh7_A>6OaTf<XJ_4n~EPGr`OpizG5yhu}TO0+b_!a(|F~6<)gA2<j^--LddXkX?ym&spkT<B?+5EkV0133tUF^RGK&p2^AZKvt`v8kH+>rNRzb_rsTn4c)j)7r@iDEhp48&3~kaE0LHKAXD7pBNDk!`(Kikk<3rl@veCsnYjhBwj@Gx5ojxhL?(yl=L{FjvNKZinRk0J3uPrDv4gex8nM>0>Udh26_CN-4o;(DUFFhCJ|1k;I_s4wYU9`X!>qMB+pWSyKTcW8_%2~uR$Q;OE-iQ4dqj!-84&GaVt-k9EZuory^Bkt$H-A`1pmb8>?#MIG{|4pqskh$Q;de)f9jks&g@43=ehAA7i^cEC=(^WrNFkX_9h)6*K1d--nf2>fZhNqC9R<M(-*Ql3k-TpiXnKr8^%CPCkdYaw9r`!Xys^GbwmGRIdxA=cJ|}<E!gJ;P!nPI=s)=4$tL{j{MNlL)r<f^iFWfUgI_;yf-bYHIdsy16?5K6S#-G9s2i!I=<Y>m>n#+PUkEv!M`73{-2A6IyoT^HU%|&4yGN^@`83LgQO>J3*eOsm()j;h{OWWStliE49PK;O@qx2~K&B@NvTDE9@(M&IL@)Q5pJ4VqxNP8DONpP?!K(t`s(sSrnc2u@N+q{Z+x*W%5o)~ml_Un5gPin!3h7aeNZl2%q)HGVEwJ?dp6Tk@1ZP@|}L1S;v>^lNpm;ac!@Q}8x-_w^xGO<};^LBkg-m$LmnRb6aGo+3u*nwMjWI;htVqpdsoKI39RfcJH14fpqebckD^Ug3$y-z1%631m~RqDSYQ-aHG%T)R_7%@XBr^ZP}yD~x<r&}#JK@omco+SMl<A7_NXc2@aw(ZC*>F6Hc#8_x==I=M<0s%Khd1|%-)HTYiy0z<d!Gw~`4CCi#k0T+yAzV1<NwB%wNdRIl85l5_twAbYiX*#xZn&O{{|S_KHORW8ZI2+p;FYcYY$kD7H{)!S^wYz5TP`(UMQTqzJu-$5WmNUq=Xgae6<rZD2cHvUzHn{{Mt0&~9u({l2n+Kx?9X!9>bv>fMy`?4EOY~7GKBOpf&82C=HDq@Yovw4F*o>sh4;_%r$Z>UVWEW)2sb@j$W{(qM+5!fde{uL4>$u;8Q6jc8%%R~C^hY-yZw&?T!96}M?QcL3Xd34cA)O4VhnI$FgRiPpZ*Lgf@88VhrBBG!g1r@b5etxz1n-;Udd?vhX|(>w8rJ85;+UvWhH?>H>nw+nf~hYrEv@djBmwSH&QQ~TG=E5p|`6SdA&yx^}|Z!&i>v?-MBU@?OU7t(u^Z9*p?E;nx<Gjuslj5bgtm*&@ha9k>ITFWu51yFE&Ju;0E;$_0U_fqF?d1@6|%U(r+g%+!s5p4M7b^<*NK$uoia6gq6pnqkt@R=yd",
  "2EU?!aikg<Y3`LyG~tcEl-oX5JJ1?7<smH9v@U0o1x>AaHdBl)E8d0)3DWgO%rRIEgpHx3<$b$8YTesXKFab<=<EtANsgk`p804SYm5AUXoFdX)+X)<7vij6h|-ZI)<1b01R$=~E*@w-`%;@nt*XGMXE1S)?OBOU!5`I;-XiE1!x~z$gONDBu>E4gYju0lfxyxZIItl(NU4wCk~mLWety#Jg@IM=<WT>vp0M<3;wGyUrneBfG|!cQ0~W1Mt8E&PFw^o*UGhYmyQ^e3mZ2rtxRk9KBHEue%`b=(QK^|V%n?1p1OgT6n~uao(&S8yO9-}qy0XlKFbKg95l(25t6F|LfSBRvz`44iNyO29l9ZvrCU{?*^S5Q2BMB*^7!cX4rhKoGizQY|>5MH_B4f#?&F||1*xkc1tXnVWVAR<AAvv3$BWFA=dj9*%cx_l2v))a-#jY86e-$s}S@k4yyI2!ba*PClVM+W%QU`;tQw&J+?JnX)tY`f9KT5cX1SCxOtAL4L#wv)HEA^)_e|uJe9D~DvDWnEO6J-XrYbxx@C3HA^{Y?;O<VhGJzlz&nc$wKzo!nzR_4~NVdSM~5jPs4Lbp(WA&Po9~D$aPaAj}ji?%5S2e;nSeRlLfxLr!tAwG_F18}&+VmT&<FK*FkoQZE9!$oc<p-(*NfY>1Vsd~jMZVinu=nJWUtE*~Cv$u6)?vLnLP3EHF+X~x-I19ftfIEbbp@oj8sAE%5^tB=(b*Q*{^K&}+VI9jA=sJvd5=PSTn{+WBSRpBK3wjnGQYJ&G@tb=e~F^-kmMD6mCa|8o7IX!q;mV3SgdG5tuL&W`r;%a(q5fD!3kXUuM(*JfX+8FF8wbv;GyvYLt+`AP$CeGa@wMv66d;{t}zM2;UOHGOVcz;m7aWTI($kL*5lkR3dv5bwdIu~9%OuNv@m)`;J+u24pD^xDh2T~M?HQmQ@SMliAw>0t5_`f?su+j_%S|o;kC}W5EiXDN%@?o~lW7T5S_q^#Y0~2-x%c?Ce0mPU~h_SclPT`}el%a_Eamef+M(YccN;x#<B}z{$3;2aPh1!AP7=1>VzHyg%#&FmnAg;2R*XeloEwbnP3mVB@ldKyOr3l62*ZcoEKIJen>}tl`2|Z|7q|b^Nc%=5nRvv6VIWS~a>9DSJ7<rQ`av_5d_0sa~",
  "{q;VV1+*|^RkHwmNm!Qf?`DLJwA-h?6fMnwtz0l9v`9OLm~^;XYVzsMFnDPUzWfgDQQsBVNzIF|kJ}(jP-~h_XhabN^mCU?nLqr^17UWIbZ;6V9fRAJNydwCQ6}T2GrJ(C>|N})kR%X`gY?BdA~X|(6{VmgocUyAX=`SVJ5aY9z8wh$MGzMK5=MWm7*-RoP=jj0tl+A1+ZAPJOr-pfm$L0BnCVfL#;rH|r4q@8uq-ZLlvo;bcI&PGjBb;uaK6)5+8QjMzWk&9Z^!LuDcRk7Es`{UTPN8?p7i)S-d+RJybodh-J+DyzOjIfBdq7T?oSz62CwA|nMbR}1zNGjqTcu4M#eS(BdNbD2F{S+2$^^2a96D?hkLd??9?HD(R?+kKb*dS*jH*>pnN;{q_=yRA3=cEEfd9rL^F169<^UV-nAPYG2#|XrjWzabE+$mTMz%s62nB@91m{d<2*FoO2q1<TWHs(<>z}Zrw&ZUu<)yJf&68g$%h|DTks5rM}qTz%y3!3|1AlaK(7n?Z`-)(p>}in9NnWQ);~m@>D_`0S%2Mro>sWl7l$2q*5cO9qG8jq4SPmGiJSMCO*#SpF=z;aJ6pL=Wt(NgKHdxzC-~g0g$pchh8<F09vy%*d5C6Da2e~RR_j?t%~BN(7%}TkDrgAB2EPC<m}XI$bjXzeh`ysWLy|+3oW4c^XOc5+OCyZ<JSBOE=8?gG>~LK>ogbu@s-eiPJmx0ji(HEDxBAY(tm|VNs4Lei+AeLQe4gj9UOWn-rpXr5Ej+G9-5`oYj{L@r$B+#myh^H9#cFtWhK@^~SP`kfJ6{&^j~Fu8mSAejhP8}^u<#2o<wWs;5h4>cK~MwV;dqAD4lFgEp`nm-np#8AaoQaMDgV(^`xQwbvnBeg-TdZ)vj&NkDXv_0G@r|M#cpB*MY}V$6#znlr3KT>qMHiMELU^z+@bZguT1|9EjwmuPTMjo8i=r8W210=x-_8P@jOf)FpX`FpFFxF>_g!QLL#hBHi(dSq5Ai3I=DWdie)$o=6;dhM29olY`FHKfg3)n4bBM2?z?!!Wkr;LMR)#t8hSLs8WJv8B<y#3g3RLYZVD)zy*ER0Nvgu$(3@l*abXKPQ{(HBof+hbNVn8<biSa}$&Y`1iL0|P%+?bc^N&JfnhZSPPP7{=EWVEk3Iv7lq4r9A6>4-5`>O@QQYd-xR@fHFjt>5}0uod%M||Gh*17ggwxl54Y~aNK+P#PH=Q3XzbgC5Jd!&unh6k4DWjePP{_pVnTfr`UY$v0<5`{V5PrPp#tH(>LZ0K(=fXfkh4*ZWK4ufaCIBzqjBU=~Nin>fT_G68g3$^IjDdk85VXHkGH_P+_cr(r;OB`4;!G^pIm;5c}",
  "DL+M$r9elq9FXn|rhzTs+W(yLOxD|K`22%lLF@`7s-6t$<tvXeC+F?CGCQM6hj>zOgA|~DUVtrM<Ewp&>9z3t19w^c@LHkh->6FNrC#jv<tZXWvaqW+el%iXQ6F`SYjTBzp^6X1l3t(o5s>-cFs7?J&p}{1K6~Ll)I``rX!S*H5?jMC!Xfp`z>`@G<PqnUmM7&c)*jW4?Id{J*!7|0=vHjX#<es3*2+Q6v^h2@v`K1FgE(qf3MYBpy?}4V$wVqI?~1f1K-(5hEI!QX2<Z8VZ3?h;17rAm(%Aq;l+1Cg^zb1Whub^m7J3tJrT&a&In2r^;7y~|{c>&)d%US^pJ*mP|HC(tA@SiHc#cKfS2I!^@<5vZJX6-rviJt7)ohO5PcA5%6xShCMMH1{C;TsLg<48@%uL#kxvgx=-Z~ME_miPP@R6L}+B#oNa`4U=L012wxg!0qj-0q|yh6WAFWytVPE+t(CMn%^=sQXE2Xp-4YA<s82c>^EvyhOf-k{xn`HDik_aiIDi#4H;KLUe&fi1<;Su%&$j<dRZbt-TaHJEH}w3?{B_f0eX((4VxCXS<`KiD_JS}rz2#PRA8x-O%y?Q+{~<7Ng2Y5#hxq+E&W9s2I6%DTZo+w8_tSv$j}dwz<uUNt<`mVw%opE6miJX3N@?J=GkAzz{q@zT&~<ha6)UAcs#rZ#Z9oYs!W;WClQlqnz6SgU69!l5HcKCy+o!STiOn}*^lqK5)?a2>JV+@kf?eLCRcC2I#VNTp>)uXN8O#lQzC*qrk3MVg`X-tljms~5~BH2s+xAv)?k^cl(ajRs<mxUO}*a;6n2P0oljet*22xd!k#8G4Qz7qL9Oqz<IvZ880@C=0jw{r5rkZfe-t&#-Rz{a)kli)C~sCC|*Eh$*hQEt;~Dt`{kcPNZMUA>IwGd2L6-likRKun0pI&K^Tx&qk_NOkJN^Q^t4$lriHAv7Wd}sE;hiBEht*u_NupB35)ajUl(NC_wxYdHwxw&k3BT+-^}F_wx|`8t8N{@n~7(96o3`m|<5Kamk3;49&+R8zx0eZWYK)8da$g68Q8QZI?(R*u98Vabd=iic&R$Ni~Q5Dh)MKsSeA02<-$N2auSSx~Na|-Ntkcs1YCsb&aA~_-J)QU(G0RLQdQ3HQPtwQ8A^?7B|S&<A_Jrz@~8-ysCOx7AMoRhT(i-Nd6yDaii(QLU7_<1Q(=JkRw<xAkGi?k3C9#&>nBa-j^Cr8)F1A_GC2HiFI`;6^Hf?;1M9!kEx1H^NWFB>Ejj_yN`iceR^G6|2Gk8*t2tw{~A+YUI$K_;FUA*+fHNW"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

def _secret_for_item(index):
    """Open the encrypted answer/explanation payload for a 1-based item index."""
    secret = _open_secret(ITEM_SECRETS[index - 1], "os-mental-models:question:" + str(index))
    if secret is None:
        print("  [error] Could not open item data -- contact your instructor.")
        sys.exit(1)
    return secret


class ActivityEngine:
    """Core check/passphrase logic for Activity: OS Mental Models; importable without a TTY."""

    slug = "os-mental-models"
    title = "Activity: OS Mental Models"
    description = 'posix-file-tour, file-io-contracts, write-your-first-syscalls, and hex-dump all put you face to face with open/read/write/close -- but none of them stop to explain what an operating system actually IS, why your program cannot touch the disk directly, or what a syscall is a request TO. This activity is the missing conceptual opener for the row: eleven no-code questions building the mental model every other activity in Basic OS Theory quietly assumes.'

    def items(self):
        """Return the public (non-secret) item dicts, in display order."""
        return QUESTIONS

    def check(self, index, raw):
        """Check a 1-based item's raw answer; return {correct, feedback, explanation}."""
        secret = _secret_for_item(index)
        correct = raw == secret["answer"]
        return {
            "correct": correct,
            "feedback": None if correct else (secret.get("wrong") or {}).get(raw),
            "explanation": secret.get("explanation", "") if correct else None,
        }

    def passphrase(self, answers):
        """Return the unlocked passphrase once all answers are correct, else None."""
        return _decrypt(_BLOB, answers)


ENGINE = ActivityEngine()
def _ask(item, index, total):
    result = None
    while True:
        raw = input("  Your answer: ").strip()
        if not raw:
            continue
        result = ENGINE.check(index, raw)
        if result["correct"]:
            if result.get("explanation"):
                for ln in _wrap(result["explanation"]):
                    print(ln)
            return raw
        _show_wrong(raw, {raw: result["feedback"]} if result.get("feedback") else {})
        print("           Trace through the function step by step and try again.")


def main():
    _banner(ENGINE.title)
    print()
    input("  Press Enter to begin...")

    answers = []
    items = ENGINE.items()
    total = len(items)
    for i, item in enumerate(items, 1):
        answers.append(_ask(item, i, total))

    print()
    print("  All correct.")
    passphrase = ENGINE.passphrase(answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
