#!/usr/bin/env python3
# Generated by aprog-private/activities/generate_activities.py
# To update snippets: edit quiz-data/iostream-interceptor.json and re-run the generator.
"""Activity: iostream Interceptor


"""
import json, os, subprocess, sys, tempfile

# -- Crypto / obfuscation --
_KEY_A = "cb52eaec553f63f651e09c53128144b569ee9b042549f6225bd55b5a8f4f72b4"
_KEY_B = "a0556b87563556c77f0ab55b922b44700c92efb34cb35be2aea345ec1c6bb811"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "b22d6a7ab275a20bdf4d3a20e51ec92bc24f63de8b1ce6bb3dc0837172266ce9db4996e5340bae1f58c61ac3db5cea8f5483677b1a9f427c"

# -- Public snippets and encrypted feedback/explanation material --
SNIPPETS = json.loads(r"""
[
  {
    "id": 1,
    "title": "chaining operator<<",
    "platform_note": "any platform, int = 32 bits",
    "code": "#include <iostream>\nint main() {\n    int x = 5;\n    std::cout << \"x=\" << x << \" sq=\" << x * x << \"\\n\";\n}",
    "prompt": "What does this print?"
  },
  {
    "id": 2,
    "title": ">> skips leading whitespace",
    "platform_note": "any platform",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nint main() {\n    std::istringstream ss(\"  hello world\");\n    std::string word;\n    ss >> word;\n    std::cout << word << \"\\n\";\n}",
    "prompt": "What does this print?"
  },
  {
    "id": 3,
    "title": "getline does NOT skip leading whitespace",
    "platform_note": "any platform",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nint main() {\n    std::istringstream ss(\"  hello world\");\n    std::string line;\n    std::getline(ss, line);\n    std::cout << \"|\" << line << \"|\\n\";\n}",
    "prompt": "What does this print?"
  },
  {
    "id": 4,
    "title": ">> then getline -- the leftover newline trap",
    "platform_note": "any platform",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nint main() {\n    std::istringstream ss(\"42\\nhello\");\n    int n;\n    ss >> n;\n    std::string line;\n    std::getline(ss, line);\n    std::cout << n << \"\\n\";\n    std::cout << \"|\" << line << \"|\\n\";\n}",
    "prompt": "What does this print? (two lines)"
  },
  {
    "id": 5,
    "title": "fail flag after type mismatch",
    "platform_note": "any platform",
    "code": "#include <iostream>\n#include <sstream>\nint main() {\n    std::istringstream ss(\"abc\");\n    int n;\n    ss >> n;\n    std::cout << ss.fail() << \"\\n\";\n}",
    "prompt": "What does this print?"
  },
  {
    "id": 6,
    "title": "failed extraction zeroes the variable; second read is no-op",
    "platform_note": "any platform, C++11 or later",
    "code": "#include <iostream>\n#include <sstream>\nint main() {\n    std::istringstream ss(\"abc\");\n    int n = 99;\n    ss >> n;\n    int m = 77;\n    ss >> m;\n    std::cout << n << \"\\n\";\n    std::cout << m << \"\\n\";\n}\n",
    "prompt": "What does this print? (two lines)"
  },
  {
    "id": 7,
    "title": "clear() re-enables a failed stream",
    "platform_note": "any platform",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nint main() {\n    std::istringstream ss(\"abc 42\");\n    int n = 0;\n    ss >> n;\n    ss.clear();\n    std::string s;\n    ss >> s;\n    ss >> n;\n    std::cout << s << \" \" << n << \"\\n\";\n}",
    "prompt": "What does this print?"
  }
]
""")
SNIPPET_SECRETS = json.loads(r"""
[
  ";y+d*W|P;zqN{rviCSO#C!oCCzoJq#3EP9l_C=c;4cfDWw=mXy>l~J_K@B9PmQDuK8>w~=ahKi1T|fJVuokTwSYvLD$o%}0T(KT>A6zxuY@yLd<Z-<=OgjeX;BcCq9Pr#?lzI@}b9~eaj#sB579S(Yp=)qDWbnKit1&P0tkEa8usg0Iw>MUx2L`%L%INZ#cYh<NE=zqLjfO+cXdpIdO*h0UNFJkiuHpNoEk+p#VN=OzeQSM|&HT2>oDfBK$POAH-CUvR0^afJh5vn#rAEAnhV=`g+6R!my%xL&pvXcV$jd7#qnc?oX+Bo-Mpu&@v{P+bVLS7^S_!D`C~O^1haAaz7X}aBQz*{h2e&IJ=HP5Jr0M",
  "k>?!f0e3<TJn)tdmWV6cjH^(?OZk7HkSf#aaz#;9vXgN#>9|p6P|%e|f%v@hpZfKE(;v_j(15+OB7<vgl&VJVreem~x<gcIfqQ}<yE8fAdsA=mbiP0z#|_Te$<|{yDSME63de;6iK+HdO%u+eJm{X}hpJsBQ+Iz}RKp%(1~^jp=H0?!sr(v!ZwLC&4kuYd<J2Bgk|mN0wzPn=?9LBS%)FAgf(d4nmNVB}M#0$&y^+awrTk#)ejYgq+T;<{z(#XmZ7ol~{%8DPQHs<Z4PGv^5rE4LOj470d&k?%Jh|;{kQ`e77tPdlpL{k}9U4TzHA1|n&$@?j%T0u%2Nx?I?5n*awPlR!CkH2weArM{)3<Nlb`I%D3=Z|&!lUFka!9rSC3ahxL{wSVCP|Xg90CJ`R6<D2mH",
  "0}6&Wk=s=Q%JIxHK4LVEdlf`povFb*ie`kkTA-Tl37glpCc${$w2PB8X|?)zJPSS_Y=PSx&i{Ha)R6t;f9{v*`{6Bq=8-QnI0y^IzkBj^%M9AP9CZT9n{Ws^jL`n(g1l)M-5Gf>M1HqnQ}`pyK1R&&k5eo|<QfQ$n~jZ=sO|xY#{3{%KZI8ln1OayinEVu<nz!@V~O<3B&XD=2d*4X)2}b#xdEj1GgkDOX4VVynh6eGv2!HPGLT$piMpwV+0~_|pZe|IguR|7Tw(IENbAxq(X%(iQOvtL?Q9X$C4P-KG#K4-TZvcpvbQoJyaKD=h@0<arC*a#pYFZ8hX0O+0X9d|=XY{Hrx7fUG^veH+c-Ra3B?kXmVP<rZi8T;k80;%Ea&{TyP)M!6~U|=aD|shm@cBTQ^bh-",
  "E21>b;m_8!f%QA8&-Aepa7<Cdj5hvs2gunVYKS>=?j566S&#!FXq3*j2lC*)qFG);p{lE6P5<GAYrL#gz*v%%LH`O2O`~?2AIc1TP_*Q-&?vqKW#BV7Q<;hiqF%0jxKyB9K0#>%^647W_Hf>`xVq!h|MmE0*NU4~3PE*)K>4O~8??f1&F__%z5>*2)B)`4m0K}(exD_&N_{;~SRGCH@xd#YmQ@6(02Witm*#LAj4g**iu5vh-y)Lt&H=G~^BXZTav!BR2<&u{5+hZL&d5bpOnEdaqk!R`H|a;Vz^~u<Us>599Ee*Wmq<-|7MXICEi<$Gi@3MLqR77Wm9A)#xXWNkuo!W-1M8*%lvE;1S!ycT&Qq@UZ6k+`Ld#(Xii)q5S07CLKT1d`U@319ZJEH^)QKZN&5di-",
  "#+xz6=v*|ROI$tB(SN^s%}rM!mc;2~pOu^K0?;ZDVL`_h^iNhtCs<>y+<}T-vX!M^e{H#`F?&ah7znqS&{S^5_IoSCiimWq+!jnN3+%869l3nptr&=TS?imv?6o=z7q|bA(A#DF?#D?Pw}AnFr+`p#t5gV~F>wU8KDbth91B_$<pjSg`c%`j4iuZIiYT>4xekJOky5-tQ(IEO<<G<pQ{#kRd3Wa600e;bi>rto+>woe3tP-jZ%gvi*M&nt61z&VQf;O0l9Dun=bh(zHi*=m_x<rJ#twe~4HKWMTzd}N!%5{r3ow<=shs6r;y8RF*MmpxA~!Q@EZjsQTn2t`qWpRt0T!Rqzh0!b^(L$nKH1qR-$WTEK2_8IjGl;Lp_^zTY`N*+u207MqqD<^A^",
  "f$R4ys5yI;Di1mKvD<O5ipZkIJb&X*avE-fID`~_{n=yIR0bqkiQ~PJ;)~FgjArZ}Jy{pNDq#3NMPDn6Z$`Q@{#;E}qeKX$_y3fq8oaE3AaXQ%$P9L0rWi`Sdp|x$bmBww4KWP;cuzm<$`4an%uo={1p4i|Zv6-m@a7!Z(6ZG6M*^kNzd(!<MgYoSEhujoY|YFPxdZGqoV8-^!{kWrnt1}req!QBF>WVal#XIOnf6@Df7Q<Y&kh?I=*S@rENhDR4%}ndpq_A(_v<XV*R6c~Q0qu0rcL_YE5}e)C`bJ-@VxnrK-Evbf07m9C5Vepn+svfU7$%ia4GP-jW9K;x*7lGzcOwWe1_fQi5O)zoMVOXRLsRJpkQ{%_aYxDQCtgo$Ed86p3uV-fTMu6pdV+BT4lTV8`x_U95~0&%%hFmlaWZ~ekV(PgV9F4e#+S?iiw>J%^TxGPi;cFu3?#68NK+enE",
  "k_^V&5mQvN{Db-nrOWx?yVKSj)k?2w(?+tf&Y;oO!1?%ZH5<C^Xp`+|P%&qmfIEJCy0>k!7T>kuTIcW|F%zNs9;ea>Uao=0S-O`XVKuVm#i{IRHLE4A^I{LL)rAV2@%$D$xH&y3&*IxV>8R0C*^TTAH1p;SNYZquOgRohMzf~y2?UZYPwQr5k~PlW5fRY^9kK2RSVW=hR3F+<fBt1AtX?W+Vi+%EFSJ>W?rWlVEmj_VKe9>y#@>RS&XbnEB{LBASco_<6dmSR9}OCXc7_}ApJ<XS%}Z?7**c>bZDP_mR^L3iE-5xy_SMjm=1PB@?vqSgfqlj{9@1FWu<DyWe-Z!U`_8gU50Dh4sZbgtDm)vsjT<kcJSQ1W0NXZ$kK;OF%6`51hOZ%4hP=VXK!KrS$6hZBVoSU<EkShK)=*PFs&)cCv4c>ua$agJPA#o|@;#y!1^k)vLe5NbXqyr3iiepJW;sGs&tllHmj"
]
""")

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()


def _secret_for_snippet(index):
    secret = _open_secret(SNIPPET_SECRETS[index - 1], "iostream-interceptor:snippet:" + str(index))
    if secret is None:
        print("  [error] Could not open snippet quiz-data -- contact your instructor.")
        sys.exit(1)
    return secret

def _find_compiler():
    for c in ("g++", "clang++"):
        if subprocess.run(["which", c], capture_output=True).returncode == 0:
            return c
    return None


def _compile_run(code, compiler, tmpdir, idx):
    src = os.path.join(tmpdir, f"s{idx:02}.cpp")
    exe = os.path.join(tmpdir, f"s{idx:02}")
    with open(src, "w") as f:
        f.write(code)
    r = subprocess.run([compiler, "-std=c++17", "-o", exe, src],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, r.stderr
    r = subprocess.run([exe], capture_output=True, text=True, timeout=5)
    return r.stdout.strip(), None


def _ask(s, actual, index, total):
    secret = _secret_for_snippet(index)
    print(f"\n{' ':=<70}")
    print(f"  Snippet {index:02}/{total:02}: {s['title']}")
    print(f"{' ':=<70}")
    if s.get("platform_note"):
        print(f"  Platform: {s['platform_note']}")
    print()
    for line in s["code"].splitlines():
        print(f"    {line}")
    print()
    print(f"  {s['prompt']}")
    attempts = 0
    while True:
        n_lines = actual.count("\n") + 1
        if n_lines > 1:
            print(f"  (Output has {n_lines} lines -- enter each line, then press Enter.)")
            parts = []
            for ln_i in range(1, n_lines + 1):
                parts.append(input(f"  Line {ln_i}: ").rstrip("\r"))
            raw = "\n".join(parts)
        else:
            raw = input("  Your prediction: ").strip()
            if not raw:
                continue
        if raw == actual:
            if attempts > 0:
                for ln in _wrap(secret.get("explanation", "")):
                    print(ln)
            else:
                print(f"  Correct.  {secret.get('explanation', '')}")
            return raw
        attempts += 1
        _show_wrong(raw, secret.get("wrong") or {})
        print(f"  Actual output: {actual!r}   Type it exactly to continue.")


def main():
    _banner("Activity: iostream Interceptor")
    print()
    input("  Press Enter to begin...")

    compiler = _find_compiler()
    if not compiler:
        print("error: no C++ compiler found (need g++ or clang++)", file=sys.stderr)
        sys.exit(1)

    print(f"\n  Compiling snippets with {compiler}...", end=" ", flush=True)
    actuals = []
    with tempfile.TemporaryDirectory(prefix="iostream-interceptor-") as tmpdir:
        for s in SNIPPETS:
            out, err = _compile_run(s["code"], compiler, tmpdir, s["id"])
            if out is None:
                print(f"FAILED\nerror: snippet {s['id']} compile error:\n{err}",
                      file=sys.stderr)
                sys.exit(1)
            actuals.append(out)
    print("done")

    answers = []
    for i, (s, actual) in enumerate(zip(SNIPPETS, actuals), 1):
        answers.append(_ask(s, actual, i, len(SNIPPETS)))

    print()
    print("  All correct.")
    passphrase = _decrypt(_BLOB, answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
