#!/usr/bin/env python3
# Generated by aprog-private/activities/generate_activities.py
# To update questions: edit data/bit-manipulation-re.json and re-run the generator.
"""Activity 3: Bit Manipulation Reverse Engineering

Students trace through five mystery bitwise functions without running the code.
Wrong answers are explained and re-prompted. A passphrase is revealed when all
five are correct.
"""
import json, sys

# -- Crypto --
import hashlib as _hl, hmac as _hm

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

_BLOB = "daa16a7c638cd67e486c7c84dd9d1f734d768e1e4d1c3b5b669fe3a1bd7d81d32944069ffbfe9f162154c2543253be6d2f5af05f189e161deea172f334d6"

# -- Questions --
QUESTIONS = json.loads(r"""
[
  {
    "fn": "f1",
    "prompt": "What does f1(24) return?",
    "hint": "24 = 0b00011000. Start by computing -24 in two's-complement.",
    "answer": "8",
    "wrong": {
      "24": "f1 does not return its input. x & -x isolates the LOWEST set bit. -24 in two's complement: flip 0b00011000 -> 0b11100111, add 1 -> 0b11101000. AND: 0b00011000 & 0b11101000 = 0b00001000 = 8.",
      "0": "x & -x is 0 only when x = 0. For x = 24, the lowest set bit is at bit position 3, value 8.",
      "4": "Check your two's-complement. -24: flip 0b00011000 -> 0b11100111, add 1 -> 0b11101000. 0b00011000 & 0b11101000 = 0b00001000 = 8, not 4.",
      "16": "16 = 0b10000 is the UPPER set bit of 24 (0b11000), not the lowest. x & -x gives the LOWEST set bit.",
      "12": "12 is the input 24 with a bit flipped. -x in two's complement does not flip a single bit. Trace carefully: flip all bits of 24, then add 1.",
      "3": "3 = 0b11 -- this is not one of 24's set bits. 24 = 0b00011000; its set bits have values 8 and 16."
    },
    "explanation": "x & -x isolates the lowest-order set bit. -x in two's complement flips all bits then adds 1, which carries through all trailing zeros and the lowest set bit, zeroing everything above it."
  },
  {
    "fn": "f2",
    "prompt": "What does f2(24) return?",
    "hint": "24 = 0b00011000. Compute 24 - 1 = 23 in binary, then AND.",
    "answer": "16",
    "wrong": {
      "8": "x & (x-1) CLEARS the lowest set bit; it doesn't isolate it. 24 & 23 = 0b00011000 & 0b00010111 = 0b00010000 = 16.",
      "24": "x & (x-1) always gives a strictly smaller result than x (for x > 0). 23 = 0b00010111. 0b00011000 & 0b00010111 = 0b00010000 = 16.",
      "0": "0 would mean 24 is a power of two (it is not -- 24 = 16 + 8). 24 & 23 = 0b00010000 = 16.",
      "4": "Recompute 23 in binary: 0b00010111. 0b00011000 & 0b00010111: bit4 = 1&1 = 1, all lower bits = 0. Result = 0b00010000 = 16.",
      "23": "23 = 24 - 1 is one of the operands, not the result. The AND gives 0b00011000 & 0b00010111 = 0b00010000 = 16."
    },
    "explanation": "x & (x-1) clears the lowest-order set bit. Subtracting 1 flips the lowest set bit and all bits below it. ANDing with the original preserves everything above and zeros those positions."
  },
  {
    "fn": "f3",
    "prompt": "What does f3(0b10110101) return?",
    "hint": "0b10110101 = 181. Trace the loop: each iteration clears one set bit. How many iterations until x = 0?",
    "answer": "5",
    "wrong": {
      "8": "8 is the total number of bits in a byte, not the number of SET bits. Write out 0b10110101 and count the 1s.",
      "4": "Recount: bit0=1, bit1=0, bit2=1, bit3=0, bit4=1, bit5=1, bit6=0, bit7=1. That is five 1-bits, not four.",
      "3": "Recount from LSB: bit0=1, bit1=0, bit2=1, bit3=0, bit4=1, bit5=1, bit6=0, bit7=1. Ones at positions 0,2,4,5,7 = 5 total.",
      "6": "Recount: 0b10110101. Bit pattern from MSB: 1,0,1,1,0,1,0,1. Count the 1s: positions 7,5,4,2,0 = 5, not 6.",
      "7": "Trace the loop manually. Each iteration clears one 1-bit via x &= (x-1). 0b10110101 has 5 set bits, so the loop runs 5 times.",
      "181": "181 is the input value, not the bit count. The loop counts set bits; 181 = 0b10110101 has 5 set bits."
    },
    "explanation": "Brian Kernighan's popcount algorithm. Each x &= (x-1) clears the lowest set bit. The loop runs exactly once per set bit. 0b10110101 has bits set at positions 0,2,4,5,7 -> count = 5."
  },
  {
    "fn": "f4",
    "prompt": "What does f4(0x0506) return? (give the decimal value)",
    "hint": "0x0506 = 1286. Trace each mask+shift: what does (x & 0x00FF) << 8 produce? What does (x & 0xFF00) >> 8 produce?",
    "answer": "1541",
    "wrong": {
      "1286": "1286 is the input (0x0506). Trace f4: (0x0506 & 0x00FF) = 0x0006, shift left 8 -> 0x0600. (0x0506 & 0xFF00) = 0x0500, shift right 8 -> 0x0005. OR: 0x0600 | 0x0005 = 0x0605 = 1541.",
      "0x0605": "0x0605 is correct hex -- convert to decimal: 6 * 256 + 5 = 1536 + 5 = 1541.",
      "1536": "1536 = 0x0600. You have the high byte right but missed adding the low byte (5). 0x0605 = 1536 + 5 = 1541.",
      "771": "771 = 0x0303. That is not the result. (0x06 << 8) | 0x05 = 0x0600 | 0x0005 = 0x0605 = 1541.",
      "1540": "Close -- off by one. 0x0605 = 6*256 + 5 = 1536 + 5 = 1541, not 1540.",
      "0506": "0x0506 = 1286 is the input unchanged. f4 swaps the two lowest bytes: result is 0x0605 = 1541."
    },
    "explanation": "f4 swaps the two lowest bytes. 0x0506: low byte 0x06 shifts left 8 -> 0x0600; next byte 0x05 shifts right 8 -> 0x0005. OR = 0x0605 = 1541."
  },
  {
    "fn": "f5",
    "prompt": "What does f5(6) return?",
    "hint": "6 = 0b110. Compute 6 >> 1 first, then XOR that with the original 6.",
    "answer": "5",
    "wrong": {
      "3": "6 >> 1 = 3, but f5 XORs the shifted value with the ORIGINAL, not just returns the shift. 6 ^ 3 = 0b110 ^ 0b011 = 0b101 = 5.",
      "7": "6 | 1 = 7 uses OR. This function uses XOR: 6 ^ (6 >> 1) = 0b110 ^ 0b011 = 0b101 = 5.",
      "12": "12 = 6 << 1. This function shifts RIGHT, not left: 6 ^ (6 >> 1) = 0b110 ^ 0b011 = 0b101 = 5.",
      "0": "XOR of 6 and 3 is not zero. 0b110 ^ 0b011: bit2=1^0=1, bit1=1^1=0, bit0=0^1=1 -> 0b101 = 5.",
      "2": "2 = 0b010. Check bit by bit: 0b110 ^ 0b011 -> bit2=1, bit1=0, bit0=1 = 0b101 = 5.",
      "9": "9 = 0b1001. 6 is only 3 bits wide (0b110) and 6>>1 = 3 = 0b011. XOR gives 0b101 = 5."
    },
    "explanation": "f5 computes the binary-reflected Gray code of x. Adjacent Gray codes differ in exactly one bit. f5(6) = 0b110 ^ 0b011 = 0b101 = 5."
  }
]
""")

FUNCTIONS_TEXT = """\

    int f1(int x) { return x & -x; }

    int f2(int x) { return x & (x - 1); }

    int f3(int x) {
        int count = 0;
        while (x) { x &= (x - 1); count++; }
        return count;
    }

    int f4(int x) {
        return ((x & 0x00FF) << 8) | ((x & 0xFF00) >> 8);
    }

    int f5(int x) { return x ^ (x >> 1); }
"""

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()


def _ask(q, index, total):
    print(f"\n  Q{index}/{total}  [{q['fn']}]  {q['prompt']}")
    print(f"           Hint: {q['hint']}")
    attempts = 0
    while True:
        raw = input("  Your answer: ").strip()
        if not raw:
            continue
        if raw == q["answer"]:
            if attempts > 0:
                for ln in _wrap(q["explanation"]):
                    print(ln)
            else:
                print(f"  Correct.  {q['explanation']}")
            return raw
        attempts += 1
        _show_wrong(raw, q.get("wrong") or {})
        print("           Trace through the function step by step and try again.")


def main():
    _banner("Activity 3: Bit Manipulation Reverse Engineering")
    print()

    print("  The five functions:")
    print(FUNCTIONS_TEXT)
    print("  Rules")
    print("    - Do NOT compile or run the code.")
    print("    - Trace by hand using binary arithmetic.")
    print("    - Wrong answers are explained and re-prompted.")
    print("    - All five must be correct to receive the passphrase.")
    print()
    input("  Write your one-line descriptions for each function, then press Enter...")

    answers = []
    total   = len(QUESTIONS)
    for i, q in enumerate(QUESTIONS, 1):
        answers.append(_ask(q, i, total))

    print()
    print("  All correct.")
    passphrase = _decrypt(_BLOB, answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
