#!/usr/bin/env python3
# Generated by aprog-private/activities/generate_activities.py
# To update questions: edit quiz-data/bit-manipulation-re.json and re-run the generator.
"""Activity 3: Bit Manipulation Reverse Engineering

Students trace through five mystery bitwise functions without running the code.
Wrong answers are explained and re-prompted. A passphrase is revealed when all
five are correct.
"""
import json, sys

# -- Crypto / obfuscation --
_KEY_A = "704b3a7405232fb74aa43d9c7ecd4f6effe66147e37463a751beb015c07f306a"
_KEY_B = "695f76d5766b1fc42c55e32b660e99492ee7141fc6aeb31a5a4ee35c2c527c0d"
import base64 as _b64, hashlib as _hl, hmac as _hm, json as _js, zlib as _zl

_SALT      = bytes.fromhex("a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6")
_KDF_ITERS = 100000

# Split runtime key. This is obfuscation only; do not treat it as a secret.
def _xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

def _runtime_key():
    return _xor_bytes(bytes.fromhex(_KEY_A), bytes.fromhex(_KEY_B))

def _derive_key(answers):
    return _hl.pbkdf2_hmac("sha256", "|".join(answers).encode(), _SALT, _KDF_ITERS)

def _stream(key, length):
    ks, i = b"", 0
    while len(ks) < length:
        ks += _hl.sha256(key + i.to_bytes(4, "little")).digest()
        i += 1
    return ks[:length]

def _decrypt(blob_hex, answers):
    blob    = bytes.fromhex(blob_hex)
    key     = _derive_key(answers)
    ct, mac = blob[:-32], blob[-32:]
    if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
        return None
    return bytes(a ^ b for a, b in zip(ct, _stream(key, len(ct)))).decode()

def _item_key(label):
    return _hm.new(_runtime_key(), label.encode(), _hl.sha256).digest()

def _open_secret(blob_text, label):
    try:
        blob = _b64.b85decode(blob_text.encode())
        key = _item_key(label)
        ct, mac = blob[:-32], blob[-32:]
        if not _hm.compare_digest(mac, _hm.new(key, ct, _hl.sha256).digest()):
            return None
        pt = _xor_bytes(ct, _stream(key, len(ct)))
        data = _js.loads(_zl.decompress(pt).decode())
        return data if isinstance(data, dict) else None
    except Exception:
        return None

_BLOB = "daa16a7c638cd67e486c7c84dd9d1f734d768e1e4d1c3b5b669fe3a1bd7d81d32944069ffbfe9f162154c2543253be6d2f5af05f189e161deea172f334d6"

# -- Public questions and encrypted answer/explanation material --
QUESTIONS = json.loads(r"""
[
  {
    "fn": "f1",
    "prompt": "What does f1(24) return?",
    "hint": "24 = 0b00011000. Start by computing -24 in two's-complement."
  },
  {
    "fn": "f2",
    "prompt": "What does f2(24) return?",
    "hint": "24 = 0b00011000. Compute 24 - 1 = 23 in binary, then AND."
  },
  {
    "fn": "f3",
    "prompt": "What does f3(0b10110101) return?",
    "hint": "0b10110101 = 181. Trace the loop: each iteration clears one set bit. How many iterations until x = 0?"
  },
  {
    "fn": "f4",
    "prompt": "What does f4(0x0506) return? (give the decimal value)",
    "hint": "0x0506 = 1286. Trace each mask+shift: what does (x & 0x00FF) << 8 produce? What does (x & 0xFF00) >> 8 produce?"
  },
  {
    "fn": "f5",
    "prompt": "What does f5(6) return?",
    "hint": "6 = 0b110. Compute 6 >> 1 first, then XOR that with the original 6."
  }
]
""")
QUESTION_SECRETS = json.loads(r"""
[
  "bJR-+FEV$(oQDfK0dNTUrB$AO;H!=;UwuCWm=bVf9HwTWjr^UVt3tKaCgmhw$j!k7Yuvi^r&hQP8nn3lm70vUO5wV>1_70#M_CsAT_LI2HjZ`0k`jR)QcPI651$J>(*8m8Tk1At#c*(6;M;-TP+w!~&TgN^Q=VOgD)c|g9(Tb`ADLRahv5X!zSRtTG68&2sP<M`I4(E|$b!i4QP|E`(RCX1HeTw3ipJl1t}Q~>OQ4rFo{OFuj$Mv->{5z^I?9!8Q><k%dG_O7xDGt7ji?i%1DNOq!dn0BOmAbjKuY0+-=8<k?2_QOlxb!kA>;$5yOt2{%2QggNV8yVYW#8n?JR{%05=SFkiHW=s_}?NmPwhiC$}Iz-)Fct7bKLedO9I9WVik!F2Iz7IB<y08q|U&@Y@GyC#ry<X_`K6L6l1PJL)_R#7)<~h5adKWglm3{Q$B79wh8hnF#3H4x%mXM%us2e2<yF-Ar(W322xQX6$|TRxy}`3s7E~2D(Hiaw~KsQTcI0zeL!-t6hbfC8E&|@=c0}cNsQYG%6^aw>#cO7iW78c8P8v8DSPI8aQ-Ll#PXSkcx32d|TJyqiB!^-TIPwi*>w0(u3zxXaZ~;<!^35-_x(SQ}%<^KEmg@BZj8W@R<=w76",
  "Ci`>wMTFr&cG>=xF1q!AN)Hb(m5gH3it-abT2Pfy6HHL|CD3Jym{DoLY}eMd7~!TBsySMFtP4ID+XC%Mpv>l7$__(5(A7$CC>%Sg1(J`ebPrZU7Al4Kg5yqbUXxV0!7{xNDIWzo#p3df2&OMdQq^M`Xs?Jvz8u4~Fe#I0ad;z?G@GS}BcGTrsIzA(ZN9Y(>1%`8H2h?I9)8KzQDc0If5<8%-kYeU4Mr0oZt95)tp{g%^gTi@&#R6tRqlqwkZDE_@BkXD!x&hYT)mT(!cy6ruB`iaS{jtr$cq$*`rSg0C_tz1x+-hsQ)6YTctR>T{24y6!7+{frRk5rYani*0Aa*(<9MJZEG)7^?9OPHC5k<SQFFu%4qjnA#C-DZj!7|BoGBiz)XJPAF`Gp%rBix`VCRP})599LatMTA@rdRct%>kFFtI7wnwqa^^g1Ii0j>is$M65kC9O8HmYdxR#WC33s$F8jxccwKfs$gsT{fkmtoSJ6t0seij_O=i89+-_@2-Kb`%fqB1I|b=k|%H1Qa0<5SO&?mltN~AeW!1kNFibf#ch9`",
  "Amvp6rZbRcK3movg33G;I}mc+@)|&A47CBy#0LA1dMj(RN8ypp${SP|yvJ=CXUYoM#pz>EWzq8e{-h0&yHBdYl_y-*4Rh(_Rf36hKqZ2AmKh%9+oDKxrWOjwD7RoH^DYoLmzjbM-ID>cLv$ZfYgwkKXh@_gm&S+fdu{pJc@ZY6AD_#8Yty}D3Tl}BJg$br6tE0SZ<0C)(I@adDM0cP{rboTf%Q$%y!Tz>Sfa()2X?K(-yeZ#w)$v%V|pPRT3lt<b&v9_vE?eg^kh?cIgSwgDM*qVn5j7N-tcMXkD$Pa4nl=TyByIlTn{YHK2Ikq4`4jMZf23ln^L&^A(4w*5jz7%{{Ry!m-4;@7w56&ZSq`Ltj<U2$3c0B8Oa#k1Iq!!yM)uJVOsH@22h?(l-@k4HB(+U6xTbP3ckZZ>Zw#Q=&4ZBVoy~S0|89XR+q;sutl+A!=>NaXG9HkTV>--wt~z`wkJ1QamP>$_6qo}u4PI>uX+HDNhp@SNU2nqQCM}Hsm$JvXV;^oeKF~>{>Gq54UAT51vZA07;V^ueKj8AqjPDS+1=3zfZa1B1Um->#F(?qL}Q(%>N^u$by1&vRU)%Qb747@d?5we?F@(P7!m",
  "Ndj9)YN$GQkZm@nFk5*!N<N2AXK(jY1gyx<%QlUEYw?u1Ppg9a2wD;2F;_4cl2I>!(j#c2lbi=8r6cy*8IVfyNs_Dmk4NC|lG>vu)6sUyHReK>p6wBU6X8cEE(@&d&WJ&HAay7p^8<ob8UoIuVahv+BifATU``Nu1?GXa%B2i0-#PTHu2qdRipO_7(?3J>+=fyUGh;I$ZvNBNkHk~_aL+oHyatRty%d=;s!WTQb90r?_2ymz*#}gfv}gQ;^x%}<cM3yTwQ*u!9`7mJZUYY(GxeerBtTiQ+Xfbk*Y;dqF0fmZ{Z$*n1~&>9V8BT67k5Ue9uf^M0rxk%tViV&La}a7(4ql8YH^`_uz&s`E*SDx%S?T<^$&0dtWkw2sI~R170HQsK^b5-;BZ@4cpbbN!S%}Ww+D{6;2>;9Py)x-Ip=)k?q?rE|Ihcp6<>sBYMzUY-x6aGBUrPmxBGC~tR^a_yN*F3Ru?8#MK%RQ%p(kV8@i41+Sa8Uk^mkXL2xJjAK<1b6aR+T2v1-SOE6gGc7JVwT`<eTlYH+",
  "GVkjDCzQYfgJ3j~KCeOgV?_sesoGDTCHS0#i2CR-7Sw%qjJ1(G5^j+?=zlLJGjr})a<G2=Z&7{Y_?bVK?(zkFM4Pn~rd+HW2x)<AH+#0D**Swy8g>YWM4jfa3(|-4AnQA^vlG)NuNK1*Wl%mKTd+UrYAUa41ro|d#UN#eoZe;E0^(-S0xibNG$ST(<;-|pbynBkHUHR<4P<VD-hoD0v7?^$tAyEF-9TnW`n<-ik~VVW<{ztois8|1<j=|j6b{jD;6A%Ppt=srt0}KfVZ6*|KS->U-U#A*fTCNaokGN~h%G#%yBe{1aF<gMUMkTwu(pe7Qlu=gY(}44Q+mfRrJ)!ANKNqe@+ktFs+a5&=T0Ra8PVG>>mJY<F;ekSCMcc$Bn4pBi<KWfPB;l*0^RDQ32FAYAleMi)k<kmi*;sHqUWn%f!>Um^SRp?4ZxyE_1BEH>~hU1{X(O`@KLUB+Z?0ES^pP$I-+2%z(#RBglIk@5w7qEjQj*;LzK;^7sLq=U5HvTSF1Mx@`WAgcFUs8hK%6}pU<drenb"
]
""")

FUNCTIONS_TEXT = """
    int f1(int x) { return x & -x; }

    int f2(int x) { return x & (x - 1); }

    int f3(int x) {
        int count = 0;
        while (x) { x &= (x - 1); count++; }
        return count;
    }

    int f4(int x) {
        return ((x & 0x00FF) << 8) | ((x & 0xFF00) >> 8);
    }

    int f5(int x) { return x ^ (x >> 1); }
"""

# -- Helpers --
import textwrap as _tw

_LINE_WIDTH = 70

def _banner(title):
    print("=" * _LINE_WIDTH)
    pad = (_LINE_WIDTH - len(title) - 2) // 2
    print(" " * pad + " " + title + " " + " " * pad)
    print("=" * _LINE_WIDTH)

def _hr():
    print("-" * _LINE_WIDTH)

def _wrap(text):
    return _tw.wrap(text, width=_LINE_WIDTH - 4,
                    initial_indent="  ", subsequent_indent="    ")

def _show_wrong(raw, wrong_dict):
    exp = wrong_dict.get(raw)
    if exp:
        print()
        for ln in _wrap(f"[wrong] {exp}"):
            print(ln)
    else:
        print(f"  [wrong] {raw!r} is not the correct answer.")

def _show_passphrase(passphrase):
    print()
    _hr()
    print(f"  Passphrase: {passphrase}")
    _hr()
    print()


def _secret_for_question(index):
    secret = _open_secret(QUESTION_SECRETS[index - 1], "bit-manipulation-re:question:" + str(index))
    if secret is None:
        print("  [error] Could not open question quiz-data -- contact your instructor.")
        sys.exit(1)
    return secret

def _ask(q, index, total):
    secret = _secret_for_question(index)
    print(f"\n  Q{index}/{total}  [{q['fn']}]  {q['prompt']}")
    print(f"           Hint: {q['hint']}")
    attempts = 0
    while True:
        raw = input("  Your answer: ").strip()
        if not raw:
            continue
        if raw == secret["answer"]:
            if attempts > 0:
                for ln in _wrap(secret.get("explanation", "")):
                    print(ln)
            else:
                print(f"  Correct.  {secret.get('explanation', '')}")
            return raw
        attempts += 1
        _show_wrong(raw, secret.get("wrong") or {})
        print("           Trace through the function step by step and try again.")


def main():
    _banner("Activity 3: Bit Manipulation Reverse Engineering")
    print()

    print("  The five functions:")
    print(FUNCTIONS_TEXT)
    print("  Rules")
    print("    - Do NOT compile or run the code.")
    print("    - Trace by hand using binary arithmetic.")
    print("    - Wrong answers are explained and re-prompted.")
    print("    - All five must be correct to receive the passphrase.")
    print()
    input("  Write your one-line descriptions for each function, then press Enter...")

    answers = []
    total = len(QUESTIONS)
    for i, q in enumerate(QUESTIONS, 1):
        answers.append(_ask(q, i, total))

    print()
    print("  All correct.")
    passphrase = _decrypt(_BLOB, answers)
    if passphrase is None:
        print("  [error] Decryption failed -- contact your instructor.")
        sys.exit(1)
    _show_passphrase(passphrase)


if __name__ == "__main__":
    main()
